### ISSUE TITLE
some time dropdown list is behave differntly when it is at bottom of the screen

### ISSUE THREAD

**Issue by vikasvaisha** [select2/select2#3009] opened 2015-02-06 08:07 UTC
Hi,

Thanks for reply on my previous issue. I as facing one more issue when my asp:dropdown  control is at bottom of the window as shown in below screen short
![issue](https://cloud.githubusercontent.com/assets/10848779/6076166/3724a966-ae05-11e4-9bb9-31e10582c0c6.png)

**Comment by kevin-brown** [comment] 2015-02-06 22:31
@vikasvaisha Can you reproduce this on the examples page?

https://select2.github.io/examples.html

If not, can you create a jsbin or link to a page where we can reproduce this issue?

**Comment by vikasvaisha** [comment] 2015-02-07 07:01
Hi Kevin,

I created same issue on example page too.
I went to the link scroll the page until dropdown is at bottom of my window and clicked on it.

![select2_issue2](https://cloud.githubusercontent.com/assets/10848779/6091207/dd1cc0e6-aec4-11e4-8843-416f81c6d072.png)

I have created on more project to illustrate this issue

![select2_issue](https://cloud.githubusercontent.com/assets/10848779/6091212/12dbce7a-aec5-11e4-8b85-53e09978a05a.png)

If you want I can mail the code of second screenshot for your reference.


Thanks once again :)

**Comment by kevin-brown** [comment] 2015-02-07 15:38
Now that we know it happens on the examples page, and sounds like it's an IE issue, I have a few final questions:

- What versions of IE have you seen this happen on?
- Does this happen on any other browsers?

**Comment by vikasvaisha** [comment] 2015-02-08 09:51
I have tested it on Chrome 40.0.2214, IE 11, Firefox 34.0.5 and also on Firefox developer edition but result was same.

**Comment by jelhan** [comment] 2015-02-20 20:34
I could also reproduce the issue in Firefox 35.0.1.

* It only occurs when select is opened first time. `select2-container` gets a wrong `top` value.
* It doesn't occur on all select2 elements. On example page I could only reproduce the issue for select2 in *Loading remote data* chapter. In my own project it occurs on select2 using a data array, but only on the last one of third select2.

![select2-dropdown-issue](https://cloud.githubusercontent.com/assets/4965703/6308876/35f5dc7e-b948-11e4-8632-6f47e54f9825.png)

**Comment by jelhan** [comment] 2015-02-24 14:39
I tracked down the issue to `dropdown.height` value: https://github.com/select2/select2/blob/select2-ng/dist/js/select2.full.js#L3929

On first open `this.$dropdown.outerHeight(false)` returns a wrong value. Opening select2 in **Loading remote data** first time `dropdown.height` is `192`. Afterwards value is set correctly to `77`. Gap is exactly the difference of `115px`.

**Comment by jelhan** [comment] 2015-03-02 10:58
Issue seems to be fixed. Atleast I wasn't able to reproduce it using latest dev or on example page.

**Comment by kevin-brown** [comment] 2016-06-25 18:53
This issue has been fixed in the latest version of Select2.

**Closed by kevin-brown** 2016-06-25 18:53 UTC
Labels: needs information
