### ISSUE TITLE
Add onfocus callback

### ISSUE THREAD

**Issue by alvarotrigo** [select2/select2#3701] opened 2015-08-21 10:01 UTC
I've checked the documentation but I found not reference to callbacks. Just in the Data Set or AJAX sections, but I don't have it very clear what are the ones in Data Set for.

I would expect to see some callbacks such as: `onFocus`, `onOpen`, `onClose`, `onChange` and so on.

**Comment by alvarotrigo** [comment] 2015-08-21 10:11
Ok... I found it on the "Examples" page instead. **It should be in the documentation rather than in a examples page**.

In any case, I didn't see any `on-focus`.

**Comment by kevin-brown** [comment] 2015-08-21 14:08
Duplicate of https://github.com/select2/select2/issues/3152 which was merged into https://github.com/select2/select2/issues/1908.

**Closed by kevin-brown** 2015-08-21 14:08 UTC

**Comment by alvarotrigo** [comment] 2015-08-21 14:19
Just as a note. This is also a request for a better documentation structure. 
There should be a `callbacks` menu or similar.

**Comment by kevin-brown** [comment] 2015-08-21 14:31
For what it's worth, I have a giant list of things which people have mentioned are missing from the documentation (or why they couldn't find things), and I tend to add the topic of most tickets to it. Especially duplicates, because usually those are needed by more people.

> This is also a request for a better documentation structure.

There are [many of them](https://github.com/select2/select2/labels/documentation). We're aiming to redesign how the documentation is set up so it's a bit more clear and covers practical use cases in the near future.

**Comment by alvarotrigo** [comment] 2015-08-21 14:44
> There are many of them. We're aiming to redesign how the documentation is set up so it's a bit more clear and covers practical use cases in the near future.

Awesome.
