### ISSUE TITLE
Floating textbox after select2 drops up

### ISSUE THREAD

**Issue by medmondson** [select2/select2#4969] opened 2017-06-23 13:31 UTC
## Prerequisites

- [Y] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [Y] The issue still exists against the latest `master` branch of Select2
- [Y] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [Y] I have attempted to find the simplest possible steps to reproduce the issue
- [N - Screencast] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Please see screen cast taken from the [examples page](https://select2.github.io/examples.html#data-ajax):

![select2 issue](https://user-images.githubusercontent.com/1955888/27484196-371682d8-5820-11e7-912c-048f6482c56c.gif)

If I resize my window such that the drop down drops 'up' I get a floating box after a search.

Browsers
-  Google Chrome

Operating System
- Windows

Libraries

- jQuery version: Latest on example
- Select2 version: Latest on example

**Comment by thauk-copperleaf** [comment] 2017-06-23 21:15
Great writeup. We're seeing the same issue.

**Comment by BARNZ** [comment] 2017-06-28 09:17
Yep super annoying. This is a duplicate of #4614 where [this comment](https://github.com/select2/select2/issues/4614#issuecomment-251277428) has a workaround you can use.

The order of internal events seem incorrect: 

1. Dropdown is resized+positioned
1. The dropdown results of the previous search are cleared invalidating the previous position calculation

Workaround above is to just to resize and position dropdown again afterwards.

**Comment by medmondson** [comment] 2017-07-03 11:15
@BARNZ - Agree this works.  Are PRs no longer being accepted by this project?

**Comment by alexweissman** [comment] 2017-09-12 01:36
This bug has a working solution in https://github.com/select2/select2/issues/4614.  Closing as a duplicate.

**Closed by alexweissman** 2017-09-12 01:36 UTC
Labels: confirmed bug, duplicate
