### ISSUE TITLE
Dropdown opens automatically when default value set - only in IE browsers

### ISSUE THREAD

**Issue by seenimurugan** [select2/select2#3551] opened 2015-07-06 10:18 UTC
Apologies if same kind of issue raised already(i skimmed the bug list but could not find the same)

When default value set to the select2(v4.0.0) component, it opens the dropdown option list automatically when the page loads. I created the plunker - http://plnkr.co/edit/wiXaWwr3DIYq8vSnRaBx?p=preview 

Open the link in any version of IE browsers and it opens the dropdown automatically. 

And also does not close the option list when no option selected.

**Comment by kevin-brown** [comment] 2015-07-07 01:20
Sounds like a duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-07-07 01:20 UTC
