### ISSUE TITLE
single model cannot input Chinese at IE8

### ISSUE THREAD

**Issue by qinshouzhi** [select2/select2#3624] opened 2015-07-30 00:28 UTC
在IE8，单选模式下，查询输入框，不允许输入中文。

---

Google Translate: In IE8, radio mode, query input box, not allowed to enter the Chinese.

**Comment by kevin-brown** [comment] 2015-07-30 15:17
English translations (as best as possible) are encouraged _along with_ the native responses.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by wdietz** [comment] 2015-08-06 15:33
I ran into this issue in IE 11 and was able to reproduce it in IE8 and 9 also.
Unfortunately I am unable to make an isolated test case at this time.
The issue happens when multiple keystrokes are required to produce a single glyph.
For example the sequence j-1-3 should produce the character 哺 but instead only creates the character ˇ from the 3 because the j1 are lost.

jQuery version 1.7.1
I don't know how to get the Select2 version.
Windows 7 IE 8-11

The fix was to remove a seemingly benign line of code.
https://github.com/select2/select2/pull/3654

**Comment by qinshouzhi** [comment] 2015-08-18 23:45
give me you E-mail,ok?I will send some demo to you.

**Comment by alexweissman** [comment] 2017-12-09 00:55
It would appear that #3654 has been merged, so this should be resolved.

**Closed by alexweissman** 2017-12-09 00:55 UTC
Labels: browser: IE, status: needs information
