### ISSUE TITLE
Select2 4.0.6 ignores data-*

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#5459] opened 2019-02-19 09:31 UTC
While 4.0.5 (master) version is working fine... 4.0.6 rc is not working. 
Jguery: 2.2.1,
select2: branch 4.x > dist

<select style="width: 200px;" data-placeholder="Select an option" multiple class="select2" name="xxx">
<option></option>
<option value="1">val1</option>
<option value="2">val2</option>
<option value="3">val3</option>
</select>

Placeholder does not appear even if I add: data-tags="true"...

**Comment by toxpal** [comment] 2019-02-24 11:17
The same happens with allowclear option when using data- fields. 4.0.5 worked well, 4.0.6 doesn't work.

**Comment by toxpal** [comment] 2019-03-07 22:41
Is select2 still maintained? I love this plugin, but the latest working version (4.0.5) was released years ago, and latest RC version was released about a year ago, and no more updates/bug fixes...

**Comment by jonahgreenthal** [comment] 2019-03-07 22:42
Unfortunately, it doesn't seem like it.

**Comment by toxpal** [comment] 2019-03-08 12:43
Oh well, I downgraded back to 4.0.5 for now, so at least data- stuff works... It's shame to see that both select2 v4 and select2 v5 are not updated for a long time. Hopefully we will see some action because it's probably the best select plugin of all time.

**Comment by Seb33300** [comment] 2019-03-13 08:42
Duplicate of #5180.

**Comment by kevin-brown** [comment] 2019-03-26 10:59
Closing this in favor of https://github.com/select2/select2/issues/5180 since it has a reproducible test case we can work with.

**Closed by kevin-brown** 2019-03-26 10:59 UTC
Labels: status: possible bug (unconfirmed)

**Comment by crabnky** [comment] 2019-04-03 13:34
Duplicate of https://github.com/select2/select2/issues/5320 as well.
