### ISSUE TITLE
[Help] Click twice input search

### ISSUE THREAD

**Issue by vuducbinh0110** [select2/select2#3789] opened 2015-09-23 07:11 UTC
When you click to the input first, it will show the result.
And when you click to the input twice. the result was lost.

How to always show the result when you click to the input?
Please help me, thanks.

**Comment by kevin-brown** [comment] 2015-09-25 22:19
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by alexweissman** [comment] 2017-12-09 00:50
Likely a duplicate of #4472.

This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.

**Closed by alexweissman** 2017-12-09 00:50 UTC
Labels: support: usage question
