### ISSUE TITLE
Problem with outerWidth() calculation (solution included)

### ISSUE THREAD

**Issue by Daijobou** [select2/select2#3812] opened 2015-10-05 13:17 UTC
I see a pixel problem with https://github.com/select2/select2/blob/master/dist/js/select2.js#L4194
My select2-dropdown is 1px to wide. Reason: I use
~~~~~
<select ..... style="width:90%">
~~~~~
that is 426.547px´(in my case). But outerWidth returns only integer 427px, i.e ignoring the decimal value / round value. My personal solution is to use:
~~~~~
this.$container[0].getBoundingClientRect().width
~~~~~
instead of outerWidth(). It was introduced in IE4 and is supported by all browsers.
See: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by kevin-brown** [comment] 2015-10-06 22:49
This is a duplicate of https://github.com/select2/select2/issues/3558.

**Closed by kevin-brown** 2015-10-06 22:49 UTC

**Comment by Daijobou** [comment] 2015-10-07 09:11
Thanks, I answer a solution in #3558. ;)
