### ISSUE TITLE
Bug: auto click on item when results are over select field

### ISSUE THREAD

**Issue by arcaweb** [select2/select2#5819] opened 2020-04-01 10:34 UTC
![Capture d’écran 2020-04-01 à 12 32 37](https://user-images.githubusercontent.com/1327272/78127848-290bdd00-7415-11ea-8bb7-88b91fa6d33b.png)

![Capture d’écran 2020-04-01 à 12 32 44](https://user-images.githubusercontent.com/1327272/78127847-28734680-7415-11ea-9302-f5af5c1b5ecd.png)

Hello guys,

I have add a `margin-top: -40px` to `.select2-dropdown--below` in order to show result box over select field.

But when I click on the select field, it open results, and instantly select first item on list. If I keep mouse clicked, I can select another item.

Search is deactivated, if I enable it, it is ok because I think it clicks in search field.

Is it a select2 bug or a "normal" behavior ?

Thanks

**Comment by kevin-brown** [comment] 2020-04-02 00:24
Duplicate of https://github.com/select2/select2/pull/3369#issuecomment-246135221, we recommend you override the handlers to be click handlers on your own if you wish to do this.

**Closed by kevin-brown** 2020-04-02 00:24 UTC
