### ISSUE TITLE
Multiple select with placeholder is not working very well in IE11

### ISSUE THREAD

**Issue by jseminck** [select2/select2#3312] opened 2015-05-04 07:26 UTC
Hey,

Using IE11, go to the examples webpage: https://select2.github.io/examples.html

Under the "Placeholders" section, the second example is a Multiselect box. If you select 1 state, then the "selection list" with states remains on top/focused until you select a second state. As soon as you select a second state everything works fine.

This issue seems to be related to the placeholders, because the "Multiselect" example above without a placeholder works just fine. Also in my own project, if I remove the "placeholder" option on the select2 initialization function, then everything works fine.

Thanks,
Joachim

**Comment by kevin-brown** [comment] 2015-05-21 15:11
Duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-05-21 15:11 UTC
