### ISSUE TITLE
Add an option to disable/remove/hide selected items from the list in a multiple select

### ISSUE THREAD

**Issue by multiwebinc** [select2/select2#4858] opened 2017-04-05 04:22 UTC
It would be great if you could add an option so that when the user selects one of the options that they don't appear in the list anymore, either that or else they appear grayed out and not selectable.

Something like:

```
$('#select').select2({
    hideSelected: true
});
```

I've sort of accomplished it [here](https://jsbin.com/racoqoyabu/1/edit?html,css,js,output). The `<option>` is disabled in the original `<select>` element and then select2 is re-applied. Disabled elements are hidden with CSS. However I feel it's kind of hackish since I re-add the select2 from scratch on every single change.

**Comment by alexweissman** [comment] 2017-09-29 04:59
At the moment, selected items _do_ get a different style applied, and then reselecting them actually removes them from the current selections.  This would be a pretty dramatic departure from the current behavior, but it makes sense to me.

**Comment by alexweissman** [comment] 2017-09-29 05:11
Actually, if you look at #1538, Kevin makes a pretty good case for why you wouldn't want to hide the selected items completely:

> Right now the only way to unselect arbitrary (other than the last) options using the keyboard is to type CTRL + SPACE when the result is highlighted. This is to command for toggling a result, so it will select or unselect the highlighted result depending on what state it was previously in. Screen readers should read out the state of the option (whether it is selected or not) as they move through the results list, which is usually important.

> Without an alternate way to unselect arbitrary options using the keyboard, the UX problems caused by that far outweigh the UX annoyances that you currently have by showing the selected results.

This seems like a common request, so we should add it to the documentation.

**Comment by alexweissman** [comment] 2017-09-29 16:53
I just realized that this is a duplicate of #4105.

**Closed by alexweissman** 2017-09-29 16:53 UTC
Labels: documentation, feature request
