### ISSUE TITLE
Issues with responsive width

### ISSUE THREAD

**Issue by fredmalone** [select2/select2#3278] opened 2015-04-23 16:13 UTC
Unless I am missing something (I apologize if I have), select2 is not fully responsive.  Look at this code:

```
    <div class="col-sm-6">
        <div class="form-group">
            <label>Submit to</label>
            <select class="form-control" id="SubmitQueue" name="SubmitQueue">
                <option value="1">Subsequent Civil</option>
                <option value="2">Subsequent Criminal</option>
                <option value="3">Judge Order - Civil</option>
                <option value="4">Review Sign</option>
                <option value="5">Subsequent Domestic Family</option>
                <option value="6">Judge Order - Criminal</option>
            </select>
        </div>
    </div>
```

The original select has 100% width from the form-control class.  Select2 is creating a fixed width container.  Thus, when I resize the window the select2 container does not resize as it should since the col-sm-6 class is a percentage.  

So did I miss something in my initialization or is this an issue?

EDIT:  OK. I looked throught the code and I noticed that the _resolveWidth doesn't even attempt to get a percentage width from CSS and only works with an inline style.    I can live with that.  How did it work in 3.5.2 without the inline style?

**Comment by eobeda** [comment] 2015-04-26 23:56
What I was seeing is that the 100% width is being converted into 100px. Hence the loss in responsiveness.  Are your element initially hidden ?  I was using the following to work-around for some of the issues. I never got the place-holder text working on long strings. Manually clearing the selection worked, but I never got a programmatic solution.
 //// Fix a select2 ver 4.x issue with widths on initially hidden elements
        if ($(element).not(':visible')) {
            $('.select2-search__field').width("100%");  // The placeholder text needs help as well.

**Comment by fredmalone** [comment] 2015-04-27 19:15
No, they are not initially hidden.  I will look at that options.width to see if it works for me.

**Comment by alexcroox** [comment] 2015-08-10 09:16
I've found that if you have select 2 in a hidden div, when you later reveal that div the width is wrong, is there a method to re-initialise the positioning?

**Comment by alexcroox** [comment] 2015-08-10 09:19
Temporary workaround is to specify width in the init() I can get away with this as all mine happen to work fine 100% width.

`.select2({ width: '100%' });`

**Comment by hhubik** [comment] 2015-09-24 00:31
Also having this issue.  Have a select2 (v4) in a Bootstrap v3 accordion panel that is closed on page load.  When I expand the panel for the first time, the width of the placeholder text is set to 100px even though the select2 element is much wider based on the markup and the browser window size.  After I enter one or two values and then delete them, the placeholder displays correctly.

My HTML markup is 
`<select id="mySelect" class="form-control" style="width: 80%;" multiple="multiple"></select>`

The select2 is getting remote data via Ajax, in case it matters.

Also using the [bootstrap theme](https://github.com/select2/select2-bootstrap-theme)  for select2.

**Comment by abr4xas** [comment] 2016-04-16 22:23
I have the same problem using https://github.com/select2/select2-bootstrap-theme
js
```js
    // Select2
    $('#mySelect').select2({
        theme: "bootstrap",
        placeholder: 'Categorias...',
        allowClear: true,
        tags: true,
        maximumSelectionLength: 3,
        width: '100%'
    });
```
html

```html
<div class="form-group">
  <label class="sr-only" for="categorias">Categorias</label>
  <select id="mySelect" class="form-control" style="width: 100%;" multiple="multiple">
    <option>Tour de Compras</option>
    <option>Guia</option>
    <option>Internacional</option>
    <option>Desayuno</option>
    <option>Traslados</option>
  </select>
</div>
```
![animacion](https://cloud.githubusercontent.com/assets/405484/14583928/18693f3a-03fb-11e6-8330-5e17e954275a.gif)

![screenshot from 2016-04-16 17 50 52](https://cloud.githubusercontent.com/assets/405484/14583958/147aaf16-03fc-11e6-8746-c8c114297dfd.png)

**Comment by ShalluOodles** [comment] 2016-09-29 11:07
I have problem with select tag .i.e when i resize the windows , it doesn't work, doesn't show the options list.

**Comment by tchiotludo** [comment] 2016-10-05 08:09
I use the select2-bootstrap-theme and with this simple hack 
`$(self._select2).parent().find(".select2-container").css('width', '');` all is working fine on my side.

why not allow a an option `width:'none'` that doesn't set the width on : 
```js

  Select2.prototype._resolveWidth = function ($element, method) {
    var WIDTH = /^width:(([-+]?([0-9]*\.)?[0-9]+)(px|em|ex|%|in|cm|mm|pt|pc))/i;
    // +++
    if (method == 'none') {
        return null;
    }
    // end +++

    if (method == 'resolve') {
      var styleWidth = this._resolveWidth($element, 'style');

      if (styleWidth != null) {
        return styleWidth;
      }

      return this._resolveWidth($element, 'element');
    }
```
Only the css will be responsible on width on the select2 container.

**Comment by seanjamu** [comment] 2016-11-04 16:34
Hello, I add custom.css

@media screen and (max-width: 767px) {
    .select2 {
        width: 100% !important;
    }
}

and solved

**Comment by mohammad-melhem** [comment] 2016-11-17 10:51
I tried adding the media query that seanjamu suggested but it's still not working. I'm lost what is the real solution for not breaking on window resize with bootstrap? it still breaks even on the demo page when you zoom in and out. Also using the theme above didn't solve it. 

Any advice would be really appreciated. Thx.

**Comment by drvid** [comment] 2016-11-17 19:56
Using Bootstrap theme I have the same issue. @seanjamu 's CSS override works well enough for now, but why on earth are they defining the width of an input using an inline style with pixels?

**Comment by s0By** [comment] 2016-11-30 09:14
@tchiotludo props for this method. I think it would be nice to have this implemented for "more" advanced users. I had css widths set since select2 3.5 and now I either need to either add !important to every class (which is lame) or have a width: 'none' solution, which is pretty neat.

**Comment by BallisticPain** [comment] 2017-01-09 06:04
@tchiotludo solution worked for me with Angular 2.

```
this.element.nativeElement.parent().find(".select2-container").css('width', '');
```

**Comment by pixelplant** [comment] 2017-01-29 10:35
It was probably not the case when @tchiotludo commented on his lines of code, but now you can just pass a `width: ''` (empty string) parameter to your select2 config and no width will be added. You will need to handle the width in your css code though, so add a width:100% or whatever you need depending on the screen resolution.

**Comment by nelson6e65** [comment] 2017-02-06 08:38
In the HTML5 data-* attribute, you can solve this by setting `data-width`:

```html
<select id="customer" name="customer" class="form-control select2"
    data-width="100%" required>
</select>
```

**Comment by pfleu** [comment] 2017-04-28 15:53
For those experiencing truncated placeholder with v4 of select2, here is a working solution by @labster found [here](https://github.com/select2/select2/issues/291#issuecomment-273927769):
`.select2-selection--multiple .select2-search--inline .select2-search__field {
    width: auto !important;
}`

**Comment by demedos** [comment] 2017-10-12 10:50
Thanks @tchiotludo , [your comment was useful](https://github.com/select2/select2/issues/3278#issuecomment-251609785). It really seems like the problem is [select2-bootstrap-theme](https://github.com/select2/select2-bootstrap-theme) setting a fixed with on the select container; this solves the problem for me:

```
$(function() { 
  $('#controlID').select2({ theme: 'bootstrap' }); 
  $('#controlID').parent().find('.select2-container').css('width', ''); 
});
```

**Comment by fk** [comment] 2017-10-12 18:43
Hello all! It's been a while since I actively worked on and with select2-bootstrap-theme (and with select2 itself for that matter), so please take all my comments with a grain of salt.

As far as I recall things, the theme does __not__ set a fixed width on the select2 container. Actually, I'm pretty sure about this; the theme merely defines CSS. What you are seeing is what I believe to (still) be Select2's default behavior – set the width of the select2 container to the width of the original `<select>` element it was initialized on.

@demedos I'd love to take a look at this if you can show me where select2-bootstrap-theme does set a width on the select2 container.

FWIW, the [demonstration pages for select2-bootstrap-theme](https://select2.github.io/select2-bootstrap-theme/) use the same (or _similar_) workaround people are recommending here, which is setting `width: null`, which will disable the default behavior I mentioned above: https://github.com/select2/select2-bootstrap-theme/blob/8f833863dc3bf5c0d8d7113a8da43acb2c7c7c91/docs/_layouts/default.html#L541

That should have been documented – I apologize that it was not.
Please help out and improve the documentation if you find the time to do so!

That said, the last time I checked Select2 still had problems fully supporting responsive designs. One thing I seem to remember is related to `.select2-search__field` (as mentioned in https://github.com/select2/select2/issues/3278#issuecomment-298035731).

**Comment by demedos** [comment] 2017-10-12 18:55
@fk I'm sorry, I didn't have the time to check your source code and the problem seemed to have happened just right after I installed your theme, but apparently I was wrong. Thank you for pointing us out!

**Comment by fk** [comment] 2017-10-12 19:16
@demedos No worries! 🤗  ❤️ 

Hopefully I will have some time next week to get back on track with select2 a little and at least update the documentation and close [that other issue](https://github.com/select2/select2-bootstrap-theme/issues/30) in the select2-bootstrap-theme repo.

**Comment by alexweissman** [comment] 2017-10-12 20:18
@fk I've set up a temporary chat room for Select2 in https://chat.userfrosting.com/channel/select2, if you want to talk about any ideas you have in real time.  I'm thinking about setting up a dedicated Select2 chat server as well, to take some of the pressure off of the issue tracker - would be interested in hearing your thoughts on that.

**Comment by besi** [comment] 2017-10-15 09:30
I do the following to accomplish @alexcroox's suggestion in a global scope:

```js
$.fn.select2.defaults.set( "width", "100%" );
```

**Comment by jdarrohn** [comment] 2017-10-21 18:34
You're the real MVP @alexcroox

**Comment by wnunez09** [comment] 2018-05-26 16:30
solved with: https://stackoverflow.com/questions/50540292/responsive-fix-input-group-with-select2-and-other-form-control-element-or-input

**Comment by klawrow** [comment] 2018-07-24 16:22
Thanks @alexcroox!  My instance was with the select being initially hidden, then upon display the width would reset to 100px versus what I set as 100%.  It's a bit of a shotgun solution, but hey it works for my case.

**Comment by pedrofurtado** [comment] 2018-09-17 23:57
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Closed by pedrofurtado** 2018-09-17 23:57 UTC
Labels: 4.x, feature request, styling

**Comment by hussonkevin** [comment] 2018-10-17 10:42
correctly corrected with sass code :
``````

**Comment by rishav00a** [comment] 2018-12-09 07:42
Finally Solved this issue,
previously i was overriding the styling using JQuery but it was not able to find that element.
As a solution what is did is 

-> Create a js function

function chsize() {
		$(".select2-container--default").css("width","100%"); // this onw works only on Desktop
		$("head").append($("<link rel='stylesheet' href='/static/landing/css/override.css' type='text/css' media='screen' />")); // this will work everyehere whether it is Mobile, Desktop 
	}

-> Call the function on page load inside body tag

   <body onload="chsize();">

-> Here is my CSS file override.css
     .select2-container--default
{
  width: 100%;
}


Enjoy :)

**Comment by ikarthikng** [comment] 2019-01-11 14:31
Using @alexcroox method I added the following CSS to my page

`.select2 {
   width: 100% !important;
}`

and **removed placeholder option** during initialization in JavaScript. This is the only hack which has worked for me so far after spending many hours searching for a work around using CSS and JavaScript. I am using 4.0.2 version of select2.

**Comment by Tahirhan** [comment] 2019-04-08 06:49
Hi, I had same issue in table element and managed to solve the issue with this code : 


                    td_element.appendChild(select_element);
                    
                    var selectWidth = document.getElementById('select_element_id').clientWidth;

                    $("#select_element_id").select2({
                        placeholder: "Placeholder..",
                        allowClear: true,
                        width: selectWidth.toString()+'px'
                    });

**Comment by irshdweb** [comment] 2019-12-05 13:04
I had the same issue in angular. I added
::ng-deep .select2-container{
            display:block !important;
            width: 100% !important;
  }

and it's working

**Comment by oesah** [comment] 2020-08-15 00:10
> In the HTML5 data-* attribute, you can solve this by setting `data-width`:
> 
> ```
> <select id="customer" name="customer" class="form-control select2"
>     data-width="100%" required>
> </select>
> ```

This is a better solution than using css `width: 100%`, because that might impact the outer html DOM, as it did with my project. If I used css and clicked on the select button, I could scroll on the x and x axis. Using data-width="100%" on the element, that issue was resolved and still gave the same styling as with css.

**Comment by noobkisser** [comment] 2021-01-12 14:47
> In the HTML5 data-* attribute, you can solve this by setting `data-width`:
> 
> ```
> <select id="customer" name="customer" class="form-control select2"
>     data-width="100%" required>
> </select>
> ```

This was by far the best solution with minimal cognitive load. Thumbs up

**Comment by nelson6e65** [comment] 2021-01-13 15:35
> This was by far the best solution with minimal cognitive load. Thumbs up

Thanks!

**Comment by LufoX11** [comment] 2021-11-28 04:42
I'm working with Bootstrap 4 and tabs. The select2 elements are using some wrappers around them, so width 100% doesn't work for me since it breaks those wrapping elements:
![image](https://user-images.githubusercontent.com/819192/143729417-e5cb1b04-d292-4f53-9b21-2d24a420397a.png)
![image](https://user-images.githubusercontent.com/819192/143729472-4f73599f-9d51-4f35-b07c-786782a5f6d6.png)
I also have a lot of specific configuration including parsing functions and a general initialization function like `$(".select2").select2({...})`, so simply calling `.select2()` will also break functionality. I tried to, at least, get the object initial configuration from the element, but I wasn't be able to do it (do somebody know how to do it?).

My solution was to put all of this initialization function inside a global scope var and call it after tab is shown:

```javascript
// General initialization
window.__initSelect2 = function () {
    function parser(state) {...}
    $(".select2").select2({
        templateResult: parser,
        templateSelection: parser
    }).off("select2:unselecting").on("select2:unselecting", function () {
        ...
    }).off("select2:opening").on("select2:opening", function (e) {
        ...   
    });
};
__initSelect2();
```
```javascript
// Tabs (I'm using CoreUI theme, so the event name is a slightly different than the original "shown.bs.tab"
$('#tabs a[data-toggle="tab"]').on("shown.coreui.tab", function (e) {
    if (e.target.dataset.tab == "my-desired-tab") {
        __initSelect2();
    }
});
```
Fortunately bindings (like `$(...).on("change", ...)`) are not being detached after reinitializating the element, so you won't lose functionality.

I wish you people include something like `.select2("refresh")` in the future to avoid doing horrible workarounds like this one :disappointed:

**Comment by mertsei** [comment] 2023-02-10 18:58
Found a simple and hassle-free solution, without the need to manually set any styles or anything like that.
I would just add an `addEventListener('resize')` along with a function that calls `.select2('destroy')` on all the inputs that I want to be resized, so that they could be initialized again — with a slight delay, which seems to be necessary but is unperceivable amidst other resizing/replacement happening on the page:

``` js
window.addEventListener('resize', fleetFiltersResize);

function fleetFiltersResize() {
    setTimeout(function() {
        for (let i = 1; i <= filtersItem.length; i++) {
          $(`.fleet-filters__item.${i}`).select2('destroy');
        }

        fleetFiltersInitialize();
    }, 300);
}
```
