### ISSUE TITLE
Can't Close Select2 on select an option

### ISSUE THREAD

**Issue by Mursivic** [select2/select2#5499] opened 2019-05-02 10:31 UTC
Hey there , 
I'm having a trouble in closing the select2 appended list <UL> after i choose an option , this issue exists only in the lat version of select2 , but the earlier versions don't ,

**Comment by maurofmferrao** [comment] 2019-05-02 10:40
I'm having the same problem on version 4.0.6 (version 4.0.5 works). Somehow the dropdown search is adding **data-select2-id** to several DOM elements, outside the target select2 object.

The bug is being reported in stackoverflow: https://stackoverflow.com/questions/55949585/jquery-select2-not-closing-anywhere-also-not-on-their-own-website

And as this user states, it happens in the official doc page too: https://select2.org/getting-started/basic-usage.

**Comment by martinbroos** [comment] 2019-05-02 12:39
This is fixed in 4.0.7-rc.0

**Comment by stevepiercy** [comment] 2019-05-02 20:42
I reported it in the forum, too. Glad it's not just me.
https://forums.select2.org/t/demos-selecting-option-does-not-dismiss-list-of-options/730

**Comment by WebDevEtc** [comment] 2019-05-03 07:10
FYI, as a temporary fix: reverting to an older version (4.0.3) seems to work (tested only in Chrome)

**Comment by tfbrito** [comment] 2019-05-06 14:13
This problem is occurring in the version 4.0.6 that is marked as latest release. There should be another stable version with the fix otherwise people may update and have problems on there pages.

**Comment by kevin-brown** [comment] 2019-05-06 17:09
This is a duplicate of https://github.com/select2/select2/issues/5490 and fixed in Select2 4.0.7-rc.0.

**Closed by kevin-brown** 2019-05-06 17:09 UTC
