### ISSUE TITLE
Uncaught TypeError: Cannot read property 'select2' of undefined

### ISSUE THREAD

**Issue by cloudybrain** [select2/select2#3800] opened 2015-09-28 05:55 UTC
I'm not really sure how to explain what's happening here, but I'm trying to wrap up my select2 plugin as a reactjs component, the way I do it is I remove all the "<option>" and fill it up when a new dataset is given. When I click the dropdown, I get no error, when I make a new selection, and click the same dropdown to open it again I get the aforementioned error:

Uncaught TypeError: Cannot read property 'select2' of undefined

And I saw that the error is located in this section of the code (found in select.full.js):

```
             $all.each(function () {
                  var $this = $(this);
                  if (this == $select[0]) {
                      return;
                  }
                  var $element = $this.data('element');
                  $element.select2('close');
              });
```

If I simply open the dropdown, this == $select[0] is equal to true, and everything is great.. but after I make the selection, and I open the same dropdown, this == $select[0], is false, and $element can't be found. Is it really wise to check the equality of two jquery objects? The functionality on my page is working, and everything seems to be great, but it's just annoying to see this error in my console, when it's not really an error. What are you really checking for here?

**Comment by anyexinglu** [comment] 2016-11-27 08:30
I have the problem "Uncaught TypeError: Cannot read property 'select2' of undefined" too,
But I saw that the error is located in this section of the code (found in [line 5656 of select.js](https://github.com/select2/select2/blob/563198a4a2e0eb9f7adbc4775d360db1037a13db/dist/js/select2.js#L5656)):
`if ($.fn.select2 == null) {`
So I add the code before that line
`!$.fn && ($.fn = {})`
 Then the problem solved.

**Comment by alexweissman** [comment] 2017-12-14 22:14
This appears to be a duplicate of #3282.

**Closed by alexweissman** 2017-12-14 22:14 UTC
Labels: status: possible bug (unconfirmed)
