### ISSUE TITLE
Not enough Keyboard accessibility capabilities

### ISSUE THREAD

**Issue by weisborg** [select2/select2#6093] opened 2021-09-10 16:29 UTC
If I have a user that mostly uses keyboard or can only use keyboard or other device that functions like a keyboard, then this is not functional enough for them.  Tabbing into it does nothing without Spacbar or Enter.  If the list has the search box they can type and filter the list hitting Enter or Tab (Tab needs hit twice, when one tab should go to the next input) to select it.  I can do something to show the list on focus, but if the list has no search box they can't type letters to jump to those entries like a standard select, so they are limited to scrolling up and down with the arrow keys that won't work well for visually impaired.  This makes me have to show the Search Box at all times...even small boxes like Male/Female.

Might want to model this after the old Bootstrap Combobox library a little there.  The developer gave up on it, but I've been heavily modifying it to work for my company.  It has the search box as part of the main control and when you tab into it you are in the text input of it.  Their arrow changes to the X to clear, so easier to click and doesn't render the bottom border jagged.  Its main downfall is taking the name away from the select and putting it on the text input making it harder to read values, and it has events to update the value(One of my modifications since JavaScript value changes doesn't trigger anything) and list instead of triggering change to do both like this does.

**Comment by kevin-brown** [comment] 2021-12-04 00:50
So I'm going to largely call this a duplicate of https://github.com/select2/select2/issues/3472 since the issue is mostly around Select2 dropdowns and the keyboard accessibility issues there.

**Closed as completed by kevin-brown** 2021-12-04 00:50 UTC
