### ISSUE TITLE
select2 element loses focus if enclosed in <label> tag - v4.0.2

### ISSUE THREAD

**Issue by magveda** [select2/select2#4304] opened 2016-04-13 11:05 UTC
When selecting the select2 element it is losing focus if it is inside the <label></label>

https://jsfiddle.net/gpson/xst6jbkq/

**Comment by kevin-brown** [comment] 2016-04-13 22:29
This is a duplicate of https://github.com/select2/select2/issues/4203.

**Closed by kevin-brown** 2016-04-13 22:29 UTC
