### ISSUE TITLE
Tags true does not work with jQuery 3.4.1

### ISSUE THREAD

**Issue by PHPist** [select2/select2#5547] opened 2019-06-25 22:31 UTC
[test](https://jsbin.com/qitaqawapi/edit?html,output)

**Comment by PHPist** [comment] 2019-06-25 22:58
[test](https://jsbin.com/qitaqawapi/edit?html,output)

**Comment by kevin-brown** [comment] 2019-06-26 01:58
Duplicate of https://github.com/select2/select2/issues/5516.

**Closed by kevin-brown** 2019-06-26 01:58 UTC
