### ISSUE TITLE
Gap left between textinput and selection label after searching, closing and reopening

### ISSUE THREAD

**Issue by alicansa** [select2/select2#4848] opened 2017-03-23 14:44 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Allow clear and allow select2 to show results on clear.  As shown here : [http://imgur.com/VTxtpzh](url)
2. Use select2 to show some results.
3. Click outside and close the results panel. 
3. Force select2 (position the element at the bottom of the page) to show results above the input
4. Either click on the textinput or clear the field using the cross, i.e force the select2 to show the textinput. Result is as shown here: [http://i.imgur.com/valcbPM](url)

## Expected behavior and actual behavior

When I follow those steps, I see a gap between text input and the selection label which shows the result. The gap is caused by the fact that the results are deleted after the textinput is repositioned. So if another positioning event is triggered afterwards (such as scrolling) the gap disappears. 

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- Select2 version: 4.0.3

**Comment by alexweissman** [comment] 2017-09-17 02:17
Duplicate of #4614.

**Closed by alexweissman** 2017-09-17 02:17 UTC
