### ISSUE TITLE
Dynamic Change Options Using Array Data Source

### ISSUE THREAD

**Issue by ZhaofengWu** [select2/select2#5038] opened 2017-09-13 14:46 UTC
In the documentation, Ajax and Array are juxtaposed as two types of data sources. However, it looks like the latter is less flexible than the former. With Ajax, you can dynamically alter the options _as the input string changes_, as well as having pagination. I wonder if you can do the same with javascript array?

I.e. I want to move the computation from back-end to front-end, while maintaining the ability to dynamically change the options (and hopefully pagination). Is that possible?

I am aware of the existence of matcher, but I want a little more control than simple filtering.

Note that this is not a duplicate of #2830.

**Comment by alexweissman** [comment] 2017-09-13 15:24
So with Ajax, `<option>` elements actually don't even get created until they are selected for the first time.  Contrast this with an Array source, where all the `<option>`s are created immediately on initialization.

I'm wondering - what is the point of using pagination, if you want to preload all of the options on the client-side anyway?  Generally, pagination is used to decrease the response size, and reduce the burden on the client for rendering all of the options up-front.

Please join me on my [chat server](https://chat.userfrosting.com/channel/select2) to discuss this further.

**Comment by alexweissman** [comment] 2017-09-14 00:04
I'm actually going to close this as a duplicate of #4621.

**Closed by alexweissman** 2017-09-14 00:04 UTC
Labels: question

**Comment by muthu32** [comment] 2017-12-06 07:35
#4621 is not a duplicate of this issue. Solution for "handling huge amounts of data" is ajax with pagination. But this solution is not applicable on this issue. Please reopen this issue and make a valid api to change data dynamically.
