### ISSUE TITLE
[Question] Ajax remote data : keep the results after closing the dropdown 

### ISSUE THREAD

**Issue by flashios09** [select2/select2#3745] opened 2015-09-07 20:27 UTC
Hi @kevin-brown ,
Thanks for this awesome plugin :+1: 
Sorry for my bad english 
I have an ajax request that get a list of items but every time that i choose a value, close the dropdown and re-open the it i loose the remote data :(
How can i keep the results after closing the dropdown ?

**Comment by jcspader** [comment] 2015-09-10 19:36
Guy, try create the $.ajax function and setting select2 data.

Like this:

```javascript
$.ajax()
.done(function(data){
	$("select")select2({
		 data: $.map(data, function (obj) {
			 return {
				 id: obj.Value,
				 text: obj.Text
			 };
		 })
	 });
});
```

**Comment by alexweissman** [comment] 2017-12-15 04:31
Seems like this is a duplicate of #3649.

**Closed by alexweissman** 2017-12-15 04:31 UTC
Labels: feature: ajax
