### ISSUE TITLE
Maximum call stack exceeded on dependent dropdown

### ISSUE THREAD

**Issue by abdallahmaali** [select2/select2#4544] opened 2016-08-22 11:00 UTC
i have tow dropdown  the first one show the item number ,and the second one show the item
number  so the user can select the item by select it by item number or by item name 

i create simple on change function to update another dropdown value 

```
//////for set Blocks Number and Blocks name Equal each a other  when dropdown changed /////////

   $(document).on("change", "#general_info_block_number", function () {
        id = $(this).val();
        // $('#general_info_block').val(id);
        $("#general_info_block").select2().select2('val',id);`
    });
    $(document).on("change", "#general_info_block", function () {
        id = $(this).val();
        // $('#general_info_block_number').val(id);
        $("#general_info_block_number").select2().select2('val',id);

    });
```

> and i'm trying  multiple command to set value but  i have same problem 
> **Maximum call stack exceeded on dependent dropdown**

any one could help me please ?

**Comment by willmacdonald** [comment] 2016-10-04 12:30
Me too. I'm testing in latest chrome & firefox. I'm using v4.0.3. Same problem in 4.0.1.
I'll try 4.0.0 next.

**Comment by alexweissman** [comment] 2017-12-08 22:00
Looks like your code could have an infinite recursion due to a cyclical dependency.  At any rate, this appears to be a usage question, not a bug or feature request, so I am closing it.

Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.

**Closed by alexweissman** 2017-12-08 22:00 UTC
