### ISSUE TITLE
when use multi-select with [closeOnSelect: false] each time you select option the menu scroll to the first option. v4.0.3

### ISSUE THREAD

**Issue by AWasseem** [select2/select2#4417] opened 2016-06-13 17:57 UTC
when use multi-select with [closeOnSelect: false] each time you select option the menu scroll to the first option .
then  scroll again down to select another option its do not keep the last position i stood on v4.0.3
example:
1- select (a)

![image](https://cloud.githubusercontent.com/assets/18052887/16017614/fb29c024-31a0-11e6-9e23-f84e55f79079.png)

2- after select (i) the menu scroll to (a) again

![image](https://cloud.githubusercontent.com/assets/18052887/16017606/f621d63e-31a0-11e6-8220-6ebfcf816917.png)
## Environment

Libraries
- Select2 version:4.0.3

**Comment by jgbishop** [comment] 2016-09-05 13:01
This bug is a byproduct of the commit to fix #4238. I'm not sure what the best course of action on this is, but I'd argue that the auto-highlight feature should be adjusted to work either only in the infinite scroll case (while the popup is open and the user is scrolling), or via a user-set option.

**Comment by EstherAF** [comment] 2016-10-27 08:07
Totally agree with @jgbishop here. I don't know enough about this project to try to fix this by myself and make a pull request.
If @AlexanderLeonov is not answering, @kevin-brown may have an opinion about how to tackle this issue...
By now, I'm downgrading to 4.0.2, where this issue is not happening.

**Comment by AlexanderLeonov** [comment] 2016-10-30 15:28
@jgbishop, you are not entirely correct. I've walked through the commits and discovered that this change was actually introduced by the commit [9f58128](https://github.com/select2/select2/commit/9f581285d88128b29a01fc1e5fd2d445d610b553), particularly by adding `this.ensureHighlightVisible();` call in the `highlightFirstItem()`. What is more interesting is that the behavior had not actually changed a lot - the first item had been highlighting even before my commit, it just hadn't been forced to scroll into view until @kevin-brown added above call.
So, I guess the solution would be to remove `this.ensureHighlightVisible();` call, but I'm not sure why it was done in the first place.
@kevin-brown, can you please comment this moment?

**Comment by iangus** [comment] 2017-01-03 14:47
The issue stems from the call to self.highlightFirstItem() on line 279 of results.js. This was introduced in commit [e897d00](https://github.com/select2/select2/commit/e897d008a672da262ba84cee2a144578696ada29) as self.focusFirstItem(). @kevin-brown @AlexanderLeonov, why is this call made on select? Is there any reason for highlighting the first selected element on selection? Removing this call will solve the issue.

**Comment by aristidesfl** [comment] 2017-01-06 16:19
#4682 is a duplicate of this?

**Comment by phazei** [comment] 2017-03-23 16:52
There's a proposed solution in #4584 
```js
if(!(self.options.get('multiple') && !self.options.get('closeOnSelect'))) {
  self.highlightFirstItem();
}
```

**Comment by alexweissman** [comment] 2017-09-25 18:06
#4869 also addresses the problem.  This solution needs to be compared to the solution proposed in #4584, which is to add some logic to conditionally invoke `self.highlightFirstItem()`:

```
if(!(self.options.get('multiple') && !self.options.get('closeOnSelect'))) {
  self.highlightFirstItem();
}
```

@MicahBrown could you please take a look at this?

**Comment by smalezan** [comment] 2017-11-16 13:02
Find this part of the select2.min.js and delete it.

,f=this.$results.scrollTop()+(e-d),g=e-d;f-=2*a.outerHeight(!1),c<=2?this.$results.scrollTop(0):(g>this.$results.outerHeight()||g<0)&&this.$results.scrollTop(f)

It worked for me

**Comment by alexweissman** [comment] 2017-11-19 03:17
@smalezan deleting minified, compiled code is literally the worst possible way to solve a problem like this.  Please take some time to learn about version control, minification, and the general concept of a "build step" in deploying an application.

**Comment by nikhilzac95** [comment] 2018-02-15 10:54
@kevin-brown @alexweissman is there update regarding this? Is there a way to fix this issue?

**Comment by marcioJesus** [comment] 2018-03-21 18:05
@kevin-brown @alexweissman any news for fix this issue?
Has the same behaviour in version 4.0.5
The good suggestion for solution is this PR [#5150](https://github.com/select2/select2/pull/5150#pullrequestreview-105830441)

**Comment by pedrofurtado** [comment] 2018-03-21 18:53
@kevin-brown @alexweissman It's good to add this fix in next release (4.0.6). So, all users can get this fix.

**Comment by james-simpson** [comment] 2018-05-24 09:38
@kevin-brown @alexweissman I've had to put this work around manually into our version, is there any update of whether this will make it into the 4.0.6 release? It doesn't currently seem to be in the milestones.

**Comment by danreg** [comment] 2018-07-02 12:35
@kevin-brown @alexweissman could you please put this fix into a release?

**Comment by eugeneborodkin** [comment] 2018-09-11 14:26
This is horrible. The Multi-Select is almost unusable because of this auto-top-scroll on every selection. How come this isn't part of the plugin yet? When will this be fixed? What should we do in the meantime (it's Sep. 2018 currently)?

**Comment by eugeneborodkin** [comment] 2018-09-11 17:10
****Current solution which works for me***
https://stackoverflow.com/a/48928317/1005607

Replace this _highlightFirstItem function() {...}_ to be  "{return false;}" as below:

`c.prototype.highlightFirstItem=function(){return false;}`

**Comment by pedrofurtado** [comment] 2018-09-11 18:45
This issue can be closed. The solution is already merged in https://github.com/select2/select2/pull/5150 . There are some docs improvements (these links is in the PR page) to explaining how to config select2 to fix this bug.
In the next release, this change will be available for all users.

**Closed by pedrofurtado** 2018-09-11 18:45 UTC
Labels: 4.x, confirmed bug

**Comment by nikhilzac95** [comment] 2018-09-12 09:35
When would the next release be @pedrofurtado ?

**Comment by nikhilzac95** [comment] 2018-09-12 11:31
Thanks for the update @pedrofurtado 👍

**Comment by Ankita9818** [comment] 2018-10-23 13:19
When would the next release be @pedrofurtado ?

**Comment by risingtalent22** [comment] 2019-04-16 07:49
@pedrofurtado , this issue still remains in v4.0.6-rc.1.

**Comment by shahimclt** [comment] 2019-04-30 16:08
Just got released: https://github.com/select2/select2/releases/tag/4.0.6

**Comment by eugeneborodkin** [comment] 2020-03-30 16:12
Although Version **4.0.6** fixes this Autoscroll-To-First bug in MultiSelect, another bug got introduced in this version.
If I have multiple Select2's on the page, some of which are **flat single-select** dropdowns, those dropdowns are now broken. When I open a flat single-select, I can no longer close it; the popup stays open.
I only solved this and got all Select2's to work (both multi and single) when I went back to **4.0.6 RC1** and manually made this modification,
_`c.prototype.highlightFirstItem=function(){ **return false;** }`_

Now I can close my flat single-selects, AND avoid the autoscroll-to-first in multi-selects.

**Comment by kevin-brown** [comment] 2020-03-30 23:39
> Now I can close my flat single-selects, AND avoid the autoscroll-to-first in multi-selects, all on the same page.

Have you considered upgrading to the latest version of Select2, 4.0.13?

**Comment by click2cloud-Sohel** [comment] 2021-01-07 09:24
By Removing  this.ensureHighlightVisible() from select2.js work for me

**Comment by hemant-rao** [comment] 2021-03-23 15:06
this code working fine for my side, I hope this will help you.

$('#selectmultiple').select2({
    closeOnSelect: false
})
 .on('select2:selecting', e => $(e.currentTarget).data('scrolltop', $('.select2-results__options').scrollTop()))
 .on('select2:select', e => $('.select2-results__options').scrollTop($(e.currentTarget).data('scrolltop')));
