### ISSUE TITLE
Placeholder width bug with multiselect2

### ISSUE THREAD

**Issue by Arkayus** [select2/select2#4323] opened 2016-04-22 17:37 UTC
In the lastest version of select2, If a select is not visible when select2 init it, the select2 will not have the width of the select but will have always 100% and the placeholder will always have 100px. Why ?

Also, i'm able to reproduce it on your website, in the examples section.

**Comment by kevin-brown** [comment] 2016-04-23 18:05
I wasn't able to reproduce this in the examples page, but I also may have misinterpreted the issue.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by ShudhPandit** [comment] 2016-04-28 08:24
Here is your jsfiddle:

https://jsfiddle.net/km1adzaq/

The second field-set doesn't shows full placeholder

**Comment by maodei** [comment] 2016-05-24 04:59
Yes, I saw this problem too. An example is put a select2 control in a tab which is initially not active, and then when activate that tab, you see the select2 placeholder only partially displayed.

Is there any fix or workaround available?

Thanks

**Comment by dellch** [comment] 2016-06-02 22:23
Here is a simple example of the problem http://jsfiddle.net/say2rwmt/4/ using bootstrap tabs to initially hide the select2.  When you click the second tab, you'll see the placeholder is truncated.

Note: as soon as you enter text, and backspace, the placeholder resets to it's correct size.  

A workaround for this specific instance is to hook into the tab shown event and (re)initialize select2: 
`
$('a').on('shown.bs.tab', function(){ $(".s2").select2(); });
`

**Comment by dellch** [comment] 2016-06-03 14:32
Found a possible fix (lines 2009-2011 in select2.js, or 2005-2007 in select2.min.js reproduced below).
Originial fiddle with problem: http://jsfiddle.net/say2rwmt/4/
Updated fiddle with fix:  http://jsfiddle.net/br917x0b/1/
Change:
```javascript
if (this.$search.attr('placeholder') !== '') {
    width = this.$selection.find('.select2-selection__rendered').innerWidth();
} else {
```

to:

```javascript
if (this.$search.attr('placeholder') !== '') {
    width = this.$element.innerWidth();
} else {
```

Small issue in that if the placeholder is longer than the available width, there is no nice padding at the end, it just gets cut off when the element ends:

**Comment by dellch** [comment] 2016-06-03 14:57
Haven't had time for much testing but possible fix/workaround around line 2005 (in select2.min.js):

Original fiddle (with problem): http://jsfiddle.net/say2rwmt/4/
Updated fiddle: http://jsfiddle.net/br917x0b/3/

Original:
```javascript
if (this.$search.attr('placeholder') !== '') {
    width = this.$selection.find('.select2-selection__rendered').innerWidth();
} else {
```

changed to:
```javascript
if (this.$search.attr('placeholder') !== '') {
    width = this.$element.width() === 1 ? this.$selection.width() : this.$element.width();
} else {
```

**Comment by maodei** [comment] 2016-07-06 12:44
` $('a').on('shown.bs.tab', function(){ $(".s2").select2(); }); `
this workaround works while
`if (this.$search.attr('placeholder') !== '') {
    width = this.$element.width() === 1 ? this.$selection.width() : this.$element.width();
} else {`
dose not work.

**Comment by SgtOddball** [comment] 2016-07-19 11:08
I've come across the same issue too, except I'm drawing the select2 elements on page load. 

I've noticed also that even if you replace the placeholder's length of 100px with 100% it still doesn't display correctly since the wrapping li doesn't span the whole line (specifically the li with the select2-search select2-search--inline which requires the following class in the CSS to have `width:100%` applied .select2-container .select2-search--inline).

The remaining issue then is that the final input box inside of the above li is being set to 100px via inline styling and thus can't be overwritten in the CSS file. I'll look to see if I can spot where it's being applied to the input.

**Comment by SgtOddball** [comment] 2016-07-20 10:28
Also worth noting that If you select a value then remove it, then the correct width does get applied to the placeholder instead of the 100px.

Could it be that the width is being gotten before the select box has been drawn on the DOM leading to a default value being used instead? So that when the values are changed and then blanked, the select box is present and a correct width can then be applied? Just a hunch at any rate.

Finally as a side note, I tried seeing exactly where the placeholder triggers the width value functions (of which there are a few) but the only one that default to 'px' weren't being triggered. Quite confusing really.

**Comment by Cruiser13** [comment] 2017-04-12 16:03
Same issue, my css solution:
`
.select2-search__field {
	width: 100% !important;
}
`

**Comment by sourovroy** [comment] 2017-10-10 07:35
Thanks @dellch , i fixed this in my end by your code. 
Thank you

**Comment by EricJZell** [comment] 2017-11-08 22:52
@Cruiser13 's solution worked for me, but I also had to include the li element:
```
.select2-search--inline, .select2-search__field { width: 100% !important; }
```

**Comment by alexweissman** [comment] 2017-11-18 22:17
There is a better discussion of this problem in #4513, so I am closing this discussion.

**Closed by alexweissman** 2017-11-18 22:17 UTC
Labels: needs information
