### ISSUE TITLE
Removing every second option closes the dropdown

### ISSUE THREAD

**Issue by donruperto** [select2/select2#6033] opened 2021-05-18 13:39 UTC
Hi,

using Select2 with the option `data-close-on-select=false` causes the dropdown to close on every second remove-click on a selected option. It should stay open until i force to close it.

demo can be found here: [JsFiddle](https://jsfiddle.net/mukL6ag8/4/)

steps to reproduce:
* click into select
* select all 4 options
* close select by clicking next to "Option 4"
* remove "Option 4" => select opens
* remove "Option 3" => select closes
* remove "Option 2" => select opens again

**Comment by kevin-brown** [comment] 2021-05-21 01:55
You're seeing the side effect of a different issue (that's marked wontfix): clicking the clear button or the remove button toggles the drop-down. What you're really seeing is it toggle every time, not just it opening every second time.

Duplicate of https://github.com/select2/select2/issues/3320

**Closed as completed** 2021-05-21 01:57 UTC
