### ISSUE TITLE
[4.x] Focus on tab not working

### ISSUE THREAD

**Issue by patrickbrouwers** [select2/select2#3441] opened 2015-06-05 11:30 UTC
What I want to achieve is when user hits `TAB` and lands on a select2 box, they can immediately start typing without having to click on the element. This does not seem to work. It also seems that 4.x doesn't have a focus event anymore, so I can't trigger it manually.

Jsbin:
http://output.jsbin.com/safalu/1/

**Comment by kevin-brown** [comment] 2015-06-05 13:09
Duplicate of https://github.com/select2/select2/issues/3279#issuecomment-96450069, the reasons behind the current behaviour are described there.

We do have plans on automatically focusing the search field when the container is focused (on multiple selects) though (https://github.com/select2/select2/pull/3415) but that's going to land in 4.0.1.

**Closed by kevin-brown** 2015-06-05 13:09 UTC

**Comment by patrickbrouwers** [comment] 2015-06-05 13:38
Thanks!
