### ISSUE TITLE
Select2 multiple, Ajax doesn't trigger with preselected data

### ISSUE THREAD

**Issue by CallYourPlayer** [select2/select2#5131] opened 2017-11-15 08:57 UTC
I have a select2 multiple, that has to be filled with cities names starting with the first characters that the user inserts into the search field. When I open the page to create a new object, this works fine, but when I open the page in edit mode, the values are preselected and the Ajax search isn't triggered. What I'm doing wrong? This is my select2 HTML:

div class="input-group selectNazioniCitta"
  select class="form-control select2" name="countryNotValid">/select
  span class="input-group-addon" - /span
  select class="form-control select2" name="citiesNotValid"  multiple="multiple"/select"
/div

And this is the js code where I initialize my select2
function updSelCitta(elem, country, city) {
var o = "actionMethod/action.aspx/doGetCitiesSpecialOffer", sel = $(elem).find('select[name*="citiesNotValid"]');
    cities = city.split(';');
    for (var i = 0; i < cities.length; i++) {
        if (cities[i] == "") {
            initialData.push({
                id: "-1",
                text: "Tutte"
            });
            //options += "<option value=\"-1\" selected>Tutte</option>";
            selectedData.push("-1");
        } else {
            initialData.push({
                id: cities[i],
                text: cities[i]
            });
            options += "<option value=\"" + cities[i] + "\" selected>" + cities[i] + "</option>";
            selectedData.push(cities[i]);
        }
    };
    $(sel).val([]);
    $(sel).append(options).trigger("change");
    $(sel).select2({
      language: "it",
      placeholder: {
        id: "-1", 
        text: "Tutte"
      },
      width: "100%",
      multiple: true,
      allowClear: true,
      ajax: {
        delay: 500,
        type: "POST",
        contentType: "application/json; charset=utf-8",
        url: o,
        dataType: "json",
        cache: 1,
        data: function (params) {
            var query = JSON.stringify({
                country_code: country,
                search: params.term
            })
            return query;
        },
        processResults: function (t) {
            return {
                results: $.map(JSON.parse(t.d), function (obj) {
                    if (obj.city_name == "-") {
                        return { id: "-1", text: "Tutte" };
                    }
                    return { id: obj.city_name, text: obj.city_name };
                })
            };
        },
        error: function (t, o, i) {
            var n = "Error. Check parameters";
            })) : console.log(n)
        }
    },
    minimumInputLength: 2,
});

**Comment by alexweissman** [comment] 2017-11-19 02:57
PLEASE.  USE. MARKDOWN.

Also, this is a USAGE question, not a bug report or feature request.  So, it is very obvious that you did not read the issue guidelines.  Closing.

**Closed by alexweissman** 2017-11-19 02:57 UTC
