### ISSUE TITLE
Select2 "tags" mode loses focus while entering tags in Internet Explorer

### ISSUE THREAD

**Issue by kirkyoder** [select2/select2#4525] opened 2016-08-08 17:09 UTC
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Enable "tags" mode to allow user creation of tags.
2. Using IE11, attempt to add the tag "foo bar baz"

(You can also repro this behavior via the Select2 docs page for Tags: https://select2.github.io/examples.html#tags. The example works perfectly in Chrome, but the issue here repros in Internet Explorer.

This issue doesn't repro in 4.0.2, so this functionality regressed at some point between 4.0.2 and 4.0.3.
## Expected behavior and actual behavior

When I follow those steps, I see...

The input element loses focus after a few characters, so I'll only get "fo" in the input box & then focus goes away.

I was expecting...

To be able to type the tag, in its entirety, without losing focus: "foo bar baz".
## Environment

Browsers
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.10.2
- Select2 version: 4.0.3 (master)
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by zmeghji** [comment] 2016-08-10 19:35
We had an occurence of the same bug when using select2js with cordova for ios. Have you been able to find any workarounds?
The previous version of select appears not to allow you to create a new tag by tapping the text in the results box.

**Comment by kirkyoder** [comment] 2016-08-10 21:04
@zmeghji: I reverted back to 4.0.2 and haven't had any issues

**Comment by jlowcs** [comment] 2016-08-24 07:26
I have the same issue in IE11. It can also be reproduced here: https://select2.github.io/examples.html#tags

**Comment by jlowcs** [comment] 2016-08-24 08:11
The issue comes from the `_synSubtree` function which was added in this commit: https://github.com/select2/select2/commit/ea79a197e0ffe55aa600eed6d18cbd1c804c3176

If I comment the content of the function, the issue disappears.

More specifically, the `self.trigger('selection:update', ...)` line in that function seems to be the culprit.

Then, if I continue following the thread, I end up on `Search.prototype.update`. In there, I see that we append `$searchContainer`, then refocus on `$search` if there was focus before. It seems that it is because of that code that we tend to lose the focus.

Here's a fix that seems to work:
```javascript
  Search.prototype.update = function (decorated, data) {
    var searchHadFocus = this.$search[0] == document.activeElement;

    this.$search.attr('placeholder', '');

    decorated.call(this, data);

    //FIXED: add the following check to avoid appending the element if it's already there
    if (this.$selection.find('.select2-selection__rendered').find(this.$searchContainer).length) {
    	this.resizeSearch();
    	return ;
    }

    this.$selection.find('.select2-selection__rendered')
                   .append(this.$searchContainer);

    this.resizeSearch();
    if (searchHadFocus) {
      this.$search.focus();
    }
  };
```

What do you guys think? Does it seem right to you? Should I submit a PR with that fix?

**Comment by mitja-p** [comment] 2016-09-23 22:07
For me it did not work for multi select tags. I had to also fix how this function works:
MultipleSelection.prototype.update
    Utils.appendMany($rendered, $selections, true /* prepend */ );

With the following functions modified:

MultipleSelection.prototype.clear = function () {
    this.$selection.find('.select2-selection__rendered').children('.select2-selection__choice').remove();
  };

  /* This one does not support jQuery 1.7 anymore)
  Utils.appendMany = function ($element, $nodes, prepend) {
    // jQuery 1.7.x does not support $.fn.append() with an array
    // Fall back to a jQuery object collection using $.fn.add()
    if ($.fn.jquery.substr(0, 3) === '1.7') {
      var $jqNodes = $();

      $.map($nodes, function (node) {
        $jqNodes = $jqNodes.add(node);
      });

      $nodes = $jqNodes;
    }
    if (prepend)/* modified  */
      $element.prepend($nodes);
    else
      $element.append($nodes);
  };

The problem is not only in IE but also on mobile devices where loss of focus causes Windows phone 8.1 browser and iOS 7.1.2 browser to lose focus and therefore prevent you from entering a tag till the end.

**Comment by Davidrl1000** [comment] 2017-01-03 17:36
I reverted back as @kirkyoder and it worked for me

**Comment by biegl** [comment] 2017-01-18 16:05
Tagging is still broken in 4.0.3.

**Comment by GrgDmr** [comment] 2017-03-28 13:10
+1

**Comment by kartikluke** [comment] 2017-07-18 15:04
I get the issue even after downgrading.

**Comment by sam-simpleclick** [comment] 2017-07-25 13:45
Rolling back to 4.0.1 fixes the issue for me

**Comment by alexweissman** [comment] 2017-10-03 21:48
I'm actually closing this as a duplicate of #4398.  Please continue any further discussion there.

**Closed by alexweissman** 2017-10-03 21:48 UTC
