### ISSUE TITLE
select2 focus is not working for tab order

### ISSUE THREAD

**Issue by gowriprasanthvm92** [select2/select2#4426] opened 2016-06-16 07:12 UTC
## Expected behavior and actual behavior

From input if I use tab it will focus on select2. On focus, content message should change. but content message is not updating.

https://jsfiddle.net/Lupj6oaw/

**Comment by kevin-brown** [comment] 2016-06-16 21:38
This is a duplicate of https://github.com/select2/select2/issues/3876.

**Closed by kevin-brown** 2016-06-16 21:38 UTC
