### ISSUE TITLE
How to hide selected values in the drop down for a multi select box

### ISSUE THREAD

**Issue by kumaroswal** [select2/select2#3177] opened 2015-03-19 22:15 UTC
I have been using version 3.4.8. 
I was using the multi select drop down in that.
Once we select a value from the dropdown it automatically gets hidden.
In 4.0 it seems to be highlighted in grey and removes itself if clicked again which isnt expected and is not intuitive at all.
Please help me achieve the same old functionality for all browsers.
I tried this and it worked for ie 10 11 but doesnt work for ie 8 and 9 in quirks mode.
 .select2-results__option[aria-selected="true"] {
        display: none;
    }

**Comment by kevin-brown** [comment] 2015-03-19 22:49
Duplicate of https://github.com/select2/select2/issues/3046.

**Closed by kevin-brown** 2015-03-19 22:49 UTC

**Comment by martin9970** [comment] 2024-02-02 05:24
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.jquery.min.js"></script> 
 use this script and use this class (((  multiple class="chosen-select"     ))))  to hide the selected value
