### ISSUE TITLE
close mark (×) is not working

### ISSUE THREAD

**Issue by vetrivivek** [select2/select2#4938] opened 2017-06-05 10:05 UTC
i am using select2 in angularjs.I can close selected value atleast more than two.it it has less than 2 values i cannot close.can you tell me the solution for this problem

Thanks in advance

**Comment by alexweissman** [comment] 2017-09-25 03:28
I'm closing this as a "low-quality issue".  My guess is that this is probably a duplicate of other issues related to removing selections anyway.

**Closed by alexweissman** 2017-09-25 03:28 UTC
