### ISSUE TITLE
Select2 4.0 in bootstrap modal

### ISSUE THREAD

**Issue by ArtemLubimov** [select2/select2#4393] opened 2016-05-30 20:17 UTC
Hi, I need to use select2 (multiple and single) with search in bootstrap modal, but when i try using it, i can't see options, it seems like select2 open, but modal hide them. How can i fix it?

**Comment by cigaar** [comment] 2016-05-31 08:11
This is what I did; it seems to work on 4.0.x:
```javascript
element.on("select2:open",function(event){
			var modal = element.closest('.modal');
			if(modal[0]){
				var modalZ=modal.css('z-index');
				var newZ=parseInt(modalZ)+1;
				element.data('select2').$container.css('z-index',newZ);
				element.data('select2').$dropdown.css('z-index',newZ);
				element.data('select2').$element.css('z-index',newZ);
				element.data('select2').$results.css('z-index',newZ);
				element.data('select2').$selection.css('z-index',newZ);
			}
		});
```

**Comment by SgtOddball** [comment] 2016-05-31 11:01
I think this might depend on when you trigger the select2 creation to happen, I've not seen this issue myself but then I only create the select box when the modal is being called using the 
```javascript
    $('#myModal').on('shown.bs.modal', function () {
        $('#select').select2()
    })
```
script. That way it's always in the correct position I've found.

**Comment by kevin-brown** [comment] 2016-06-07 15:16
This is a duplicate of https://github.com/select2/select2/issues/600#issuecomment-102857595.

**Closed by kevin-brown** 2016-06-07 15:16 UTC

**Comment by ArtemLubimov** [comment] 2016-06-26 17:26
I use the way that cigaar propose. It work in Chrome, but in Firefox in search input don't focus, can anyone help with this?

**Comment by ArtemLubimov** [comment] 2016-06-26 17:33
fix using - ` dropdownParent: "#modal_id"` .

**Comment by vertisan** [comment] 2016-10-02 20:18
It's not works on Bootstrap 3.3.7
