### ISSUE TITLE
Can't override tokenSeparators set to defaults

### ISSUE THREAD

**Issue by sergiz** [select2/select2#5951] opened 2020-11-24 10:06 UTC
https://jsbin.com/kibipakivu/1/edit?html,js,output

As you can see, tokenSeparators is set to select2.defaults. If you then want to override that on the actual select2 instance, the separators will be merged and not overridden.

You can easily test that, by going to supplied jsbin and start typing in select box. You can then use space or comma and new tag will be added, even though the separators were supposed to be reset to default [].

**Comment by kevin-brown** [comment] 2020-11-28 03:38
```js
 $('#example1').select2({
  tags: true,
  tokenSeparators: null,
});
```

This is one of those weird edge cases where how we apply defaults using `$.extend` comes into play, specifically because we are using a recursive deep copy. When a recursive deep copy is used for an array, it will overwrite the array contents if there is a conflict (so the contents differ) but if one side is empty, it will just merge it. This is the behaviour you're seeing here, since the two arrays are getting merged and the default is being maintained.

```js
> $.extend({a:[1]},{a:[]})
< {a: Array(0)}
> $.extend(true, {a:[1]},{a:[]})
< {a: Array(1)}
```

You can work around this by setting the value to `null` which will overwrite the array set in the defaults and do what you're expecting.

```js
> $.extend(true, {a:[1]},{a:null})
< {a: null}
```

Select2 specifically treats `null` and `[]` the same for array values for this reason (and because it makes defaults _way_ easier to set). As a result, I'm going to close off this ticket as not a bug, but I am willing to review pull requests for the documentation to improve it to make this more clear. We don't have a ton of array options so there aren't a lot of places where this will be an issue.

**Closed by kevin-brown** 2020-11-28 03:38 UTC

**Comment by sergiz** [comment] 2020-11-28 09:09
Thanks for the explanation.

What confused me is that the docs state that the default for tokenSeparators is []. So I expected if I use the default value I would get the default result.

**Comment by kevin-brown** [comment] 2020-11-28 19:48
> So I expected if I use the default value I would get the default result.

Good catch! That actually makes a lot of sense and it's unfortunate that `$.extend` doesn't work the way you or I would have expected it. I think the easy "fix" for this would be to update the documentation to reflect `null` being the actual default value for `tokenSeparators`, similar to how that is the default for `data`.

Interested in making a pull request for that?

**Comment by sergiz** [comment] 2020-11-30 09:32
I just opened a PR for it.
