### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by PatrikElfstrom** [select2/select2#2988] opened 2015-01-29 09:12 UTC
Using select2 in WordPress (v4.1) with the included jQuery will generate this error.
The error occurs on row 641:

    var $el = $(el);

Changing $ to jQuery solves the issue.
Another solution is to use your own jQuery.

And the root of the problem is:

    jQuery.noConflict();

Which WordPress adds in the jQuery file

**Comment by kevin-brown** [comment] 2015-01-29 12:05
Duplicate of https://github.com/select2/select2/issues/2985.

**Closed by kevin-brown** 2015-01-29 12:05 UTC
