### ISSUE TITLE
Drop-down list that does not appear on mobile

### ISSUE THREAD

**Issue by pandigital** [select2/select2#5672] opened 2019-10-21 07:02 UTC
Hello, 

We are currently having a problem with select2. On mobile some select refuses to open. There is no JS error. Looks like the clickable location is out of sync. You have to try hard to open the drop-down list.

**Comment by Benjamin-Adrea** [comment] 2019-10-21 09:17
Same here on desktop : 

<img width="808" alt="Capture d’écran 2019-10-21 à 11 14 25" src="https://user-images.githubusercontent.com/12295662/67192667-47949380-f3f4-11e9-9775-ee39e12231ed.png">


<img width="531" alt="Capture d’écran 2019-10-21 à 11 16 53" src="https://user-images.githubusercontent.com/12295662/67192681-4e230b00-f3f4-11e9-801f-8494be8641a1.png">

**Comment by kevin-brown** [comment] 2019-10-31 02:50
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by Benjamin-Adrea** [comment] 2019-10-31 08:35
Hello

Ok I'll try to explain.

In 4.0.10, everything is OK.
I run "yarn upgrade select2", to get on 4.0.11, and then : 

<img width="380" alt="Capture d’écran 2019-10-31 à 09 28 48" src="https://user-images.githubusercontent.com/12295662/67930810-dc4f7c00-fbc0-11e9-8f9e-62c522769d30.png">

See the display

I reproduce that on firefox AND chrome (latest versions). I am on macOs (10.15.1)

Other packages : 

```
{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.27.0",
        "autoprefixer": "^9.6.0",
        "core-js": "^3.0.0",
        "jquery": "^3.4.1",
        "materialize-css": "^1.0.0",
        "node-sass": "^4.12.0",
        "postcss-loader": "^3.0.0",
        "sass-loader": "^7.0.1",
        "select2": "^4.0.8",
        "webpack-notifier": "^1.6.0"
    },
    "license": "ADREA MUTUELLE",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production --progress"
    },
    "browserslist": [
        "> 1%",
        "last 2 versions"
    ]
}
```

Jquery version "3.4.1"
I use Webpack with symfony bundle (named webpack encore)

**Comment by Benjamin-Adrea** [comment] 2019-10-31 09:07
OK, so I removed the materialize-css dependancy (https://materializecss.com/) and the 4.0.11 is OK now....

So the problem is between the 4.0.11 AND materialize-css :(

**Comment by kevin-brown** [comment] 2019-10-31 11:28
There's a high probability that this is the same issue as https://github.com/select2/select2/issues/5682, given that the only change in 4.0.11 to the code also happened to cause that one. So I'm going to close this off as a duplicate for now and come back if that doesn't happen to be the same issue.

**Closed by kevin-brown** 2019-10-31 11:28 UTC
Labels: 4.x, feature: dropdown, status: possible bug (unconfirmed)
