### ISSUE TITLE
Search field can appear at a distance above where the SELECT control appears under certain circumstances

### ISSUE THREAD

**Issue by tonzagub** [select2/select2#4320] opened 2016-04-21 08:22 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of Select2
- [X] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Description

When using AJAX to load remote data for the control (as in http://select2.github.io/examples.html#data-ajax), the search field may appear at a distance above where the SELECT control appears in the HTML markup under the following circumstances:

1.  there has been a query made by the control and has obtained a valid search result beforehand,
2.  the control is located at the lower quarter of a browser window's content region, and
3.  the window has not been scrolled since the control was last used.

## Steps to reproduce the issue

- **[1]** go to http://select2.github.io/examples.html#data-ajax and scroll the browser window so that the SELECT control appears at the bottom of the browser's content region rather than at the top.
- **[2]** click on the control region.

The pop-up region containing the search field should appear directly above the SELECT control region.  Instead, there is a gap of 12 pixels above the SELECT control region.

**Firefox does not present such a large gap, but the gap is there nevertheless.**

- **[3]** type something in to make a search query and let some results appear.
- **[4]** click anywhere outside of the select2 control to dismiss the search field.
- **[5]** repeat step **[2]**.

The pop-up region containing the search field should appear directly above the SELECT control region.  Instead, there is a much larger gap above the SELECT control region.

At this point, if you repeat steps **[2]** and **[4]** repeatedly, you'll see the control will settle to doing something it is supposed to be doing.

## Expected behavior and actual behavior

See Steps to Reproduce for the behavioural descriptions.

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer

Operating System

- [X] Windows
- [X] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.12.3, 2.2.3 (tried both)
- Select2 version: 4.0.2-master (as of 21/4/2016)

## Isolating the problem

- [X] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by tonzagub** [comment] 2016-04-21 08:24
Sorry, I used Australian dates in this bug report.  Please excuse me!  Where it says:

  - Select2 version: 4.0.2-master (as of 21/4/2016)

it can also say:

  - Select2 version: 4.0.2-master (as of 4/21/2016)

as appropriate.  Thanks!

**Comment by kevin-brown** [comment] 2016-04-21 13:43
This is actually a duplicate of https://github.com/select2/select2/issues/3905, we aren't correctly fixing the position of the dropdown.

**Closed by kevin-brown** 2016-04-21 13:43 UTC

**Comment by tonzagub** [comment] 2016-04-22 07:52
Hi Kevin,

Thanks for the advice and feedback.  For the interim, the handler that was
demoed in 3905 seems to work for me, so I can use that in the meantime.

Cheers!

Tony.


On Thursday, April 21, 2016, Kevin Brown <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Closed #4320 <https://github.com/select2/select2/issues/4320>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/select2/select2/issues/4320#event-636177762>
>


-- 

*—tonza*
