### ISSUE TITLE
iPad keyboard "next" doesn't close select2 dropdown

### ISSUE THREAD

**Issue by phazei** [select2/select2#1378] opened 2013-06-03 21:08 UTC
If the dropdown is open and someone clicks the iPad keyboard shortcut for "next" or "previous" the dropdown stays open often covering the next input box.  It also doesn't open the dropdown then those buttons are used to focus to a select2 box.

**Comment by kevin-brown** [comment] 2016-06-25 18:37
This is a duplicate of https://github.com/select2/select2/issues/4013.

**Closed by kevin-brown** 2016-06-25 18:37 UTC
