### ISSUE TITLE
About initSelection

### ISSUE THREAD

**Issue by KnightHJ** [select2/select2#3794] opened 2015-09-25 02:11 UTC
I use “initSelection” to initialize the data.
The select can show the option but it dosen't has any values.
And I don' know how to use “DataAdapter.current”...

I hope someone can give me some advice.
Thanks.

```
$("#facade").select2({
					      ajax: {
					        url: "queryMethod.do",
					        dataType: 'json',
					        delay: 250,
					        data: function (params) {
					          return {
					            q: params.term
					          };
					        },
					        processResults: function (data, page) {
					        	$("#facade-alarm").tooltip('hide');
					          return {
					            results: data
					          };
					        },
					        cache: true
					      }, 
					      initSelection: function (element, callback) {
					        	var initdata = [];
								if(	data.facadeWeb != null) {
									   for(var i=0;i<data.facadeWeb.length;i++){
									       	initdata.push({ id: data.facadeWeb[i].facade_id, name: data.facadeWeb[i].facadeName });
									   }
								 }						        			        
						        callback(initdata);
						  },
					      allowClear: true,
					      escapeMarkup: function (markup) { return markup; },
					      minimumInputLength: 2,
					      templateResult: formatRepo,
					      templateSelection: formatRepoSelection
					      
					    });	    		
```

**Comment by kevin-brown** [comment] 2015-09-25 22:19
This is a duplicate of https://github.com/select2/select2/issues/3116, check that ticket for some guidance.

**Closed by kevin-brown** 2015-09-25 22:19 UTC
