### ISSUE TITLE
Dropdown detached with fixed position sidebar

### ISSUE THREAD

**Issue by ckuwanoe** [select2/select2#3614] opened 2015-07-26 02:18 UTC
I'm having some issues with using the plugin on a new site and I think it has to do with the fixed position sidebar which is causing the offset to be calculated improperly. I had a similar issue with the bootstrap datepicker plugin, but I was able to resolve that with the container option which allowed me to attach it to the correct container div. I tried the same with the new dropdownParent option with no luck. I was wondering if anyone had any similar experience with this that could point me in the right direction?

![shift - field dropdowns placement 1](https://cloud.githubusercontent.com/assets/161009/8892206/cde7baa6-3301-11e5-9e54-2db7707bd3c5.png)

![shift - field dropdown placement 2](https://cloud.githubusercontent.com/assets/161009/8892207/d46db60a-3301-11e5-8b5a-3bcd4627daa6.png)

Thanks

**Comment by kevin-brown** [comment] 2015-07-26 16:50
This sounds like a possible duplicate of https://github.com/select2/select2/issues/3303.

**Comment by ckuwanoe** [comment] 2015-07-28 05:37
As best I can tell it is related to the same issue. I tried the monkey patch in that other thread with no luck. I guess I'll have to find another plugin until someone can figure out a fix for this. Thanks for the heads up.

**Closed** 2015-11-27 22:58 UTC
Labels: 4.x, needs information
