### ISSUE TITLE
Multiple Select: Selected Option not removed from Options since 4.0

### ISSUE THREAD

**Issue by krisdigital** [select2/select2#3850] opened 2015-10-19 22:17 UTC
On the Demo-Page, after selecting "Alaska" from the dropdown in the multiple select demo, Alaska is still under the options. If selected again, it is removed from the selected tags..

A quick fix:

```css
[aria-selected="true"] {
  display:none;
}
```

**Comment by kevin-brown** [comment] 2015-10-27 23:02
This is a duplicate of https://github.com/select2/select2/issues/1538.

It's a new feature in 4.0.0 that was introduced largely for accessibility reasons.

**Closed by kevin-brown** 2015-10-27 23:02 UTC
