### ISSUE TITLE
[v4.0.1] Placeholder attribute doesn't appear to work

### ISSUE THREAD

**Issue by matt-stuart** [select2/select2#4059] opened 2016-01-05 06:13 UTC
The following select:
```
<select name="country" id="country" placeholder="Select Country.." data-required="1" class="select2 w300" data-field="country" tabindex="-1" aria-hidden="true">
<option value=""></option>
<option value="Canada">Canada</option>
<option value="United States">United States</option>
<option value="Afghanistan">Afghanistan</option>
</select>

<script type="text/javascript">
$('#country').select2();
</script>
```
Does **not** produce a select2 w/ a place holder which is how the documentation and previous versions worked. Also, there's a "blank" element right below the search. Using: 
```
<select name="country" id="country" data-placeholder="Select Country.." data-required="1" class="select2 w300" data-field="country" tabindex="-1" aria-hidden="true">
<option value=""></option>
<option value="Canada">Canada</option>
<option value="United States">United States</option>
<option value="Afghanistan">Afghanistan</option>
</select>

<script type="text/javascript">
$('#country').select2();
</script>
```
**Does** produce a select2 w/ a place holder and no blank element.

**Comment by kevin-brown** [comment] 2016-01-05 15:33
`placeholder` is not a valid attribute for a `<select>` element. So Select2 requires that you use `data-placeholder` instead.

It _is_ a valid attribute for `<input />`, which is why older versions of Select2 supported it. Now that we are requiring a `<select>` for pretty much everything, it's not supported.

This is a duplicate of https://github.com/select2/select2/issues/3555.

**Closed by kevin-brown** 2016-01-05 15:33 UTC
