### ISSUE TITLE
Multiple select erases text when trying reposition cursor with mouse

### ISSUE THREAD

**Issue by rywall** [select2/select2#3517] opened 2015-06-23 23:00 UTC
To repro:
1. Go to https://select2.github.io/examples.html#multiple
2. Type "Hello World" in the multiple select
3. Try to use your mouse to reposition the cursor between 'Hello' and 'World'
4. Notice the whole phrase is deleted.

**Comment by kevin-brown** [comment] 2015-06-25 17:38
It looks like the `click` is propagating up to the container is causing it to toggle.

**Comment by tholu** [comment] 2017-09-06 14:31
@kevin-brown This bug is really annoying. Since you seem to have already done some investigation on this, is there an easy fix? Will you accept a PR for a fix?

**Comment by tholu** [comment] 2019-03-13 15:23
As this is a confirmed bug, I think the issue should not be closed.

**Comment by kevin-brown** [comment] 2019-05-15 11:29
I'm pretty sure there's a duplicate of this ticket in this tracker, since I remember seeing something more recently about it.

This is still a bug though.

**Comment by rywall** [comment] 2019-07-15 01:50
Still a bug. Just repro'ed this using the steps in the first comment.

**Comment by blikblum** [comment] 2019-07-21 10:29
Should be fixed by #5551

**Comment by blikblum** [comment] 2019-07-21 10:31
Probably fixed by #5551

**Closed** 2019-07-21 17:04 UTC
Labels: 4.x, confirmed bug
