### ISSUE TITLE
Bootstrap3 + select2 dropdown width

### ISSUE THREAD

**Issue by hardyhardy** [select2/select2#2593] opened 2014-08-07 08:00 UTC
There is an issue with dropdown width when I use select2 with bootstrap3.
![select2-dropdown-width-bug](https://cloud.githubusercontent.com/assets/398871/3838710/9bdf702c-1e07-11e4-93f1-00bd78c230d3.png)

And the next select2 in a line works ok 
![select2-dropdown-width-nobug](https://cloud.githubusercontent.com/assets/398871/3838715/b1f8e8d4-1e07-11e4-8f5d-4903099fc834.png)

My markup 
![select2-markup](https://cloud.githubusercontent.com/assets/398871/3838792/ac61cd4a-1e08-11e4-9c36-abd471ffc245.png)

I've digged a bit and found the next: In bootstrap 3 grid width is set in percents, and in real life the computed width of my .col is 140.547px. Of course browser paints one column 140px width and another 141px width. And select2 always rounds mathimatically correct 141px. But this causes visual bugs!

Do you have any ideas how to avoid this behaviour?

**Comment by alexweissman** [comment] 2017-12-09 19:23
Duplicate of #1692.

**Closed by alexweissman** 2017-12-09 19:23 UTC
