### ISSUE TITLE
noResults property

### ISSUE THREAD

**Issue by brussens** [select2/select2#3966] opened 2015-11-28 06:43 UTC
Good time!
Thank you for the great plugin!
There are some suggestions: will be very convenient, if it is possible to override noResults property.

The fact that the format used Yii2 locales type "ru-RU", so much easier in the widget itself override message, converting it to the server.
Sorry for bad english.

**Comment by alexweissman** [comment] 2017-12-16 01:26
Duplicate of #3799.

**Closed by alexweissman** 2017-12-16 01:26 UTC
