### ISSUE TITLE
jQuery select2 with "Loading remote data" approach- Get values in the order they were selected 

### ISSUE THREAD

**Issue by jaypshah** [select2/select2#4872] opened 2017-04-20 09:47 UTC
I'm developing a form with a number of multiselection dropdowns. It has around more than 10thound records. So, I used Select2 library with "Loading remote data" approach for that.

The problem is that when I try to get selected values they are returned in the order they are specified in `<select>` element, not the order they have been selected.

I tried many solutions written on other issues but all are working on binding static records but I am not able to resolve my problem while binding records through remote.

Let us know what configuration is to be done or code should be written to get value in order they have been selected.

Thanks in advance
Jay Shah

**Comment by alexweissman** [comment] 2017-09-29 17:12
This is a duplicate of #3106.

**Closed by alexweissman** 2017-09-29 17:12 UTC
