### ISSUE TITLE
Select2:selecting event has problem to get value

### ISSUE THREAD

**Issue by mArtinko5MB** [select2/select2#4112] opened 2016-01-22 12:51 UTC
Hello friend,

i have a problem with select2:selecting event. I thought it works like this: 

* select an option with value = 2
 * catch select2:selecting where

```javascript
$whatever_element.on('select2:selecting','#whatever_selector', function() {
    console.log("value = " + $(this).val().toString());
});
```
which gives `"value = ''"` (empty string) and is supposed to be good output

 * select some other option from the exact selectbox
 * and with previous JS code i should get `"value = '2'"` in my console, shouldn't I ? (as last selected option value)

Thing is i am getting  in the last step `"value = null"`

Is this bug or am i doing something wrong?

Thanks for reply.

**Comment by kevin-brown** [comment] 2016-01-23 17:17
`$(this).val()` will get you the value of the currently selected `<option>`, which is why you are getting a blank string for the placeholder.

Aside from that, this is a duplicate of https://github.com/select2/select2/issues/4099.

**Closed by kevin-brown** 2016-01-23 17:17 UTC

**Comment by BenjaminBeck** [comment] 2017-03-04 21:23
Because this was googles first result this as a answer:
To get the just selected value:
```
$whatever_element.on('select2:selecting', function(e) {
    console.log(  e.choice  );
});
```
