### ISSUE TITLE
Placeholder width cutting off text when Select2 is initialized inside a hidden element

### ISSUE THREAD

**Issue by yeago** [select2/select2#291] opened 2012-08-02 21:44 UTC
We're having to patch select2 like so to get our placeholder text to appear properly.
- ln 345: width: auto !important;

This happens when the new width option is either not provided or is set to 'element'. The placeholder gets an inline css width set, which mysteriously goes away and never comes back when the input is interacted with.

**Comment by r-nicol** [comment] 2015-05-13 07:56
I am also seeing this issue even when the element is active and shown. It sets the inner select2-search__field to like 35px for me. My temp solution was a modified version of @jgeurts solution

.select2-container .select2-search__field {
    width: 100% !important;
}
This works for version 4.0.0.

**Comment by pjclas** [comment] 2015-05-13 12:07
The above didn't work for me, I had to add the containing \<li\> as well:
```CSS
    .select2-container .select2-search, 
    .select2-container .select2-search__field {
        width: 100% !important;
    }
```

The problem is now the search field drops to the next line after you've added an element...

**Comment by r-nicol** [comment] 2015-05-13 14:38
I take that back, the whole multi select is just a mess for me on closer inspection. Overflows, dropdown is partial covered. I am guessing some other styles are breaking it, but nothing jumps out. I only have generic reset styles applying. I will strip the CSS I have back to see what is playing with it.

**Comment by tylik1** [comment] 2015-07-19 12:25
Ran into the same issue by setting width of multiselect to 100%
This css  fixed the issue

.select2-container .select2-search__field:not([placeholder = '']) {
    width: 100%!important;
}

The css will set input width to 100% only if placeholder attribute value is not empty.

**Comment by leonwolfus** [comment] 2015-11-09 14:19
I found the following way for my multiselect with hidden input: 
```css
.select2-container.select2-container-multi .select2-choices .select2-search-field:first-child {
     width: 100% !important;
}
```
it sets 100% only in case of there is no choises.

**Comment by kankerlijer** [comment] 2016-02-05 17:52
I fixed it by setting input field to width: auto;
copy pasted the selectors via G-inspector
```
.select2-container--krajee .select2-selection--multiple .select2-search--inline .select2-search__field {
    width: auto !important;
}
```
Seems to have no effect on other css stuff regarding select2
cool widget, lots of hassle

**Comment by fro** [comment] 2016-02-18 14:11
I'm using Select2 4.0.0 & here's my css fix to show the full placeholder and keep the height of the select wrapper. Please have a try:

```
.your-custom-context-selector .select2-container .select2-search__field:not([placeholder='']) {
  width: 100% !important;
  margin-right: 100000px;
}

```

I advise you to set a custom selector depending your needs.

Cheers

**Comment by ShudhPandit** [comment] 2016-04-28 08:29
The jsfiddle

https://jsfiddle.net/shudhpandit/0h0qwtor/

**Comment by bluespuke** [comment] 2016-04-28 13:15
I have a simple setup but i'm experencing the same error as in @ShudhPandit 's jsfiddle.

**Comment by Sammaye** [comment] 2016-06-18 11:21
Still getting this in Ajax mode, it seems to manually set the placeholder to 100px. I am getting this on 4.0.2 but I have checked 4.0.3 commits and the fixes there shouldn't effect this so it seems this problem is still there

**Comment by melissawahnish** [comment] 2016-07-14 17:47
Had same problem with placeholder being cut off when form is shown with Ajax.  I'm on gem version 4.0.3.  @kankerlijer's solution worked for me.

**Comment by pekapa** [comment] 2016-08-05 01:11
I'm also getting the elements via Ajax, what I've done to solve this is delay calling the select2() by wrapping selector in a function and setTimeout with a 1ms delay.

**Comment by webdeva4** [comment] 2016-08-09 19:00
@fro solution worked for me. Thanks!

**Comment by ssmulders** [comment] 2016-12-05 09:53
@fro I couldn't add a custom class, unfortunately, however specifying it more did the trick without breaking other markups (so far ;-))

```
.select2-container .select2-selection.select2-selection--multiple .select2-search.select2-search--inline .select2-search__field:not([placeholder='']) {
  width: 100% !important;
  margin-right: 100000px;
}
```

**Comment by benturkia** [comment] 2016-12-15 10:44
/**
     * fix bug width input search
     */
    $(".select2-selection__rendered").each(function (index, value) {
      var li = $(value).find('.select2-selection__choice');
      if($(li).length <= 0){
        var inputSearch = $(value).find('.select2-search__field');
        $(inputSearch).css('width', 'auto');
      }
    });

**Comment by aristidesfl** [comment] 2017-01-06 16:00
This is closed even though the problem still exists?

**Comment by labster** [comment] 2017-01-19 23:08
This seems to fix the issue for me:
```
.select2-selection--multiple .select2-search--inline .select2-search__field {
    width: auto !important;
}
```

But I'd ask the maintainers to either reopen this issue, or point us all to look at a new issue.

**Comment by jpic** [comment] 2017-01-20 07:38
Hi all !

Thanks a lot for your contribution !

It would be great if someone could open a new issue with an exhaustive presentation of the case.

Best,
James

**Comment by YAnatolich** [comment] 2017-03-22 08:17
This seems to fix the issue for me:

.select2-selection--multiple .select2-search--inline .select2-search__field {
    width: auto !important;
}
It was resolved for me.

**Comment by bews** [comment] 2017-05-08 09:56
> This seems to fix the issue for me:

Doesn't work if placeholder is too long.

So this is my fix:
```javascript
Search.prototype.resizeSearch = function () {
  this.$search.css('width', '25px');

  var width = '';
  var widthParent = '';

  if (this.$search.attr('placeholder') !== '') {
    width = '100%';
    widthParent = '100%';
  } else {
    var minimumWidth = this.$search.val().length + 1;
    width = (minimumWidth * 0.75) + 'em';
    widthParent = 'auto';
  }

  this.$search.css('width', width);
  this.$search.closest('.select2-search--inline').css('width', widthParent);
};
```

**Comment by eayin2** [comment] 2017-05-26 16:58
@bews That fixed it for me. Thanks a ton!

**Comment by jpic** [comment] 2017-05-27 22:54
Thanks for your feedback @eayin2, if this fixes the issue for more people it would be good to know.

Thanks for the patch @bews

**Comment by ToreOlavKristiansen** [comment] 2017-10-05 08:53
@bews solution fixed it for me too.

**Comment by alexweissman** [comment] 2017-10-05 17:34
Ok, I'll reopen this issue since it appears to still be a problem.  @bews have you submitted a PR to the repo?

**Comment by ToreOlavKristiansen** [comment] 2017-10-05 20:25
@alexweissman I am still on v4.0.3. On this version, @bews solution fixed the problem. We can't upgrade our projects to v4.0.4 yet.

**Comment by bews** [comment] 2017-10-06 07:53
@alexweissman it's already here: https://github.com/select2/select2/pull/4898

**Comment by alexweissman** [comment] 2017-12-15 22:21
To everyone in this thread: 

There is a more recent version of this issue, #3817, which is a more focused discussion and has more up-to-date information on this bug.  

So, I am closing this issue as per @jpic's suggestion.  Please subscribe to #3817 and we can continue the conversation there.

**Closed by alexweissman** 2017-12-15 22:21 UTC
Labels: feature: placeholders, status: pending PR merge
