### ISSUE TITLE
MinimumInputLength message does not disappear when length is reached.

### ISSUE THREAD

**Issue by yvangg** [select2/select2#3764] opened 2015-09-14 10:58 UTC
In a select with data retrieved from an AJAX operation the message "Please enter 1 or more characters" does not disappear when you press the last char. The "Searching..." message appears correctly but the other message still appears. This does not happen in the version 3.5.4.

This behavior can be checked in the documentation examples.

3.5.4 version
![Right dropdown](http://i.imgur.com/2Sa4PSA.png)

4.0.0 version
![Wrong dropdown](http://i.imgur.com/EnuRRj1.png)

**Comment by kevin-brown** [comment] 2015-09-15 01:18
This is a duplicate of https://github.com/select2/select2/issues/3343 and will be fixed in the upcoming 4.0.1.

**Closed by kevin-brown** 2015-09-15 01:18 UTC
