### ISSUE TITLE
In IE9 backspace in select menu does not refresh search results

### ISSUE THREAD

**Issue by cdaveb** [select2/select2#3417] opened 2015-05-27 22:35 UTC
I'm using Select2 4.0.0. In Internet Explorer 9 (using Windows 7), if you type in the select menu it successfully limits the items to those matching the text, but if you then use backspace to delete characters, it doesn't refresh the search results. It will only refresh the search results if you exit the menu and reopen it, or type something new.

This behavior does not exist in the other browsers I've tested it in (such as Chrome Mac, IE8 or IE10).

Here are examples of the issue using the Select2 website examples page:
![step1](https://cloud.githubusercontent.com/assets/6133808/7848072/6c46b20a-047d-11e5-9a85-136ebd243a32.png)
![step2](https://cloud.githubusercontent.com/assets/6133808/7848073/71d94be2-047d-11e5-807a-1894326fcbb0.png)
![step3](https://cloud.githubusercontent.com/assets/6133808/7848078/75f0707a-047d-11e5-912a-11b43aed35fe.png)

**Comment by kevin-brown** [comment] 2015-05-28 00:51
I was able to reproduce this in IE 9 compatibility mode.

**Comment by acetrand** [comment] 2015-06-09 09:08
+1 Same here. Tested on Win7 IE9.

Note that Select 3.5.2 works.

**Comment by acetrand** [comment] 2015-06-09 11:46
I did some more investigation on this and the source for it seems to be that it listens for `keyup` or `ìnput` which isn't triggered in IE9 for backspace.

I haven't looked if Microsoft has this documented somewhere but I found a thread on a similar issue: http://stackoverflow.com/questions/6382389/oninput-in-ie9-doesnt-fire-when-we-hit-backspace-del-do-cut

**Comment by theelectricwiz** [comment] 2016-05-03 11:51
+1. Just tried removing the input event handling altogether (leaving in keyup) and it fixes the issue. What is the benefit of using the input event over the keyup event in this instance?

**Comment by theelectricwiz** [comment] 2016-05-03 15:23
For completeness, the input event is required to handle the special input characteristics of touchscreen devices, in particular firefox on these devices (#2997). The bug is only on IE9 (<IE9 doesn't support oninput and it is fixed in >IE9) (tested with https://jsfiddle.net/uxewb7pw/)

**Comment by theelectricwiz** [comment] 2016-05-03 15:37
In my second attempt, I have created a special case just for IE9 which fixes the problem https://github.com/theelectricwiz/select2/commit/c74f51be75458c8e21df58767ed350c241706f3a#diff-bb1b322a1846b8b86b3741d853a1f0ee

`src/js/select2/dropdown/search.js 37`
```javascript
    var keyevent;
    if (!window.navigator.userAgent.match(/MSIE 9\.0/)) {
      this.$search.on('input', function (evt) {
        // Unbind the duplicated `keyup` event
        $(this).off('keyup');
      });
      keyevent = 'keyup input';
    } else {
      keyevent = 'keyup';
    }

    this.$search.on(keyevent, function (evt) {
        self.handleSearch(evt);
    });	
```

**Comment by kevin-brown** [comment] 2016-05-03 16:55
Just collecting links to resources related to this problem

- http://stackoverflow.com/q/6382389/359284
- http://benalpert.com/2013/06/18/a-near-perfect-oninput-shim-for-ie-8-and-9.html
- http://www.useragentman.com/blog/2011/05/12/fixing-oninput-in-ie9-using-html5widgets/
- https://github.com/angular/angular.js/issues/879
- http://www.matts411.com/post/internet-explorer-9-oninput/

**Comment by okonon** [comment] 2016-08-02 15:33
@cdaveb @bytesnz @kevin-brown 
Try following :
1. Search angular.js for `if (event == 'input' && msie == 9) return false;` line (depending on your angular version could be different lines) 
2. change the above code to `if (event == 'input' && msie < 10) return false;`

**Comment by MtarantoOa** [comment] 2017-09-05 15:06
Hi guys Im using select2 in an Angular 2 template. We use the backspace key to delete the tags of the input. We found this solution:
`		$.fn.select2.amd.require(['select2/selection/search'], function (Search) {
			var oldRemoveChoice = Search.prototype.searchRemoveChoice;

			Search.prototype.searchRemoveChoice = function () {
				oldRemoveChoice.apply(this, arguments);
				this.$search.val('');
			};
		});`

That work great on Chrome. But on IE the second time I hit the backspace key the browser just go back.
I was looking for some solution like change the version of the library but it does not work for me.

Im using this version:  "select2": "4.0.3"

Do you know any workaround or how to fix this?

Thanks!

**Comment by alexweissman** [comment] 2017-12-09 19:31
I believe that this is the same underlying issue (IE not propagating `keyup`) that causes #3168.

**Comment by pedrofurtado** [comment] 2018-09-15 03:51
Discussion continues here -> https://github.com/select2/select2/pull/3394

**Closed by pedrofurtado** 2018-09-15 03:51 UTC
Labels: 4.x, browser: IE, confirmed bug
