### ISSUE TITLE
No support for jQuery.noConflict

### ISSUE THREAD

**Issue by DeniR** [select2/select2#3234] opened 2015-04-05 16:09 UTC
Error in code `return $.fn.select2.amd=`
There must be jQuery instread of $, because jQuery can have another variable name after noConflict, like `var $j = jQuery.noConflict(); `

**Comment by kevin-brown** [comment] 2015-04-05 17:39
Duplicate of https://github.com/select2/select2/pull/3192, fixed in https://github.com/select2/select2/commit/da1ec4e02865f3b23d7634eba509e3438d4ab874.

**Closed by kevin-brown** 2015-04-05 17:39 UTC
