### ISSUE TITLE
Scroll to Bottom on Long List

### ISSUE THREAD

**Issue by debugd** [select2/select2#6077] opened 2021-08-13 14:34 UTC
When you have a long select2 list and click an item at the top of the list it doesn't remove it, instead it jumps to the bottom.

Here's a fiddle to demonstrate.

http://jsbin.com/jibefazebi/edit?html,js,output

What is expected it when you click the X to remove an item, it removes the item and it doesn't scroll you to the bottom of the select2 and open the options up.

This issue was previously incorrectly closed here: https://github.com/select2/select2/issues/5155

**Comment by kevin-brown** [comment] 2021-08-18 16:58
Duplicate of #5155 which has been reopened.

**Closed as completed by kevin-brown** 2021-08-18 16:58 UTC
