### ISSUE TITLE
Disable input text on select

### ISSUE THREAD

**Issue by furyscript** [select2/select2#3349] opened 2015-05-12 12:33 UTC
Hi all,

I use this code for "hiding" the input on select2:
`minimumResultsForSearch: -1`

In desktop browser seems to work, but when I try to view the page in mobile, the input keyboard show up always but the input on select2 element is hiding.
Solution? @ivaynberg @kevin-brown and other.

**Comment by furyscript** [comment] 2015-05-12 13:20
I set
*$(".select2-search, .select2-focusser").remove();*
But it's not pretty solution...

**Comment by kevin-brown** [comment] 2015-05-12 15:28
Duplicate of https://github.com/select2/select2/issues/1541, mostly fixed in 4.0.0.

**Closed by kevin-brown** 2015-05-12 15:28 UTC
