### ISSUE TITLE
If ajax timeout is set, select2 doesn't seem to load the correct list when everything is cleared fast.

### ISSUE THREAD

**Issue by divyangbw** [select2/select2#4028] opened 2015-12-15 19:45 UTC
Hey, so for version 4.0, I have a list of say 5 items and ajax timeout set to 300ms.

```
List = ["aaa", "aab", "b", "c", "d"]
Search: "aa"
Returned List = ["aaa", "aab"], the url = foo.com/term="aa" // Expected 
Very quickly backspace "aa" so term="".
New returned List = ["aaa", "aah"], because the url = foo.com/term="a". // Not Expected 
```

So for some reason, the last request is `term="a"` instead of `term=""`. I am using the default ajax settings, except for `processResults` and `data`, where I simply convert the params.term and params.page to something my server would understand, so I doubt that would cause any issues. `cache` is also set to true.

Would this be a bug or is it expected? Wouldn't ajax always pick the last request when timeout is set? If it is expected, ideas on how I could force ignore timeout on the condition that `term=""`?

Thanks :)

**Comment by kevin-brown** [comment] 2015-12-22 00:21
This is likely a race condition caused by multiple requests being sent out.

**Comment by Pablissimo** [comment] 2016-09-05 10:03
Seeing this myself just now and on the examples page (on the Github example type any text then quickly control-backspace to delete - a query is issued anyway with the last text).

To my eyes it appears to be a fault in [ajax.js line 97](https://github.com/select2/select2/blob/master/src/js/select2/data/ajax.js#L97) where if the search term changes but is cleared the timeout isn't cancelled so the last non-empty query gets issued when the existing timer elapses?

**Comment by alexweissman** [comment] 2017-12-15 03:59
This is a duplicate of #3512.

**Closed by alexweissman** 2017-12-15 03:59 UTC
Labels: 4.x, confirmed bug, feature: ajax
