### ISSUE TITLE
complex name errors

### ISSUE THREAD

**Issue by semmais** [select2/select2#4057] opened 2016-01-04 10:21 UTC
EDIT: i found similar issue @ #3618 (is critical)

if the select use a name like name="group[guid-xp].item[guid-2].type"  when selecting options, the select output to the console following error:

Uncaught SyntaxError: Invalid regular expression: /(^|\.)item[guid-2]-lc\.(?:.*\.|)select2\.(?:.*\.|)select2-group[guid-xp](\.|$)/: Range out of order in character class

example: https://jsfiddle.net/ogg1o102/

**Comment by semmais** [comment] 2016-01-04 10:29
The problem happens when the name there is a "-" is followed by a number.
Is normal have that where using guid's.

**Comment by semmais** [comment] 2016-01-04 10:56
i found similar issue @ #3618

**Comment by kevin-brown** [comment] 2016-01-04 14:13
Duplicate of https://github.com/select2/select2/issues/3618.

**Closed by kevin-brown** 2016-01-04 14:13 UTC
