### ISSUE TITLE
ê character and tagging support bug on firefox

### ISSUE THREAD

**Issue by hedii** [select2/select2#4986] opened 2017-07-10 09:47 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Using firefox on a mac (see related versions below)
2. Visit select2 documentation for tagging support (https://select2.github.io/examples.html#tags)
3. Click on the example field and start typing `fête` (the `ê` is the combination of `^` and then `e`)

## Expected behavior and actual behavior

When I follow those steps, I see that the select2 field become unresponsive afte trying to type the `ê` character. We cannot type anymore on the field after that.

I was expecting to get the word `fête` as a tag on the field.

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox latest (54.0.1 64bits)
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X (10.12.5)
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment] 2017-09-13 22:39
This appears to be a duplicate of #4792.

**Closed by alexweissman** 2017-09-13 22:39 UTC
