### ISSUE TITLE
closeOnSelect and removing selected choices toggles dropdownmenu

### ISSUE THREAD

**Issue by scooterlord** [select2/select2#6214] opened 2023-01-09 21:16 UTC
Hello everyone,

I encountered the following bug - in multiple-option selects and when using `closeOnSelect: false` , when you start removing selected choices that sit alongside the `select2-selection__rendered` area, then the menu toggles on each item remove.

Here is a jsfiddle that can clearly showcase the issue:
https://jsfiddle.net/8a2rc0zv/

**Comment by kevin-brown** [comment] 2023-01-14 18:29
Duplicate of https://github.com/select2/select2/issues/3320, there's ways to prevent it.

**Closed as not planned by kevin-brown** 2023-01-14 18:29 UTC
