### ISSUE TITLE
Inputting the exact value not choosing the option when the value and display text are different

### ISSUE THREAD

**Issue by cytsunny** [select2/select2#5051] opened 2017-09-25 03:43 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an select element with value not equal to the display text.
2. Call the select2 function, with tag function turned on
Or
1+2. https://jsfiddle.net/rLmztr2d/237/

3. Input a value that is equal to the display text and press `,`

## Expected behavior and actual behavior

When I follow those steps, I see...
A new tab created with value and display tag both equal to the input value

I was expecting...
The option with the display text chosen, no new tab created.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

P.S. I have already found a way to hot fix the problem, but I hope select2 will fix it so that no more hot fix is needed.
https://stackoverflow.com/questions/46361910/select2-error-on-tag-when-value-is-not-the-same-as-display-value/46362316#46395657

**Comment by alexweissman** [comment] 2017-09-25 04:21
This is a duplicate of #4779 and #3681.  Please search the issues carefully before opening a new one!

**Closed by alexweissman** 2017-09-25 04:21 UTC

**Comment by cytsunny** [comment] 2017-09-25 11:02
#3681 (& #4779)'s problem is that it fails to select a new tag when it matches the id of an existing tag.  In my case, I have no problem selecting the new tag. The problem is that while it is expected to select the old tag, but a new tag is created. How is that duplicated?

**Comment by alexweissman** [comment] 2017-09-25 17:41
My mistake, I believe I misunderstood your issue.  It sounds to me like this is actually a duplicate of #4610, then?

**Comment by cytsunny** [comment] 2017-09-26 02:36
Oh, you are right. This is a duplicate then. Sorry for the inconvenience caused.

**Comment by alexweissman** [comment] 2017-09-26 16:51
No problem, there are a lot of open issues with wade through still!
