### ISSUE TITLE
Wrong documentation of maximumSelectionSize

### ISSUE THREAD

**Issue by heebj** [select2/select2#3445] opened 2015-06-07 10:05 UTC
On the examples page in the section "Limiting the number of selections" the option is named "maxSelectionLength" and in the code example next to it it is named "maximumSelectionLength". Both seems to be wrong, it should be "maximumSelectionSize".

BTW: on the options page this option is not documented at all.

**Comment by kevin-brown** [comment] 2015-06-07 16:13
Duplicate of https://github.com/select2/select2/issues/3326.

> BTW: on the options page this option is not documented at all.

One of many options that aren't documented, we have plans to change how things are documented.

**Closed by kevin-brown** 2015-06-07 16:13 UTC
