### ISSUE TITLE
addEventListener not working with select2

### ISSUE THREAD

**Issue by orthener** [select2/select2#5971] opened 2021-01-16 23:34 UTC
Some JS plugins using native event listeners. And they stop working with selects after initing select2.
Imfo: https://makandracards.com/makandra/71890-events-triggered-by-jquery-cannot-be-observed-by-native-event-listeners
My workaround:
1) copy files to a project
2) replace all 
```
this.$element.trigger('input').trigger('change');
```
to
```
let eventInput = new CustomEvent('change');
let eventChange = new CustomEvent('change');
self.$element[0].dispatchEvent(eventInput);
self.$element[0].dispatchEvent(eventChange);
```
------------------------------------

Problem: need to do this all time on all projects.

-----------------------------------

My opinion: it should be in select2 by default

**Comment by Defimas** [comment] 2021-01-21 13:39
I agree and please add the "selected" attribute to the native element's <option>.

**Comment by kevin-brown** [comment] 2021-01-22 18:32
Duplicate of https://github.com/select2/select2/issues/1908

**Closed by kevin-brown** 2021-01-22 18:32 UTC

**Comment by manu0087** [comment] 2021-10-29 14:04
hi,
if could help someone, i solved doing this:
```

            $('.js-example-basic-single').select2({dropdownAutoWidth : true});
            $('.js-example-basic-single').on('change', function (e)
            {
                tmp_div = document.createElement("input");
                e.target.appendChild(tmp_div)
                tmp_div.dispatchEvent(new Event("change"))
                e.target.removeChild(tmp_div)
            });

    document.getElementById("MyDiv").addEventListener('change', function (event)
    {
        alert(event)
        var elem = event.target;
    });

<div>
  <input value="" id="MyElement" type="text">
  <select id="cmb_UM1" class="js-example-basic-single select2-hidden-accessible" data-select2-id="select2-data-ctl00_Content_cmb_UM1">
    <option selected="selected" value="" title="" data-select2-id="select2-data-2-vplr"></option>
    <option value=" 1001171997" title=" 1001171997" data-select2-id="select2-data-12-gcgl"> 1001171997</option>
  </select>
</div>

```
Select2 doesn't fire native Onchange, but fires its. that mean "addEventListener" will not fired when your dropdown change value. to do that, i created on its event a textbox, appended to him, fired the Onchange texbox and than remove it.
