### ISSUE TITLE
HTML5 required oninvalid - select2 doesn't work well

### ISSUE THREAD

**Issue by Tin-Nguyen** [select2/select2#3824] opened 2015-10-10 00:09 UTC
Hi,

I'm facing 1 issue. All dropdowns are using select2. When I apply the HTML5 required function, it works well. But when I add the attribute 'oninvalid' to custom the shown message. The control doesn't work well.

The browser always show and ask I need to select 1 item in dropdown although I have already selected.

Do we have any solution to fix this?
<img width="364" alt="screen shot 2015-10-10 at 7 05 12 am" src="https://cloud.githubusercontent.com/assets/5414916/10407976/4a158eda-6f1d-11e5-9eda-d3f1da293f59.png">

Thanks in advanced.

**Comment by kevin-brown** [comment] 2015-10-12 16:02
This is a duplicate of https://github.com/select2/select2/issues/128.

**Closed by kevin-brown** 2015-10-12 16:02 UTC

**Comment by rsynnest** [comment] 2017-03-28 00:03
In case anyone else comes across this like I did, #128 is actually unrelated to this. What @Tin-Nguyen is referring to is most likely a separate issue which stems from the misuse of the [setCustomValidity](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Constraint_API%27s_element.setCustomValidity()) function.

Passing a non-empty string to setCustomValidity (ie `oninvalid="this.setCustomValidity('Custom error message')"` ) will make the field fail validation.
Passing an empty string to setCustomValidity will make the field pass validation.

So if you use setCustomValidity to set a custom error message, you need to make sure to only do so when the field is invalid, otherwise you get stuck with invalid errors for all submissions after the first attempt at submitting a blank string, which is what @Tin-Nguyen is experiencing.

Fiddle example here: https://jsfiddle.net/7qzL093c/
Explained in more detail here: http://stackoverflow.com/questions/5272433/html5-form-required-attribute-set-custom-validation-message?answertab=active#tab-top
