### ISSUE TITLE
Selected options does not show when using ajax

### ISSUE THREAD

**Issue by lsv** [select2/select2#3979] opened 2015-12-02 08:20 UTC
I created this fiddle, to test it out

https://jsfiddle.net/mav6a1d5/

Why is the "123" not pre selected?

If I remove the options from select2() then it does show, but then it opvious cant search.

My use case for this is:
A user have 3 options, which get validated on server side, if the user has some errors (either in the selects or in other fields) then they should come back, but now with pre selected selects.

**Comment by kevin-brown** [comment] 2015-12-04 17:54
This is a duplicate of https://github.com/select2/select2/issues/3990 (picked that ticket because it is general).

**Closed by kevin-brown** 2015-12-04 17:54 UTC
