### ISSUE TITLE
Stop dropdown opening after removing tag

### ISSUE THREAD

**Issue by ironhussar** [select2/select2#4046] opened 2015-12-28 23:24 UTC
Hi,

Every time I remove a tag by clicking the X, the dropdown opens. This is opposite behaviour to v3. Can this be reverted to how it used to work, or made an option?

I can override this in the open event in my code, but it causes the dropdown to flash quickly each time.

**Comment by kevin-brown** [comment] 2015-12-29 00:11
This is a duplicate of https://github.com/select2/select2/issues/3209#issuecomment-149663474.

**Closed by kevin-brown** 2015-12-29 00:11 UTC
