### ISSUE TITLE
Bootstrap text wraps under select box. Select2 4.0

### ISSUE THREAD

**Issue by Godrules500** [select2/select2#3062] opened 2015-02-23 14:08 UTC
Not sure if this issue exists, but I just upgraded to the select2 4, but the text in the selectbox is wrapping under the selectbox.  Basically it seems like the text is just on top of the selectbox and not inside of it.

Also, my css I'm applying isn't applying to the HTML tag isn't being used.

In this particular instance, I'm using the ajax to load the values.

**Comment by skeefo** [comment] 2015-02-24 09:30
I think I have the same issue. I've made jsfiddle.
http://jsfiddle.net/bhzz6twr/
Long text in option if chosen "goes out" of selectbox.
I've fixed it in my project by adding style
.select2-container .select2-selection--single {overflow: hidden;}

**Comment by kevin-brown** [comment] 2015-02-24 13:13
Duplicate of https://github.com/select2/select2/issues/2984, fixed on the latest branch.

**Closed by kevin-brown** 2015-02-24 13:13 UTC

**Comment by skeefo** [comment] 2015-02-24 14:05
Thank you, it works.

**Comment by AcTiv3MineD** [comment] 2018-01-02 14:23
Also i added height: auto; to the css suggested by: @skeefo

As with overflow hidden alone, it cuts the text and doesn't show the rest. 

The final CSS would be like:
.select2-container .select2-selection--single {
  overflow: hidden;
  height: auto;
}
