### ISSUE TITLE
docs/samples not runing in localhost

### ISSUE THREAD

**Issue by douglasdeodato** [select2/select2#4628] opened 2016-10-12 13:39 UTC
## Steps to reproduce the issue
1. run `grunt docs` from the folder `select2`
## Expected behavior and actual behavior

When I follow those steps, I supose to see in the `http://localhost:4000/examples.html` runing exactly the same from:  https://select2.github.io/examples.html
## Environment

Browsers
- [x] Google Chrome
- [x ] Mozilla Firefox
- [x ] Internet Explorer

Operating System
- [ x ] Linux
## Isolating the problem
- [ x] This bug happens [on the examples page](https://select2.github.io/examples.html)

error:
all vendor libraries are missing.
https://gist.github.com/douglasdeodato/7677a74f4cde2e32ece4686e9792fc37

**Comment by alexweissman** [comment] 2017-08-31 16:59
@douglasdeodato I can't reproduce this _particular_ issue, but I am having problems with the css links when I build the docs:

![screen shot 2017-08-31 at 12 59 19 pm](https://user-images.githubusercontent.com/5004534/29935298-3e1f283e-8e4c-11e7-97c5-d8f62cfd8045.png)

Are you still experiencing this issue?

**Comment by alexweissman** [comment] 2017-08-31 22:48
Actually, looks like I had an older version of Jekyll installed.  After upgrading to the latest version of Jekyll, it seems to work fine for me.

**Comment by alexweissman** [comment] 2017-09-13 22:25
The old Jekyll docs have been deprecated and replaced with https://github.com/select2/docs, so I am closing this issue.

**Closed by alexweissman** 2017-09-13 22:25 UTC
