### ISSUE TITLE
Ajax transport function does not be called

### ISSUE THREAD

**Issue by Omar-allahham** [select2/select2#4180] opened 2016-02-11 14:32 UTC
I'm using select for searching in usernames with Meteor framework, when i upgraded to 4.0.1 I notice that transport function in  Ajax object not called anywhere: 
this my code :

```
     $('#contributingIds').select2({
            // Must enter at least 1 character before we search
            minimumInputLength: 1,
            // Cannot select multiple items
            multiple: true,
            tags: true,
            language: 'ar',
            //tokenSeparators: [','],
            minimumInputLength: 2,
            cache: true,
            // Fetch the results with a Meteor method instead of ajax
            ajax: {
                data: function (params) {
                    return {
                        q: params.term, // search term
                        page: params.page|| 10
                    }
                },
                transport: function (params, success, failure) {
                    Meteor.call('usernamesSearch', params.data.q, function (err, results) {
                        if (err) {
                            failure(err);
                            return;
                        }

                        params.success(results);
                    });
                },
                processResults: function (data) {
                    var results = [];
                    _.each(data.results, function (result) {
                        results.push({
                            id: result._id,
                            text: result.username
                        });
                    });

                    return {
                        results: results
                    };
                }
            }

        });
```

what is changed ?

**Comment by kevin-brown** [comment] 2016-02-11 14:49
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using?
- Are you using Select2 with other plugins?
- Is this a regression from a previous version of Select2? What version?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

**Comment by alexweissman** [comment] 2017-09-25 02:19
Closing due to lack of information.

**Closed by alexweissman** 2017-09-25 02:19 UTC
Labels: 4.x, needs information

**Comment by ktrzeciaknubisa** [comment] 2024-12-20 21:22
I couldn't get it to work at first either, but then I figured that `$('#contributingIds').select2()` needs to be invoked inside `$(document).ready()`, or a shorthand, e.g. like:

```
$(function() {   
    $("#contributingIds").select2(opts)
});
