### ISSUE TITLE
Init method screws up the select box

### ISSUE THREAD

**Issue by ova2** [select2/select2#2963] opened 2015-01-23 08:37 UTC
Go to "Programmatic access" example on the https://select2.github.io/examples.html and click on "Destroy" and "Init" buttons. Select2 gets screwed up. It looks too narrow.

**Comment by kevin-brown** [comment] 2015-01-23 13:52
Duplicate of https://github.com/select2/select2/issues/2935, will be fixed in 4.0.0-beta.3.

**Closed by kevin-brown** 2015-01-23 13:52 UTC
