### ISSUE TITLE
Using the initSelection option with version 4

### ISSUE THREAD

**Issue by flashios09** [select2/select2#3755] opened 2015-09-10 10:41 UTC
Hi,

Before i used the initSelection option to init my select2, with version 4 it doesn't work anymore and i didn't find anything in the documentation :(

**Comment by kevin-brown** [comment] 2015-09-10 18:34
This is a duplicate of https://github.com/select2/select2/issues/3116.  You may have some luck checking out the comments on that ticket.

**Closed by kevin-brown** 2015-09-10 18:34 UTC
