### ISSUE TITLE
select2 working is not good with bootstrap popover and modal

### ISSUE THREAD

**Issue by jeessy2** [select2/select2#3662] opened 2015-08-07 15:31 UTC
display in "webui popover" , it's not good
 ![1](https://cloud.githubusercontent.com/assets/6205259/9139262/b9ecbeca-3d5b-11e5-820d-c2ea1f78cb4c.png)

display in "bootstrap dialog",  Can't input character!!
![2](https://cloud.githubusercontent.com/assets/6205259/9139326/32fcb158-3d5c-11e5-8e4f-1ce1605206a9.png)

**Comment by kevin-brown** [comment] 2015-08-08 14:37
This is a duplicate of https://github.com/select2/select2/issues/600#issuecomment-102857595.

**Closed by kevin-brown** 2015-08-08 14:37 UTC
