### ISSUE TITLE
minimumResultsForSearch Not Working

### ISSUE THREAD

**Issue by fredmalone** [select2/select2#3055] opened 2015-02-18 23:39 UTC
Couldn't get this option to work in the latest beta.  I found this code in the source:

`  Search.prototype.showSearch = function (_, params) {
    return true;
  };`

If I set this to return false the search box goes away.  So is the code not calling the code for the minimumResultsForSearch option?  When I debug in Chrome it never does.

Am I missing something?  I have limited knowledge of javascript plugins.

Update: 
Here is a jsbin for this:
http://jsbin.com/mikulufaza/1/edit?html,css,js,output

Also, I tried the Infinity literal and that works.  

Thanks.

**Comment by kevin-brown** [comment] 2015-02-18 23:42
Can you create a jsfiddle or jsbin that reproduces this issue?

The latest beta does not support the `-1` fallback (though the upcoming rc.1 does), but you can use the literal `Infinity` until then to get the same effect.

**Comment by jelhan** [comment] 2015-02-19 13:49
Updated JSBin using `minimumResultsForSearch: Infinity`: http://jsbin.com/hahifemune/2/edit?html,js,output

@kevin-brown What benefit has `-1` over `Infinity` value for disabling search at all? Perhaps `-1` fallback isn't needed at all?

**Comment by kevin-brown** [comment] 2015-02-19 14:00
Closing this off now that we can confirm that the jsfiddle works with `Infinity` instead of `-1`.

> What benefit has -1 over Infinity value for disabling search at all? Perhaps -1 fallback isn't needed at all?

Backwards compatibility with older versions of Select2.

**Closed by kevin-brown** 2015-02-19 14:00 UTC

**Comment by jelhan** [comment] 2015-02-19 14:01
So prefered value is `Infinity` over `-1` in 4.x? Will `-1` be deprecated in future?

**Comment by kevin-brown** [comment] 2015-02-19 14:03
> So prefered value is `Infinity` over `-1` in 4.x?

Yes, because it is more clear. "We need infinite items for the search to display."

> Will `-1` be deprecated in future?

Not in the near future.

**Comment by fredmalone** [comment] 2015-02-19 14:05
This works for me.  I will plan to update all of my select2 calls to
Infinity instead of -1.  Thanks for clarifying this.
