### ISSUE TITLE
Tags functionality is not working as the previous version for <input> tags

### ISSUE THREAD

**Issue by MrGorki** [select2/select2#4232] opened 2016-03-04 17:12 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of Select2
- [X] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [X] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use select2.full.js
2. Add `<input id="test" />` tag to your page
3. Assign select2 with preloaded tags via `$('#test').select2({ tags: ["Alabama", "Arkansas"]});`

## Expected behavior and actual behavior

When I follow those steps, I see an empty select2 box with No results found message

I was expecting the old behavior of version 3 which will be a tag enabled select box with loaded values

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer

Operating System

- [X] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.1
- Select2 version: 4.0.1 and 4.0.2-rc.1

**Comment by kevin-brown** [comment] 2016-03-04 18:33
This is a duplicate of https://github.com/select2/select2/issues/3722.

Basically support for `<input />` tags might as well be missing.

**Closed by kevin-brown** 2016-03-04 18:33 UTC
