### ISSUE TITLE
Select2 dropdown does not update position when its height changes

### ISSUE THREAD

**Issue by FredrikC** [select2/select2#4309] opened 2016-04-14 16:00 UTC
## Steps to reproduce the issue

1. Create a select2 with minimum input length
2. Scroll the page so the dropdown appears above the original input
3. Type a characters which produces matches
4. Press backspace to remove the character resulting in no matches

![Animation of bug](http://i.imgur.com/Oxa4JzT.gif)

## Expected behavior and actual behavior

When I follow those steps, I see the dropdown to still be positioned as there were matches

I was expecting the dropdown to readjust the positioning and size when the number of matches changes.

Not sure if this is a duplicate of [select2/issues/4168](https://github.com/select2/select2/issues/4168) or not.

## Environment

Browsers

- [X] Google Chrome
- [X] Internet Explorer

Operating System

- [X] Windows

Libraries

- jQuery version: 2.2.0
- Select2 version: 4.0.1

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using Select2 without other pluigns
- [X] I can reproduce this bug in [a jsbin](http://jsfiddle.net/81sr8v4h/10/)

**Comment by kevin-brown** [comment] 2016-04-14 21:50
This is a duplicate of https://github.com/select2/select2/issues/3905.

**Closed by kevin-brown** 2016-04-14 21:50 UTC
