### ISSUE TITLE
how is it customize 'No results found'?

### ISSUE THREAD

**Issue by lei159130** [select2/select2#4995] opened 2017-07-23 04:09 UTC
Such as title.

**Comment by LiuZwen** [comment] 2017-07-25 03:09
leave

**Comment by nbkjzv6** [comment] 2017-07-29 12:50
The CSS property for it is .select2-results__message

**Comment by alexweissman** [comment] 2017-09-10 23:12
Do you want to customize the message itself?  I'm not sure, but this might be handled by the [translation module](https://select2.org/i18n#translation-objects).  We should probably add this to the docs somewhere.

**Comment by alexweissman** [comment] 2017-09-13 22:47
This might actually be a duplicate of #4088.

**Comment by alexweissman** [comment] 2017-10-12 03:19
Yeah, this is definitely a duplicate of #4088.

**Closed by alexweissman** 2017-10-12 03:19 UTC
Labels: documentation
