### ISSUE TITLE
Filter when typing without search box

### ISSUE THREAD

**Issue by alvarotrigo** [select2/select2#3965] opened 2015-11-27 16:28 UTC
When using select2 with the `minimumResultsForSearch` option, it won't filter the select box content when typing as it happens with normal select boxes.

``` javascript
$(".js-example-basic-hide-search").select2({
  minimumResultsForSearch: Infinity
});
```

I believe that's the expect result in any select box even though the search box is not there.
The search box seems not to be very welcome for some people / client / bosses due to the fact that it alters the UI and adds an extra box. 
This is an issue that [has been requested for a long time](https://github.com/select2/select2/issues/1345#issuecomment-124285439) but it seems it won't be added to the plugin.

Therefore the closest solution would be to use a default filtering without a search box, but it seems it doesn't work either, which seems to push us away from the plugin to end up using a normal select box with bootstrap styles for the closing select box.

**Comment by kevin-brown** [comment] 2015-11-27 19:55
The reasons for why Select2 doesn't allow searching without an input box are [covered in depth over here](https://github.com/select2/select2/issues/3279#issuecomment-96450069). It can be summed up as "we haven't found a good way".

I'm not sure if I would call this a duplicate of https://github.com/select2/select2/issues/3279, partially because I'm also not sure how you are envisioning this issue being fixed.

**Comment by alexweissman** [comment] 2017-12-09 17:45
Please continue discussion of this feature in #1345.

**Closed by alexweissman** 2017-12-09 17:45 UTC
