### ISSUE TITLE
FEATURE REQUEST - Accessibility

### ISSUE THREAD

**Issue by schneiderbruno** [select2/select2#5509] opened 2019-05-08 23:55 UTC
good night

I am web developer, and using this lib I noticed that for the fields where there is the option to remove a label the "x" is shown for this removal.
I would like to give the advice, you insert the attribute "title" for questions of accessibility.

It's my contribution.

<span class = "select2-selection__choice__remove" title = "Remove" role = "presentation">

Thanks for the plugin, very useful

**Comment by kevin-brown** [comment] 2019-05-14 22:41
Duplicate of https://github.com/select2/select2/issues/3744.

**Closed by kevin-brown** 2019-05-14 22:41 UTC
