### ISSUE TITLE
[FeatureRequest] Option to not trigger open on unselect

### ISSUE THREAD

**Issue by althaus** [select2/select2#3838] opened 2015-10-16 09:50 UTC
Hi,

at the moment there's no simple way to prevent the opening of the dropdown if a user unselects an element on a select. Preventing the `unselect` triggers the click on the select. With no event handling, you cannot prevent this line:

https://github.com/select2/select2/blob/master/src/js/select2/selection/allowClear.js#L65

We're using select2 for some excessive user<->member<->group handling and the dropdown is bad for the UX, if someone just want's to remove a group membership.

Cheers
Matthias

**Comment by kevin-brown** [comment] 2015-10-16 20:06
This is a duplicate of https://github.com/select2/select2/issues/3320.

**Closed by kevin-brown** 2015-10-16 20:06 UTC

**Comment by althaus** [comment] 2015-10-19 06:59
Sorry for the dupe. Seems my SearchFu was bad on Friday. :(
