### ISSUE TITLE
[IE9] [jQuery: 3.1.0] dropdown position bug after scroll

### ISSUE THREAD

**Issue by DragorWW** [select2/select2#4635] opened 2016-10-17 04:45 UTC
## Steps to reproduce the issue
1. Open IE9, go to http://codepen.io/DragorWW/full/LRJOBR/
2. Click on firts select
3. scroll page down
## Expected behavior and actual behavior

When I follow those steps, I see dropdown panel runs upward.

![2016-10-17 11-36-23](https://cloud.githubusercontent.com/assets/1303845/19425636/077856da-945f-11e6-9a28-28e5802e10d9.png)

I was expecting dropdown panel save position under select.
## Environment

Browsers: Internet Explorer 9

Operating System: Window 7

Libraries
- jQuery: 3.1.0
- Select2: 4.0.3
## Isolating the problem
- [example bug](http://codepen.io/DragorWW/full/LRJOBR/)

**Comment by danielpriplata** [comment] 2017-02-01 15:51
Hello,

I was going to create a new issue, but I stumble upon this one. I have the exact same problem under IE10 - WIN7. And it seems to be related to JQuery 3. Using JQuery 2.2.4 "fixes" the issue.

Can we expect it will be fixed using JQuery 3?

Following is the report I was going to file:

## Prerequisites

- [] I have searched for similar issues in both open and closed tickets and cannot find a duplicate. 
- [ ] The issue still exists against the latest `master` branch of Select2 (sorry didn't test this)
- [X] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

See https://jsfiddle.net/bmz7gm0t/ under IE10

(you'll have to scroll down a bit to find the select input)

## Expected behavior and actual behavior

When I follow those steps, I see...

Here is a screenshot of the result. The dropdown is misplaced, way above the input.
![ie10_2](https://cloud.githubusercontent.com/assets/22370483/22512961/fc6bab30-e89a-11e6-9510-12ef9ea910f4.jpg)

Note that this only happens when scrolling down. If the input is place at the top of the page and doesn't require you to scroll, then the dorpdown is placed correctly.

I was expecting...

The dropdown should be "attached" to the input.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [X] Internet Explorer 10

Operating System

- [X] Windows 7
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- Select2 version: 4.0.3

**Comment by artursopelnik** [comment] 2017-02-08 15:54
+1

**Comment by leesherwood** [comment] 2017-03-08 09:58
Getting the same issue here too. 

As a workaround until it is fixed, you can listen for the open event and move the dropdown. 
`.on('select2:open', function(){
        var c = $(this).data('select2').$container,
            cp = c.offset(),
            ch = c.outerHeight(),
            t = cp.top + ch,
            dd = $(this).data('select2').$dropdown;

        setTimeout(function(){ dd.css('top', t+'px'); }, 0);
    });`

It sometimes might cause a flicker where the plugin sets the position, then this _fix_ fires. For me this wasn't an issue as the dropdown was always being positioned above the window so the flicker was hidden.

Here's this _fix_ applied to the example fiddle:
https://jsfiddle.net/t96tb3qh/2/

**Comment by gavb17** [comment] 2017-08-24 08:12
Have come across this issue and 2 things we tried:

`body {
    position: relative;
}`

or load in jQuery migrate - https://www.npmjs.com/package/jquery-migrate

**Comment by alexweissman** [comment] 2017-09-17 02:18
This issue could potentially be related to #4614.

**Comment by alexweissman** [comment] 2017-12-14 22:06
Appears to be a duplicate of #4614, and not limited to IE.

**Closed by alexweissman** 2017-12-14 22:06 UTC
Labels: browser: IE, status: possible bug (unconfirmed)
