### ISSUE TITLE
Missing suport for long search input

### ISSUE THREAD

**Issue by Temepest74** [select2/select2#5939] opened 2020-10-23 15:05 UTC
The select2 multibox does not work well with a large text into the input field. Please help me with this bug. The screenshot was took from here https://select2.org/getting-started/basic-usage.
![image](https://user-images.githubusercontent.com/28103890/97020437-3aa40600-155a-11eb-8cc7-dbb62661de79.png)

**Comment by kevin-brown** [comment] 2020-11-28 04:16
Duplicate of https://github.com/select2/select2/issues/5863.

**Closed by kevin-brown** 2020-11-28 04:16 UTC
