### ISSUE TITLE
focus() doesn't work with new jquery 3.6.0

### ISSUE THREAD

**Issue by itajackass** [select2/select2#6005] opened 2021-03-18 09:54 UTC
automatic focus inside input search field, doesn't work after upgrade to latest jqeury 3.6.0.

**Comment by MoreMeng** [comment] 2021-03-19 02:54
https://github.com/select2/select2/issues/5996

**Comment by tagliala** [comment] 2021-03-19 13:41
Duplicate of #5993

**Comment by kevin-brown** [comment] 2021-03-22 18:53
Duplicate of https://github.com/select2/select2/issues/5993.

**Closed as completed by kevin-brown** 2021-03-22 18:53 UTC
