### ISSUE TITLE
Run createSearchChoice() before query()

### ISSUE THREAD

**Issue by mrgray** [select2/select2#2992] opened 2015-01-29 22:37 UTC
So basically I have a select2 which initializes a text field that allows a single value which searches for pre-defined titles using Bloodhound through query().

The problem is that createSearchChoice() which allows a user to select a new title gets called after query() so there's a buffer timeframe where a user has to wait for the ajax call to finish before he/she can select the newly typed in value, is there any way to avoid this/get around?

Help would be really appreciated!

**Comment by kevin-brown** [comment] 2016-06-25 18:48
This is a duplicate of https://github.com/select2/select2/issues/2231.

**Closed by kevin-brown** 2016-06-25 18:48 UTC
