### ISSUE TITLE
data-minimum-input-length and data-ajax--url do not work.

### ISSUE THREAD

**Issue by tetranz** [select2/select2#5180] opened 2017-12-27 17:09 UTC
This is probably a partial duplicate of https://github.com/select2/select2/pull/5169 and the associated fixes mentioned there but it seems to be more too.

With 4.0.6-rc.0 I am unable to specify ajax url and minimum input length using data-* attributes.
This does not work: http://jsbin.com/lazabud/edit?html,output

It works when I move the options to the function call. I think https://github.com/select2/select2/pull/5169 covers the ajax url but not the minimum input length. 

This still doesn't work properly: http://jsbin.com/vuleyoq/edit?html,output
It executes the query immediately before I enter any text.

This works correctly: http://jsbin.com/zupeki/edit?html,output

These all work with 4.0.5.

**Comment by alexweissman** [comment] 2017-12-27 19:33
@NadeemAfana can you take a look at this?

**Comment by NadeemAfana** [comment] 2017-12-27 19:53
Yes, this is a duplicate of #5169.

**Comment by alexweissman** [comment] 2017-12-27 20:01
Ah ok.  So does #5169 fix the minimum input length as well?

**Comment by NadeemAfana** [comment] 2017-12-27 20:20
Yes, it should. Let me know if you see any issue with that.

**Comment by tetranz** [comment] 2017-12-28 13:57
ok, thanks for looking at this although I'm a little confused.  5169 just changes one line of code related t the the url. `Utils.StoreData($e[0], 'ajax--url', Utils.GetData($e[0], 'ajaxUrl'));`

I don't see how that does anything with the minimum length. 4.0.5 is working fine for me so I'll take another look when that is merged and recompiled.

**Comment by alexweissman** [comment] 2017-12-29 03:28
I'll try to put out 4.0.6-rc.2 soon.

**Comment by kl3sk** [comment] 2018-03-30 08:41
Hi,
Any release ready ?
The problem still exists

thx

**Comment by KODerFunk** [comment] 2018-05-10 06:32
I experienced problems with `data-allow-clear` and `data-placeholder`.

**Comment by Ragash** [comment] 2018-05-28 22:45
same problem with 4.0.11, any workaround?

**Comment by kl3sk** [comment] 2018-05-30 07:57
@Ragash the last version is 4.0.6-rc.1 where did you find 4.0.11 ?

**Comment by Ragash** [comment] 2018-06-13 14:19
sorry my mind was wandering and i copied the Symfony version, instead the select2, lol.

i was actually under 4.06, and to resolve the bug i had to switch to 4.0.5, Rc2 didn't solved the issue at last for me

**Comment by chaumo** [comment] 2019-04-03 10:47
I've update from 4.0.5 to 4.0.6.rc1 because of other issues and now ajax search is broken
Changing to the 'old' deprecated data-ajax-url works, but new data-ajax--url doesn't  :( Any update or estimate for 4.0.6?

**Comment by crabnky** [comment] 2019-04-03 13:34
I think this is a duplicate of https://github.com/select2/select2/issues/5320.

**Closed** 2019-04-28 02:20 UTC
Labels: confirmed bug
