### ISSUE TITLE
Is maximumSelectionLength and closeOnSelect used on same time ?

### ISSUE THREAD

**Issue by sabinesh01** [select2/select2#4916] opened 2017-05-23 05:57 UTC
## Prerequisites

- [-] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. set options maximumSelectionLength:2, closeOnSelect: false for select tag with multiple attribute.
2. closeOnSelect:false is working fine but the maximumSelectionLength:2 is not working.
3. able to select all the options in dropdown. 
4. maximumSelectionLength error message displays when i delete the options from input box
5. Please find the attachment. the error message displays when i delete the options

## Expected behavior and actual behavior

When I follow those steps, I see, able to select all the options in dropdown

I was expecting, close the dropdown after select 2 options

## Environment

Browsers

- [-] Google Chrome
- [-] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [-] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.11.3
- Select2 version: 4.0.2

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [-] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)
<img width="614" alt="screen shot 2017-05-23 at 11 22 22 am" src="https://cloud.githubusercontent.com/assets/10168890/26340121/3687f506-3faa-11e7-8b7a-71f15f41ed81.png">

**Comment by alexweissman** [comment] 2017-09-25 02:05
This is a duplicate of #3514.

**Closed by alexweissman** 2017-09-25 02:05 UTC
