### ISSUE TITLE
in a multi-select select2, cannot click 'x' icon on an item to remove it if the focus is outside the select.  Worked fine in 4.0.0, broke in 4.0.1-rc.1, still broken

### ISSUE THREAD

**Issue by jamesmanning** [select2/select2#4658] opened 2016-10-27 19:06 UTC
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of Select2
- [X] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [X] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Create select that supports multiple selection with enough items selected that the bottom (where the focus will go when it's selected) is out of the current viewport (that seems to be the difference in my testing)
2. Have focus outside of the select (in the codepens, there's an input box for that)
3. Try clicking an 'x' in one of the currently selected items to remove it
## Expected behavior and actual behavior

When I follow those steps, I see...

Start with 4.0.1-rc.1 ( http://codepen.io/jamesmanning/pen/WGBxaZ ), the item isn't removed.  Clicking the x a second time (once the select gets focus) works, though.

I was expecting...
Clicking the x to remove the item works even if the focus is outside the select, like it did in 4.0.0 ( http://codepen.io/jamesmanning/pen/rrgLPL )
## Environment

Browsers
- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.1.3 (used in the codepens)
- Select2 version: breaks as of 4.0.1-rc.1, still broken in 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using Select2 without other pluigns
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/)

I made a jsbin repro at https://output.jsbin.com/hihozotupi/ but the width of the rendered select is way too narrow and I'm not sure why, but the codepen ones render wide enough to more easily see the behavior.

Working codepen (select2 4.0.0) = http://codepen.io/jamesmanning/pen/rrgLPL
Broken codepen (select2 4.0.1-rc.1) = http://codepen.io/jamesmanning/pen/WGBxaZ

**Comment by althaus** [comment] 2017-08-14 08:32
Did you found any workaround for this issue?

**Comment by jamesmanning** [comment] 2017-08-14 10:52
@althaus downgrading to 4.0.0 worked fine for me.

**Comment by althaus** [comment] 2017-08-15 10:45
@jamesmanning Ok. I've added a workaround for us that intercepts the mousedown event on the choice remove element and triggers `click` again. Not a really clean solution, but it's doing its job. :/

**Comment by alexweissman** [comment] 2017-10-03 18:06
This seems to be working fine again as of 4.0.4.  Possibly resolved by fixing some other issues related to the Select2 focus.

**Closed by alexweissman** 2017-10-03 18:06 UTC

**Comment by NeliHarbuzava** [comment] 2021-01-22 12:36
I can see it in version 4.0.13

**Comment by ghost** [comment] 2021-01-22 12:47
I can't remove options in the beginning of a select, but can remove those which are in the end of the list.

I suppose that this bug happens when a lot of options inside
if there are not many options, it can't be reproduced.
Maybe it is reproduced when a select is too high and does not fit the screen view and needs to be scrolled and focused

Compare:
-  [Select2 Test - 4.0.13 - lot of options (doesn't work)](https://codepen.io/neliharbuzava/pen/VwKOvdg)
- [Select2 Test - 4.0.13 - less options (works!)](https://codepen.io/neliharbuzava/pen/YzGbyJM)

**Comment by ghost** [comment] 2021-01-22 14:21
First [this event](https://github.com/select2/select2/blob/develop/src/js/select2/selection/multiple.js#L32) gets triggered
But [this event](https://github.com/select2/select2/blob/develop/src/js/select2/selection/multiple.js#L38) is not triggered for some reason. I think that's the reason of the bug

@kevin-brown  I've found that if I comment [this line](https://github.com/select2/select2/blob/develop/src/js/select2/core.js#L493) everything works fine

**Comment by kevin-brown** [comment] 2021-01-25 12:52
@NeliHarbuzava can you do me a favor and open a new ticket? It's easier to track since this ticket is long gone from our radar.
