### ISSUE TITLE
Safari 9 Search field

### ISSUE THREAD

**Issue by vdclouis** [select2/select2#3738] opened 2015-09-04 11:46 UTC
this needs to be added to make sure this input has no border in Safari 9

```css
.select2-container--default .select2-search--inline .select2-search__field {
    -webkit-appearance: none;
}
```

**Comment by kevin-brown** [comment] 2015-09-18 19:44
This is a duplicate of https://github.com/select2/select2/issues/3459.

**Closed by kevin-brown** 2015-09-18 19:44 UTC
Labels: 4.x

**Comment by istng** [comment] 2022-12-29 17:49
Thanks! I was not being able to properly change font size and font family on Safari (options and search input), and this fixed it, like so:
```
    .select2-container .select2-dropdown,
    .select2.select2-container,
    .select2-search--dropdown .select2-search__field {
      -webkit-appearance: none !important;
      font-family: sans-serif;
      font-weight: regular;
      -webkit-font-smoothing: antialised;
      font-size: 18px;
    }
```
