### ISSUE TITLE
Safari macOS.- Error in 4.0.3 using dropdownParent argument in definition - TypeError: m.css is not a function

### ISSUE THREAD

**Issue by rosorrentino** [select2/select2#4465] opened 2016-07-07 17:05 UTC
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of Select2
- [ X] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [X ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use Bootstrap and create a modal
2. Add a select2 inside it so add dropdownParent - As described in https://select2.github.io/options.html#dropdownParent
3. Try to use tour dropdown

## Expected behavior and actual behavior
No errors

ACTUAL

Error 
TypeError: m.css is not a function. (In 'm.css("position")', 'm.css' is undefined)

![captura de tela 2016-07-07 as 17 50 58](https://cloud.githubusercontent.com/assets/11443180/16661856/de6b9e56-446c-11e6-90e9-c01a97a85e58.png)

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [X] Apple Safari 10.0 from Sierra Developer Preview
Note same error on Safari 9 - Mac OS X 10.11.5 

It does work on Firefox without any error

Operating System

- [ ] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: jquery-2.1.4.min
- Select2 version: 4.0.3

Note: This problem is not present using Select2 4.0.0 

## Isolating the problem

- [ -] This bug happens [on the examples page](https://select2.github.io/examples.html)
- There is no modal error
- [ -] The bug happens consistently across all tested browsers
- No only iOS and macOS Safari
- [X ] This bug happens when using Select2 without other pluigns
Yes

**Comment by kevin-brown** [comment] 2016-07-07 22:09
This is almost guaranteed to be a duplicate of https://github.com/select2/select2/issues/4289#issuecomment-208092613.

**Closed by kevin-brown** 2016-07-07 22:09 UTC

**Comment by rosorrentino** [comment] 2016-07-11 14:30
PS If anyone sees this one, I had a cache issue with Firefox, it’s for all browsers.
