### ISSUE TITLE
Lock old tags from being removed?

### ISSUE THREAD

**Issue by seabasss** [select2/select2#4955] opened 2017-06-14 05:44 UTC
Hey,

Is it possible to lock tags so they appear as selected, but without the remove-x and backspace-remove? E.g. I want to be able to add new tags, but not remove old. New tags should be able to be removed though.

Thank you!

**Comment by seabasss** [comment] 2017-09-14 06:19
Bump :)

**Comment by alexweissman** [comment] 2017-09-22 16:41
This is a duplicate of #4859.

**Closed by alexweissman** 2017-09-22 16:41 UTC
Labels: feature request
