### ISSUE TITLE
Issue with 'tag' option and not 'multiple' input

### ISSUE THREAD

**Issue by Loki3000** [select2/select2#4374] opened 2016-05-23 10:46 UTC
## Steps to reproduce the issue

http://jsfiddle.net/w5hvcjdo/7/
1.    Enter "sometext" and press enter. 
2.    Enter "sometext" again and press enter. 
3.    Enter "sometext2" and press enter.
## Expected behavior
1. sometext added and selected
2. sometext added and selected
3. sometext2 added and selected
## Actual behavior
1. sometext added
2. sometext added
3. sometext2 added and selected
## Environment

Browsers
- [x] Mozilla Firefox

Operating System
- [x] Windows
- [x] I can reproduce this bug in [a jsfiddle](http://jsfiddle.net/w5hvcjdo/7/)

**Comment by kevin-brown** [comment] 2016-05-23 13:33
I'm not sure how you're checking if the elements are being selected, but the `selected` property on the `<option>` tags is being set to `true` when they are selected. The HTML `selected` attribute is not being set, because we're dealing with the JavaScript DOM elements and not the HTML elements.

**Comment by Loki3000** [comment] 2016-05-23 14:02
Hm... but select2 container still blank in two first cases and becomes filled only at step 3.
As I see, it's filled by exactly selected item. So in first two steps there is no selected item.

**Comment by kevin-brown** [comment] 2016-05-23 16:19
> but select2 container still blank in two first cases

I can't reproduce that in Chrome, for me it properly shows the selected item. Same for Edge.

**Comment by Loki3000** [comment] 2016-05-23 20:01
Strange to hear it.
Reproduced in Chrome:
![chrome](https://cloud.githubusercontent.com/assets/12333165/15482731/e7792fbe-2139-11e6-9b43-9d12dc696f3e.png)
Reproduced in FireFox:
![ff](https://cloud.githubusercontent.com/assets/12333165/15482732/e79d377e-2139-11e6-9e97-7a0f4d58b659.png)
Reproduced in Internet Explorer:
![ie](https://cloud.githubusercontent.com/assets/12333165/15482733/e79f93fc-2139-11e6-863f-5821c1f2c463.png)

**Comment by Loki3000** [comment] 2016-05-25 07:57
I discover that adding of blank <option> tag into <select> solves problem.
But it's not solution - just temporary hack.

**Comment by alexweissman** [comment] 2017-12-09 17:35
It's unclear what the issue is here, so I am closing it.

If you have discovered an underlying bug causing this problem, please search the open issues and comment there (or if an issue specifically about the underlying bug is not already open, you may open a new one - just make sure it identifies the **underlying bug**).

If, on the other hand, this is simply a matter of using Select2's features properly, it should be discussed on the [forums](https://forums.select2.org) instead.

**Closed by alexweissman** 2017-12-09 17:35 UTC
Labels: 4.x, support: troubleshooting
