### ISSUE TITLE
Showing tags(with dynamic ones) in the right order

### ISSUE THREAD

**Issue by ismnoiet** [select2/select2#4148] opened 2016-02-04 10:38 UTC
When i use the list of predefined items it is all organised and in the right order.
But when i add dynamic tags(created on the fly), and try to add once again predefined items  it is not in the right order and i get the dynamic tags always to the end even if they are not the last picked items.

**Comment by kevin-brown** [comment] 2016-02-04 18:35
This is a duplicate of https://github.com/select2/select2/issues/3106.

**Closed by kevin-brown** 2016-02-04 18:35 UTC
