### ISSUE TITLE
Re-sizing and re-position of dropdown popup doesn't work on window resize

### ISSUE THREAD

**Issue by ova2** [select2/select2#2977] opened 2015-01-27 11:28 UTC
My native select element has ```width:100%``` (is responsive). Now, I have a problem with the size of dropdown popup.

Steps to reproduce the bug:

1) Open Select2 4.0 beta with items.
2) Resize the window.
3) The size of the open dropdown doesn't get resized. It still has the original size.

Even worst. When resizing the window, the popup sticks at the original position and is not aligned with the field shown current select. You know, due to page's reflow, the select field and the dropdown can be at different positions.

This is a big problem for us because we develop a responsive web application for desktop and mobile. **I think you have always to align the open dropdown with the select field + shrink / enlarge it according to the current size of the select field.**

**Comment by kevin-brown** [comment] 2015-01-27 14:17
Duplicate of https://github.com/select2/select2/issues/2975.

**Closed by kevin-brown** 2015-01-27 14:17 UTC

**Comment by ova2** [comment] 2015-01-27 14:23
Do you mean, that works now? I have downloaded Select2 on last Friday (23.01) and it was not working.

**Comment by kevin-brown** [comment] 2015-01-27 14:26
#2975 is open, so it's not 100% fixed. Select2 should reposition itself when the window resizes and on scroll, but there are still some issues that need to be worked out before the next beta release.

**Comment by ova2** [comment] 2015-01-27 18:22
Ok, thanks for the clarification Kevin.
