### ISSUE TITLE
documentation update for "pre-used classes"

### ISSUE THREAD

**Issue by jeanpoelie** [select2/select2#3972] opened 2015-11-30 15:21 UTC
It would be nice to see some documentation about pre-used classes which i cannot use to name the dropdown.
I called it select2-dropdown, but this one is pre-used and messed the whole design up... after hours of searching i finally found it.

**Comment by alexweissman** [comment] 2017-09-14 01:19
This is a duplicate of #2809.

**Closed by alexweissman** 2017-09-14 01:19 UTC
