### ISSUE TITLE
how to trigger event on focus and blur

### ISSUE THREAD

**Issue by cornernote** [select2/select2#3457] opened 2015-06-10 10:12 UTC
It seems that in the 4.x releases the focus and blur events have been removed.  I assume this is because there is another way to hook into these events, but I can't find any documentation on this.

Can anyone give me a kick in the right direction as to how I handle focus and blur events?

Thanks.

**Comment by kevin-brown** [comment] 2015-06-11 00:27
Merging this into https://github.com/select2/select2/issues/1908, it's a duplicate of https://github.com/select2/select2/issues/3152.

**Closed by kevin-brown** 2015-06-11 00:27 UTC
