### ISSUE TITLE
Select2 with delayed Ajax and tags selects the wrong item when typing quickly

### ISSUE THREAD

**Issue by evigeant** [select2/select2#4440] opened 2016-06-23 14:25 UTC
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

In case there was an option I didn't know about, I opened this question, but got no response:
http://stackoverflow.com/q/37926173/5170665
## Steps to reproduce the issue
1. Create a Select2 using Ajax (with a delay) and tagging support. See https://jsfiddle.net/4rp8y9Lr/
2. Type <kbd>a</kbd>+<kbd>d</kbd> in the select2 box and wait until results appear but do not select any
3. The first result is highlited ("ad")
4. Then very quickly (quicker than delay), type <kbd>r</kbd>+<kbd>e</kbd>+<kbd>t</kbd> + <kbd>Enter</kbd>
## Expected behavior and actual behavior

When I follow those steps, the previously highlited result ("ad") is selected.

I was expecting either a new tag "adret" to be created or nothing selected until the Ajax finishes the lookup.

Basically, during the delay and Ajax call, the previous results are not cleared and still highlited, so the <kbd>Enter</kbd> key selects it.
## Actual use case

This is a simpler example than my actual use case which is for entering emails addresses (emails can be suggested by Ajax or new addresses can be entered).

When the Select2 gets focus, an Ajax call proposes a few email contacts by default, however, when the user types another email address quickly and presses <kbd>Enter</kbd> then the initially selected email address is added to the dropdown which is quite unexpected for users.
## Environment

Browsers
- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.12.4
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsfiddle](https://jsfiddle.net/4rp8y9Lr/)

**Comment by alexweissman** [comment] 2017-09-22 17:20
Closing this as a duplicate of #4854.  Even though this issue is older, there is already an ongoing discussion in that thread.

**Closed by alexweissman** 2017-09-22 17:20 UTC
Labels: 4.x
