### ISSUE TITLE
Show/Hide  options  programaticaly

### ISSUE THREAD

**Issue by StjopAvetisyan** [select2/select2#4991] opened 2017-07-19 12:39 UTC
"Display
Select2 provides options that allow you to directly affect how the container that holds the current selection is displayed."

So please explain me  how  can I  work wit just this  one  sentence

Is  there  any wat to SHOW/HIDE  just ONE (only ONE ) option from dropdown list in whitout making ajax call or  refilling data  into slect ?

**Comment by Grezvany13** [comment] 2017-09-29 09:08
+1

Although I would suggest to be able to modify the original ```select``` and then properly display (after re-initialising).

I already saw several issues related to the fact that Select2 doesn't care about CSS styling (```display:none```), and I even noticed that it doesn't even care about the ```hidden``` attribute.

CodePen: https://codepen.io/anon/pen/JrJKBq

As you can see the default handling (at least in Chrome) will hide the options which have either ```display:none``` in the CSS or have the ```hidden``` attribute. At least it follows the ```disabled``` attribute.

**Comment by alexweissman** [comment] 2017-09-29 16:52
I'm actually going to close this as a duplicate of #4105.  I am surprised though, that Select2 does not respect the `hidden` attribute on a hardcoded `<option>` element.

**Closed by alexweissman** 2017-09-29 16:52 UTC
Labels: feature request

**Comment by jfvoliveira** [comment] 2018-04-16 18:08
Hello. Does Select2 still not respect the hidden attribute of the option html element?
How can we make it respect it and hide those options?

**Comment by slava-lu** [comment] 2019-08-18 18:18
Is it still not working?

**Comment by reallyslick** [comment] 2020-12-01 17:26
+1 Would like to hide all options that do not have attribute=value

**Comment by laflier** [comment] 2022-07-26 13:37
+1 What @reallyslick said. Here's a workaround.

https://codepen.io/lflier/pen/xxWXwpg
