### ISSUE TITLE
Dropdown position off when selecting option

### ISSUE THREAD

**Issue by ethikz** [select2/select2#4501] opened 2016-07-25 21:24 UTC
I am using autocomplete with only one option allowed.  The issue is when there isn't room below the input the dropdown then goes above, which is ok but after making a selection and then clicking back on the input the container doesn't appear to clear the previous position of the open dropdown so it positions it weirdly.  When you click on the input again it readjusts.

This is most likely a duplicate of #3905 but wanted to bring it up to be sure.  If so feel free to close 😄 

The solution in 3905 doesn't fix the problem though.  When implemented it overlays the message on top of the input.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. shrink your browser to mobile view and make it small enough where there isn't room for the dropdown to open on bottom.
2. Make a selection
3. Without exiting the input, click in the open space in the input and above you'll see the position issue

## Expected behavior and actual behavior

When I follow those steps, I see...: The dropdown is way above the input

I was expecting...: To see the dropdown right above the input, touching input

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version: 2
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html#multiple-max)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](http://jsbin.com/kadeje/edit?html,output)

**Comment by kevin-brown** [comment] 2016-08-26 23:20
Correct, this is a duplicate of https://github.com/select2/select2/issues/3905.

**Closed by kevin-brown** 2016-08-26 23:20 UTC
