### ISSUE TITLE
Bad performance with a list of 950 items

### ISSUE THREAD

**Issue by marcgise** [select2/select2#3127] opened 2015-03-10 12:01 UTC
Hi,

I read something about the bad performance of Select2 component with a large list of items (950 in my case), but I don't found any solution.

As far as I get to know, the problem is in the initSelection method, when loading all the items. When calling callback function, Select2 component executes updateSelection() method (line 3303), that ends with calling an addSelectedChoice() method (line 2973), then formatSelection() method (line 3066) and finally the text() method (line 3443).

Every item go over this large road, and it consumes a lot of seconds. In my case, it takes about 45 or 50 seconds to load all the items.

I'm using Chrome in Windows and 3.5.2 version of Select2.

Is there any solution?

Thanks,
Marc

**Comment by kevin-brown** [comment] 2015-03-10 12:39
Much of this was _greatly improved_ in 4.0. I actually wrote about it a bit in [this blog post on jQuery performance](http://blog.kevinbrown.in/select2/2014/12/15/jquery-js-performance.html).

For 3.5.x, this is a duplicate of https://github.com/select2/select2/issues/781.

**Closed by kevin-brown** 2015-03-10 12:39 UTC
