### ISSUE TITLE
Allow to select values with up-down arrow keys

### ISSUE THREAD

**Issue by uzlov** [select2/select2#3682] opened 2015-08-18 15:10 UTC
The same with native select - when select don't open.

**Comment by uzlov** [comment] 2015-08-18 15:14
this.on('keypress', function (evt) {
      var key = evt.which;

      if (self.isOpen()) {
...
      } else {
...
        if (key === KEYS.DOWN) {
          this.$element.find('option:selected').next().attr('selected', 'selected').trigger('change');
          evt.preventDefault();
        }
        if (key === KEYS.UP) {
          this.$element.find('option:selected').prev().attr('selected', 'selected').trigger('change');
          evt.preventDefault();
        }
      }

**Comment by kevin-brown** [comment] 2015-08-18 15:15
This is a duplicate of https://github.com/select2/select2/issues/3472.

**Closed by kevin-brown** 2015-08-18 15:15 UTC

**Comment by akinhwan** [comment] 2019-03-04 19:18
so we just need to update the core.js file with the above function? is there a reason it is not part of the core.js ? just wondering
