### ISSUE TITLE
Press and hold Enter - it adds infinite instances of the first option

### ISSUE THREAD

**Issue by eddieklc** [select2/select2#4075] opened 2016-01-11 10:47 UTC
This is my code for populating the select list:

```javascript
var projectTypes = new FormData();
$.ajax({
  url: "php/json_project_types.php",
  type: "GET",
  dataType: 'json',
  data: projectTypes,
  cache:false,
  contentType: false,
  processData: false,
  success: function (data){
    $.each(data, function (i, item) {
      $('#PRtype-cb').append($('<option>', { 
          value: item.value,
          text : item.text 
      }));
    });
  }
});
```

And it does this (i selected the first one):
![screenshot_15](https://cloud.githubusercontent.com/assets/15689404/12231589/14d63cbc-b859-11e5-8f25-03a17439c881.png)

This happens if I just keep pressing Enter key:
![screenshot_16](https://cloud.githubusercontent.com/assets/15689404/12231590/14efb55c-b859-11e5-9edb-62ef7f1c0c2b.png)

**Comment by kevin-brown** [comment] 2016-01-11 15:07
You didn't include how you initialized Select2, and I suspect that is playing a role here. I can't reproduce the issue [on the examples page](https://select2.github.io/examples.html#multiple).

Note that the code you supplied should end up being roughly the same as statically defining these options (to Select2, at least), because they are being created outside of Select2.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by eddieklc** [comment] 2016-01-11 15:27
Dear Kevin,
I do apologize for the lack of info which I'm providing right away :)

Here's the init:
```javascript
$(".multiselect-search").select2({
      placeholder: "Select options below"
    });
```

I do understand that my method of populating the select2 is analog to hardcoded options in HTML (which also do not work as I wanted), but that shouldn't be problem, as far as I can see...

Answers to your other questions:
- I literally added the first option (either by clicking on it or typing and hitting enter) and kept hitting enter, the same option just kept adding to the select box.
- I tested this on Win8.1 x64 and xUbuntu; Chrome normal dist and Canary, Firefox and Firefox Dev Edition, Opera, all of these are up-to-date. And yes, the bug happens in every single testing instance.
 - I am not using Select2 with other plugins (Bootstrap is all over the site, tho). My jQuery version is 1.11.1, and Select2 version 3.4.3.

Thanks for the reply

**Comment by kevin-brown** [comment] 2016-01-11 15:37
I was attempting to reproduce this on Select2 4.0.1 (the latest release) instead of 3.4.3, so that's the first issue. Select2 3.4.3 was released on Sep 17, 2013, which was more than 2 years ago. As a result, it's out of the support cycle (all of 3.4.x is, actually), and **I would recommend upgrading to 3.5.4 or 4.0.1 if possible**.

I can't reproduce this on the [examples page for 3.5.4](https://select2.github.io/select2/#multi), so I suspect the issue may have been fixed in the last few years.

**Comment by eddieklc** [comment] 2016-01-11 15:38
Oh oops... I guess it was built-in in the dashboard theme I bought...

Will do an upgrade and I'll let you know the status of this bug. Thanks!

**Comment by eddieklc** [comment] 2016-04-19 12:17
@kevin-brown you can close this, the error was due to collision caused by the use of outdated Select2 plugin, everything works fine with the latest dist. Thanks for your support,

Eddie

**Closed** 2016-04-19 18:41 UTC
Labels: 3.x, needs information
