### ISSUE TITLE
can not input chinese on firefox broswer

### ISSUE THREAD

**Issue by zhangliu** [select2/select2#4967] opened 2017-06-21 08:43 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [√ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [√ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. install firefox
2. use "Automatic tokenization" function 
3. input chinese

## Expected behavior and actual behavior

When I follow those steps, I can not input any chinese.

I was expecting some chinese tag show

## Environment

Browsers

- [ ] Google Chrome
- [√ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [√ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.9.1
- Select2 version: 4.0.3

## Isolating the problem

- [√ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment] 2017-09-13 23:37
This is a duplicate of #4743.

**Closed by alexweissman** 2017-09-13 23:37 UTC
Labels: translation/i18n
