### ISSUE TITLE
Auto select an input text search term when blur

### ISSUE THREAD

**Issue by lovedota** [select2/select2#1994] opened 2013-12-21 06:25 UTC
Hi
I use select2 for tag user selection on Ajax

I am using a createSearchChoice for adding the search term for the selection list if there are no items.
But sometimes the server is slow for query, while ajax is calling the user tab to another textbox, and they want the select2 select this input text search term that they type before.
How can I do it.

**Comment by kevin-brown** [comment] 2016-06-25 18:03
This is effectively a duplicate of https://github.com/select2/select2/issues/2231, as they both point back to the same issue.

**Closed by kevin-brown** 2016-06-25 18:03 UTC
