### ISSUE TITLE
Use Multi-select theme for single select.

### ISSUE THREAD

**Issue by adzay** [select2/select2#3197] opened 2015-03-26 18:20 UTC
In the examples I have noticed that a multi-select box has a different autocomplete theme to the single sleect boxes.

- Select2 Single select boxes  two will put the search field beneath the input field.
- Select2  Multi-Selext boxes has the search field  within the input field. This is the style I would prefer.

For now In order to get that look I set my select box as as a multiple and then I limit selection to 1. Is there an option that will allow me to achieve the multi-select box look on a single select element

**Comment by kevin-brown** [comment] 2015-03-26 20:55
Duplicate of https://github.com/select2/select2/issues/1345.

**Closed by kevin-brown** 2015-03-26 20:55 UTC
