### ISSUE TITLE
Empty value options don't get displayed on search results

### ISSUE THREAD

**Issue by rubengc** [select2/select2#5783] opened 2020-02-26 13:40 UTC
I just see that on 4.0.4 was introduced support for empty options

I'm using 4.0.13 and still facing the issue that an option without value (but with a label) doesn't gets rendered
```
<select>
    <option value>Default</option>
    <option value="1">Option 1</option>
    <option value="2">Option 2</option>
</select>
```

It's a bug fix that needs get fixed or there is a way to force show the empty value option?

Thanks in advance!

**Comment by kevin-brown** [comment] 2020-02-26 19:57
Select2 will automatically hide the option which aligns with the placeholder option within the drop-down. This is a duplicate of #5688 because the documentation for this doesn't exist.

I would recommend using the `allowClear` option if you want users to be able to reset back to the placeholder option.

**Closed** 2020-02-26 19:57 UTC

**Comment by tflori** [comment] 2025-02-19 14:26
I have to disagree heavily. Allow clear is not the same as having a selectable placeholder item in your select box.

Allow clear adds a button with content "x" - that is not even an implementation of a button that you can modify via css (you should definetly do that with `::before { content: "x" }`). But a question I have: what is the typical behaviour of a button with an "x"? it closes a window/dialog - there is nothing to close. You have to hover over the button to see that the title says "remove all items". And even on your documentation page it is oddly positioned:

![Image](https://github.com/user-attachments/assets/bfe856de-594b-470c-9ec4-b658befff4ac)

Please add an option to disable hiding the placeholder. This is how select boxes always worked:

```html
<select>
  <option value="">- nothing selected -</option>
  <option value="0">this is zero</option>
  <option value="1">this is one</option>
</select>
```

Select2 is a game changer and everyone is using it. But you should be able to apply select2 to a select element without changing it's behavior right?
