### ISSUE TITLE
Placeholder in multiple select

### ISSUE THREAD

**Issue by Myrdivar** [select2/select2#3861] opened 2015-10-22 13:18 UTC
Hi,

I'm experiencing a strange behaviour with the placeholder even on your example page. If I click, open and select an option the control remains opened until I select a second one. When I succesfully remove both selected options the control remains opened even when I click outside the control.

I'm running the latest IE.

**Comment by kevin-brown** [comment] 2015-10-27 22:51
This is a duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-10-27 22:51 UTC
