### ISSUE TITLE
How could enable duplicate values to select2 ?

### ISSUE THREAD

**Issue by fernandopaiva** [select2/select2#3829] opened 2015-10-13 04:04 UTC
I'm looking for any way to enable duplicate values. I'm using select2 4.0 but I don't know how I could do this.
I need that select2 has one or more ids to the same value. Example: ("A", "B", "C"), the value "A" is selected once or twice or more: ("A", "B", "A", "C"). In this example I have two "A".

How could I do this ?

**Comment by kevin-brown** [comment] 2015-10-13 19:15
This is a duplicate of https://github.com/select2/select2/issues/1002#issuecomment-111492975.

**Closed by kevin-brown** 2015-10-13 19:15 UTC

**Comment by phuwin** [comment] 2015-11-09 13:38
But still no answer for this yet?
@kevin-brown

**Comment by brightniyonzima** [comment] 2020-02-12 02:39
@kevin-brown Pliz provide an answer for this. I have noticed you can just been closing issues related tot this query but there is no clear answer or sample code for this
