### ISSUE TITLE
select2 tree hierarchy problem

### ISSUE THREAD

**Issue by adessilly** [select2/select2#3881] opened 2015-10-29 15:34 UTC
Hi,

We have a problem with select2 using a tree hierarchy, only the lvl 0 and lvl 1 items can be selected. The others are clickable but they don't appear to be selected.

You can check this out here : https://jsfiddle.net/1wkvn1ya/3/

**Comment by kevin-brown** [comment] 2015-10-30 00:46
This looks like a duplicate of https://github.com/select2/select2/issues/3866.

**Closed by kevin-brown** 2015-10-30 00:46 UTC
