### ISSUE TITLE
Doesn't respond on focus

### ISSUE THREAD

**Issue by rain01** [select2/select2#3633] opened 2015-07-31 18:49 UTC
When you TAB onto focus a regular `<select>` you can start typing right away and it will select the option depending what you type... but with select2 when you TAB onto it and start typing, it won't do anything.

Is it possible to have it open on focus at least? The same when you click on it?

**Comment by kevin-brown** [comment] 2015-07-31 19:04
Duplicate of https://github.com/select2/select2/issues/3279.

**Closed by kevin-brown** 2015-07-31 19:04 UTC
