### ISSUE TITLE
Request : Add option to prevent/disable new tag when not found in the list

### ISSUE THREAD

**Issue by fas3r** [select2/select2#4228] opened 2016-03-02 04:31 UTC
Hello,

when tagging is active , the default behave is to create a new tag even if nothing was found in the list. Would be possible to disable/prevent this to keep the same behave than without tagging.

Thank you by advance.

**Comment by matzeso** [comment] 2016-03-02 15:16
Maybe you can use normal multiple select? Than you have "tags", too - but you can not add new values.
https://select2.github.io/examples.html#multiple

**Comment by fas3r** [comment] 2016-03-10 01:42
It does not seems to work when using ajax.

**Comment by kevin-brown** [comment] 2016-03-10 15:32
This is a duplicate of https://github.com/select2/select2/issues/3974, and the documentation for this is something we are actively working on.

The short answer is that you can override `createTag` to be a function which returns `undefined` when you don't want the tag to be created.

https://select2.github.io/options.html#can-i-control-when-tags-are-created

**Closed by kevin-brown** 2016-03-10 15:32 UTC
