### ISSUE TITLE
Setting value without triggering the change event

### ISSUE THREAD

**Issue by enumag** [select2/select2#4159] opened 2016-02-07 12:26 UTC
According to the docs when I want to set a new value by jQuery I should just call `$('#selectid').val(value).trigger('change')`. This is not acceptable for me though because I use the change event to handle user interactions. However usually I don't want to trigger these when the value is set by javascript.

Is there a way to set the value without triggering the event? I would not mind triggering some custom event like `.trigger('select2:change')` or something.

**Comment by kevin-brown** [comment] 2016-02-08 22:30
Select2 only officially supports the `change` event for notifying the component when there is a change. This is pretty standard and we're avoiding implementing a custom event to get around this.

You _can_ trigger the internal handler by just triggering `change.select2`, thanks to the way that jQuery namespaces events.

http://stackoverflow.com/q/17819709/359284#31856728

This is a duplicate of https://github.com/select2/select2/issues/3620.

**Closed by kevin-brown** 2016-02-08 22:30 UTC

**Comment by enumag** [comment] 2016-02-08 22:54
In my opinion you whould put this to documentation instead of or at least alongside with the normal change event.

Thanks!

**Comment by wasimxe** [comment] 2018-01-04 12:06
$('.select_auto').on('select2:selecting', function(e) { 

When trigger change, above function should be trigger, but its not. I changed selecting to change but still not working
