### ISSUE TITLE
TypeError when preventing "opening"

### ISSUE THREAD

**Issue by althaus** [select2/select2#3837] opened 2015-10-16 09:44 UTC
Hi,

I'm working around to prevent the default toggle when a user removes an element from a multiple selection. Sending `preventDefault` on the `opening` event triggers a TypeError in the console:

`TypeError: args is undefined` in line https://github.com/select2/select2/blob/master/src/js/select2/core.js#L372

See this fiddle: https://jsfiddle.net/dauLcumq/1/

Sadly the documentation lacks hints on how to handle events.

Cheers
Matthias

**Comment by kevin-brown** [comment] 2015-10-16 17:51
This is a duplicate of https://github.com/select2/select2/issues/3431.

**Closed by kevin-brown** 2015-10-16 17:51 UTC

**Comment by althaus** [comment] 2015-10-19 06:59
Sorry for the dupe. Seems my SearchFu was bad on Friday. :(
