### ISSUE TITLE
Cannot disable select using IE8

### ISSUE THREAD

**Issue by kjprice** [select2/select2#3991] opened 2015-12-04 18:49 UTC
We received a report that one of our fields was not disabling correctly. Upon further inspection, it appears that the field is not disabling in IE8.

This is taken from the [Examples page](https://select2.github.io/examples.html) (note that the `Disable` button had just been clicked):

![image](https://cloud.githubusercontent.com/assets/2319673/11598050/2e6c910e-9a85-11e5-979e-ca0806e7a1c4.png)

I am not sure if IE8 will be supported, but it would be nice to have.

**Comment by kevin-brown** [comment] 2015-12-04 20:38
This is a duplicate of https://github.com/select2/select2/issues/3271.

**Closed by kevin-brown** 2015-12-04 20:38 UTC
