### ISSUE TITLE
Dropdown not repositioned after clearing search term

### ISSUE THREAD

**Issue by nradford** [select2/select2#3786] opened 2015-09-21 20:42 UTC
In the "Loading remote data" demo (https://select2.github.io/examples.html) if you scroll down far enough to make the dropdown appear above the select you can see that the dropdown is not repositioned after you clear the search.

If you search for "a" and wait for the results to load then delete the "a" the dropdown does not move even though the results are cleared.  
![screenshot 2015-09-21 15 39 44](https://cloud.githubusercontent.com/assets/954495/10004395/1145d7ea-6077-11e5-9aa5-21b61d7f79d8.png)

It looks like the _positionDropdown function is not called when the search term is deleted.

**Comment by kevin-brown** [comment] 2015-09-22 14:46
I was able to reproduce this on Chrome in Windows 10 on the documentation page.

**Comment by florinac** [comment] 2016-03-17 09:10
+1
Also noticed the same problem occurs after selecting an option and then reopening the dropdown.

**Comment by michaud** [comment] 2016-06-03 10:44
+1
My solution was clearing the results:

```
                    $(that._countrySelect).data('select2').on('open', function (e) {
                        this.results.clear();
                        this.dropdown._positionDropdown();
                    })
```

**Comment by alexweissman** [comment] 2017-09-17 02:13
Closing this as a duplicate of #4614.

**Closed by alexweissman** 2017-09-17 02:13 UTC
Labels: 4.x, confirmed bug
