### ISSUE TITLE
Search on select box when typing on focus

### ISSUE THREAD

**Issue by alvarotrigo** [select2/select2#3702] opened 2015-08-21 11:29 UTC
I managed to fix the accessibility problem of using the keyboard arrows to move through the different options when the element is on focus by following [this suggested fix](https://github.com/select2/select2/issues/3472#issuecomment-132246474).

Now, I was wondering if there's any way to directly open the select dialog box to start searching if the user has the select box on focus and they start typing.

Otherwise the process becomes a bit slower and the user has to click on the select box to open it for a search or rather click the enter button. 

I managed to fix it with a bad hack so whenever the user types on a focused select box, it starts filtering through the possible options.
[Reproduction online](http://jsfiddle.net/mJEZK/17/)

But it would be nice to have an option for it in the plugin.

```javascript
$(".select2").select2();

//on key down
$(document).keypress(keydownHandler);

function keydownHandler(e) {
    var activeSelectBox = $('.select2-container.select2-container--focus').prev('.select2');
    activeSelectBox.select2('open');
    
    activeChar =String.fromCharCode(e.which);
    setTimeout(function(){
    	$('.select2-container--open').find('.select2-search__field').val(activeChar);
    }, 30);
}
```

**Comment by kevin-brown** [comment] 2015-08-21 13:57
> Now, I was wondering if there's any way to directly open the select dialog box to start searching if the user has the select box on focus and they start typing.

Sounds like a duplicate of https://github.com/select2/select2/issues/3279.

**Closed by kevin-brown** 2015-08-21 13:57 UTC
