### ISSUE TITLE
Bootrstrap modals?

### ISSUE THREAD

**Issue by morrow95** [select2/select2#3367] opened 2015-05-17 03:24 UTC
Anyone have 4.0 working in Bootstrap modals?  It is probably a css issue, but seeing as how popular bootstrap is I'm sure this would apply to quite a lot of people.

The funny thing is this works in IE 11, but not the latest Firefox, Chrome, or Safari - https://jsfiddle.net/u5n590cq/6/

**Comment by kevin-brown** [comment] 2015-05-17 20:56
Duplicate of https://github.com/select2/select2/issues/600, works at https://jsfiddle.net/u5n590cq/7/.

**Closed by kevin-brown** 2015-05-17 20:56 UTC
