### ISSUE TITLE
Can't close dropdown on small height screen

### ISSUE THREAD

**Issue by MWDavidH** [select2/select2#4731] opened 2016-12-23 11:16 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. open codepen link in fullscreen (need full height screen)
2. click on each select2 and outside it at the bottom or in sidebar to try to close dropdown

## Expected behavior and actual behavior

When I follow those steps, I was expecting dropdown close

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows

Libraries

- jQuery version: 1.11.3
- Select2 version: 4.0.3

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] I can reproduce this bug in [a codepen](http://codepen.io/anon/pen/PbgMGj)

![screenshot_4](https://cloud.githubusercontent.com/assets/19555404/21452767/79f99f1e-c909-11e6-87ef-0562338ed22e.jpg)

**Comment by kevin-brown** [comment] 2017-01-05 23:28
I was only able to reproduce this one on the "With DropdownParent" one, which you'll notice definitely has issues. The problem here is actually that for the `dropdownParent` option, you're passing in multiple options. Select2 expects you to pass in a single option so it can consistently track down the parent.

As far as why you can't click on the very bottom and close the Select2, this is because technically that's outside of the body of the document. Select2 can't actually detect clicks down there (consistently, across all browsers) because it's outside of the range we can detect.

I was not able to reproduce the issue with having it close when clicking the right sidebar. I'm going to close off this ticket as not a bug, but if you're able to write up some steps for consistently reproducing the closing issue, then I can reopen this.

**Closed by kevin-brown** 2017-01-05 23:28 UTC

**Comment by MWDavidH** [comment] 2017-01-06 08:15
Hi, thanks for your answer, did you saw the codepen link ? http://codepen.io/anon/pen/PbgMGj
To reproduce the bug you need to move up the codepen window to the top or on a fullscreen view

![screenshot_7](https://cloud.githubusercontent.com/assets/19555404/21711696/8bb3c72e-d3f0-11e6-8119-94c3c11343e4.jpg)
