### ISSUE TITLE
No tag created between <option selected> and data array in script

### ISSUE THREAD

**Issue by boubou1030** [select2/select2#3955] opened 2015-11-23 16:53 UTC
I use Select2 4.0.1-rc.1. 
The data: ["Clare","Cork","South Dublin"] is defined in javascript.
The selected option "Cork" is derived from database in html.
I would like to show "Cork" in tag, however, this tag didn't be shown.
I'm wondering how to solve this problem? Thanks.
https://jsfiddle.net/Lroq1oac/1/

But it works in Select2 4.0.0
https://jsfiddle.net/r7cop362/

**Comment by boubou1030** [comment] 2015-12-01 15:39
This question is specific and simple, just wondering if there is any 
keyword or related issue number so that I can look it up? Thanks.

**Comment by kevin-brown** [comment] 2015-12-04 17:54
This is a duplicate of https://github.com/select2/select2/issues/3990 (picked that ticket because it is general).

**Closed by kevin-brown** 2015-12-04 17:54 UTC

**Comment by boubou1030** [comment] 2015-12-04 19:21
Thanks! Hope it will be fixed soon.
