### ISSUE TITLE
On IE 11, Pressing Enter to select an option, loses the focus from select.

### ISSUE THREAD

**Issue by chanchalkariwala** [select2/select2#3450] opened 2015-06-09 10:27 UTC
I am planning to use select2 for prouction, when I faced this issue while exploring.
Refer the first example for Multiple Select boxes - https://select2.github.io/examples.html

When I type something and hit enter to select any option, select loses focus. The focus is now on the browser. So when I hit backspace in order to deselect the option, it actually performs Browser Back function.

Secondly, say if select the box again after hitting enter, hitting backspace one removes the tag but select loses the focus again. So when I hit backspace again, it again performs Browser back function.

Please resolve this or provide a workaround, because most of our user base uses IE.

**Comment by kevin-brown** [comment] 2015-06-09 14:07
Duplicate of https://github.com/select2/select2/issues/3332.

**Closed by kevin-brown** 2015-06-09 14:07 UTC
