### ISSUE TITLE
Display a drop-down box to locate the problem

### ISSUE THREAD

**Issue by phphuan** [select2/select2#5074] opened 2017-10-09 09:16 UTC
## Prerequisites

With the select2 plugin in the browser page to a different location ( switch at the top to the bottom ), the search results will display a drop-down box of positioning is not accurate

## Steps to reproduce the issue

1.Scroll the browser's scrollbar color option(html tag select) at the top of the page.Then click the input box Get search results
2.Scroll the browser's scrollbar color option at the bottom of the page
3.Then click the input box Get search results.Positioning is not accurate display of the results

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment
Browsers

 Google Chrome
版本 56.0.2924.87
Operating System

 Windows7
Libraries

jQuery version:
1.9.1
Select2 version:
4.0.2

![seelct2](https://user-images.githubusercontent.com/12897599/31331531-3c354e1c-ad15-11e7-9ee1-9c7678129a31.jpg)

**Comment by alexweissman** [comment] 2017-10-09 14:40
Sounds like maybe this is a duplicate of #4230?  There are numerous [position-related issues](https://github.com/select2/select2/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20position%20) already open.

**Closed** 2017-12-08 18:30 UTC
Labels: duplicate
