### ISSUE TITLE
Select4 not playing nicely with bootstrap modals.

### ISSUE THREAD

**Issue by piegus** [select2/select2#3382] opened 2015-05-20 22:25 UTC
hi.
I was porting to new select2 v 4.
But i stumbled on select2 not working on modal windows.
 here is jsbin to show what's going on:
http://jsbin.com/yelinicuwi/1/

apparently removing tabindex='-1' from modal div worked, I can click on select2 and I see letters appearing. But there isn't any ajax going off from this.
I see letters but ajax query is not firing.

**Comment by albertolobrano** [comment] 2015-05-21 17:48
I have go the same problem.  select2 works fine on normal pages but is not for bootstrap modals.

**Comment by albertolobrano** [comment] 2015-05-21 18:52
For some reason the select2 component does not work in modal.  the search input and the list of items is not coming up.  It is calling the ajax function which is resolving with some data. 

can you help me understand what it is going on?  I am on select2 3.0.0 and bootstrap 3.3.4

 I did not have this issue with the previous version of select. 


![screen shot 2015-05-21 at 20 49 06](https://cloud.githubusercontent.com/assets/930785/7756353/f8101d1c-fffa-11e4-8d72-791b1717b717.png)
![screen shot 2015-05-21 at 20 49 31](https://cloud.githubusercontent.com/assets/930785/7756354/f8111e10-fffa-11e4-9ac7-535a53994425.png)

**Comment by kevin-brown** [comment] 2015-05-21 19:09
Duplicate of https://github.com/select2/select2/issues/2152.

**Closed by kevin-brown** 2015-05-21 19:09 UTC

**Comment by albertolobrano** [comment] 2015-05-22 06:37
with the same code i was running version 3 of select2 and i  had no issues.   i don't think this issue is related to the others. Tabindex is set to 0 for the select 2 component

**Comment by albertolobrano** [comment] 2015-05-22 07:23
my issue is not related to tabindex or focus issues.  It was a z-index issue.  the modal z-index was higher than the select2 z-index.  I increased select-2 z-index and everything is working fine.
