### ISSUE TITLE
Focus is going out when  backspace clicked On internet explorer 8

### ISSUE THREAD

**Issue by ameersohel** [select2/select2#3719] opened 2015-08-28 13:19 UTC
am using select2 4.0.0 on IE 8. when I try to remove an option using backspace ,option is removed but select2 is unfocused. If I click backspace immediately then browser is redirecting to previous page

**Comment by kevin-brown** [comment] 2015-08-28 13:52
This is a duplicate of https://github.com/select2/select2/issues/3168.

**Closed by kevin-brown** 2015-08-28 13:52 UTC
