### ISSUE TITLE
(v 4.0.0) Open and opening events seem to fire multiple times?

### ISSUE THREAD

**Issue by rohan-deshpande** [select2/select2#3868] opened 2015-10-26 05:11 UTC
I have a simple initialize method like so

    init:function (raw, options) {
        var _this = this;
        var $select2 = $(React.findDOMNode(this.refs.select2));

        $select2.select2({data:options});

        $select2.on('select2:open', function (e) {
            console.log('open');
        });

        $select2.on('select2:opening', function (e) {
            console.log('opening');
        });
    }

Options is not small, maybe 3000 items in the array. In any case, when I click inside the form field, this is the log output

```
opening
open
opening
open
```

This happens on clicking into the field just once. It's slightly problematic because due to the amount of items being listed, there is a noticeable delay in rendering the options. It feels kind of buggy so I'd like to place a loader somewhere which would start on the `opening` event and hide on the `open` event, however, this isn't really possible because these events fire twice. FYI the options are only rendered on the second set of events being fired.

Not too sure what is going on. 

**Edit** well I've solved my original need for this solution by using `minimumInputLength` but I still don't know why these events are firing like this.

**Comment by kevin-brown** [comment] 2015-10-27 23:01
This is a duplicate of https://github.com/select2/select2/issues/3503.

**Closed by kevin-brown** 2015-10-27 23:01 UTC
