### ISSUE TITLE
Expand/collapse tags

### ISSUE THREAD

**Issue by spirit2343** [select2/select2#2456] opened 2014-06-12 01:59 UTC
Is it possible to collapse tags and expand them when necessary?

Thank you

**Comment by mokross** [comment] 2016-02-04 13:54
It would :+1: for that feature!

**Comment by kevin-brown** [comment] 2016-02-04 18:49
This appears to be a duplicate of https://github.com/select2/select2/issues/3269.

**Closed by kevin-brown** 2016-02-04 18:49 UTC
