### ISSUE TITLE
home and end keys do not change the selection

### ISSUE THREAD

**Issue by okonomiyaki** [select2/select2#3739] opened 2015-09-04 21:13 UTC
In a regular select box, pressing home or end changes the selection to the first or last option, respectively, whether the selection list is expanded or not.

In select2 4.0, home and end keys aren't handled and the event is passed up to the browser.

**Comment by kevin-brown** [comment] 2015-09-05 03:40
Even though the title issue may not reflect it, this is effectively a duplicate of .https://github.com/select2/select2/issues/3472 and is blocked by the issues described in https://github.com/select2/select2/issues/3279#issuecomment-96450069.

**Closed by kevin-brown** 2015-09-05 03:40 UTC

**Comment by the-super-coder** [comment] 2016-03-16 12:28
If this feature is not going to be a part of the official build, is there any way to extend the library and implement this?
