### ISSUE TITLE
templateSelection rendered after onchange was triggered

### ISSUE THREAD

**Issue by Seb33300** [select2/select2#5088] opened 2017-10-23 16:00 UTC
I am using the `templateSelection` option to dynamically add `data-*` attributes to my `<option>` (loaded via ajax).

I added a listener on the `change` event to get the selected value.
But the `change` event seems to be triggered before the `templateSelection`.

This make me impossible to get the data-* values from the listener.

See: https://jsfiddle.net/odzq2wkj/2/ (just select a value from the list)

**Comment by alexweissman** [comment] 2017-10-23 16:46
Looks like a duplicate of https://github.com/select2/select2/issues/5036.

**Closed by alexweissman** 2017-10-23 16:46 UTC

**Comment by Seb33300** [comment] 2017-10-23 17:16
I don't think this is the same issue.

I can access to data-* attribute properly.
But the `onchange` is triggered before select2 call the `templateSelection` function so I can't access to the data-* since they are added after.
