### ISSUE TITLE
Cannot focus select2

### ISSUE THREAD

**Issue by gitPhate** [select2/select2#3469] opened 2015-06-11 12:33 UTC
I wanted to focus on the select2 element, in order to make borders of it blue and the user can use it by hitting the enter key. I tried with jQuery and searched for some docs on your site, but I haven't found anything.
What can I do?

**Comment by kevin-brown** [comment] 2015-06-11 13:40
Duplicate of https://github.com/select2/select2/issues/2311.

**Closed by kevin-brown** 2015-06-11 13:40 UTC
