### ISSUE TITLE
box-sizing: border-box is missing on input field for multiple selection

### ISSUE THREAD

**Issue by ova2** [select2/select2#3029] opened 2015-02-10 10:01 UTC
Please add ```box-sizing: border-box``` as follows:

```css
.select2-container--default .select2-selection--multiple .select2-selection__rendered {
    list-style: none;
    margin: 0;
    padding: 0 5px 5px 5px;
    width: 100%;
    box-sizing: border-box;
}
```

Otherwise the width is not correct calculated with ```width: 100%``` + padding / margin. Please note, ```padding``` is also corrected as ```0 5px 5px 5px;```. In the showcase, this setting is done for all elements in the bootstrap.css. But I don't have bootstrap.css.

I already reported a similar issue for search field https://github.com/select2/select2/issues/2978

Thanks a lot!

**Comment by ova2** [comment] 2015-02-10 11:04
I also had some empty space between input field and the dropdown (multiselect onyl). This problem was due to ```display: inline-block``` for class ```.select2-container .select2-selection--multiple .select2-selection__rendered```. I changed it to ```display: block``` as follows

```css
.select2-container .select2-selection--multiple .select2-selection__rendered {
    display: block;
    overflow: hidden;
    padding-left: 8px;
    text-overflow: ellipsis;
}
```

and the empty space was gone. Can you consider this fix too? Thanks.

**Comment by ova2** [comment] 2015-02-14 15:42
Thanks. Did you also add ```display: block``` for ```.select2-selection__rendered```?

**Comment by kevin-brown** [comment] 2015-02-14 17:22
Nope, I also missed the padding issue. I'll fix those both later, but I'll reopen this for now.

**Comment by kevin-brown** [comment] 2015-03-01 23:55
Closing this off again.

> Last but not least my settings for select2-selection__choice (simple compare with current defaults).

The individual selections start to look quite large with the added top/bottom padding.

> This problem was due to display: inline-block for class .select2-container .select2-selection--multiple .select2-selection__rendered.

Couldn't reproduce the issue, and changing it to `display: block` caused the padding to be removed.

---

I'd need to see jsfiddles/jsbins which showed the difference with these slight changes to see what the impact is.

**Closed by kevin-brown** 2015-03-01 23:55 UTC
