### ISSUE TITLE
creating a new tag with a token separator does not trigger a select2:select event

### ISSUE THREAD

**Issue by AlexJuarez** [select2/select2#3805] opened 2015-09-30 18:54 UTC
The event creation is inconsistent

**Comment by AlexJuarez** [comment] 2015-10-01 16:23
see line https://github.com/select2/select2/blob/master/src/js/select2/data/tokenizer.js#L73 for new tag creation after selection.

**Comment by kevin-brown** [comment] 2015-10-12 19:26
This is a duplicate of https://github.com/select2/select2/issues/3325.

**Closed by kevin-brown** 2015-10-12 19:26 UTC
