### ISSUE TITLE
Tab - Switch to next form element does not work, because form focus is lost

### ISSUE THREAD

**Issue by nino-s** [select2/select2#4419] opened 2016-06-14 07:47 UTC
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Visit [https://select2.github.io/examples.html](https://select2.github.io/examples.html)
2. Select a Select2 field with a search field 
3. Now press Esc or Tab
4. The active select field is not marked active anymore
## Expected behavior and actual behavior

When I follow those steps, I see that the active field of the form is lost.

I was expecting that the field is still marked as active.
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.2.3 and version on examples page
- Select2 version: 4.0.3 and master version
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

The bug came up on the 4.0.3 release. I found the commit and already commented it: [Support the focus event](https://github.com/select2/select2/commit/31e7a1d4c52ed7477769fcad5d15166ae3c9b4d0)

**Comment by phazei** [comment] 2016-06-17 17:34
Also lost after selecting an option with the keyboard

**Comment by phazei** [comment] 2016-06-17 18:13
maybe similar/dupe of this 
https://github.com/select2/select2/issues/4384

**Comment by rvion** [comment] 2016-06-22 11:08
same on chrome, this is quite annoying

**Comment by drewmcd621** [comment] 2016-09-26 15:45
This appears to be an issue that is in 4.0.3 only:

4.0.2 works correctly: https://jsfiddle.net/nwvg0kLx/1/

4.0.3 not working: https://jsfiddle.net/k5p4k528/1/

I also tried it in both 4.0.0 and 4.0.1 and both worked.

**Comment by evanhooff** [comment] 2017-01-17 14:55
Very annoying, please fix...

**Comment by nino-s** [comment] 2017-01-18 13:51
@kevin-brown any news on this one?

**Comment by Vaccano** [comment] 2017-03-14 23:03
A fix would be great on this.  

Since it has been 3/4 a year and the issue was introduced in a patch release, I have to wonder if Select2 no longer being maintained?

**Comment by phazei** [comment] 2017-03-23 16:43
This temp fix does work:

https://github.com/select2/select2/issues/4384#issuecomment-228464364

**Comment by nino-s** [comment] 2017-09-05 08:16
@alexweissman I saw that you have taken over this project? Can we get a statement from your side?

**Comment by alexweissman** [comment] 2017-09-05 19:14
I've been added as a maintainer, but I'm not familiar enough with the codebase to start merging in actual changes to the code yet.  My priorities right now are to clean up and improve the documentation, as well as the issue tracker.

@nino-s have you submitted a PR for this already?  A PR, and some code reviews from other members of the community, would help this get fixed more quickly.

**Comment by nino-s** [comment] 2017-09-06 06:20
Ah i understand. I wish you a good start with such a large project ;)

Ofcourse i did: https://github.com/select2/select2/pull/4427

**Comment by alexweissman** [comment] 2017-09-06 12:25
I'm actually confused as to why this is a problem, though.  Isn't focus _supposed_ to be lost when you tab/escape from a control?

**Comment by nino-s** [comment] 2017-09-06 13:57
Go to any example on the https://select2.github.io/examples.html page. If you click on a select2 field and afterwards press Tab, you should not loose the focus on the current element, should you? Tabbing should switch to the next form elements.

Actually, select2 does not do switch to the next form element, because the whole focus is lost.

**Comment by alexweissman** [comment] 2017-09-06 14:35
OK, so this is the real problem:

> Select2 does not do switch to the next form element, because the whole focus is lost

Could you please edit the title to clarify this?  Communication is key...

**Comment by nino-s** [comment] 2017-09-06 14:41
Here you go, also modified pull request title.

**Comment by alexweissman** [comment] 2017-09-06 14:57
Thanks!  So, something I could do until I can get a hold of @kevin-brown, is to start merging these more thoroughly tested/reviewed PRs into a new branch.  Would that work for you?

**Comment by nino-s** [comment] 2017-09-06 15:02
I just thought that you would maintain the project, thats why i wrote here again. A temp fix was already found: https://github.com/select2/select2/issues/4384#issuecomment-228464364

Their is no need to make a new branch only for this PR. But if more PRs form you will follow, it would be a good idea to make a new branch. I do not know how @kevin-brown will handle this?

**Comment by alexweissman** [comment] 2017-09-06 15:05
Right, what I'm saying is that I can merge multiple PRs into a single new branch for now, to be merged back into `master` and released pending Kevin's approval.

**Comment by alexweissman** [comment] 2017-09-06 15:05
Actually, if you want to join me on my [chat server](https://chat.userfrosting.com/channel/select2), we can strategize more there.

**Comment by alexweissman** [comment] 2017-09-06 21:06
It begins... https://github.com/select2/select2/tree/hotfix

**Comment by nino-s** [comment] 2017-09-08 08:58
Sorry, that i did not join the chat. I was very busy.

Great to hear with the new branch!

**Comment by alexweissman** [comment] 2017-09-24 16:41
@nino-s I have merged your fix into `master`, so it should appear in the 4.0.4 release.

**Closed by alexweissman** 2017-09-24 16:41 UTC
Labels: 4.x, confirmed bug
