### ISSUE TITLE
selectOnClose: Error

### ISSUE THREAD

**Issue by anilastrio** [select2/select2#2962] opened 2015-01-23 07:03 UTC
Tried your latest select2 version now, but there seem to be an error.

```php
$('#test').select2({
	dir: "<?php right_to_left(); ?>",
	language: "<?php echo $get_site_lang; ?>",
	selectOnClose: true,
	tags:true,
	tokenSeparators: [","]
});
```

Error from console
```javascript
select2.js:567 Observable.trigger
select2.js:4775 Select2.trigger
select2.js:4593 (anonymous function)
select2.js:2721 SelectAdapter.current
select2.js:4592 (anonymous function)
jquery.min.js:3 m.event.dispatch
jquery.min.js:3 r.handle
jquery.min.js:3 m.event.trigger
jquery.min.js:3 (anonymous function)
jquery.min.js:2 m.extend.each
jquery.min.js:2 m.fn.m.each
jquery.min.js:3 m.fn.extend.trigger
select2.js:2731 SelectAdapter.select
select2.js:2801 (anonymous function)
select2.js:577 Observable.invoke
select2.js:567 Observable.trigger
...
select2.js:577 Observable.invoke
select2.js:571 Observable.trigger
select2.js:1054 (anonymous function)
jquery.min.js:3 m.event.dispatch
jquery.min.js:3 r.handle
jquery.min.js:3 m.event.trigger
jquery.min.js:3 (anonymous function)
```

**Comment by jonahgreenthal** [comment] 2015-01-26 20:53
Is this and #2953 the same thing as "this.getHighlightedResults is not a function" when I have configured `selectOnClose: true`? #2953 says that it will be fixed in the next beta release; any word on when that will be?

**Comment by kevin-brown** [comment] 2015-01-26 22:35
Duplicate of https://github.com/select2/select2/issues/2953.

> any word on when that will be?

I'm _hoping_ to have that be in the next day or two, but it all depends on when I get [the bug list](https://github.com/select2/select2/issues?q=is%3Aopen+milestone%3A4.0+label%3Abug) reduced. As always, pull requests are greatly appreciated and will always speed things up.

**Closed by kevin-brown** 2015-01-26 22:35 UTC
