### ISSUE TITLE
Enabled/disabled state not respected on options

### ISSUE THREAD

**Issue by virgiliu** [select2/select2#3347] opened 2015-05-12 10:57 UTC
http://jsfiddle.net/upgrmrL3/1/

When clicking the disable button all options get disabled. When clicking "enable" the options in the select2 dropdown still appear as disabled.

![screen shot 2015-05-12 at 13 53 06](https://cloud.githubusercontent.com/assets/426097/7585719/43e5a544-f8ae-11e4-8f10-5012acf9e9b2.png)

Sometimes the disable attribute is not respected either: by clicking disable the options in the dropdown won't get disabled.

![screen-shot-2015-05-12-at-13 54 13](https://cloud.githubusercontent.com/assets/426097/7585797/b22f185a-f8ae-11e4-913a-aa5158340451.png)

The screenshots were taken on the same fiddle, with some cache clearing and refreshes between them.
Testing was done on Firefox 37.0.2 on Mac OS

**Comment by kevin-brown** [comment] 2015-05-12 15:35
There's a duplicate of this somewhere, and it is a bug caused by us caching the `disabled` state of results.

**Comment by vyrotek** [comment] 2015-05-28 18:36
This is affecting us as well. Our work around was to destroy it and recreate it but it's not very elegant.

**Comment by kevin-brown** [comment] 2015-05-30 00:53
I couldn't find the duplicate (guess it never existed), but the issue can be fixed similar to the `selected` property.

https://github.com/select2/select2/commit/54154c3df6b7e2f59dc76b663f230f9b773397f2

Also, this is not limited to multiple selects.

**Comment by advokata** [comment] 2015-07-14 08:52
Is there any workaround for this issue ?

**Comment by virgiliu** [comment] 2015-07-14 10:17
Destroying the select2 element and instantiating it again should fix it.

**Comment by chrisspen** [comment] 2016-04-20 15:02
The workaround is hide/disable the option(s) and then call `.select2()` on the select again. It's annoying but it works.

**Comment by SaharZehavi** [comment] 2016-12-27 15:37
so is there a solution for this problem? 
for some unknown reason i can't re-call select2 on the element.

**Comment by michmzr** [comment] 2017-05-04 11:37
I created a hack  for hiding disabled optgroups:
```javascript
   $.initialize(".select2-results__option[role='group']", function(index, optionGroup)
    {
        let optGroupName = $(this).attr("aria-label");

        let select2ResultsId =$(this).closest("ul.select2-results__options").attr("id");

        if(select2ResultsId)
        {
            let ptrn = /^select2-([\w]+)-results/i;
            let res =ptrn.exec(select2ResultsId);

            if(res.length > 0)
            {
                let relSelect2Id = res[1];

                let relOptGroup= $("#" + relSelect2Id).find("optgroup[label='" +optGroupName +  "'][disabled]");

                if (relOptGroup.length)
                {
                    $(optionGroup).attr("disabled", "disabled");
                    $(optionGroup).attr("aria-disabled", "true");
                }
            }
        }
    });
```

Css:
```css
.select2-results__option[aria-disabled=true],
    .select2-results__option[disabled]
{display:none}
```
$.initialize is  jquery plugin: [https://github.com/pietrasiak/jquery.initialize](https://github.com/pietrasiak/jquery.initialize)

**Related optgroup in select must have attribute disabled **

**Comment by sundquistm** [comment] 2018-08-21 15:21
I just want to reiterate the importance of this fix. Without this behavior, Select2 is less analogous to a normal select element. We can work around it, but it's been kind of painful.

**Comment by prionkor** [comment] 2018-08-28 05:43
Need this to be fixed. +1

**Comment by patricrivera** [comment] 2018-09-05 07:07
I also needed this to be fixed. +1

**Comment by pedrofurtado** [comment] 2018-09-05 19:43
PRs and JSFiddle examples are welcome.

**Comment by fr0z3nfyr** [comment] 2019-02-18 09:20
Any progress on this issue? Isn't the library supposed to imitate all behavior from native select? Can someone point me in right direction so that I can look at the code and attempt to fix this and offer a PR.

**Comment by kevin-brown** [comment] 2019-05-15 02:11
A couple of the linked pull requests are slated to land in 4.0.8, so this should be getting fixed within the next release.

**Comment by MattPurland** [comment] 2019-05-15 09:42
Thanks @kevin-brown. Any ideas as to when this might be?

**Closed** 2019-07-10 00:58 UTC
Labels: 4.x, confirmed bug, help wanted

**Comment by tuytoosh** [comment] 2021-01-14 20:01
I have the same problem.
