### ISSUE TITLE
Prevent unselect option on multiselect

### ISSUE THREAD

**Issue by qanle** [select2/select2#4672] opened 2016-11-05 08:14 UTC
Hi everybody,

I have 2 option is default, and set it to select2 multiselect, now i want user have select/unselect another option but don't unselect option default had set selectd.

I think and tried using

```
$select_user_role.on("select2:unselecting", function (e) {
if e.value = 'admin' then e.preventDefault();
}
```
but i don't get value on event unselecting :-1: 

Please help me,

Regards,

**Comment by tagx** [comment] 2017-04-06 01:44
try this one dude. 
var sel = $("#select_user_role option:selected").val(); // getting the value of the option
if(sel.val() == "admin")
{
e.preventDefault();
}

**Comment by tagx** [comment] 2017-04-06 03:14
$select_user_role.on("select2:unselecting", function (e) {
var sel_user_role = $("#select_user_role option:selected").val(); // getting the value of option
if (sel_user_role == "admin") {
 e.preventDefault();
} else {
 return true;
}
}

**Comment by alexweissman** [comment] 2017-09-22 16:40
I know this is an older issue, but I am closing it as a duplicate of #4859.  The feature request seems to be explained much more clearly in that issue.

**Closed by alexweissman** 2017-09-22 16:40 UTC
