### ISSUE TITLE
Need in "id" attribute specified on autogenerated "input" element

### ISSUE THREAD

**Issue by PhantomYdn** [select2/select2#4147] opened 2016-02-04 05:09 UTC
In case of multiple boxes Select2 creates <span> element just right after `<select>`. That span contains `<input>` element within. Due to absence of "id" attribute on that element focus in input element might be lost in case of using Apache Wicket web framework (I guess, others are also effected) which can update initial element by ajax.

Is there a way to define "id" attribute for autogenerated `<input>` element?
If no: is it possible to make transparent refocus on input element if focus was  set to `<select>` in JS?

**Comment by kevin-brown** [comment] 2016-02-04 18:45
This is actually a duplicate of https://github.com/select2/select2/issues/3876, the problem is that Select2 doesn't respond to the `focus` event in 4.0.x.

**Closed by kevin-brown** 2016-02-04 18:45 UTC
