### ISSUE TITLE
Continuous focus on select2 in Internet Explorer

### ISSUE THREAD

**Issue by ameersohel** [select2/select2#3718] opened 2015-08-28 13:12 UTC
I am Using select2 4.0.0 on Internet explorer with ajax option and multiple select box. If I click on other select box(normal html select)  elements on document, am unable to see options of other elements because of select2 box is getting focused.

**Comment by kevin-brown** [comment] 2015-08-28 13:15
This is a duplicate of https://github.com/select2/select2/issues/3300 and will be fixed in 4.0.1.

**Closed by kevin-brown** 2015-08-28 13:15 UTC
