### ISSUE TITLE
4.0.0 beta 2: Cannot initialize, i18n issues

### ISSUE THREAD

**Issue by aequasi** [select2/select2#2948] opened 2015-01-19 21:13 UTC
getting this in my console, using select.min.js

```
No select2/i18n/en-us
```

**Comment by kevin-brown** [comment] 2015-01-19 21:20
Duplicate of https://github.com/select2/select2/issues/2934. This should be fixed on the `select2-ng` branch and will be included in the next release.

**Closed by kevin-brown** 2015-01-19 21:20 UTC
