### ISSUE TITLE
Position of the options does not change when multi select grows in height

### ISSUE THREAD

**Issue by jklapwijk** [select2/select2#4899] opened 2017-05-09 06:57 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to this jsfiddle: http://jsbin.com/gixemazama/1/edit?html,js,output
2. add option B to the selection

## Expected behavior and actual behavior

The input with the selected options is now higher and contains option B, but the option list remains on the same spot, so it is in front of the selected options and therefore the selected option B is not visible.

I was expecting that the option list would be attached to the bottom of the selection list and therefore would move down.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Edge

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment] 2017-09-17 02:23
Confirmed problem, and updated jsbin: http://jsbin.com/nolajupeco/1/edit?html,js,output

**Comment by alexweissman** [comment] 2017-09-17 02:27
Actually, just realized that this is a duplicate of #4511.

**Closed by alexweissman** 2017-09-17 02:27 UTC
Labels: confirmed bug
