### ISSUE TITLE
Can't initialize not unique id

### ISSUE THREAD

**Issue by adjarriawan** [select2/select2#6147] opened 2022-03-06 10:18 UTC
select2 only initialize last element dropdown with element id not unique, example bellow this code.

jquery: 3.5.1
select2: 4.1.0-rc.0

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
        rel="stylesheet"/>
  <script
          src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body>
  <select class="form-control fruits"
          name="fruits[]"
          id="fruits[]">
    <option>Choose Option</option>
    <option valud="1">Banana</option>
    <option valud="2">Avocado</option>
    <option valud="3">Cherry</option>
  </select>
  
  <select class="form-control fruits"
          name="fruits[]"
          id="fruits[]">
    <option>Choose Option</option>
    <option valud="1">Banana</option>
    <option valud="2">Avocado</option>
    <option valud="3">Cherry</option>
  </select>

<script>
   $('.fruits').select2();
</script>
</body>
</html>
```

demo link : https://jsbin.com/yurojisoce/edit?html,js,output

**Comment by jonahgreenthal** [comment] 2022-03-06 16:25
The HTML spec requires IDs to be unique within an HTML document. If you don't follow the rules, you can't expect things to work.

**Comment by kevin-brown** [comment] 2022-03-06 18:08
Duplicate of https://github.com/select2/select2/issues/5999. We don't support this because, as noted, it is out of spec.

**Closed as completed by kevin-brown** 2022-03-06 18:08 UTC
