### ISSUE TITLE
Multiselect value needed for drop down to close in IE11

### ISSUE THREAD

**Issue by wilkmit** [select2/select2#3487] opened 2015-06-17 13:21 UTC
Multiselect value needed for drop down to close in IE11. Also finding that 2 values are needed for drop down to close.

http://jsfiddle.net/wphqwvLf/15/

**Comment by kevin-brown** [comment] 2015-06-17 23:10
Duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-06-17 23:10 UTC
