### ISSUE TITLE
Escape key closes bootstrap modal

### ISSUE THREAD

**Issue by noctivityinc** [select2/select2#2222] opened 2014-03-31 21:28 UTC
Fantastic work on this.  I have a small issue that I am hoping has a simple solution.

When you are focused on select2 (Im using a text box for tagging) and you hit escape it closes the MODAL.  I want it to do NOTHING.

I have this set for the modal:

     $modal.modal
        backdrop: 'static'
        keyboard: false

which works fine as long as I am not focused on the select2 input box but if I am typing in that box and hit escape for some reason (which Ive done a number of times) it closes the modal.

How can I prevent this?

**Comment by kevin-brown** [comment] 2016-06-25 18:09
This is a duplicate of https://github.com/select2/select2/issues/2731.

**Closed by kevin-brown** 2016-06-25 18:09 UTC
