### ISSUE TITLE
multiple open events called on click and "open, close, open" events called on IE11

### ISSUE THREAD

**Issue by VyTacka** [select2/select2#3161] opened 2015-03-16 11:48 UTC
When I click on multiple select somehow it calls 2 open events. In Chrome, Firefox and other browsers it work's well, but in IE11 it calls "open" "close" "open" events, and then I can't close select dropdown until I select any value. And when I clear value in IE11 for select from javascript it opens that select dropdown.
Version 4.0.0-rc.2

**Comment by n1smo** [comment] 2015-03-21 13:02
Sounds like something i mentioned a few days ago.
https://github.com/select2/select2/issues/3142

**Comment by kevin-brown** [comment] 2015-03-22 01:44
Closing this as a duplicate of https://github.com/select2/select2/issues/3142, must have missed this ticket earlier.

**Closed by kevin-brown** 2015-03-22 01:44 UTC
