### ISSUE TITLE
Mousedown + mousemove + fixefox + ajax issue

### ISSUE THREAD

**Issue by foxontherock** [select2/select2#3256] opened 2015-04-13 13:59 UTC
When using ajax, only in Firefox, if no delay is defined, we move the mouse during the ajax call, the text of the page is selected like if we hold the mouse down to select normal text. And, after that, we can't select the item in tne combo.

We have a temporary fix, waiting for the real fix, if we add "delay=100" in the ajax setup, the text is selected behind the dropdown (still buggy), but we can click the item in the combo, and the selection is un-done by selecting an item.

Can be reproduced in the select2 examples pages, section "loading remote data", just move the mouse when you click "select/select2" sample ajax combo.

**Comment by foxontherock** [comment] 2015-04-13 14:07
Oh, looks like the issue 3151
https://github.com/select2/select2/issues/3151

**Comment by alexweissman** [comment] 2017-12-08 22:49
Closing as duplicate of #3151.

**Closed by alexweissman** 2017-12-08 22:49 UTC
