### ISSUE TITLE
select2 with tags select automatically

### ISSUE THREAD

**Issue by sadden3194** [select2/select2#6244] opened 2023-04-19 10:29 UTC
Hi all,

I am using select2 and all works fine. Now I would like to create a select2 input field with the tag option:
http://jsfiddle.net/L680dyb7/

My problem: If you will type "Te" (for "Test") it will be automatically select the option "Alabama". This should not be. Is this a bug or how can I solve this?

With version 4.0.2 no problem!
With version > 4.0.2 = problem

**Comment by kevin-brown** [comment] 2023-04-27 22:50
Duplicate of https://github.com/select2/select2/issues/3553#issuecomment-119772829.

**Closed as not planned by kevin-brown** 2023-04-27 22:50 UTC
