### ISSUE TITLE
Blur event in select2 v4.x

### ISSUE THREAD

**Issue by kartik-v** [select2/select2#3775] opened 2015-09-17 06:28 UTC
How do I trap the blur event in Select2 v4.0 - `select2:blur` does not work - suppose its disabled for some reason.

**Comment by kevin-brown** [comment] 2015-09-17 18:29
Duplicate of https://github.com/select2/select2/issues/3152 which was merged into https://github.com/select2/select2/issues/1908.

**Closed by kevin-brown** 2015-09-17 18:29 UTC
