### ISSUE TITLE
maximumSelectionLength issue with tokenSeparators on created tags

### ISSUE THREAD

**Issue by akoury** [select2/select2#4500] opened 2016-07-24 21:57 UTC
maximumSelectionLength is being ignored when i use the tags: true option, i can create as many tags as a i want while separating them through the characters i specified in the tokenSeparators, therefore it ignores the limit.

**Comment by kevin-brown** [comment] 2016-08-26 23:22
This is a bug, and I thought there was already a ticket about it. But I can't find one, so this will remain open until it's fixed, or until the duplicate comes up.

**Comment by lel1234** [comment] 2016-10-12 17:17
Any fix for this yet?

**Comment by konchober** [comment] 2016-10-27 09:31
Hello! I overwrite tokenizer function for paste from clipboard.
But select2 (multiple) ignore maximumSelectionLength directive.

I can acces to this value in overwrited tokenizer via this.maximumSelectionLength
But I cannot access to count of current selected values.

Could you tell me how to do it?

**Comment by konchober** [comment] 2016-10-27 10:12
A lot of hurts, but it works =)

cnt = null; this.current(function (selected) { cnt = selected.length; });
if( this.maximumSelectionLength < cnt ) {
// 'You can only select ' + self.maximumSelectionLength + ' item'
}

**Comment by alexweissman** [comment] 2017-09-25 02:11
Closing this as a duplicate of #3514.

**Closed by alexweissman** 2017-09-25 02:11 UTC
Labels: 4.x, confirmed bug
