### ISSUE TITLE
noResults message with search term

### ISSUE THREAD

**Issue by emir** [select2/select2#4088] opened 2016-01-17 22:47 UTC
I would like to show search term on noResults message. Is there any way to doing this?

Currently my code is like below, but it didn't work:

``` javascript
$('#divId').select2(
    {
        language: {
             noResults: function(term) {
                 return "No results found. Add <b>" + term + "</b>?";
            }
        }
    }
);
```

**Comment by quintstoffers** [comment] 2016-02-03 09:14
Instead of using the noResults functionality you could try using the tags instead. We're successfully using it to allow users to add new items on the fly. Thanks to #4008 we can use the insertTag option to add the non-existing item to the bottom of the list. That way your user would always have the option to insert his own tag, even if some matches are found.

You can use the insertTag option like so (note that I'm modifying the tag so that I can detect it later on):
```
    baseOptions.insertTag = function (array, tag) {
        tag.isTag = true;
        // Add to the end of the array so that it appears at the bottom of the list.
        array.push(tag);
    }
```

Thanks to the isTag boolean we can add some style to our tag.
```
    function formatSelect2Option(option) {
        if (option.isTag) {
            return $('<div class="add-new">' + option.text + '</div>')
        } else {
            return option.text
        }
    }
```

Finally, i'm capturing the select2:selecting event to find out if a tag was selected. If so I'm broadcasting a new event so that listeners can upload the tag for us.
```
    'select2:selecting select': function (e) {
        let selectedOption = e.data || e.params.args.data;

        // If the selected option is a tag we trigger a custom event and prevent this one never happened.
        if (selectedOption.isTag) {
            e.preventDefault();
            e.stopPropagation();
            $(e.currentTarget).trigger('select2:add-new', selectedOption);
        }
    }
```

By styling the tag you could end up with something like this:
![screen shot 2016-02-03 at 10 03 54](https://cloud.githubusercontent.com/assets/147345/12777471/7eec1c82-ca5d-11e5-9258-522618c80344.png)

Note that the insertTag functionality hasn't been released yet (stuck at 4.0.1 at the time of writing). The dist files have been updated, so you can either use those directly or use a manager like NPM to use a

**Comment by krazyjakee** [comment] 2016-04-07 08:12
For anyone else looking for a simple solution, just add this as an option...

```
insertTag: function(data, tag){
    tag.text = "Add: '#{tag.text}'";
    data.push(tag);
}
```

I believe this should be in select2 core as the current usability of adding new tags is very poor.

**Comment by aeksco** [comment] 2016-05-04 20:27
I too think it would be helpful to either expose a ```noResults``` option on initialization that accepts either a string or a callback method that returns a string. For example:

```js

// noResults option as a string
$('select').select2({
  noResults: 'No Users found.'
})

// noResults option as a function
$('select').select2({
    noResults: function(query) {
      return 'No results matching: ' + query;
    }
})
```

I'd be happy to put in a PR for this if I can get a go-ahead from a maintainer.

**Comment by mohsen** [comment] 2016-09-08 11:21
For those confusing here like me, add a tags: true so that insertTag works:
```
$('select').select2({
  tags: true,
  insertTag: ...
})
```

**Comment by ladrob** [comment] 2017-08-29 11:13
If you would like to do some more stuff on selecting newly added tag:

    $('select').select2({
        tags: true,
        insertTag: function(data, tag){
            tag.text = "Add: " + tag.text;
            data.push(tag);
        }	
    }).on('select2:select', function(){
        if($(this).find("option:selected").data("select2-tag")==true) {
            // some more stuff...
        }
    });

**Comment by alexweissman** [comment] 2017-09-13 22:49
See #3799.

**Comment by alexweissman** [comment] 2017-12-16 01:30
Actually, I'm going to close this as a duplicate of #3190.

**Closed by alexweissman** 2017-12-16 01:30 UTC
Labels: 4.x, documentation
