### ISSUE TITLE
If width is applied via css, select2 width: 'resolve' always falls back to 'element'

### ISSUE THREAD

**Issue by SlyDave** [select2/select2#3813] opened 2015-10-05 14:01 UTC
If you use CSS to apply a width to the select element that select2 is going to replace, and you init select2 with the width option of resolve, it always falls back to 'element' and sets the width of select2 replacement in pixels, even if the CSS for the select was as percentage; conversely if you set the width of the select element directly on the element as a percentage it is picked up correctly.

http://jsfiddle.net/gu9aekj3/
Inspect the 2 select2 replacements, the top one's width is set in pixels (about 800) and the bottom is a percentage.

This makes 'resolve' useless is pretty much any real world use case, certainly so for responsive design.

One would expect resolve to pick up the applied stylesheet information and use that where possible.

**Comment by kevin-brown** [comment] 2015-10-06 22:48
This is a duplicate of https://github.com/select2/select2/issues/3278.

**Closed by kevin-brown** 2015-10-06 22:48 UTC

**Comment by SlyDave** [comment] 2015-10-07 10:28
6 months :(
