### ISSUE TITLE
Select2 lost focus on Tab from opened dropdown list

### ISSUE THREAD

**Issue by faiwer** [select2/select2#4508] opened 2016-07-29 10:54 UTC
[JSFfiddle example](https://jsfiddle.net/3okp61g9/). If you press Tab while navigate in dropdown list... focus in second select2 instance is not received. Focus lost. Without opening dropdown Tab order working normally.

**Comment by RyanTuckNZ** [comment] 2017-03-14 20:09
Having the same issue with cascading selects binding dynamically from JSON data. We managed to be able to get the first Select2 to open on focus, then Enter keypress to select an option loses focus of the first Select2 and you need to Tab twice to get focus to the second.

**Comment by michalkleiner** [comment] 2017-04-12 22:15
I think this might be a regression between 4.0.2 and 4.0.3, can you @faiwer test with 4.0.2 if it's working there?

**Comment by faiwer** [comment] 2017-04-13 04:46
@michalkleiner I've tried it on 4.0.2. With 4.0.2 tab doesn't lose a focus, all right.

**Comment by michalkleiner** [comment] 2017-04-13 06:45
@faiwer tracked down to be this - https://github.com/select2/select2/commit/31e7a1d4c52ed7477769fcad5d15166ae3c9b4d0#commitcomment-21746586

**Comment by michalkleiner** [comment] 2017-04-13 06:47
Might be fixed by https://github.com/select2/select2/pull/4669

**Comment by alexweissman** [comment] 2017-09-14 01:01
This is a duplicate of #4419, which is fixed in #4427.

**Closed by alexweissman** 2017-09-14 01:01 UTC
