### ISSUE TITLE
initSelection options get lost after the new selection in Ajax method

### ISSUE THREAD

**Issue by KdArun2227** [select2/select2#4234] opened 2016-03-06 13:42 UTC
I am using ajax to bind the data, intiSelection options are getting lost after the new selection. Can you please help me to fix this issue.

Please find the below code used

 $("#selectRltProjects").select2({
                            placeholder: "Search Project",
                            minimumInputLength: 1,
                            multiple: true,
                            ajax: {
                                url: 'localhost:8065/GetProjects',
                                dataType: 'json',
                                quietMillis: 250,
                                data: function (searchText, page) { 
                                    return searchText;
                                },
                                processResults: function (data, params) {                                    
                                    var filteredArray = data;
                                    var pageSise = 100;
                                    params.page = params.page || 1;
                                    var startingIndex = params.page == 1 ? 0 : (params.page - 1) * pageSise;
                                    var paginaedData = filteredArray.slice(startingIndex, params.page * pageSise);
                                    return {
                                        results: paginaedData,
                                        pagination: {
                                            more: (params.page * pageSise) < filteredArray.length
                                        }
                                    };
                                },
                                cache: true
                            },
                            initSelection: function (element, callback) {
                                var data = [];
                                data.push({ id: '177', text: 'test' });
                                callback(data);
                            },
                            escapeMarkup: function (markup) { return markup; },
                            templateResult: formatRepoPjt, 
                            templateSelection: formatRepoSelectionPjt /
                        })

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

**Comment by kevin-brown** [comment] 2016-03-10 16:24
Closing this as a duplicate of https://github.com/select2/select2/issues/3722.

**Closed by kevin-brown** 2016-03-10 16:24 UTC

**Comment by vercotux** [comment] 2017-08-09 09:07
So what is the solution for this?

**Comment by duccanh0022** [comment] 2017-10-24 15:35
Me too, and I have to use this code (out of select2 function)
$(".assigner").append('<option value="id">text213</option>').val('id');
$(".assigner").trigger('change');

**Comment by alexweissman** [comment] 2017-10-25 16:20
@vercotux `initSelection` is actually deprecated in v4.  The preferred way to set initial values now is by [appending a new `option`](https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2).
