### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by landsman** [select2/select2#6308] opened 2024-04-29 12:21 UTC
https://select2.org

![Screenshot 2024-04-29 at 14 21 32](https://github.com/select2/select2/assets/3184228/4f201358-dd01-4676-8ba2-30dc16fcdd2e)

**Comment by jefflord** [comment] 2024-04-30 11:40
In case it's needed, https://web.archive.org/web/20240426234620/https://select2.org/

**Comment by wiklapandu** [comment] 2024-05-02 03:02
> In case it's needed, https://web.archive.org/web/20240426234620/https://select2.org/

thankyou @jefflord , its very helpfull.

**Comment by rizkytegar** [comment] 2024-05-02 04:15
![image](https://github.com/select2/select2/assets/55475891/7672d4dc-231b-4ded-9f03-a1648fda4a49)

**Comment by rizkytegar** [comment] 2024-05-02 04:15
still down, did something happen?

**Comment by gensart-x** [comment] 2024-05-04 03:01
> In case it's needed, https://web.archive.org/web/20240426234620/https://select2.org/

![image](https://github.com/select2/select2/assets/165239315/b7620221-7956-43f4-b556-2c5562d08cd3)

Even the archive is down lol, what happened in internet ?

**Comment by PENEKhun** [comment] 2024-05-04 06:10
> > In case it's needed, https://web.archive.org/web/20240426234620/https://select2.org/
> 
> ![image](https://private-user-images.githubusercontent.com/165239315/327914174-b7620221-7956-43f4-b556-2c5562d08cd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDMxODMsIm5iZiI6MTcxNDgwMjg4MywicGF0aCI6Ii8xNjUyMzkzMTUvMzI3OTE0MTc0LWI3NjIwMjIxLTc5NTYtNDNmNC1iNTU2LTJjNTU2MmQwOGNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwNjA4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjllYjk2OTUzZTRhYTY5ZGMxYTRiYzEwOWFmMWJiNzgzYjc5NzcwZWRlN2E1NTIyYTc2MDRjODIzNDVhNjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sB7-0FLsC-9jaZ2qDg72SVHyqPau2RehRnq7uI59uTE)
> 
> Even the archive is down lol, what happened in internet ?

<img width="1049" alt="image" src="https://github.com/select2/select2/assets/13290706/2c6c9267-2fba-4a3d-a8b1-b88371386d3d">

The archive should now work. Lol.

**Comment by frknakk** [comment] 2024-05-05 17:40
Just made the efforts to set up the docs on my server because the web archive is really slow. If anyone wants to use it feel free:
https://select2-docs.fatech.dev/

Only a temporary service until the official documentation is back online.

**Comment by fplanchon** [comment] 2024-05-06 13:21
> Just made the efforts to set up the docs on my server because the web archive is really slow. If anyone wants to use it feel free: https://select2-docs.fatech.dev/
> 
> Only a temporary service until the official documentation is back online.

there's still good samaritans

**Comment by spindlersouza** [comment] 2024-05-06 17:47
> Just made the efforts to set up the docs on my server because the web archive is really slow. If anyone wants to use it feel free: https://select2-docs.fatech.dev/
> 
> Only a temporary service until the official documentation is back online.


Se precisar hospedar a documentação, tenho recursos para manter online indefinidamente.

If you need to host the documentation, I have resources to keep it online indefinitely.

**Comment by kevin-brown** [comment] 2024-05-06 18:18
We are aware that the Select2.org website is offline. The cause is from the server which hosted the documentation going offline.

We are working to restore the documentation, in the interim we recommend making use of the Internet Archive to serve the documentation.

**Comment by yahya09** [comment] 2024-05-09 12:02
I see the site now up again. Thanks to the team 🤝

**Comment by gensart-x** [comment] 2024-05-10 06:40
Yeah, this issue should be closed as it is solved, Thanks to everyone involved in this.

cc. @landsman

**Closed as completed** 2024-05-10 10:06 UTC
