### ISSUE TITLE
Select2 deletes all options when hitting delete on keyboard after added a new option

### ISSUE THREAD

**Issue by simplenotezy** [select2/select2#4201] opened 2016-02-22 11:11 UTC
I have a select2 on a multiple selectbox, that already has some options on page load.

If I press "delete" on the keyboard, it will gently delete the next "option"-box. It will even keep the option box's value. Very cool - works as expected.

However, if I add a new option to the select group, and then hit the delete key again, ALL options will be removed from select2.

I have attached a video: https://youtu.be/q9l3ZkFs0Mk

Using version `Select2 4.0.1`

**Comment by alfredopacino** [comment] 2016-02-22 23:01
I faced this issue and I noticed it comes from allowClear flag

**Comment by hcancelik** [comment] 2016-03-04 05:23
+1 I'm also having the same issue. Typing several tags and hitting delete key removes all the tags.

**Comment by zoransa** [comment] 2016-03-06 00:23
+1

**Comment by rmwever** [comment] 2017-03-21 14:33
+1 I'm still experiencing this issue. Has anyone found a solution?

**Comment by alexweissman** [comment] 2017-11-06 01:55
This is a duplicate of #3335.  Please continue all further discussion there.

**Closed by alexweissman** 2017-11-06 01:55 UTC
Labels: 4.x, confirmed bug: help needed
