### ISSUE TITLE
'choice-selected' is not fired like it used to in 3.5.1

### ISSUE THREAD

**Issue by Untit1ed** [select2/select2#2952] opened 2015-01-20 22:23 UTC
'choice-selected' event is not triggered after a click event on a tag in the latest version (3.5.2).

3.5.2 - http://jsfiddle.net/z533pmux/1/ (broken)
3.5.1 - http://jsfiddle.net/z533pmux/2/ (works)

**Comment by kevin-brown** [comment] 2015-01-20 23:52
Still a duplicate of this https://github.com/select2/select2/issues/2932.

**Closed by kevin-brown** 2015-01-20 23:52 UTC

**Comment by Untit1ed** [comment] 2015-01-22 02:53
Not sure why you close the issue when it's obviously a bug.

**Comment by kevin-brown** [comment] 2015-01-22 03:12
I've reopened the other issue.
