### ISSUE TITLE
maximumSelectionLength allows to select more options

### ISSUE THREAD

**Issue by rusrip** [select2/select2#3449] opened 2015-06-09 07:14 UTC
Located here: https://select2.github.io/examples.html
Find "Limiting the number of selections"

In example maximumSelectionLength is set to 2
If user select options by left mouse button, it works fine.

If user select options by ctrl+left mouse button, he can select as much options as he want.

Is this a bug or feature?

**Comment by kevin-brown** [comment] 2015-06-09 16:04
> Is this a bug or feature?

It's a bug.

**Comment by Decagon** [comment] 2015-11-14 02:20
In Chrome 46.0.2490.80 using 4.0.1-rc.1, I'm able to select as many options as I want to, provided that I do not click outside of the dropdown. The dropdown stays open the entire time when using ctrl to select the elements, and closes automatically when I've selected the max number of elements when not using ctrl.

When I click outside of the dropdown after selecting more elements than I was allowed to, it says that I can only select two elements.

**Comment by kevin-brown** [comment] 2016-08-26 23:20
This is actually a duplicate of https://github.com/select2/select2/issues/3514.

**Closed by kevin-brown** 2016-08-26 23:20 UTC
Labels: 4.x, bug
