### ISSUE TITLE
Dropdown in multiple select boxes is not filtering selected items

### ISSUE THREAD

**Issue by PavelGavlik** [select2/select2#4182] opened 2016-02-11 16:15 UTC
What steps can be used to reproduce the issue?

1. Go to Multiple select boxes in examples page (https://select2.github.io/examples.html)
1. Add some value (e.g. Alaska)
1. Open select box again
1. Alaska is still in dropdown

What is the bug and what is the expected outcome?

Alaska should not be in dropdown when it's selected

What browser(s) and Operating System have you tested with?

Chrome and Safari on Mac

Does the bug happen consistently across all tested browsers?

Yes

-- 

I'm not sure if this is a bug, but the behavior is different from 3.x.

**Comment by kevin-brown** [comment] 2016-02-16 14:40
Duplicate of https://github.com/select2/select2/issues/1538.

**Closed by kevin-brown** 2016-02-16 14:40 UTC

**Comment by blankdots** [comment] 2016-02-24 11:43
the solution pointed by: https://github.com/select2/select2/issues/1538#issuecomment-170757783 seems to provide the expected behaviour.

```
.select2-results__option[aria-selected=true] {
    display: none;
} 
```
