### ISSUE TITLE
Multi-level nested options not selectable in Chrome

### ISSUE THREAD

**Issue by cadecannon** [select2/select2#3866] opened 2015-10-24 19:45 UTC
It appears that a newer version of Chrome (I'm running version 46.0.2490.80 (64-bit))  has broken the ability to nest deeper than one level of optgroups.  I do not see this issue in Safari 9.0 (10601.1.56.2) or Firefox 41.0.2.  I'm also running OS X 10.10.5.

Here is an [example JS Fiddle](http://jsfiddle.net/tmpb57nh/1/) illustrating the issue.  In Chrome, I can select the children successfully but am unable to select any grandchildren or deeper.  In the linked JS Fiddle example, I am unable to select Option 8 or 10.

I have partially solved this issue by changing a line in ArrayAdapter.prototype.convertToOptions from `Utils.appendMany($option, $children);` to `$options.push($children);`.  This basically prevents the underlying select from nesting it's own optgroups, but it appends any nested options to the bottom of the rendered list on select.  Still trying to work through that.

**Comment by liemlyquan** [comment] 2015-10-27 08:18
Have the same issue. The Select2 now temporarily works again thanks to your workaround :+1:

**Comment by kevin-brown** [comment] 2015-10-27 22:49
I was able to reproduce this with the latest Chrome. I'm not sure why it's happening, but it looks like it might not be properly setting the `selected` property on the `<option>` elements.

**Comment by leandrogehlen** [comment] 2016-01-08 10:49
The problem is that, the `select`, does not suport hierarchical `optgroup`

**Comment by malefice** [comment] 2017-03-24 17:22
So I tried using the latest stable release v4.0.3 with both Chrome 57.0.2987.110 and Firefox 52.0.1, but the bug is still there. Are there plans to fix this?

**Comment by leandrogehlen** [comment] 2017-03-24 19:12
I fixed it. But the PR was not accepted.
You can use this repository
https://github.com/leandrogehlen/select2

**Comment by malefice** [comment] 2017-03-25 08:05
great! I will try it out, but it has been a year though since your PR. did they give any reason as to why the PR was not accepted?

**Comment by jpic** [comment] 2017-03-25 12:17
I think because it's not standard to nest optgroups.

**Comment by leandrogehlen** [comment] 2017-03-26 14:52
Yes, i think that's it. But i think that is the only way to work

**Comment by yahyaerturan** [comment] 2017-03-30 02:53
@leandrogehlen If we use your fork's `dist` folder, can we use nested optgroups?

**Comment by leandrogehlen** [comment] 2017-03-30 09:58
I could try to do this

**Comment by malefice** [comment] 2017-05-12 08:29
@yahyaerturan, the fork works, though I really hope the fix will be merged into the main repo.

**Comment by alexweissman** [comment] 2017-12-14 21:07
This is now documented: https://select2.org/options#hierarchical-options

> **Only a single level of nesting is allowed per the HTML specification.** If you nest an `<optgroup>` within another `<optgroup>`, Select2 will not be able to detect the extra level of nesting and errors may be triggered as a result.

**Closed by alexweissman** 2017-12-14 21:07 UTC
Labels: 4.x, browser: Chrome, confirmed bug
