### ISSUE TITLE
4.x Selected items order

### ISSUE THREAD

**Issue by Pejic88** [select2/select2#4223] opened 2016-03-01 13:38 UTC
## Expected behavior and actual behavior

I have a problem with selected items order. They are sorted in alphabetical order, same as dropdown list. Is there an option to put every new selected item to the end of list?

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version: 1.11.2
- Select2 version: 4.0.1

**Comment by kevin-brown** [comment] 2016-03-01 14:57
This is a duplicate of https://github.com/select2/select2/issues/3106.

**Closed by kevin-brown** 2016-03-01 14:57 UTC
