### ISSUE TITLE
Force tags to always append at the end

### ISSUE THREAD

**Issue by thejae** [select2/select2#3659] opened 2015-08-07 04:38 UTC
I am guessing this request is related to the issue #3106

The default behavior is fine when there is only a few tags but it gets confusing to the user when there is already a number of tags selected.

Example:
Banking is the last tag selected.
![image](https://cloud.githubusercontent.com/assets/738694/9128773/7450d1a4-3d00-11e5-8986-34581feb131d.png)

Banking appears in between existing tags.
![image](https://cloud.githubusercontent.com/assets/738694/9128776/82519496-3d00-11e5-8771-52da82c8f560.png)

Can we get an option to force tags to append at the end? Much thanks :)

**Comment by kevin-brown** [comment] 2015-08-07 15:31
_Tags_ [are always added to the end](http://select2.github.io/examples.html#tags), the same [doesn't apply to selections in general](https://github.com/select2/select2/issues/3106).

So yes, this is a duplicate of https://github.com/select2/select2/issues/3106. There is an example of pushing the latest selection to the end at https://github.com/select2/select2/issues/3106#issuecomment-77988110.

**Closed by kevin-brown** 2015-08-07 15:31 UTC
