### ISSUE TITLE
Presetting values when templateSelection is defined

### ISSUE THREAD

**Issue by banesto** [select2/select2#3690] opened 2015-08-20 07:10 UTC
If select2 has a defined ```templateSelection```, then it's not possible to add predefined values as defined value is not being passed through that template function. Well at least I haven't found a way to do it.

Hamlcoffee:
```
%select{ id: "subjects", name: "subjects", class: 'chosen-select', data: { placeholder: 'Type the name of a person or subject.'}, multiple: true }
  %option{ value: 62501, selected: true, data: {display_name: 'Ask your colleagues', subject_image_url: TTM.url + '/a/assets/images/501_small.png'} } Ask you colleagues
```

Consider this coffeescript/backbone snippet:
```
modalInit: =>
    @$subjects.select2
      placeholder: "Select a subject"
      minimumInputLength: 3
      ajax:
        url: TTM.url
        dataType: 'json'
        delay: 250
        data: (params) ->
          {
            search_str: params.term
            page:       params.page
          }
        processResults: (data, page) ->
          { results: data }
        cache: true
      escapeMarkup: (markup) ->
        markup
      minimumInputLength: 3
      templateResult: @resultTemplate
      templateSelection: @choiceTemplate

  resultTemplate: (item) ->
    return "Loading&hellip;" if item.loading
    if item.subject_image_url
      style = ' style="background-image:url(' + item.subject_image_url + ')"'
    else
      style = ''
    '<span class="select2-results__image"' + style + '></span>' +
    '<span class="select2-results__title">' + item.display_name + '</span>'

  choiceTemplate: (item) ->
    output = ''

    output += '<span class="select2-selection__choice__title">' + item.display_name + '</span>'
    if (item.subject_image_url)
      output += '<img src="' + item.subject_image_url + '" width="19" height="19" />'
```

**Comment by kevin-brown** [comment] 2015-08-20 14:16
I'm going to call this a duplicate of https://github.com/select2/select2/issues/3116#issuecomment-112976757, feel free to comment about a possible solution over at that ticket.

**Closed by kevin-brown** 2015-08-20 14:16 UTC
