### ISSUE TITLE
Tags and multiple attribute not working together with jquery 3.4.1

### ISSUE THREAD

**Issue by AdrianKuriata** [select2/select2#5542] opened 2019-06-13 12:32 UTC
Hello there. I found a problem with select **multiple** and **tags** set to true value. After that can't write more than 4 characters in the search element. Problem is with **jquery 3.4.*** and **select2 4.0.7** (checked lower version - 4.0.6 - not working too) version, with **jquery 3.3.1** it's working property. I will give you an example:

[jquery 3.4.1 - not working](https://jsbin.com/jadexowuwu/1/edit?html,js,output)
[jquery < 3.4.1 - working](https://jsbin.com/tonorocije/1/edit?html,js,output)

**Comment by kevin-brown** [comment] 2019-06-15 20:47
Duplicate of https://github.com/select2/select2/issues/5485.

**Closed by kevin-brown** 2019-06-15 20:47 UTC
