### ISSUE TITLE
MaximumSelectionLength not functional when 'closeOnSelect: false' in  multiple select

### ISSUE THREAD

**Issue by ShubhamSonawane** [select2/select2#4476] opened 2016-07-13 07:09 UTC
$('.autoComplete').select2({
closeOnSelect: false,
maximumSelectionLength: 3
});

**Comment by kevin-brown** [comment] 2016-07-13 13:18
Duplicate of https://github.com/select2/select2/issues/3514.

**Closed by kevin-brown** 2016-07-13 13:18 UTC
