### ISSUE TITLE
Allow selecting the same option multiple times in a multi-select

### ISSUE THREAD

**Issue by Dineshbvn** [select2/select2#4528] opened 2016-08-12 02:57 UTC
## Steps to reproduce the issue
1.  Go to https://select2.github.io/examples.html#tags.
2.  Type Letter 'o' (Orange will be listed in Option's List).
3.  Select Orange by "Mouse".
4.  Preselected Orange Will be removed.

Need to Keep the preselected tag  while select the same again

**Comment by alexweissman** [comment] 2017-12-08 20:29
This is the expected behavior - when you try to select an option that has already been selected before, it will become unselected (as occurs in a native multi-select control).

That being said, I can see a use case for being able to make multiple selections of the same value, but I don't think it should be the default behavior.

**Comment by alexweissman** [comment] 2017-12-08 21:57
Actually, I'm going to close this as a duplicate of #4472.

**Closed by alexweissman** 2017-12-08 21:57 UTC
Labels: feature request: pending discussion
