### ISSUE TITLE
Bug on select data from url

### ISSUE THREAD

**Issue by alexpts** [select2/select2#4096] opened 2016-01-19 11:16 UTC
Example: http://codepen.io/alexpts/pen/PZOEaQ?editors=101
For reproduce see gif: https://www.dropbox.com/s/v6n6tjgltidgvv0/selec2-bug.gif?preview=selec2-bug.gif

**Comment by kevin-brown** [comment] 2016-01-19 17:52
I've been trying to strip down the codepen to see if I can reproduce the issue, but I haven't been successful.
https://codepen.io/anon/pen/mVqGqm

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?

**Comment by alexpts** [comment] 2016-01-19 18:55
http://codepen.io/alexpts/pen/PZOEaQ?editors=101
1. My steps for reproduce bugs:
1.1. Focus select
1.2. Set 'en' to input field
1.3. Wait suggest results
1.4. Press 'Enter' with selected 'en' (create new tag)
1.5. Select contains 3 items 'RU', 'SomeLongTag', 'en'
1.6. Enter text 'en' to select field
1.7. After show sugges list, click arrow down for select top item with text "Years & Years"
1.8. Press 'Enter'
1.9. Select contains 5 items 'RU', 'SomeLongTag', 'en',  'en', "Years & Years"

2. Expected 4 items 'RU', 'SomeLongTag', 'en',  "Years & Years"
3. OSx Capitan. Chrome 47 and Firefox 43.
4. ... yes

**Comment by kevin-brown** [comment] 2016-01-28 02:56
Pretty sure this is a duplicate of https://github.com/select2/select2/issues/4093.

_Side note: [Spotify killed their old API in the past week](https://developer.spotify.com/web-api/migration-guide/)._

**Comment by alexpts** [comment] 2016-01-28 05:43
I think it is not duplicate.
Try it after fix :) #4093.

**Comment by alexweissman** [comment] 2017-12-08 19:23
Is this possibly the same issue as #4404?  At any rate, I can no longer replicate the problem in 4.0.6-rc.1.

**Closed by alexweissman** 2017-12-08 19:23 UTC
Labels: 4.x, needs information
