### ISSUE TITLE
Dropdown width inside modal

### ISSUE THREAD

**Issue by dariospadoni** [select2/select2#4455] opened 2016-07-01 16:24 UTC
Hello
I'm using select2 (4.0.3) inside a bootstrap modal; I set the `dropdownParent` to the modal itself and width is set to 'resolve'. What I notice is that sometimes the dropdown is 1px larger than expected (see [here](http://www.witbit.it/tmp/bug.png)). 
I'm using the latest version of select2 and I found some other discussion here but I could not find any solution. Any help?

**Comment by kevin-brown** [comment] 2016-07-02 16:21
This is a duplicate of https://github.com/select2/select2/issues/4224.

**Closed by kevin-brown** 2016-07-02 16:21 UTC
