### ISSUE TITLE
could not put the tag in selected order, even with hidden input

### ISSUE THREAD

**Issue by hotleave** [select2/select2#4674] opened 2016-11-07 09:05 UTC
select2 could not perform as 3.5.4 which put the tags as it's order. [here is the example](http://select2.github.io/select2/#drag_drop)

even when I use input instead of select, it also use the order of data provided. try to change the code of `InputData.prototype.current` like follows:

```javascript
InputData.prototype.current = function (_, callback) {
    function getSelected (id, dataArray, selectedIds) {
      var selected = [], data;

        for(var s = 0; s < dataArray.length; s++) {
            data = dataArray[s];
            data.selected = data.selected || $.inArray(data.id, selectedIds) !== -1;

            if (data.id == id) {
                selected.push(data);
            }

            if (data.children) {
                selected.push.apply(selected, getSelected(id, data.children, selectedIds));
            }
        }

      return selected;
    }

    var selected = [],
        selectedIds = this.$element.val().split(
            this._valueSeparator
          );

    for (var d = 0; d < selectedIds.length; d++) {
      var id = selectedIds[d];

      selected.push.apply(
        selected,
        getSelected(
          id,
          this._currentData,
          selectedIds
        )
      );
    }

    callback(selected);
  };
```
Then it will put the new tag as the end of the list, but it could add duplicate values.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. instance a new select2 whith tags feature enabled, with at least 2 options
2. select the 2nd option
3. select the 1st option

## Expected behavior and actual behavior

When I follow those steps, I see 1st options is before the 2nd one, not as it's selected order(which 3.5.4 does)

I was expecting the tags will be ordered as is't selected sequence

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.12
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment] 2017-09-29 17:11
This appears to be a duplicate of #3106.

**Closed by alexweissman** 2017-09-29 17:11 UTC
