### ISSUE TITLE
How to type text directly in input (not in additional drop-down box) in single-mode?

### ISSUE THREAD

**Issue by 7iomka** [select2/select2#5143] opened 2017-11-22 17:24 UTC
Hello.
Tell me please, is there an option to make my single search option the same as in the multiple version? That is, the user types the text not in the additional drop-down box, but in the input itself, and the search results are already output in the drop-down box. I want to implement a simple site search using your plugin, and I need to make UX as simple as a simple google search form.
Help please, what settings for the plugin to work so well?

**Comment by alexweissman** [comment] 2017-11-22 18:47
Duplicate of #1345.

**Closed by alexweissman** 2017-11-22 18:47 UTC
