### ISSUE TITLE
Can i show the default list of options with remote data loading

### ISSUE THREAD

**Issue by Exerlol** [select2/select2#4158] opened 2016-02-06 18:15 UTC
Before client types into search input i wanna to show let's say 10 options in the drop down list. 
I found solution [here](http://stackoverflow.com/questions/29936022/select2-can-i-show-the-default-list-of-options-in-the-select2-ajax-call), however its for Select2 v3.5, and i need same thing just for Select2 v4 (this post has fiddle attached - http://jsfiddle.net/tw57m8bx/1/).
What i did so far on my own is:

HTML:
`<div class="col-sm-6">`
              ` <select class="js-data-example-ajax form-control">`
              `<option  title="select2/select2" selected="selected">select2/select2</option>`
              `</select>`
    `</div>`

Javascript:

  ```
 $(".js-data-example-ajax").select2({
                ajax: {
                    url: "/Home/Select2Test",
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            q: params.term,
                            page: params.page || 1,
                            pageLimit: 10
                        };
                    },
                    processResults: function (data, params) {
                        // making items selectable
                        var modifiedData = $.map(data.data, function (obj) { 
                            obj.id = obj.Id;
                            obj.text = obj.Title;

                            return obj;
                        });


                        params.page = params.page || 1;
                        return {
                            results: modifiedData,
                            pagination: {
                                more: (params.page * 10) < data.totalCount
                            }
                        };
                    },
                    cache: true
                },
                escapeMarkup: function (markup) { return markup; },
                minimumInputLength: 0,
                templateResult: function (repo) { return "<option id='" + repo.Id + "'>" + repo.Title || repo.text + "</option>" },
                templateSelection: function (repo) { return repo.Title || repo.text }
            });
```

But like this, i'm making ajax call each time i open select... Which is something i don't wanna do, all i want is to fetch 10 results from server once and show em every time user opens select until he type in search term. Btw, as u can see from above code i need infinite scroll enabled as well...
Thanks in advance!

**Comment by kevin-brown** [comment] 2016-02-08 22:24
This is a duplicate of https://github.com/select2/select2/issues/3828.

**Closed by kevin-brown** 2016-02-08 22:24 UTC
