### ISSUE TITLE
placeholder not working with array data

### ISSUE THREAD

**Issue by sh1ft-at-github** [select2/select2#3622] opened 2015-07-29 16:39 UTC
The title say all

See the example:
https://jsfiddle.net/qfamjc11/1/

To "fix" need to add an empty < option> < /option> there.

**Comment by kevin-brown** [comment] 2015-07-29 18:16
This is a duplicate of https://github.com/select2/select2/issues/3553. There is no way to automatically "fix" this.

**Closed by kevin-brown** 2015-07-29 18:16 UTC
