### ISSUE TITLE
Setting disabled <option> with .trigger('change') does not always work

### ISSUE THREAD

**Issue by kororas** [select2/select2#3816] opened 2015-10-07 12:53 UTC
Toggling disabled on an option does not always cause select2 to display the changes.
I've set an example here:

http://codepen.io/kororas/pen/NGjoZx

I've looked into destroy and init which works but it causes FLOUC which is really undesirable in our circumstances.

**Comment by kevin-brown** [comment] 2015-10-12 19:02
This is a duplicate of https://github.com/select2/select2/issues/3347.

**Closed by kevin-brown** 2015-10-12 19:02 UTC
