### ISSUE TITLE
Allow an option group to hold a value and be selectable in single option mode

### ISSUE THREAD

**Issue by CharlieHorwood** [select2/select2#5928] opened 2020-09-28 16:19 UTC
Hi,

We are using Select2 for a clients project and the client wants the following functionality:

They want a single select with clickable option groups that can be used the same as an option, this would then be styled to represent groups of options but with the first (parent) to be selectable.

Firstly is this even possible? If by some miracle there is a way round this how would I go about configuring Select2 to do it?
Below is an example of the structure we are using / wanting to extend:
`<select id="select-id">
    <optgroup label="the label">
        <option value="option_value">An option</option>
    </optgroup>
</select>`

**Comment by kevin-brown** [comment] 2020-11-28 04:21
Duplicate of https://github.com/select2/select2/issues/4149.

**Closed by kevin-brown** 2020-11-28 04:21 UTC
