### ISSUE TITLE
Event "select2:open" fires twice

### ISSUE THREAD

**Issue by shaselboeck** [select2/select2#3831] opened 2015-10-13 15:04 UTC
Look at the example page:
https://select2.github.io/examples.html

Under "Events" there are two selectboxes which both fire the event "select2:open" twice opening/clicking the selectbox.

**Comment by kevin-brown** [comment] 2015-10-13 16:21
This is a duplicate of https://github.com/select2/select2/issues/3503.

**Closed by kevin-brown** 2015-10-13 16:21 UTC
