### ISSUE TITLE
Single selects reopen after selection in 4.0.6

### ISSUE THREAD

**Issue by Hlsgs** [select2/select2#5490] opened 2019-04-28 16:52 UTC
This causes a flicker if `closeOnSelect` is on the default `true` value, either implicit or explicit. Setting `closeOnSelect` to `false` avoids the flicker, but is beside the point.
Multi-selects work fine.

**Comment by brunnopleffken** [comment] 2019-04-28 19:48
Same happens here after upgrading to 2.0.6. With single select I'm unable to close the dropdown, it's just flickering and remains open. With multi-selects I can close it but it flickers after selecting an option, I don't remember of this happening before.

**Comment by Hlsgs** [comment] 2019-04-29 00:23
@brunnopleffken it was introduced in 4.0.6 final. Anything upto 4.0.6-rc.1 is fine as far as this goes, but 4.0.5 is probably your safest bet.

**Comment by Ariex** [comment] 2019-04-29 06:28
this issue is caused by https://github.com/select2/select2/blob/develop/src/js/select2/core.js#L280 this code, if you remove it all works good

**Comment by toxpal** [comment] 2019-04-29 07:10
I came here to submit this issue after upgrading to 4.0.6, but it looks more people noticed it already. This issue didn't exist in 4.0.5 and 4.0.6 rc

Here's the fiddle for @kevin-brown to se it in action - https://jsfiddle.net/japdL67z/

**Comment by markusramsak** [comment] 2019-04-29 09:43
I can confirm this. I have the same issue. reopening on 'focus' causes this issue - like @Ariex  mentioned

**Comment by mm98** [comment] 2019-04-29 10:29
I can also confirm this.

**Comment by kevin-brown** [comment] 2019-04-29 11:33
That line (and lines surrounding it) were added in https://github.com/select2/select2/pull/5356. It's not clear why they were added, but I can tell from the jsfiddle provided (thanks!) that it means that Select2 just can't close anymore.

**Comment by Ariex** [comment] 2019-04-29 12:07
@kevin-brown my understanding is that line could be added so people can use tag to switch to this control then the search box will show automatically, but without that line people can still do that only with an extra "enter" when the text box got the focus. Also with this change, people cannot switch out of this control with tab, they have to click anywhere in this control but the search text box, then "tab" twice to close the drop down.
I think this feature brings more troubles than benefits.

that change was introduced from this PR: https://github.com/select2/select2/commit/2ea17181e3e1ee3b1bea490f405c044385a11ae2#diff-770e771e3300e4531333cd08d3c2f8f1, and there is 1 related issues #3696

**Comment by lvillanne** [comment] 2019-04-29 14:31
Same problem here after upgrading to 4.0.6 final. 4.0.6-rc.1 is fine for me.

**Comment by Viperoo** [comment] 2019-04-29 14:41
Confirm - 4.0.6

**Comment by flaushi** [comment] 2019-04-29 17:06
Confirm!

**Comment by kevin-brown** [comment] 2019-04-30 02:00
> I think this feature brings more troubles than benefits.

Agreed, especially since I just re-reviewed that and it does not appear to solve the original problem.

I welcome a pull request which reverts those changes, and I can roll a new 4.0.7 release after that is merged in.

**Comment by silvioq** [comment] 2019-05-01 00:14
> Same problem here after upgrading to 4.0.6 final. 4.0.6-rc.1 is fine for me.

4.0.6-rc.1 is not working for me.

**Closed** 2019-05-01 03:13 UTC
Labels: 4.x, confirmed bug, feature: dropdown

**Comment by kevin-brown** [comment] 2019-05-01 03:48
I just published a 4.0.7-rc.0 version to GitHub and NPM. If someone could confirm that it does in fact fix the issue (and that the regressions aren't catastrophic) on a real-world site that would be greatly appreciated.

CDNs should be catching up shortly.

**Comment by Ariex** [comment] 2019-05-01 04:05
works good for me

**Comment by mm98** [comment] 2019-05-01 06:20
4.0.6-rc.1 works for me.

**Comment by gvdlangenberg** [comment] 2019-05-01 08:18
4.0.7-rc.0 works!

**Comment by Hlsgs** [comment] 2019-05-01 08:42
@kevin-brown 4.0.7-rc.0 solves this issue indded, buit introduces #5495.

**Comment by toxpal** [comment] 2019-05-01 08:49
I'm so happy to see Kevin continues developing select2 again. I believe it was kind if abandoned for a long time (4.0.6 RC was probably released more than a year ago?), and it's great to see the best select plugin is back!

**Comment by silvioq** [comment] 2019-05-01 11:10
I confirm 4.0.7-rc.0 works fine for me

**Comment by cosmicvibes** [comment] 2019-05-03 10:09
4.0.7-rc.0 fixes this.

**Comment by herroworrd** [comment] 2019-05-06 21:28
Perhaps others can confirm but I still get unexpected/broken behaviour with 4.0.7. 

My single selects don't close on value select like they should. They won't close until a click outside the selectbox is done. Have tried setting closeOnSelect to true but this has no change.

**Comment by Chefcury1** [comment] 2019-06-29 23:07
4.0.6-rc.1 works for me.
