### ISSUE TITLE
there is an issue with placeholder in Multiselect!

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [select2/select2#5886] opened 2020-06-25 22:42 UTC
Hello, there was an issue i faced while setting placeholder with multiple enabled that it doesn't appear unless i select something then clear the selection..
i've been searching bout it for like 2 hrs and didn't find any clue on the internet bout it.
until i found that the '**input**' tag with this class **"select2-search__field**" got **width set as 0** when i first load the page so i had to make "width: auto" for that class manually...
PS: i was using **modal** window, and the issue doesn't persist for a normal page.

**Comment by kevin-brown** [comment] 2020-07-02 16:56
Duplicate of https://github.com/select2/select2/issues/5585.

**Closed by kevin-brown** 2020-07-02 16:56 UTC
