### ISSUE TITLE
Better dropdown behavior when clicking allowClear's X

### ISSUE THREAD

**Issue by MaxLap** [select2/select2#5163] opened 2017-12-13 18:17 UTC
Right, now (in 4.0.6 rc and 4.0.5 and probably far back), when you use allowClear, select something, and then click the X, the behavior of the dropdown is unintuitive: 
* If the dropdown is opened when you click the X, then the dropdown will stay open
* If the dropdown is closed when you click the X, then the dropdown will open

Basic example if you want to verify: http://jsbin.com/fakacubusi/1/edit?html,js,output

To me, if I click the X, it's because I wanted to chose "nothing". So in both situations, it would make more sense for the menu to close or remain closed.

Removing the line with `trigger('toggle', {})` solves this issue for both when the dropdown is open and when it's closed:
https://github.com/select2/select2/blob/062c6c3af5f0f39794c34c0a343a3857e587cc97/src/js/select2/selection/allowClear.js#L65

**Comment by alexweissman** [comment] 2017-12-14 01:57
#3320

**Comment by alexweissman** [comment] 2017-12-14 01:58
Duplicate of #3320 - please comment there if you have some insight on this issue.

**Closed by alexweissman** 2017-12-14 01:57 UTC

**Comment by taai** [comment] 2017-12-15 02:36
@MaxLap This is fixed in my pull request #5160 which will be published in version 4.0.6 (look at the milestone). Until that you can use this to prevent opening when clearing:

```javascript
$('#select-id').on('select2:unselecting', function(ev) {
    if (ev.params.args.originalEvent) {
        // When unselecting (in multiple mode)
        ev.params.args.originalEvent.stopPropagation();
    } else {
        // When clearing (in single mode)
        $(this).one('select2:opening', function(ev) { ev.preventDefault(); });
    }
});
```

**Comment by piotrekkmt** [comment] 2017-12-15 10:28
Thanks @taai for getting back to me at https://github.com/select2/select2/issues/3320#issuecomment-351892914 

I do agree that the behaviour is fine for what we're using it for. Clicking anywhere on the form itself makes sense to select something else from the list. 

The only thing is the above code doesn't remove the extra (V) icon on the side, does it? It would be nicer and cleaner if the user was able to clear and only see the (X) icon when the form has a value selected.

**Comment by taai** [comment] 2017-12-17 15:25
@piotrekkmt No, my code does not remove the extra ```V``` from the input field when there is a value selected. That is the point what I was talking about – if that ```V``` will be hidden, you will have to click twice to select a new value (first click on ```X``` to unselect and second click on now visible ```V``` to select) and that is what I don't want to do. Probably someone could make it configurable.

For now, you can make a event listener for value change and show-hide that ```V```, if you need it to... 😉

**Comment by ledes** [comment] 2018-05-10 16:56
Thanks for the fix @taai.
When unselecting in multiselect, it doesn't close anymore but the dropdown doesn't get re positioned.
Any eassy way to do this or I have to create an adapter to have access to _positionDropdown() and __resizeDropdown()?

**Comment by ledes** [comment] 2018-05-10 20:31
Found a way
            $element.on(UNSELECT_EVENT, function() {
                $element.resize();
            });
