### ISSUE TITLE
Several bugs and focus features ...

### ISSUE THREAD

**Issue by nporcu** [select2/select2#3644] opened 2015-08-04 13:46 UTC
Hey,
there's no possibility to focus a select2 element. In some usecases we have to be able to do so for example select2 loses focus after selection in internet explorer 11 .. so tabindex is destroyed. Please add this feature. There are several bugs. For example the token separators !always! logs warnings / errors to the browser console. Another problem is that the clearAll action logs errors when no placeholder is defined. Also it would be a nice feature to set a custom message for to much results when a remote service is used. Another bug: You cant set selected values when there is no option for it in the select element. In single select elements the clear all is also buggy. If i use the clear all on single select the value will be cleared. Ok well thats nice but the option for it is still selected in the results and this causes that you cant select that value again! The amd custom translations are badly documentated and cause of that i had to use a own webservice. All in all select2 is unstable. I dont understand how you can release that code with that much bugs. Please test your component before the release next time lost a lot of money and time cause of workarounds :).

**Comment by kevin-brown** [comment] 2015-08-05 14:53
Hi, thanks for the bug reports! It's typically recommended to report a single bug in a report, so we can focus on individual tickets and log their status without having to worry about missing reports.

> there's no possibility to focus a select2 element

Duplicate of https://github.com/select2/select2/issues/3152 / https://github.com/select2/select2/issues/1908

> For example the token separators !always! logs warnings / errors to the browser console.

Probably related to https://github.com/select2/select2/issues/3593

> Another problem is that the clearAll action logs errors when no placeholder is defined.

`placeholder` is required with `allowClear`, see https://github.com/select2/select2/issues/3016

> You cant set selected values when there is no option for it in the select element.

[This isn't something we can fix.](http://stackoverflow.com/q/29058625/359284)

> Ok well thats nice but the option for it is still selected in the results and this causes that you cant select that value again!

I wasn't able to reproduce this issue, but I suspect it's related to the earlier issue with placeholders.

> The amd custom translations are badly documentated and cause of that i had to use a own webservice.

We are looking to improve the documentation here (as well as [pretty much everywhere else](https://github.com/select2/select2/labels/documentation)) in the future.

**Closed by kevin-brown** 2015-08-05 14:53 UTC

**Comment by nporcu** [comment] 2015-08-05 15:08
@kevin-brown
> Ok well thats nice but the option for it is still selected in the results and this causes that you cant > > select that value again!

This issue is caused through the value that is still selected in the options. It shouldn't selected anymore after clearing is that right? FYI: This affects only to single selection mode.

**Comment by kevin-brown** [comment] 2015-08-05 15:11
> It shouldn't selected anymore after clearing is that right?

The option that should be selected after hitting the "clear" (`x`) icon is the placeholder. The UI should visually update to show the placeholder being selected.

You can see an example of this in the placeholder examples: http://select2.github.io/examples.html#placeholders

**Comment by nporcu** [comment] 2015-08-05 15:34
@kevin-brown 

Yes thats right and it works but if i search for a value again and i want to select the same like before -> it isn't possible because it is still selected in the options from the select element which is hidden.
