### ISSUE TITLE
Cannot hit clear button X when the value is longer

### ISSUE THREAD

**Issue by nyxz** [select2/select2#3778] opened 2015-09-17 10:34 UTC
If the `allowClear` is enabled and the value inside the input field is longer than the field itself then dots ("...") are added but the X button gets inactive.

**Comment by kevin-brown** [comment] 2015-09-17 18:28
This is a duplicate of https://github.com/select2/select2/issues/3306.

**Closed by kevin-brown** 2015-09-17 18:28 UTC
