### ISSUE TITLE
.select2-dropdown--above (inline) positioning does not take dropdownParent into account

### ISSUE THREAD

**Issue by NightJar** [select2/select2#4319] opened 2016-04-21 00:48 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [?] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

0. Place the select element in a `position: relative` container
1. Set dropdownParent: $(this).parent()
2. Open the dropdown
3. Scroll (the page) up so as to trigger the --above functionality

## Expected behavior and actual behaviour

**Expected**: The dropdown renders above the container, as it would by default

**Actual**: The dropdown disappears entirely, because the `style="top: ...` is still set as if it were relative to the `<body>` (over 3000px in my case) - this should be measured from the `dropdownParent` element set in the options.

## Environment

**Browsers**

- [x] Google Chrome

**Operating System**

- [x] Mac OS X

**Libraries**

- jQuery version: 1.9.1
- Select2 version: 4.0.2 (dist/js/select2.js)

## Isolating the problem

- [x] This bug happens when using Select2 without other pluigns

**Comment by kevin-brown** [comment] 2016-04-21 13:41
This is a duplicate of https://github.com/select2/select2/pull/4267, it's fixed on the master branch and will be included in the upcoming 4.0.3 release.

**Closed by kevin-brown** 2016-04-21 13:41 UTC

**Comment by NightJar** [comment] 2016-04-23 09:04
Sorry about the duplicate, the existing closed issue does not contain the `dropdownParent` keyword which I was searching for. Look forward to the next release then!
