### ISSUE TITLE
Multiple select box problem when using placeholders on IE10+

### ISSUE THREAD

**Issue by jemes** [select2/select2#3513] opened 2015-06-23 14:38 UTC
Hi !

In our web app, we use select2 on multiple select boxes with placeholders. It works perfectly on Chrome, Safari, Opera and Firefox. However, on IE11 there is a problem.

- When I click on the input, the dropdown appears correctly.
- Then , when I click outside the input, the focus goes back to the input and the dropdown appears again.
- The dropdown and the focus won't go away unless I select something.
- After clicking outside the input too much, IE crashes.

You can test this for yourself on the [official example page](https://select2.github.io/examples.html) (second placeholder example "select a state").

Did someone experience the same problem and know about a workaround ?

Regards

**Comment by fkranenburg** [comment] 2015-06-23 20:25
I'm using Internet Explorer 11 version 11.0.9600.17842 and do not experience this problem. Try resetting browser to defaults.

**Comment by jemes** [comment] 2015-06-23 20:44
Thanks for your reply.

I tried resetting IE to defaults but it does not do the trick. I am using 11.0.9600.17843.

Thus, all our clients that use IE experience the same problem.

I believe the problem comes from select2 because it occurs on the [official example page](https://select2.github.io/examples.html) and it does not occur only on my machine.

Regards

**Comment by tylik1** [comment] 2015-06-23 23:41
The same bug with IE10 and IE9

**Comment by kevin-brown** [comment] 2015-06-25 03:03
This appears to be a duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-06-25 03:03 UTC
