### ISSUE TITLE
Positioning bug after clearing value

### ISSUE THREAD

**Issue by NickStemerdink** [select2/select2#4194] opened 2016-02-16 14:40 UTC
The search bar is incorrectly positioned after clearing the selected value.

![image](https://cloud.githubusercontent.com/assets/1737701/13079254/99db4232-d4c3-11e5-9f72-fea1eb6eb2c9.png)

This only occurs under the following circumstances:

1. Search bar must be triggered above input field
2. There must be a minimum input length of 1
3. It should be allowed to clear values (obviously)

Reproduce here: https://jsfiddle.net/NickStemerdink/56kys576/

1. Search
2. Select value
3. Clear value (click cross)

**Comment by kevin-brown** [comment] 2016-02-16 15:33
Duplicate of https://github.com/select2/select2/issues/3786 and another ticket.

**Closed by kevin-brown** 2016-02-16 15:33 UTC
