### ISSUE TITLE
4.1.0 Beta text wrapping or not aligned.

### ISSUE THREAD

**Issue by JacoFourie** [select2/select2#5863] opened 2020-05-22 09:48 UTC
Hi all Kevin asked me to open a new issue. We have been using the Select2 module for some time now inside Oracle Apex as a plugin. We picked up an issue with IE where you could not add new text with tagging support.

https://github.com/select2/select2/issues/5378

Kevin made a fix for it that I took and added to the code we have inside the plugin for Apex. This seemed to work well. Now we want to upgrade our Oracle Apex platform from 18.1 to 20.1 and we found that version 4.0.7 that I fixed with Kevin's code no longer works.

So I decided to try out 4.1.0 Beta. Now that works fine on all browsers except we get funny text placements and alignments. 

Here is 4.0.7 alignment correct

![image](https://user-images.githubusercontent.com/17771641/82654710-73455980-9c21-11ea-8f2b-367db2846dd4.png)

4.1.0 Beta wrong

![image](https://user-images.githubusercontent.com/17771641/82654804-8fe19180-9c21-11ea-9e9e-918804f8ff5e.png)

If you enter a lot of text in 4.0.7 it fits correctly with a scrollbar at the bottom.

![image](https://user-images.githubusercontent.com/17771641/82654948-bef80300-9c21-11ea-8af2-d6d2d1bfd3b4.png)

and the text inside the box once you press enter.

![image](https://user-images.githubusercontent.com/17771641/82655153-0da59d00-9c22-11ea-9f80-a903d1fb58fe.png)

4.1.0 Beta is a bit of a mess.

![image](https://user-images.githubusercontent.com/17771641/82655037-e0f18580-9c21-11ea-8126-ab7deac8158d.png)

![image](https://user-images.githubusercontent.com/17771641/82655087-f5358280-9c21-11ea-8f8c-4f6641b9529e.png)

Is there a way the layout can be fixed or the old one be made to work on all browsers?

Thanks for a great module.

**Comment by kevin-brown** [comment] 2020-05-22 20:02
I cannot reproduce the spacing/margin issue that you are seeing when I am on https://select2.org/tagging in IE11. Make sure you're using the 4.1.0-beta.1 CSS with the 4.1.0-beta.1 JS.

I can reproduce the text within options not wrapping properly though. This is an issue that appears to be consistent within both IE11 and Chrome.

I also also reproduce the scrollbar issue where the text field appears to be extending outside of the container instead of stopping at the end.

**Comment by kevin-brown** [comment] 2020-05-22 20:18
> I can reproduce the text within options not wrapping properly though. This is an issue that appears to be consistent within both IE11 and Chrome.

Changing the rendered selection to `display: inline-block`, fixing the new margins that appear, and setting `max-width: 100%` appears to fix the issue in IE11 and Chrome. The individual choices also need `word-wrap: break-word` to be applied to them in order to properly break them across lines when they are too long.

> I can also reproduce the scrollbar issue where the text field appears to be extending outside of the container instead of stopping at the end.

It looks like the inline search wrapper needs to be set to `display: inline-block` as well to allow it to be collapsed next to the smaller selections instead of always displaying under them. Setting it to `max-width: 100%` also allows for the search box to not overflow the container, assuming `max-width: 100%` is also set on the search box as well.

**Comment by kevin-brown** [comment] 2020-05-24 00:34
I marked this as "needs information" because of not being able to reproduce the spacing issue on the documentation website.

**Comment by JacoFourie** [comment] 2020-05-24 10:46
OK I uploaded the beta plugin into the Oracle testing cloud.
I am not sure if it is some other javascript code of the old plugin that is creating the space in front.
But here you can see what it is doing no matter what browser you are using.

https://apex.oracle.com/pls/apex/f?p=96087:2:110675964291781:::::

**Comment by kevin-brown** [comment] 2020-05-24 15:04
For single selects we currently use an ellipsis to collapse long options down (relying on the title to accurately show the remainder). To remain consistent, that is what is being done for multiple selects as well.

Since I know people like multiple selects to wrap instead of being cut off, here is the CSS that can be used to enable that.

```css
.select2-selection__choice {
    word-wrap: break-word;
    overflow: visible;
    white-space: normal;
    word-break: break-all;
}
```

**Comment by JacoFourie** [comment] 2020-05-24 18:42
I added the CSS but done see any change.

**Comment by JacoFourie** [comment] 2020-06-04 13:12
Hi. Any idea when they may be fixed ?

**Comment by JacoFourie** [comment] 2020-07-22 11:40
Hi all. We need to have this fixed ASAP. How much would a bounty be to fix this?

**Comment by JacoFourie** [comment] 2020-11-24 06:17
@kevin-brown sorry to bug you. Any news on when this will be fixed?

**Comment by kevin-brown** [comment] 2020-11-28 04:15
It's been a rough couple of months so I haven't had much time to work on Select2. I am planning on finishing off 4.1.0 and releasing another beta sometime in December, which should hopefully address this issue.

**Comment by JacoFourie** [comment] 2020-12-21 07:14
> 
> 
> It's been a rough couple of months so I haven't had much time to work on Select2. I am planning on finishing off 4.1.0 and releasing another beta sometime in December, which should hopefully address this issue.

Hi. I understand. Been a hectic year. Not sure have you released the new version with the fix yet?

**Closed** 2021-01-05 03:32 UTC
Labels: 4.x, confirmed bug, status: needs information, styling

**Comment by JacoFourie** [comment] 2021-01-05 09:30
Hi Kevin. 

I have uploaded the latest version. The text not fitting at the back seems to be working but I still have a gap at the front of the box, that gap will let the text then still stick out the back on Chrome.

![image](https://user-images.githubusercontent.com/17771641/103629612-3a0bf080-4f49-11eb-9454-4377514d99cd.png)

If I het enter then it fits almost in the box. 

![image](https://user-images.githubusercontent.com/17771641/103629703-5576fb80-4f49-11eb-8685-98d5092d9720.png)

Is there somthing in the Apex plugin of framework that is causing this ?

Ypu can have a look here 

https://apex.oracle.com/pls/apex/f?p=96087:2

**Comment by JacoFourie** [comment] 2021-01-05 14:45
OK it is fixed now. You need to add this CSS.

.select2-container ul, .select2-container ol { margin: 0;}

**Comment by kevin-brown** [comment] 2021-01-05 15:03
> OK it is fixed now. You need to add this CSS.

Yup, noticed that was the issue when I looked at it. I'll make a PR today to get that CSS added.
