### ISSUE TITLE
in ipad the select is not click

### ISSUE THREAD

**Issue by c941010623** [select2/select2#3107] opened 2015-03-05 02:01 UTC
in my ipad the select can't select

when i click the selectbox(Multiple select) then keyboard is show

how can i do it ??

**Comment by kevin-brown** [comment] 2015-03-05 13:35
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by c941010623** [comment] 2015-03-10 01:52
in any mobile system
ex:ipad or andriod

than i only use select2 in html
click the inputbox the mobile keyboard is auto show
also can't select item

my test system is ipad2 ios8

**Comment by CUnknown** [comment] 2015-06-29 10:24
I have the same issue, on an ipad with ios 8, I'm unable to select an item from the dropdown directly, while skipping the type-to-search step. When I open the dropdown by tapping it, the dropdown is opened with 5 dropdown items. When I click one, the focus changes to the input (for searching) and the keyboard is opened. Due to this shift of the viewport, the tap on the dropdown item is not fired on the correct dropdown item. Therefore, I'm unable to select the correct item without using the type-to-search input.

When I search for the item (that is already visible in the dropdown) and then click on the item, everything works out fine, because the keyboard is already shown and the viewport is not shifted.

I'm using Jquery 1.11.1, the current release of Select2 and I'm not using plugins like Fastclick or hammerJS.

**Comment by yoyo837** [comment] 2017-08-08 10:26
I have the same issue.

**Comment by yoyo837** [comment] 2017-08-08 10:35
So surprised, I remove FastClick js ，it work fine.

**Comment by alexweissman** [comment] 2017-12-08 06:01
Closing because this seems to be an unfocused discussion, and there are several other, more targeted discussions about mobile issues (including issues with the virtual keyboard).

**Closed by alexweissman** 2017-12-08 06:01 UTC
Labels: compatibility, mobile: iOS, needs information
