### ISSUE TITLE
Example web page error

### ISSUE THREAD

**Issue by actricom** [select2/select2#5500] opened 2019-05-03 15:03 UTC
The first example (Single select boxes) on this page [https://select2.org/getting-started/basic-usage](https://select2.org/getting-started/basic-usage) does not work properly. The drop down refuses to close on selection, click outside or press of escape key. If you hold the escape key down long enough it does close though. Tried in Edge, Chrome and Firefox.

**Comment by yermie** [comment] 2019-05-03 21:45
I'm experiencing the same problem across my entire website. Essentially, the select2 plugin cannot be "closed" once the dropdown is triggered. The experience is broken.

![image](https://user-images.githubusercontent.com/2881605/57167283-15de3080-6db2-11e9-8e0f-ef6fd4028430.png)

**Comment by 18926589010** [comment] 2019-05-04 04:42
the same issue i am experiencing on the example page,dropdown doesnot  close after a selection was made.

**Comment by maxrd2** [comment] 2019-05-04 19:04
This is duplicate of #5499

**Comment by kevin-brown** [comment] 2019-05-06 17:09
This is a duplicate of https://github.com/select2/select2/issues/5490 and fixed in Select2 4.0.7-rc.0.

**Closed by kevin-brown** 2019-05-06 17:09 UTC
