### ISSUE TITLE
Wrong dropdown posision when above the field

### ISSUE THREAD

**Issue by artursudnik** [select2/select2#4110] opened 2016-01-22 09:41 UTC
I have problem but with dropdown list displayed above input field (when located at the bottom of the viewport).

![2016-01-22 102500](https://cloud.githubusercontent.com/assets/2759741/12507156/199357c8-c0f4-11e5-94b7-eac9cb88dad7.png). 

After activating select2 field and entering few characters list is populated with ajax and everithing is OK.

![2016-01-22 102526](https://cloud.githubusercontent.com/assets/2759741/12507157/1dfd7064-c0f4-11e5-89bd-0076cafd5737.png)

After closing dropdown and entering select2 again, when list is empty before loading data with ajax its posision is the same as before closing.

I also noticed that when displayed incorrectly when you change size of the window browser, position of the list is corrected immediately.

**Comment by kevin-brown** [comment] 2016-01-26 16:24
There's an open ticket about this.. somewhere, I know I've seen this reported. We aren't properly setting the position when the dropdown is opened, only when the results are changed or a few events are triggered.

**Comment by fxgit** [comment] 2016-01-31 05:20
a dirty solution until the bug is resolved

```javascript
$example = $(".js-data-example-ajax").select2({ ... }):
var select2_close_block = 0;
$example.on("select2:close", function (e) {
  if(select2_close_block == 0){
    select2_close_block = 1;
    $example.select2("open").select2("close");
    select2_close_block = 0;
  }
});
```

**Comment by zflat** [comment] 2016-02-13 22:42
I think this may be the same issue: https://github.com/select2/select2/issues/3905

**Comment by kevin-brown** [comment] 2016-02-13 22:53
Duplicate of https://github.com/select2/select2/issues/3905.

**Closed by kevin-brown** 2016-02-13 22:53 UTC
Labels: 4.x, bug

**Comment by michaud** [comment] 2016-06-03 10:45
+1
my solution is clearing results:

```
                    $(that._countrySelect).data('select2').on('open', function (e) {
                        this.results.clear();
                        this.dropdown._positionDropdown();
                    })
```
