### ISSUE TITLE
Select2 4.0.0 beta bug with disabled and allowClear

### ISSUE THREAD

**Issue by smzchaudary** [select2/select2#2903] opened 2015-01-09 00:27 UTC
See [here for an example] (http://plnkr.co/edit/6oSJMRu6cQfq079cyaF9?p=preview). Sample code also pasted below

When the select is disabled, and select2 option for allowClear is enabled, the allowClear button is not disabled - allowing the user to clear the select2 box.

Also, while I am at it, there is a weird behavior with select2 multiple with the allowClear option.

``` html
<!DOCTYPE html>
<html>

  <head>
    <script src="https://select2.github.io/dist/js/select2.full.js"></script>
    <link href="https://select2.github.io/dist/css/select2.min.css" type="text/css" rel="stylesheet">
  </head>

  <body>
    <h4>Even though this is disabled, I can hit the clear</h4>
    <select disabled='true' style="width: 100%">
      <option value="0">red</option>
      <option value="1">blue</option>
      <option value="2">green</option>
      <option value="3" selected='selected'>purple</option>
    </select>
    <h4>Even though this is disabled, I can hit the clear. Notice the weird position, as well as the hover mouse icon remains a cursor</h4>
    <select disabled='true' style="width: 100%" multiple="multiple">
      <option value="0">red</option>
      <option value="1">blue</option>
      <option value="2">green</option>
      <option value="3" selected='selected'>purple</option>
    </select>
    <script type="text/javascript">
      $('select').select2({
  placeholder: "Select a color",
  allowClear: true
});
    </script>
  </body>

</html>
```

**Comment by smzchaudary** [comment] 2015-01-09 03:46
Related to this issue, the [`X` in the multiselect] (https://github.com/select2/select2/blob/select2-ng/dist/js/select2.js#L1360-L1371) also removes the selections from the list.

With a simple spot fix, we can choose not to render the `X` for `allowClear` when the element is disabled.
Looking at the [`AllowClear.prototype.update` function](https://github.com/select2/select2/blob/select2-ng/dist/js/select2.js#L1501-L1518), we can change:
``` javascript
if (this.$selection.find('.select2-selection__placeholder').length > 0) {
      return;
    }
```
to
``` javascript
if ((this.$selection.find('.select2-selection__placeholder').length > 0) || (this.$element.prop('disabled') === true)) {
      return;
    }
```

The other option is to create a disabled version of the class that that will change the cursor type to something other than `pointer` (maybe `not-allowed`), as well as exclude it from the [mousedown](https://github.com/select2/select2/blob/select2-ng/dist/js/select2.js#L1491-L1493) action that removes the item.

The issue with the `X` in the multiselect box is trickier - Changing the CSS class might be the easiest way to prevent the selector from the [`click`](https://github.com/select2/select2/blob/select2-ng/dist/js/select2.js#L1360-L1371) handler.

These are just suggestions - admittedly a bit hacky in nature - but they seem to get the job done in my narrow use cases.

**Comment by kevin-brown** [comment] 2015-01-09 14:52
This should be fixed by the time the second beta rolls around (hopefully early next week). You'll know when my commit closes this off.

> Also, while I am at it, there is a weird behavior with select2 multiple with the allowClear option.

This is most likely because the `allowClear` option was intended for single selects. I'm guessing the intention for multiple selects would be to clear out all of the selected values at once?

> When the select is disabled, and select2 option for allowClear is enabled, the allowClear button is not disabled - allowing the user to clear the select2 box.

Yup, definitely a reproducible bug.

> Related to this issue, the X in the multiselect also removes the selections from the list.

Also a reproducible bug. I'm good with also just hiding the `x` in this case. This is what we did in past versions to prevent issues.

> (this.$element.prop('disabled') === true)

`this.options.disabled` should also work.

**Comment by smzchaudary** [comment] 2015-01-09 15:00
> I'm guessing the intention for multiple selects would be to clear out all of the selected values at once?

I guess so - It was more of an 'I set the `allowClear` and made the select a `multiple` and saw something weird'. In any case, I wanted to report it - if only to document it as something that an end user shouldn't do.

**Closed** 2015-01-09 16:03 UTC
Labels: bug
