### ISSUE TITLE
Programmatically adding/removing options does not work in tags mode (jsFiddle inside)

### ISSUE THREAD

**Issue by drauch** [select2/select2#4664] opened 2016-10-30 19:06 UTC
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [using v4.0.3] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [jsFiddle] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. USE the initialized Select2 (i.e., open the suggestions!)
2. Programatically add or remove options from select
## Expected behavior and actual behavior

https://jsfiddle.net/7y61zbv6/

Expected:
1. Updated suggestions
2. New options are actually selectable

When I follow those steps, I see...
1. Suggestions from before the programmatic updates
2. Moreover: the old ones are no longer selectable, i.e., do not trigger an add
## Environment

Browsers
- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 3.0.0
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in https://jsfiddle.net/7y61zbv6/ (first open the suggestions, then click Change, then again open the suggestions and try to select something in optgroup 1)

**Comment by alexweissman** [comment] 2017-09-28 01:26
So, as a general rule you actually need to call `trigger('change')` whenever you modify the DOM programmatically.  However, I notice that this does not seem to work for options in your `optgroup`.  This may be another manifestation of the general problem where the dropdown does not get updated for certain DOM changes, like the `selected` and `disabled` properties.

**Comment by elsurudo** [comment] 2017-12-11 15:30
Issue persists with 4.0.5 – adding an option to an optgroup programatically and then trigger the "change" event on the select doesn't refresh it. Have you found a workaround, by any chance?

**Comment by drauch** [comment] 2017-12-11 17:09
Unfortunately, no.

**Comment by alexweissman** [comment] 2017-12-12 02:22
There are some open PRs that address issues with `optgroup`s specifically.  If you could review some of these, and identify any that solve this issue, it would be extremely helpful.

**Comment by alexweissman** [comment] 2017-12-14 20:44
This is actually a duplicate of #3604.

**Closed by alexweissman** 2017-12-14 20:44 UTC
Labels: status: possible bug (unconfirmed)
