### ISSUE TITLE
Width Problem In bootstrap model 

### ISSUE THREAD

**Issue by Adeelgill** [select2/select2#4269] opened 2016-03-24 07:30 UTC
I have a problem with select2 width when a bootstrap model is in show. Take the width `width:100px`.
I checked a lot and find that it happens when we hide a div with `display:none` and the show the div with `display:block` the select2 get the default width which is `width:100px` but it should be the `width:100% `
![screenshot_6](https://cloud.githubusercontent.com/assets/8061685/14010836/badf0a5e-f1ba-11e5-8cff-5eb11ed8b9b6.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/8061685/14010837/badfd8c6-f1ba-11e5-9020-93485d66666e.png)

**Comment by epicserve** [comment] 2016-03-29 15:47
So I'm not using the bootstrap modal, I'm using my own custom modal within bootstrap and I'm having the same issue. I've discovered what's causing it, however I don't know how to fix it yet. The issue seems to be if you call `$('select').select2()` on selects that have a parent element where the css is `display: none`, select2 doesn't set the correct width on the select2 container. I verified this by making my modal visible on load and the select2 elems had the correct width.

I'm using select2 v4.0.2 with the latest version of select2-bootstrap-theme (adbbe902fa59) from the master branch.

Before:
![before](https://cloud.githubusercontent.com/assets/191620/14114030/1ec5a620-f59b-11e5-88ea-0a0e96590dbe.jpg)

After:
![after](https://cloud.githubusercontent.com/assets/191620/14114127/74600346-f59b-11e5-831c-48feeafa718d.png)

**Comment by epicserve** [comment] 2016-03-29 16:38
My current hack to make it work is to run `$('.filter-modal select').css('width', '100%');` before I run `$('select').select2()`.

**Comment by Adeelgill** [comment] 2016-04-05 11:55
That's also work fine for me with bootstrap thank you buddy.

**Comment by kevin-brown** [comment] 2016-04-05 14:47
This is a duplicate of https://github.com/select2/select2/issues/3278.

**Closed by kevin-brown** 2016-04-05 14:47 UTC

**Comment by ombak** [comment] 2020-03-13 03:41
I have same problem use Flask and flask-wtform. I and solve with this code:
`field_name = SelectField(
render_kw={ 'style': 'width:100%;' }
)`

**Comment by rajatmadaan786** [comment] 2020-09-29 14:03
Just added **width** property into the options and it worked for me.

    $('#domains-list').select2({
         width: '100%'
    });
