### ISSUE TITLE
Truncated placeholder for hidden multiple select

### ISSUE THREAD

**Issue by SkiF91** [select2/select2#3669] opened 2015-08-11 03:40 UTC
So, here is example: https://jsfiddle.net/spcnek5u/

After firing 'change' event everything ok (of cource if select visible).

**Comment by kevin-brown** [comment] 2015-08-11 22:25
This has to do with Select2 not being able to get the width when it is hidden because the browser does not actually report the width of hidden elements (they have no width).

This appears to be a duplicate of https://github.com/select2/select2/issues/3292, and it's not something we can (cleanly) fix.

**Closed by kevin-brown** 2015-08-11 22:25 UTC

**Comment by gwilliamtam** [comment] 2016-02-19 17:18
I fix it modifying the width after document ready:

```
$(document).ready( function() {
    // Correct bug to show placeholder
    $('.select2-search__field').css({"width":"200px"});
});
```
