### ISSUE TITLE
Procedural initialisation from <select>s: 2 empty options necessary to allow empty selection

### ISSUE THREAD

**Issue by barneycarroll** [select2/select2#2473] opened 2014-06-19 10:51 UTC
[In this fiddle](http://jsfiddle.net/barney/6yP3Y/), the 2nd select starts with 1 empty option; the 3rd with 2. The 2nd starts with no selection, but the empty selection can't be re-selected. The 3rd displays 1 empty option to the user.

**Comment by kevin-brown** [comment] 2016-06-25 18:38
This was a duplicate of https://github.com/select2/select2/issues/2142 and it has since been fixed in later versions of Select2.

**Closed by kevin-brown** 2016-06-25 18:38 UTC
