### ISSUE TITLE
Bug: select2 clears input field when focus is lost

### ISSUE THREAD

**Issue by iFlash** [select2/select2#5142] opened 2017-11-21 15:16 UTC
Select2 clears the input field as soon as the focus is lost. As this is not an expected behavior by any given user, I think this is a bug.

The input field should keep the value entered unless a search is performed and a result from the dropdown list has been selected.

**Comment by alexweissman** [comment] 2017-11-21 15:24
Duplicate of #3902.

**Closed by alexweissman** 2017-11-21 15:24 UTC
Labels: duplicate

**Comment by alexweissman** [comment] 2017-11-21 16:01
And yes, I got your extremely rude message through my website.  Have you ever maintained a large open-source project?  Literally dozens of new issues are opened every week, and no one is getting paid to do this.  

I simply do not have time to do your due diligence for you and search the open issues. The fact that I did so anyway, so I could close this duplicate issue, reflects badly on you - not me.

Let me put it another way.  Do you understand why you opened a new issue instead of finding #3902?  It's because there are already 567 open issues.  It's a problem that compounds on itself - every new issue makes it more likely that the main discussions will get lost in the noise, and cause people to open even _more_ issues.  **Each new issue makes it harder for everyone to find their issue.**

There were over 800 open issues when I stepped in, and I've sacrificed many weekends to clean it up and get us on our way to making Select2 a tractable project again.

I expect you to be thanking me for my service, not criticizing me for keeping this project running in an efficient manner.
