### ISSUE TITLE
Very strange behaviour when trying to clear Select2 instance created with `tags: true`

### ISSUE THREAD

**Issue by andregreeff** [select2/select2#6251] opened 2023-05-12 11:15 UTC
first things first: I did search through all existing issues, both open and closed.. doesn't look like this issue has been logged before.

the following JSBin contains a snippet of my project, which is sufficient to reproduce the issue: https://jsbin.com/legokuwebu/1/edit?html,js,output

the problematic behaviour itself is a little difficult to summarise, so let me describe it as a step by step process, with comments at places where something "goes awry". working from the above JSBin example:

> note: I'm not sure if my "start and end time" inputs check in the `createTag` handler is causing any problems, so I've included it in the example just in case.

1. set either "start" or "end" input to any value
2. focus the Select2 box and start typing a new name
   * the first character entered updates the "selected" entry - this I did not expect
   * none of the subsequent characters update the "selected" entry - as expected
3. press "enter" to select the new input as an entry
   * the final selection then updates the "selected" entry with the full input - as expected
4. now click the "X" to clear the selection
   * first click opens the dropdown without clearing anything
   * second click clears the current selection

now, to make things even more interesting, there is another process that results in different handling, starting out the same way:

1. set either "start" or "end" input to any value
2. focus the Select2 box and type a single letter
3. press "enter" to select the new input as an entry
4. now click the "X" to clear the selection
   * first click correctly clears the current selection

---

just for context:

along with this, I'm also attaching a listener to the `select2:select` event which saves the time window values if it gets a new entry name, or updates the "start" and "end" time inputs if it gets a known entry name, along with one more listener on `select2:clear` for clearing the "start" and "end" time inputs. whether or not I include these extra event listeners, I still get the exact same behaviour described above.

I have tried in my local project without my custom Select2 theme, just in case that caused any issues, but that made no difference either way.

any bright ideas?

**Comment by andregreeff** [comment] 2023-05-12 11:29
I did just find a forum post from mid 2018 that is _very_ similar: https://forums.select2.org/t/tags-option-with-allowclear-selectonclose-and-ajax/319

following the JSBin link from there, I can reliably reproduce this issue, but with slight differences, probably due to the remote data source.

in this example: the initial update of the "selected" entry (which always takes the first character in my examples above) appears to wait for the first Ajax response, but then:

1. if I accept that entry without any further input, then the "clear" button works exactly as expected.
2. if I modify the search further and then accept _that_ entry, then:
   * first click clears my actual selection, and shows the initial "selected" value again (first character from my examples, first post-Ajax string from forum example).
   * second click fully clears the "selected" entry.

so, it seems that the "selected" state is being set _way_ before it should be, thereby causing problems for numerous other actions that come afterwards.

**Comment by kevin-brown** [comment] 2023-05-13 02:49
This has to do with the select not being configured with an empty option for the placeholder. This is noted on the documentation page for placeholders: https://select2.org/placeholders

**Comment by kevin-brown** [comment] 2023-05-13 02:50
Duplicate of https://github.com/select2/select2/issues/3553#issuecomment-119772829.

**Closed as not planned** 2023-05-13 02:51 UTC

**Comment by andregreeff** [comment] 2023-05-15 06:51
> This has to do with the select not being configured with an empty option for the placeholder. This is noted on the documentation page for placeholders: [select2.org/placeholders](https://select2.org/placeholders)

thanks @kevin-brown, seems I can't read the docs properly..

---

_follow up edit_

I got busy resolving a few other points in my current project, so I've only just got back to this one now..

just a quick one for the sake of clarity: reworking my markup to generate the root select element with `$("<select><option>")` has also resolved the "clear current selection" functionality. 👍
