### ISSUE TITLE
Problem with multi option on select2

### ISSUE THREAD

**Issue by Fcatalao** [select2/select2#5039] opened 2017-09-14 09:26 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. See bottom description

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

Hello. I have a problem that you can try on Select2 demos.
When I use the ability to insert more than one option by text inserted mannualy, if that text lenght is bigger than HALF of the width of the select2 , after inserting (clicking ENTER), it goes to a new line, making my entry ''disappear to upside". If i click on any char key it starts the input after my already entered text in the same line (so it revert the line break).

So i'm using the ability to insert ONLY one option manually, and that option sometimes will be longer than half of the width. How can I make it to do not create a line break after entering my entry only if it's bigger than half of the width?

Example:
With a entered text less than half:
https://ibb.co/dDiZm5

With a entered text bigger than half:
https://ibb.co/jxn5tk

With a entered text bigger than half and after that, insert a text we can see the ''cursor'' goes to the front and bring back a single line entry:
https://ibb.co/npwn65

**Comment by alexweissman** [comment] 2017-09-14 15:05
This appears to be a duplicate of #3961.  Please add your comments/screenshots there.

**Closed by alexweissman** 2017-09-14 15:05 UTC
