### ISSUE TITLE
Add parameter to not open dropdown when deselecting option in multiselect

### ISSUE THREAD

**Issue by hrst** [select2/select2#5805] opened 2020-03-19 22:59 UTC
Hi everyone,

I'd have the following feature request:

The default behavior of Select2 with a multiselect is to open the dropdown when a selected option is deselected / removed (i.e. by clicking on the “X” next to it). I’d wish to not have the dropdown open when I remove an entry. It would be especially nice to have this behavior when the last entry is removed, in other words, to not show the dropdown when the select was emptied.

**Comment by kevin-brown** [comment] 2020-04-19 00:45
Duplicate of https://github.com/select2/select2/issues/3209#issuecomment-149663474, we expose ways that allow you to do this if you want to.

**Closed by kevin-brown** 2020-04-19 00:45 UTC
