### ISSUE TITLE
Can not use select2.amd with requirejs

### ISSUE THREAD

**Issue by blazkovicz** [select2/select2#3038] opened 2015-02-13 06:54 UTC
Requirejs throws error on  `return require('jquery.select2');` in the end of `select2.amd.js`:
`Module name "jquery.select2" has not been loaded yet for context: _. Use require([])`

Requirejs (latest 2.1.16) does not add defined modules to context, but adds them to the defining queue, so they would be processed one after another. That's why it is not possible to define module locally and use it instantly.

**Comment by glenpike** [comment] 2015-03-02 13:18
see #2946

**Comment by kevin-brown** [comment] 2015-03-02 14:14
Closing as a duplicate of https://github.com/select2/select2/issues/2946.

**Closed by kevin-brown** 2015-03-02 14:14 UTC
