### ISSUE TITLE
Expanding the option list does not scroll to the selected option

### ISSUE THREAD

**Issue by nailstj** [select2/select2#4204] opened 2016-02-23 11:54 UTC
I have a select box that has a long list of values with a selected option. The selected option is near to the bottom of the list and outside the visible area of what would be displayed when expanding the select box.

The first time expanding the option list, the list does not scroll to that value, it stays at the top. The second time expanding the list it scrolls to the selected value. I would expect this behavior to be consistent and always show the selected value in the visible drop down list.

https://jsfiddle.net/6zz4jbw5/

To reproduce, click on the option value once, notice that the value list starts with the first item. Click again to close. Click again to reopen and notice that the value list now shows the selected value.

**Comment by urkle** [comment] 2016-03-15 15:15
Related to #1408 and  3956

**Comment by kevin-brown** [comment] 2016-03-18 23:40
Closing this as a duplicate of https://github.com/select2/select2/issues/3956.

**Closed by kevin-brown** 2016-03-18 23:40 UTC
Labels: 4.x
