### ISSUE TITLE
Dropdown position issue (with simple live demo)

### ISSUE THREAD

**Issue by qinbx** [select2/select2#4129] opened 2016-01-28 09:03 UTC
Hi, 

 I met an issue in my project. Below is a simple demo to reproduce the issue:

http://codepen.io/qinbx/pen/Qyrqmx

Expected dropdown positon:
![select2-expect-position](https://cloud.githubusercontent.com/assets/836554/12639690/a8e185da-c5e0-11e5-8473-342af1b6e9e6.jpg)

Below is how the issue position looks like:
![select2-wrong-position](https://cloud.githubusercontent.com/assets/836554/12639704/b97e896a-c5e0-11e5-9a74-f80ba4308c0a.jpg)

Thanks all your efforts for now. Just want to let you know the issue.

**Comment by kevin-brown** [comment] 2016-01-28 16:21
This is a duplicate of https://github.com/select2/select2/issues/3970 which will be fixed in the upcoming 4.0.2-rc.1 release.

**Closed by kevin-brown** 2016-01-28 16:21 UTC

**Comment by qinbx** [comment] 2016-01-29 07:48
@kevin-brown 
Thanks for your feedback.
