### ISSUE TITLE
createTag weirdness

### ISSUE THREAD

**Issue by Spongman** [select2/select2#4885] opened 2017-04-26 01:39 UTC
tons of weirdness with createTag. check this pen: http://codepen.io/Spongman/pen/zwrMKw

- type 'a' into the select input box, NOTE:
  - a tag is created in the results list
  - the placeholder is changed
- type an addional 'b' into the select input box (making it 'ab'), NOTE:
  - the tag in the results list changed (good)
  - the placeholder still shows 'a' (bad)
- click the 'x' in the select2, NOTE:
  - the list didn't close (bad)
  - the placeholder changed to reflect the typed value (bad)
- click the 'x' again, NOTE:
   - it still doesn't close, the original placeholder is back, and the results list says "No results found"

**Comment by Spongman** [comment] 2017-05-01 20:05
is it even supposed to be altering the selection here before the user actually selects the result?

**Comment by alexweissman** [comment] 2017-09-27 21:30
So, placeholders will only work properly when you have an empty `<option>` element.  See https://select2.org/placeholders#text-placeholders

As for the dropdown not closing, I'm not sure what the intended behavior is, but I don't think it is supposed to close automatically when the selections are cleared.

**Closed** 2017-12-09 18:23 UTC
Labels: status: resolved
