### ISSUE TITLE
Duplicate values with multiple and tags.

### ISSUE THREAD

**Issue by lucasferronato** [select2/select2#4779] opened 2017-02-07 19:15 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
Actually I found [a similar one](https://github.com/select2/select2/issues/4404) but its already fixed.
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a multiselect with tags
2. Have some options (lets say `[{id: 1, text: 'foo'}]`)
3. Type 1 on the input and hit enter

## Expected behavior and actual behavior

When I follow those steps, I see 2 values on my select, `foo` and `1`

I was expecting only one (the tag: `1`)

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsfiddle.net/ferronatoo/x7byvt9s/)

**Comment by alexweissman** [comment] 2017-09-25 02:36
This issue appears to be a duplicate of #3681.

**Closed by alexweissman** 2017-09-25 02:36 UTC
Labels: confirmed bug

**Comment by Kaushik1987** [comment] 2019-09-05 17:31
Is this bug fixed ? Because I am also facing this issue.
