### ISSUE TITLE
Dropdown hint is positioned incorrectly

### ISSUE THREAD

**Issue by LuuchoRocha** [select2/select2#4526] opened 2016-08-09 04:40 UTC
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue

It is need to have a select2 input near to the bottom of the viewport so the select2 dropdown menu opens above the input. Also 'minimumInputLength' option must be  greater or equal than 1. With this conditions:
1. Write `minimunInputLength` of characters (for example, `3`)
2. Delete `1` character (to make results disappear) 
3. Then the dropdown will show `Please enter 3 or more characters...`. 
## Expected behavior and actual behavior

This last text and the entire dropdown will be displayed incorrectly as if have options below, between the hint and the input, making a ugly space between the input and the dropdown. 
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries
- jQuery version: 3.1.0
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug [here](https://jsfiddle.net/luchorocha/n1zyd1v3/)

To reproduce the bug in my fiddle, write `xyz`, then remove `z` and that's all. 
Here are some screenshots of the issue:
#1.

![1_select2](https://cloud.githubusercontent.com/assets/7143275/17504767/306ef116-5dd2-11e6-8b3c-4d21a5833b6a.png)

---
#2.

![2_select2](https://cloud.githubusercontent.com/assets/7143275/17504769/3488f1a2-5dd2-11e6-9b2b-b2143f46572a.png)

**Comment by benjiwheeler** [comment] 2016-08-10 07:02
Running into a similar issue; hint opens fine initially, but if I scroll the page, hint moves too much relative to its input, and detaches from it. (working to isolate the bug and ensure it's not conflicting with other plugins.)

**Comment by jmiguel-localvox** [comment] 2016-10-04 13:58
I forgot this issue existed, I posted in a duplicate a little hack that got around the problem for me.

https://github.com/select2/select2/issues/4614#issuecomment-251277428

**Comment by alexweissman** [comment] 2017-09-17 02:06
This is a duplicate of #4614.  Please search issues carefully before opening new ones!

**Closed by alexweissman** 2017-09-17 02:06 UTC

**Comment by lucho-rocha** [comment] 2017-09-18 12:31
@alexweissman 
This issue has been created at Aug 9 2016, the other (#4614) is dated Oct 3 2016.
I dont know why the need to be rude!

**Comment by alexweissman** [comment] 2017-09-18 17:08
My mistake, you are right!  I was cleaning up a lot of duplicate issues and using a canned response.

That being said, most discussion is taking place in #4614, so even though this issue is older, I am leaving that one open as the canonical issue.

Sorry about that!
