### ISSUE TITLE
Duplicate tags when using remote data source

### ISSUE THREAD

**Issue by dmorda** [select2/select2#4298] opened 2016-04-11 12:55 UTC
I am using Select2 to enable tagging. I need the user to be able to type in a tag and get back a list of results from an AJAX call. If the tag does not exist, the user should be able to create a tag. I've got most of the functionality working, but I ran into a strange issue where duplicate tags are created.
## Steps to reproduce the issue

Using the example below or [here](http://jsfiddle.net/dmorda/qLv9k10j/4/), do the following:
1. Enter "tagabc" and press enter
2. Enter "tagabc" again and select "tag1" from the dropdown
3. You should now see tag1, tagabc, and the duplicate tagabc in the list of tags.

**Example**

```
<html>
<head>
<style>
#tags {
  width: 300px !important;
  height: 100px !important;
  position: relative !important;
  display: block !important;
}
</style>
</head>
<body>
<h3>Steps to Reproduce</h3>
<ol>
  <li>Enter "tagabc" and press enter</li>
  <li>Enter "tagabc" again and select "tag1" from the dropdown</li>
</ol>
<p>You should now see tag1, tagabc, tagabc in the list of tags.</p>

<select id="tags" multiple style="width: 400px;"></select>

<script type="text/javascript">
$('#tags').select2({
    tags: true,
    ajax: {
        url: 'https://api.myjson.com/bins/3oz54',
        dataType: 'json',
        data: function (params) {
          return {
            q: params.term, // search term
            page: params.page
          };
        },
        processResults: function(data, params) {
                params.page = params.page || 1;
            return {
              results: data,
              pagination: {
                more: (params.page * 30) < data.total_count
              }
            };
        }
    }
});
</script>
</body>
</html>
```

Is this a bug or is there some filtering I should be doing that I'm not?

**Comment by davilious** [comment] 2016-04-27 15:31
I don't see it like a `bug` at all. The problem seems to be that you need to process the result in a different way, for example you might want to filter the results as long as you type the tag so probably you miss something like the code below. 

```javascript
        processResults: function(data, params) {
          var data = $.map(data, function(item) {
            if (item.text.match(params.term) || params.term === "") return item;
          });
          return { results: data }
        }
```

Have a look a this [jsfiddle](http://jsfiddle.net/w5hvcjdo/1/) that I forked from your code to see it working. 

I hope it helps.

**Comment by sgmckay** [comment] 2017-01-05 18:22
I am experiencing the same issue and was able to reproduce in the [fixed jsfiddle](http://jsfiddle.net/w5hvcjdo/1/)
To reproduce:
1. Enter "tag"
2. Press enter (will have "tag" selected)
3. Enter "tag"
4. Select tag1

Instead of selecting "tag1" it selects both "tag" and "tag1" so now it has "tag", "tag", "tag1" selected.  If you search for "tag" again and select a different result it will again select "tag" and the result so now you have "tag" selected 3 times.  Anytime you search for a term that has been selected ("tag") and then select a result it selects both the result and the term causing the term to be duplicated in the selected options.

**Comment by ilgiz-badamshin** [comment] 2017-01-17 08:52
+1 
Select2 4.0.3.

**Comment by m4lk** [comment] 2017-07-13 17:10
Hey bud.. We faced the same issue, and we fixed it with a few lines. Check this out:
`$select2Id.on('select2:select', function () {
    $("select[id^=edit-term] option").each(function() {
      var val = $(this).val();
      $(this).siblings("[value='"+ val +"']").remove();
    });
  });`

Not fancy, but it worked for us :)

**Comment by liux1506** [comment] 2017-09-15 03:05
+1

**Comment by alexweissman** [comment] 2017-09-15 03:55
Please refrain from "+1" comments.  Simply click the 👍 button on the top comment to express your interest in this issue.

**Comment by alexweissman** [comment] 2017-12-08 19:59
Is this still an issue as of `4.0.6-rc.1`?  See #4096 and #4404.

**Comment by alexweissman** [comment] 2017-12-16 00:43
I'm almost certain that this is a duplicate of either #4610 or #3498.

**Closed by alexweissman** 2017-12-16 00:43 UTC
Labels: feature: ajax, status: needs information, status: possible bug (unconfirmed)

**Comment by elyasmv** [comment] 2021-07-27 07:23
https://stackoverflow.com/a/68540536/8705204
