### ISSUE TITLE
In tag mode uppercase/lowercase should be ignored while submitting

### ISSUE THREAD

**Issue by maciekpaprocki** [select2/select2#3740] opened 2015-09-07 11:43 UTC
Let's say we have one of the options "Something" if someone types "something" and press enter it will add another tag instead of selecting existing one. 

It would be amazing to see it as an option once set up it will ignore letter case as this functionality could be used quite often.

**Comment by kevin-brown** [comment] 2015-09-09 16:04
This is a duplicate of https://github.com/select2/select2/issues/3566.

**Closed by kevin-brown** 2015-09-09 16:04 UTC
