### ISSUE TITLE
Ability to select a group of items?

### ISSUE THREAD

**Issue by hackeron** [select2/select2#3383] opened 2015-05-21 06:46 UTC
There are a lot of examples for Multiple select boxes showing selecting 1 item at a time. I would love the ability to click on the heading to select all items for that heading.

For example, clicking on Pacific Time Zone to select California, Nevada, Oregon, etc.

My use case is I have different locations and these locations have multiple zones/cameras - I would like to click on the location name to select all cameras for that location.

**Comment by kevin-brown** [comment] 2015-05-24 00:47
Duplicate of https://github.com/select2/select2/issues/520#issuecomment-103703792.

**Closed by kevin-brown** 2015-05-24 00:47 UTC
