### ISSUE TITLE
When the text is longer than the select2 box, the clear button isn't clickabe (allowClear: true).

### ISSUE THREAD

**Issue by pblanchardie** [select2/select2#3668] opened 2015-08-10 16:30 UTC
When the text is too long, it's properly truncated and suffixed with ..., but it makes the clear button behave unexpectedly. Apparently, the float: right isn't used properly, and the text seems to be "above".
You can manage to click on the clear button by putting you cursor under the button (then it will highlight and show the hand cursor, as expected).

**Comment by kevin-brown** [comment] 2015-08-12 00:15
This is a duplicate of https://github.com/select2/select2/issues/3306.

**Closed by kevin-brown** 2015-08-12 00:15 UTC
