### ISSUE TITLE
CloseOnSelect=false and Enter Key is keeping the text after the tag

### ISSUE THREAD

**Issue by CalvinNunes** [select2/select2#5184] opened 2018-01-04 15:13 UTC
**Select2 Version**: 
4.0.5

**Issue:**
 In a multitag (with tags: true or with pre-filled tags) everytime when i hit enter to select the tag, it creates the tag but keeps the text right on side of the new tag, it just disappear if I press another key after. (Happens only with Enter key)

**Example:**
![insta](https://user-images.githubusercontent.com/32517249/34569616-76ea9786-f150-11e7-97f4-9101eb752789.gif)

**How to reproduce:**
Tags: true,
multiple: true,
CloseOnSelect: false,
Then Press Enter to select a tag, it will create the tag, but the text will be copied right next to the tag, as you can see in the GIF example.

If i remove the CloseOnSelect, or change it to true, this Issue stops... 
there is something to do to fix it?

**Comment by alexweissman** [comment] 2018-01-04 15:57
Duplicate of #4698.

**Closed by alexweissman** 2018-01-04 15:57 UTC
