### ISSUE TITLE
When I clear one selection on a multi-select with allowClear set to true, all selections are cleared

### ISSUE THREAD

**Issue by Intrepidd** [select2/select2#3772] opened 2015-09-16 15:46 UTC
Here's an example fiddle :

http://jsfiddle.net/Intrepidd/ytL9s97k/

Try to add several results to the multiple select then remove only one, it will remove everything, and also the clear button appears.

Here's a gif demonstrating the issue : 

![clear_multiple](https://cloud.githubusercontent.com/assets/803765/9909877/98da21ce-5c9a-11e5-87fe-a66137ddc2fc.gif)

I understand you should not use `allowClear` with a multiple select but in some cases you just want to apply select2 to all selects.

A quick fix would be to call select2 two times with the following selectors :

```
$('select[multiple]').select2({width: '100%'});
$('select:not([multiple])').select2({allowClear: true, width: '100%'});
```

but this is messy.

IMHO `allowClear` should be ignored if the select is multiple

thoughts ?

**Comment by kevin-brown** [comment] 2015-09-16 20:56
This is definitely a duplicate, but part of the issue is that you are missing `placeholder`, which is required for `allowClear`. I think we trigger a warning about that when you have `debug: true` set.

Until I hunt down the ticket, this one will stay open.

**Comment by SlyDave** [comment] 2015-10-05 12:42
Whilst it may be the current requirement, I don't get why "placeholder" is a requirement for this behaviour, they do not seem related at all.

**Comment by kevin-brown** [comment] 2015-10-13 19:57
It's a requirement for single selects, and `allowClear` was designed with a single select in mind. For a single select, we need to reset it to a specific value instead of just clearing all selections.

In theory, [this line](https://github.com/select2/select2/blob/8ad8f200ba8c9429d636453b8ee3bcf593e8c87a/src/js/select2/selection/allowClear.js#L63) could be conditional (default to `null` if `this.placeholder` isn't there) which would remove the requirement for multiple selects. But then there would be a configuration difference between single and multiple selects, which is something we are trying to avoid.

**Comment by alexweissman** [comment] 2017-11-06 02:00
This is a duplicate of #3335.  Since @kevin-brown offers some useful insight, I will repost his comments in #3335.

**Closed by alexweissman** 2017-11-06 02:00 UTC
Labels: 4.x, confirmed bug: help needed
