### ISSUE TITLE
Change select elements with keyboard arrows when focusing the element

### ISSUE THREAD

**Issue by alvarotrigo** [select2/select2#3697] opened 2015-08-20 14:51 UTC
Right now, even if you manually focus the element (by using TAB or by directly clicking it and pressing ESC) the plugin won't allow you to select any other element by using the keyboard arrows (UP, DOWN).

Any other normal `<select>` element in any browser allows to do it. I believe select2 should as well in order to improve its accessibility and avoid confusion within users. 

The only way to do it at the moment seems to be by pressing ENTER (and therefore opening the options dropdown) and then moving through the elements.

**Comment by kevin-brown** [comment] 2015-08-20 16:46
Duplicate of https://github.com/select2/select2/issues/3472.

**Closed by kevin-brown** 2015-08-20 16:46 UTC
