### ISSUE TITLE
Focus an Blur events not working

### ISSUE THREAD

**Issue by samholmes** [select2/select2#3571] opened 2015-07-12 23:16 UTC
When selecting the original <select> element and registering focus and/or blur events, they never get triggered when focusing or blurring the select2 element.

**Comment by kevin-brown** [comment] 2015-07-13 00:23
Duplicate of https://github.com/select2/select2/issues/3152 which was merged into https://github.com/select2/select2/issues/1908.

**Closed by kevin-brown** 2015-07-13 00:23 UTC
