### ISSUE TITLE
Select 2-drop-auto-width varies per browser

### ISSUE THREAD

**Issue by cognizen** [select2/select2#4107] opened 2016-01-21 19:41 UTC
I have experienced and issue where it seems that the drop down container is 2 pixels thinner on safari than it is on other browsers - this was causing some unexpected wrapping in some cases.  I was able to override this in the css but thought that I'd report it in case others are experiencing the same issue and it causing issues for them as well.

**Comment by kevin-brown** [comment] 2016-01-23 16:13
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by videsignz** [comment] 2016-03-10 15:02
This may be helpful.... https://github.com/select2/select2/issues/4224

**Comment by kevin-brown** [comment] 2016-03-10 15:17
I'm going to close this as a duplicate of https://github.com/select2/select2/issues/4224.

**Closed by kevin-brown** 2016-03-10 15:17 UTC
Labels: needs information
