### ISSUE TITLE
Specify default value for after the selection(s) are cleared using allowClear

### ISSUE THREAD

**Issue by Stadly** [select2/select2#4366] opened 2016-05-19 13:24 UTC
Let's say you want to let users specify the parent element for an item using a `<select>`. It is allowed for the item to not have a parent element, so the first option is `<option value="">None</option>`. To let users easily set the parent element to "None", you enable `allowClear`. For this to work, you must specify a `placeholder`. You add `data-placeholder="None"` to the `<select>`, and `allowClear` starts working. But now "None" is no longer visible in the list of options, resulting in users getting confused and thinking that the item must have a parent specified. Furthermore, "None" is now styled like a placeholder when selected. In my understanding, a placeholder should be shown when no valid value is specified, as a hint to what can be specified. But "None" is a valid value, and should therefore be shown as such. Hence, it would be really useful to support `allowClear` without requiring a `placeholder` in single-selects.

**Comment by kevin-brown** [comment] 2016-05-19 13:30
This is a duplicate of https://github.com/select2/select2/issues/3016.

**Comment by Stadly** [comment] 2016-05-20 07:14
I understand that `allowClear` was designed to reset to the placeholder. I provide a use case where it makes sense to reset to something other than the placeholder to argue that maybe changing the design might make the feature even more useful.

I suggest changing `allowClear` to specify which value the `<select>` should be reset to, instead of just specifying a boolean value. For example with `allowClear: "-1"`, clearing the `<select>` would select the `<option>` having `value="-1"`, regardless of whether this is a placeholder or not. To make it backwards compatible, the support for `allowClear: true` should be kept, resetting to the placeholder.

**Comment by kevin-brown** [comment] 2016-07-02 23:52
I've reopened this and re-focused it on allowing a custom value to be set for the `allowClear` option. It's a new feature request, so it needs to pick up the usual traction before we pull it in for a release.

**Comment by pedrofurtado** [comment] 2018-09-17 23:15
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.

**Closed by pedrofurtado** 2018-09-17 23:15 UTC
Labels: 4.x, feature request, status: help needed
