### ISSUE TITLE
Accessibility issue 

### ISSUE THREAD

**Issue by ankitgupta2k17** [select2/select2#6197] opened 2022-10-13 11:15 UTC
I see that some of the auto generated elements in select2 plugin have the aria labels. But the autogenerated labels does not have the aria label. And this leads to my project not able to acheive AA rating. Do you have any insights or ideas how we can add aria label to these auto generated elements in dom ?

**Comment by kevin-brown** [comment] 2022-10-25 01:07
Duplicate of https://github.com/select2/select2/issues/3744

**Closed as completed by kevin-brown** 2022-10-25 01:07 UTC
