### ISSUE TITLE
Too long option name goes out of the select-box

### ISSUE THREAD

**Issue by mikeliz89** [select2/select2#3030] opened 2015-02-10 12:57 UTC
In latest 4.0.0.beta-3 of select2 I noticed this: 
I have option that has 2 rows (or more) and I select it the selection goes over the whole select element. Is this something that should be fixed? Maybe add height to the class .select2-selection__rendered?
(.select2-container--default .select2-selection--single .select2-selection__rendered {
    color: #444;
    line-height: 28px;
    line-height: 28px\9;
/* no height here */
}
Or maybe javascript could add "..." at the end of the too long option text.

**Comment by kevin-brown** [comment] 2015-02-10 13:04
Duplicate of https://github.com/select2/select2/issues/2984, fixed on the latest branch.

**Closed by kevin-brown** 2015-02-10 13:04 UTC

**Comment by mikeliz89** [comment] 2015-02-10 13:43
Thank you kind sir :) Exactly what i was looking for.
