### ISSUE TITLE
Paste into select2 is not working in IE when using select2 within  bootstrap modal

### ISSUE THREAD

**Issue by mesuttalebi** [select2/select2#4237] opened 2016-03-07 09:09 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. http://jsfiddle.net/o0d3vtek/66/

## Expected behavior and actual behavior

Try to paste into select2, in IE. using ctrl+v

It works fine in other browsers, also works in IE when it is not used within a bootstrap modal.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.1.3
- Select2 version: 4.0.2.rc1

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)
http://jsfiddle.net/milz/o0d3vtek/2/

**Comment by mesuttalebi** [comment] 2016-03-09 09:45
I Can Solve this problem by adding the line below:
`$.fn.modal.Constructor.prototype.enforceFocus = function() {};`

**Comment by kevin-brown** [comment] 2016-03-10 16:47
Duplicate of https://github.com/select2/select2/issues/600#issuecomment-102857595.

**Closed by kevin-brown** 2016-03-10 16:47 UTC
