### ISSUE TITLE
Dropdown not Exact width of Select Container (Simple Solution)

### ISSUE THREAD

**Issue by videsignz** [select2/select2#4224] opened 2016-03-01 15:10 UTC
I noticed when using this that the dropdown width would always be about 1px off either wider or narrower than the select. Not really a big deal but when using 1px borders, it just looks "wrong".

This seems to happen when you have the select set to a percentage in a responsive layout.

The solution is easy. Since `.outerWidth` rounds the pixels, you can use a different means of getting the exact width.

On line 4249 I changed this...

``` js
  AttachBody.prototype._resizeDropdown = function () {
    var css = {
      width: this.$container.outerWidth(false) + 'px'
    };
```

To this....

``` js
  AttachBody.prototype._resizeDropdown = function () {
    var css = {
      width: this.$container.get(0).getBoundingClientRect().width + 'px'
    };
```

This is an easy fix for those interested :)

**Comment by Ra1ningSn0w** [comment] 2016-03-14 08:43
Thanks for working that out! Looks now perfectly smooth!

**Comment by dariospadoni** [comment] 2016-07-04 08:54
Any chance to have this fix also in the distributed source code?

**Comment by alexweissman** [comment] 2017-12-15 01:02
This is a duplicate of #1692.

**Closed by alexweissman** 2017-12-15 01:02 UTC
Labels: 4.x, confirmed bug
