### ISSUE TITLE
behavior of remove tag

### ISSUE THREAD

**Issue by rqx110** [select2/select2#4957] opened 2017-06-16 01:25 UTC
when using latest version:
in tagging mode:
![image](https://user-images.githubusercontent.com/1829209/27207919-dcf3e828-5274-11e7-85bb-df9108106ba7.png)
press backspace to remove last tag, it will look like this:
![image](https://user-images.githubusercontent.com/1829209/27207969-3861da12-5275-11e7-82ea-f2a71a4b3687.png)
it not like the previous version (v3.5.3) : when press backspace it will first select the tag, when press backspace again to remove the tag.

**Comment by cubiclesoft** [comment] 2017-07-08 08:15
I'm not a fan of the new backspace/arrow key behavior which affects all select2 multiselect (i.e. it's not just tagging mode).  I'd love to see a plugin or an option for restoring the previous behavior for removing tags via keyboard interaction.  Pressing ```backspace + tab``` now results in complete removal of the tag - which is certainly not what the user wanted to do and arrow keys do not function at all like they used to.  Until this and other relevant issues get fixed, I'm not upgrading to the 4.0 series.

**Comment by alexweissman** [comment] 2017-09-16 20:36
This is a duplicate of #3354.  Please search the open issues thoroughly before opening a new issue!

**Closed by alexweissman** 2017-09-16 20:36 UTC
