### ISSUE TITLE
Firefox opening selection problem

### ISSUE THREAD

**Issue by VD17593** [select2/select2#3151] opened 2015-03-13 17:49 UTC
When clicking on the box in order to open the selection,  in Firefox (version 36.0.1) when you just drag a little, the whole text till the end of the page is selected (which is confusing for users).
This doesn't seems to be happening in other browsers.

Tried it with the basic select2 examples.

![example](https://cloud.githubusercontent.com/assets/5879012/6644072/994c01e4-c9b1-11e4-9705-614978fd4d97.PNG)

**Comment by kevin-brown** [comment] 2015-03-13 21:31
We need to add `-ms` and `-moz` prefixes for `user-select` in [the CSS for single selects](https://github.com/select2/select2/blob/7a1791d5f36e527fbe0bd4f1bfb63f7d13d3cb62/src/scss/_single.scss#L10).

**Comment by kevin-brown** [comment] 2015-06-03 22:26
Duplicate of https://github.com/select2/select2/issues/3216.

**Closed by kevin-brown** 2015-06-03 22:26 UTC
Labels: 4.x, enhancement
