### ISSUE TITLE
Select2 4.0 unusable tags

### ISSUE THREAD

**Issue by dimka665** [select2/select2#3059] opened 2015-02-21 19:02 UTC
It's OK that behavior of Select2 4.0.0-beta in tag mode differs from Select2 3.5 behavior?
Suggestion and adding new tag works after Enter press only. Tags removes by letter-after-letter way. And so on...

It's #3053 problem. Without opening dropdown on character Tags is unusable. Double Enter to remove tag? Are you seriously? Using __Enter__ to remove tag?

Ubuntu GNOME 64bit
Google Chrome 40
Firefox 35

To reproduce: https://select2.github.io/examples.html#tags
- Click on tag input
- Type "tag1"
- Enter
- (no Enter) just type "tag2"
- Enter
- Where we are? What happens? May be one more Enter?
- Enter
- Was remove first tag. We see letters (no tag) "tag2". Tag input lost focus. We are disappointed.

**Comment by kevin-brown** [comment] 2015-02-21 21:21
Thanks for adding some more information, I wasn't able to reply when I tagged this.

This is actually a duplicate of https://github.com/select2/select2/issues/3036, and I noticed that the key handling is even more messed up for tags than it normally is.

**Closed** 2015-02-21 21:58 UTC
