### ISSUE TITLE
cant type into Input when Select is on a Jquery mobile popup

### ISSUE THREAD

**Issue by backlashs** [select2/select2#3713] opened 2015-08-27 13:34 UTC
Input isn't focus-able when select is on a  Jquery mobile popup. On current build of 4.0.0
Is there a work around/fix for this issue?

**Comment by kevin-brown** [comment] 2015-08-27 13:41
Duplicate of https://github.com/select2/select2/issues/2177.

**Closed by kevin-brown** 2015-08-27 13:41 UTC
