### ISSUE TITLE
Select2 gives focus to wrong input on small resolutions

### ISSUE THREAD

**Issue by Nbaru** [select2/select2#5515] opened 2019-05-22 11:59 UTC
There are two instances of Select2 with dropdowns on a small viewport (tablet, phone, etc.) and one dropdown is open. When a user clicks on the second input, Select2 gives focus to the first input instead of the second one.

Select2 4.0.7, tested on Chrome and Safari on Linux and MacOS 

CodePen link: https://codepen.io/anon/pen/pmpEEB

**Comment by kevin-brown** [comment] 2019-06-03 12:22
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

**Comment by Nbaru** [comment] 2019-06-20 14:00
> What steps can be used to reproduce the issue?
See CodePen:  https://codepen.io/anon/pen/pmpEEB

> What is the bug and what is the expected outcome?
There are two instances of Select2 with dropdowns on a small viewport (tablet, phone, etc.) and one dropdown is open. When a user clicks on the second input, Select2 gives focus to the first input instead of the second one.

> What browser(s) and Operating System have you tested with?
tested on Chrome and Safari on Linux and MacOS

> Does the bug happen consistently across all tested browsers?
No.

> What version of jQuery are you using? And what version of Select2?
Select2 4.0.7, jquery 3.3.1

> Are you using Select2 with other plugins?
No.

@jkuchar

**Comment by kevin-brown** [comment] 2019-08-24 03:19
Duplicate of https://github.com/select2/select2/issues/3663.

For some reason I couldn't repro it properly the first time.

**Closed by kevin-brown** 2019-08-24 03:19 UTC
Labels: 4.x, status: possible bug (unconfirmed)
