### ISSUE TITLE
Select2 Still showing options IF disabled after hitting spacebar

### ISSUE THREAD

**Issue by William-H-M** [select2/select2#5156] opened 2017-12-06 14:39 UTC
While the select is disabled it's still possible to select an option **IF** the spacebar is hit with the select being in focus.

This will happen with either single or multiple select
https://jsfiddle.net/William_/9pqh3m63/1/

**Steps to reproduce:**

1. Disable the selects
2. Set focus on select and hit SPACEBAR. 

This will open the select and allow you to select an option.

**Select2 versions used:**
From 4.05 to 4.0.6-rc.1
Version used on fiddle: 4.0.5-rc.0

**Browsers used:**
Firefox 57.0.1 (64-bit)
Chrome Version 62.0.3202.94 (64 bits)

**Operation system:** Windows 10 Build 1709

**DISCLAIMER:** I'm **NOT** the original reporter of the bug this was found at [SO question](https://stackoverflow.com/questions/47580879/select2-dropdown-on-disabled-mode)

There's a workaround provided in one of the [answers](https://stackoverflow.com/a/47593924/8538799) but for it to work it must be used the select2.full.min

In case of the link being dead answer provided here:

```
$('#select2').select2({
  containerCssClass: 'mysel-con',
  placeholder: 'Select an option'
});

$('#select2Multiple').select2({
  placeholder: 'Select an option',
});

$('#disableBtn').on('click', function() {
  $('#select2').select2('enable', false);
  $('#select2Multiple').select2('enable', false);
  $('.mysel-con').css('pointer-events', 'none');
});

$('#enableBtn').on('click', function() {
  $('#select2').select2('enable');
  $('#select2Multiple').select2('enable');
  $('.mysel-con').css('pointer-events');
});
```

Thanks to @beaver71 for the workaround.

**Comment by alexweissman** [comment] 2017-12-08 01:42
I believe this is a duplicate of #4695 (or at the very least, likely the same underlying problem).

**Closed by alexweissman** 2017-12-08 01:42 UTC
