### ISSUE TITLE
v4.03 (standard build) : is there a file which provide list of all available options ?

### ISSUE THREAD

**Issue by vhanahrni** [select2/select2#4728] opened 2016-12-21 18:16 UTC
In the old doc I see this, but I can not find out where is this file in the build.  Where is this file please ?

```javascript 
language: {
  // You can find all of the options in the language files provided in the
  // build. They all must be functions that return the string that should be
  // displayed.
  inputTooShort: function () {
    return "You must enter more characters...";
  }
}

**Comment by kevin-brown** [comment] 2017-01-06 20:30
Duplicate of https://github.com/select2/select2/issues/4687.

**Closed by kevin-brown** 2017-01-06 20:30 UTC
