### ISSUE TITLE
Prevent reload of options when opening the select input

### ISSUE THREAD

**Issue by victor0402** [select2/select2#3977] opened 2015-12-01 15:35 UTC
I'm using select2 plugin(v4) and loading the select options with ajax.
If i open the select input on the first time the data will be loaded. When I open the select again, the same data is reloaded.

There is any way to prevent this "reloading" of data? I mean, if i just open the select2 and the options were previously loaded I don't want to load again.

```
$(select_input).select2({
  ajax: {
    url: url,
    dataType: 'json',
    quietMillis: 250,
    data: function (params) {
      return {
        term: params.term,
        page: params.page,
        page_limit: default_page_size
      };
    },
    processResults: function (data) {
      return {
        results: data.data,
        pagination: {
          more: (data.page * default_page_size) < data.count
        }
      };
    },
    cache: true
  },
  escapeMarkup: function (markup) {
    return markup;
  },
  minimumInputLength: 0,
  templateResult: formatTemplateResult,
  templateSelection: formatTemplateSelection
});
```

**Comment by suyogdk** [comment] 2015-12-03 04:25
Facing same issue...

**Comment by igorsantos07** [comment] 2015-12-03 05:58
I guess this should be doable with the `ajax.cache` option, but I didn't manage to get it working here :/

**Comment by d3vkit** [comment] 2017-08-02 21:12
I worked around this by emptying the results when the user opens it:

```
$(document).on('select2:open', empty_select_filter);

...

var empty_select_filter = function(event) {
    var $select, id;

    $select = $(event.target);
    id = $select.attr('id');

    // The first item in the list is an li that says "searching", so not removing that one
    $('#select2-' + id + '-results li:not(:first)').remove();
  }
```

This might be a solution, but I have not had time to implement it:

https://stackoverflow.com/a/34079165/398696

**Comment by alexweissman** [comment] 2017-09-14 18:33
This appears to be a duplicate of #3649.

**Closed by alexweissman** 2017-09-14 18:33 UTC
