### ISSUE TITLE
Text of the Dropdown over flows if data is big size

### ISSUE THREAD

**Issue by vikasvaisha** [select2/select2#3001] opened 2015-02-04 13:23 UTC
Hi,

I was using this JS in one of my RnD project. where I found one bug in it.
Code that I have written is below.

    <select id="mySelect" class="SelectClass" style="width:200px" >
            <option value="1">Delhi</option>
            <option value="2">Mumbai</option>
            <option value="3">Chennai</option>
            <option value="4">Bangalore</option>
            <option value="5">This is bigger text in dropdown which is overflowing from dropdown</option>
     </select>
and script is as follow
     $(function () {
                $('.SelectClass').select2();
     });

when I selected last option I got the screen as below.
![capture](https://cloud.githubusercontent.com/assets/10848779/6041165/b8f8191c-ac9f-11e4-9acd-eea3b24b60d3.JPG)

Please help me with this

**Comment by kevin-brown** [comment] 2015-02-04 15:02
Duplicate of https://github.com/select2/select2/issues/2984, will be fixed in 4.0.0-rc.1.

**Closed by kevin-brown** 2015-02-04 15:02 UTC
