### ISSUE TITLE
Can't select a new tag that matches the id of an existing selection

### ISSUE THREAD

**Issue by berpcor** [select2/select2#3681] opened 2015-08-17 19:16 UTC
Hello.
I have the following:

```
$(".class").select2({
    tags: true,
    multiple: true,
    placeholder: "Text",
    allowClear: true,
    language: 'en',
})
```

Values of multiple select: ['some1', 'some2', 'some3' ].
If I choose 'some2' value, then I can't enter tag with the name of '2', if I choose 'some3' value, then I 
can't enter tag with the name of '3' (equals to order number of selected item).
However, if I enter 1 (2,3 etc) then plugin inserts 1st value of array of values and value '1'.
If I choose 2-nd and 3-rd value, for example, and enter a new tag with the value of '4', then on server side I get [2,3,5]. How can I determine that 5 is a tag and not the value?
 Is it normal?

**Comment by berpcor** [comment] 2015-08-17 19:46
![insta](https://cloud.githubusercontent.com/assets/1884568/9314454/4272b3d6-4553-11e5-89e1-29dc49478c8c.gif)

**Comment by weiyoung-zhou** [comment] 2015-08-26 07:16
+ 1

**Comment by weiyoung-zhou** [comment] 2015-08-26 07:27
@kevin-brown

**Comment by kevin-brown** [comment] 2015-08-26 13:37
I definitely tested this the other day, and I'm pretty sure I couldn't reproduce the issue. I'll test again later, but a jsbin would be useful.

**Comment by weiyoung-zhou** [comment] 2015-08-27 02:30
@kevin-brown 
thank for your response
here is my code, hope this helps
```
$('#pictures_tag_input').select2({
    tags: true,
    multiple: true,
    placeholder: "...",
    maximumSelectionSize: 12,
    minimumInputLength: 2,
    tokenSeparators: [",", " "],
    createTag: function(item) {
        return {
            id: item.term,
            text: item.term,
        };
    },
    templateResult: function(item){
        return item.name || item.text;
    },
    templateSelection: function(item){
        console.log(item);
        return item.name || item.text;
    },
    escapeMarkup: function (markup) { return markup; },
    ajax: {
        url: "/apis/search/tag",
        dataType: "json",
        global: false,
        cache: true,
        delay: 250,
        data: function(params) {
            return {  
                q: params.term
            };
        },
        processResults: function (data) {
            return {
                results: data.data.tags,
            };
        }
    }
});
```

**Comment by kevin-brown** [comment] 2015-08-27 13:41
Here's a jsbin with the shortened JS/HTML: http://jsbin.com/razorohozi/1/edit?html,js,output

I'm assuming that the issue is that you are doing something like this

1. Search for "ce"
2. Select "ce" (the second one, at the bottom) (tracking ticket for bug: https://github.com/select2/select2/issues/3566)
3. Search for "14" (the id of the "ce" option)
4. Select "14"

And you're seeing the "ce" disappear. This is because you're actually trying to select two options with the same value, which Select2 interprets as trying to unselect the value.

**Comment by weiyoung-zhou** [comment] 2015-08-27 13:53
@kevin-brown 
sorry..maybe i should create a new issue

my issue is like this:

 1. Search for "ce"
 2. Select "ce" (the first one)
 3. Search for "ce" again
 4. Select "ce" (the second one)
 5. There will be treble "ce"

**Comment by kevin-brown** [comment] 2015-08-27 13:55
> sorry..maybe i should create a new issue

No need to create a new ticket, I believe we're tracking that issue at https://github.com/select2/select2/issues/3566.

You can hit "Subscribe" under the "Notifications" section on the right to be notified about any updates.

**Comment by weiyoung-zhou** [comment] 2015-08-27 14:05
@kevin-brown 
thanks ~
anything helpful, i am willing to

**Comment by berpcor** [comment] 2015-08-27 20:49
http://jsbin.com/voturalomi/edit?html,js,output

1. Click input field.
2. Choose 'value1'.
Now I want to create new tags with integer values.
3. Enter '4', press enter. (tag with value of 4 created).
4. Enter '5', press enter. (tag with value of 5 created).
5. Now enter '3'. Press enter. Expected: creation of tag with value of '3'. We get: insertion of existing tag 'value3' its html value is '3') and insertion of a new tag with value of '3'.
6. Enter '3'. Choose '3' in dropdown, click it with left mouse button. Expected: deselect of tag with value of '3'.  We get: deselection of tag with value of '3'. Everything is fine, but...
7. Enter '3' again. Choose '3' in dropdown, click it with left mouse button. Expected: insertion of tag with value of '3'. We get: deselection of tag 'value3' (its html value is '3').

**Comment by kevin-brown** [comment] 2015-08-27 21:38
Alright, so Select2 shouldn't interpret selecting two options with the same value as unselecting it. And the strange thing is that _it actually doesn't_ when you have two different `<option>` elements originally. It's just tags which are causing issues.

So this is definitely a bug.

**Comment by srdjanmarjanovic** [comment] 2016-08-19 19:53
It has been a year since last update, but this issue is still present. I unintentionally made a duplicate of this issue which I was unaware of - it's [this one](https://github.com/select2/select2/issues/4539). It might reveal some new info how this bug could be fixed.

**Comment by alexweissman** [comment] 2017-09-25 02:36
See https://jsfiddle.net/ferronatoo/x7byvt9s/ for another example of this bug.

**Comment by alexweissman** [comment] 2017-12-16 00:34
This is actually a duplicate of #3498, so please continue the conversation there.

**Closed by alexweissman** 2017-12-16 00:34 UTC
Labels: 4.x, confirmed bug
