### ISSUE TITLE
Mutliple select with placeholder - can't close dropdown when deselecting items in IE11

### ISSUE THREAD

**Issue by tyrex1975** [select2/select2#3613] opened 2015-07-25 12:00 UTC
In the examples page: https://select2.github.io/examples.html

Scroll to 'Placeholders' examples, and select some options in the 'multiple' dropdown. Now deselect all of them. The dropdown won't close, not even when you use other examples on the page.

Seems ok in Chrome however.

**Comment by tyrex1975** [comment] 2015-07-25 12:03
PS. I checked this on the 3.5.2 examples page and it isn't a problem - only in 4.0.

**Comment by kevin-brown** [comment] 2015-07-25 22:45
This is a duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-07-25 22:45 UTC
