### ISSUE TITLE
allowClear v3 vs v4

### ISSUE THREAD

**Issue by AubreyHewes** [select2/select2#4156] opened 2016-02-05 21:35 UTC
When using `allowClear`

In v3 when _clearing_ the select2 is reset to the placeholder..
In v4 the select2 is reset to the placeholder but the options are also activated (ie popup of the options)..

https://jsbin.com/qekihi/edit?output

Is this a bug or by design?
Is there a way to force v3 behaviour on a reset (clear) in v4?

Thanks!

**Comment by kevin-brown** [comment] 2016-02-08 01:16
This is a duplicate of https://github.com/select2/select2/issues/3320.

**Closed by kevin-brown** 2016-02-08 01:16 UTC
