### ISSUE TITLE
select 2 4.0: Multi-select does not get rendered with focus after select

### ISSUE THREAD

**Issue by RabenErland** [select2/select2#3499] opened 2015-06-19 09:34 UTC
A multi select box does not get rendered with focus after a selection has been made. The multi-select span element does not get the necessary select2-container--focus css class. 

The problem can be viewed on the Select2 examples page on the multi-select in the Placeholder section.

**Comment by kquinbar** [comment] 2015-06-19 12:35
I have seen this same issue in the demo page and in our own codebase. From what I can tell though is that it only occurs if you select from the dropdown with the keyboard. If you use the mouse to select from the dropdown, then focus is retained by select2

**Comment by RabenErland** [comment] 2015-06-19 12:44
Testing on the demo page focus rendering is not applied neither when using keyboard nor when using mouse - this is true in both IE and Chrome.

**Comment by kevin-brown** [comment] 2015-06-19 22:52
This is a duplicate of https://github.com/select2/select2/issues/3332.

**Closed by kevin-brown** 2015-06-19 22:52 UTC
