### ISSUE TITLE
Select2-Tags In IE Having issue with longer text in tags.

### ISSUE THREAD

**Issue by ankita-bhatt** [select2/select2#4968] opened 2017-06-21 10:28 UTC
@swhitt @arnar  @KevM  @stephane  @cheeaun 
When i create a tag with longer text the extra cross is coming in IE.

![image](https://user-images.githubusercontent.com/28589844/27379776-4257f3ca-569a-11e7-9017-43362b3b4b96.png)

**Comment by alexweissman** [comment] 2017-09-16 20:33
Possible duplicate of #3961?

**Comment by alexweissman** [comment] 2017-12-16 00:47
This issue is not about tagging, it is about multi-select.

**Closed** 2017-12-16 00:49 UTC
Labels: browser: IE, feature: multi-select

**Comment by ankita-bhatt** [comment] 2018-01-12 06:35
@alexweissman 
Can you please reopen the issue.

As the select2 multiselect with tags:true causing the issue in internet [explorer.]

**Comment by alexweissman** [comment] 2018-01-12 19:02
We need a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example of the problem, using our [JSBin template](http://jsbin.com/hojajiwoye/edit?html,js,output).

**Comment by ankita-bhatt** [comment] 2018-01-15 03:43
@alexweissman 
Thank you for giving the guideline. 

Here i have make a select2 box 
**js code** : `$('#example1').select2({
        multiple: true,
        tokenSeparators: [',', ' '],
        tags: true
    });`

**HTML code** :  `<select id="example1" style="width: 100%;">
  </select>`


A select box allowed to enter a custom created tag.
Here, The issue is specific to a internet explorer. When i open my web site in IE and try to make a custom tag in select2.

As the text gets longer as shown in the screen shot attached above.
The cross sign of a tag is blinking continuously until the tag is created in the select box.
Custom tag creation is working well in other browsers.

@alexweissman 
I just popup a solution is if we allowed to enter a video to display problem.Might make a communication easy. I don't know that this is possible or not. But will be very helpful for the users. 👍 )

Looking forward to get the answer. You can suggest any changes requiered to understand the problem.

**Comment by mdshohelrana** [comment] 2019-04-09 08:01
Why closed this issue?, This still appears to stable version 4.05.
