### ISSUE TITLE
Select2-results with checkbox in 3.5.2

### ISSUE THREAD

**Issue by AshwiniNaidu** [select2/select2#3251] opened 2015-04-10 10:26 UTC
I am currently using select2 3.5.2 for multi-select in my project and I have a requirement to show select2 multi select dropdown like a single select dropdown, i.e.,  adding a dropdown arrow and displaying search box in the dropdown. In addition to this, I need to display checkboxes in the results list beside every value which will be checked/unchecked upon selection and preserve the selection when we open the dropdown again. Do we have anything readily available to acheive this functionality?

Also, closeOnSelect: false is not working on multiselect.

**Comment by kevin-brown** [comment] 2015-04-10 14:05
Duplicate of https://github.com/select2/select2/issues/411.

**Closed by kevin-brown** 2015-04-10 14:05 UTC
