### ISSUE TITLE
Maintain the visual position of the search box for select elements

### ISSUE THREAD

**Issue by alvarotrigo** [select2/select2#3720] opened 2015-08-28 14:45 UTC
Right now whenever you click over a select element the search box appears under it instead of on the select element itself.

**When you use a multi select box, it works as I would expect.** The search box is the select box itself and the options appear under it. 

Isn't there anyway to do the same with a single choice select ? 

[Demo online](http://jsfiddle.net/5Lkxwfz2/)

**Comment by kevin-brown** [comment] 2015-08-29 19:44
This appears to be a duplicate of https://github.com/select2/select2/issues/1345#issuecomment-124285439.

**Closed by kevin-brown** 2015-08-29 19:44 UTC
