### ISSUE TITLE
select2 inside bootstrap.modal

### ISSUE THREAD

**Issue by n0n0n0** [select2/select2#2152] opened 2014-02-28 06:50 UTC
If I placed select2 (with loading data via ajax) inside div, which after using as bootstrap.modal() then after click on select2, input, where I must type symbols for search in select2, is not active. I cant type anything in that input. On same page select2 not inside modal() div working normal. Checked in latest mozilla and chrome.

**Comment by kevin-brown** [comment] 2015-05-21 19:10
Duplicate of https://github.com/select2/select2/issues/600.

**Closed by kevin-brown** 2015-05-21 19:10 UTC

**Comment by danirzv** [comment] 2022-02-14 13:56
modal closes if you hold down mouse click on select2 and drag mouse to opened dropdown then release.
it did not fix with removing `tabindex`
please inform if there is any fix

**Comment by inferno7291** [comment] 2022-03-15 09:14
@danirzv https://github.com/select2/select2/issues/3388#issuecomment-383667214

**Comment by danirzv** [comment] 2022-03-23 09:28
> @danirzv [#3388 (comment)](https://github.com/select2/select2/issues/3388#issuecomment-383667214)

I've fixed it with using option dropdownParent as blow
`$('#FooSelect2').select2({
          dropdownParent: $('#BarModal > div > div')});`
