### ISSUE TITLE
[4.0.1] How to set the search input box's placeholder?

### ISSUE THREAD

**Issue by livem** [select2/select2#4061] opened 2016-01-05 11:17 UTC
Hi , I want to set some tips in **dropdown search input box** with input tag attributes **placeholder** , 

what look like blew:
![input-placeholder](https://cloud.githubusercontent.com/assets/2949746/12113776/0e2d6732-b3e0-11e5-92bc-45d50b4dfe18.png)

the select2 **option** placeholder is not for this.
```javascript
{ placeholder:'......' }
```

Now I do this with **select2:open** event : 
```javascript
$("select").on("select2:open", function(event) {
    $('input.select2-search__field').attr('placeholder', 'please type something...');
});
```

Is there some new option for this in the next version?

Thanks.

**Comment by kevin-brown** [comment] 2016-01-05 15:29
This is a duplicate of https://github.com/select2/select2/issues/3362.

The old option was not migrated to 4.0.0.

**Closed by kevin-brown** 2016-01-05 15:29 UTC
