### ISSUE TITLE
Readonly option

### ISSUE THREAD

**Issue by bensampaio** [select2/select2#3880] opened 2015-10-29 13:40 UTC
In my current project I need to display a readonly select2 element but it seems there is no option for that. For that reason, I would like to know how could I extend select2 so the `.select2-container` element contains the `.select2-container--readonly` when the `readonly` option is true. I tried to understand how to do that in the documentation but I couldn't find any hints... In case that is possible, could you provide some examples?

In any case I think this would be a nice feature to include on future releases.

Thank you!

**Comment by kevin-brown** [comment] 2015-10-29 23:01
This is a duplicate of https://github.com/select2/select2/issues/3387#issuecomment-104961591, support for `readonly` was removed in 4.0.0.

**Closed by kevin-brown** 2015-10-29 23:01 UTC

**Comment by bensampaio** [comment] 2015-10-30 07:57
Please read my question till the end. I'm not asking for this to be added to select2. I'm asking how can I do it by myself. Is it possible to extend select2 options? If yes, how? I saw in the documentation some references to select2 internal events but I have no idea which events are those and how could I use them, and I also have no idea if that would be the right way. I also read about the Adapters and Decorators thing but I also didn't get how can they be used to extend functionality.

**Comment by kevin-brown** [comment] 2015-10-30 16:04
The [general recommendation](http://stackoverflow.com/q/368813/359284) is to make Select2 disabled (either add the `disabled` attribute or call `.prop('disabled', true)`) and then re-enable it when the form is submitted. Or use a hidden input and don't both re-enabling it.

**Comment by transputec** [comment] 2017-01-25 15:26
to achieve this, i have created a workaround, without touching the core select2 library.
just create your own function to mimic the read only.

`function readonly_select(objs, action) {
    if (action===true)
        objs.prepend('<div class="disabled-select"></div>');
    else
        $(".disabled-select", objs).remove();
}`

with the basic styling of the disabled-select class

`.disabled-select {
   background-color:#d5d5d5;
   opacity:0.5;
   border-radius:3px;
   cursor:not-allowed;
   position:absolute;
   top:0;
   bottom:0;
   right:0;
   left:0;
}`

and then call the method as required
`readonly_select($("#bulkuseroptions .select2"), true);`
`readonly_select($("#bulkuseroptions .select2"), false);`
