### ISSUE TITLE
Is ability to paste data into a select2 for auto-tokenization broken?

### ISSUE THREAD

**Issue by blzone** [select2/select2#3937] opened 2015-11-16 23:56 UTC
I need the ability to paste data into a select2 data input field, that would be auto-tokenized into tags.  Is this ability supported?  I seem to have read on Issue #3458 that Pasting is currently not creatingTags.  Is this true, or has this since been corrected?  If it does support this, could you please provide a code sample on how to enable this?  I didn't see one posted on the example page. 

Would appreciate any support this!

Thanks.

**Comment by kevin-brown** [comment] 2015-11-17 19:23
Yes.

This is a duplicate of https://github.com/select2/select2/issues/3458.

**Closed by kevin-brown** 2015-11-17 19:23 UTC
