### ISSUE TITLE
Pass functions for options via data attributes

### ISSUE THREAD

**Issue by Karmalakas** [select2/select2#4702] opened 2016-11-29 14:56 UTC
Using v4.0.3
I have a bunch of selects on a page and only some of them needs custom escaping and I want to use data attributes to pass my custom function for these.

Eg.
```
<select data-minimum-input-length="2">...</select>
<select data-minimum-input-length="2" data-escape-markup="customEscapeMarkup">...</select>
```

You can guess what's the problem here - `escapeMarkup is not a function(…)` because it's a string.
Maybe it could check some of the options for `window[escapeMarkup]` or so?

Eg. instead of just:
```
Options.prototype.get = function (key) {
    return this.options[key];
};
```

Could it be something like this?
```

  Options.prototype.get = function (key) {
      var opt;
      switch (key) {
          case 'escapeMarkup':
          case 'sorter':
          case 'templateResult':
          // all other cases that should be functions
              opt = this.options[key];
              if (typeof opt != 'function' && typeof window[opt] == 'function') {
                  opt = window[opt];
              }

              break;

          default:
              opt = this.options[key];
      }
      
      return opt;
  };
```

This way you could pass a function name using data attribute and it would check if the function exists. I tried this version and it worked for me, but I could have missed something.

**Comment by md5** [comment] 2017-12-12 20:36
This looks like a duplicate of #2957

**Comment by alexweissman** [comment] 2017-12-13 00:35
Thanks!

**Closed by alexweissman** 2017-12-13 00:35 UTC
Labels: feature request
