### ISSUE TITLE
Text-Overflow disables the clear button event

### ISSUE THREAD

**Issue by pintobikez** [select2/select2#3418] opened 2015-05-28 09:45 UTC
Hi,

When text is bigger than its container and the text-overflow is used by the browser clicking on the X to clear the results doesn't work.
I have tried changing the z-index of the 'select2-selection__clear' element but it still doesn't work.

Any ideas?

**Comment by kevin-brown** [comment] 2015-05-29 23:35
Duplicate of https://github.com/select2/select2/issues/3306.

**Closed by kevin-brown** 2015-05-29 23:35 UTC
