### ISSUE TITLE
Incorrect position of dropdown above when displaying a message

### ISSUE THREAD

**Issue by jpontet** [select2/select2#3905] opened 2015-11-05 15:48 UTC
![screenshot_10](https://cloud.githubusercontent.com/assets/12096566/10973307/c4032eb6-83d4-11e5-8a3a-c09a567dde44.png)
Im sorry if this is a repeat of another bug- however I cant see that it is.

See this Fiddle: http://jsfiddle.net/srcjm1j9/
- Set your browser height about 768px, so that the select is at the bottom of the viewport (and thus renders the dropdown above the input)
- In the input type "opt", you will then get the Options list.
- Now backspace delete the "t" from "opt".
- You will see that the dropdown with message, which is positioned above the input, is incorrectly positioned.
- You will notice that if you keep the dropdown with message with open, resize the browser slightly and the dropdown will position correctly

After a brief investigation I have found that calling _positionDropdown (line 4129) when the "results: message" event (line 1120) fires resolves this issue.

Any ideas on a workable solution?

**Comment by jpontet** [comment] 2015-11-06 10:48
Update on the solution we are implementing to resolve this issue. After initializing, we have this code: 

    $("select").data("select2").on("results:message", function () {
        this.dropdown._positionDropdown();
    });

**Comment by lvlalbert** [comment] 2016-04-11 20:14
Thank You. Think fix fixed my problem. It seems when a user closes/opens the dropdown the offsets aren't calculated again until the page is resized or the user starts typing.

**Comment by michaud** [comment] 2016-06-03 10:46
+1 
my solution is clearing results

```
                    $(that._countrySelect).data('select2').on('open', function (e) {
                        this.results.clear();
                        this.dropdown._positionDropdown();
                    })
```

**Comment by alexweissman** [comment] 2017-09-17 01:58
I'm actually going to close this as a duplicate of #4614.  Even though this issue is older, there is more visibility with that issue and it seems to have better suggestions for fixes.

**Closed by alexweissman** 2017-09-17 01:58 UTC
Labels: 4.x, confirmed bug

**Comment by slipmatt** [comment] 2018-06-11 11:37
Try this

One thing i found is that when i removed the minimumInputLength: 1, the issue went away, leaving this here in case it helps anyone, i changed my ajax call to work of a delay rather

**Comment by Niaz-estefaie** [comment] 2021-05-26 04:11
I solved my issue like this

```
var select2Instance = $("#id_of_element").data('select2');
select2Instance.on('results:message', function(params){
    this.dropdown._resizeDropdown();
    this.dropdown._positionDropdown();
});
```
