### ISSUE TITLE
ajax page search

### ISSUE THREAD

**Issue by liyikai** [select2/select2#3368] opened 2015-05-18 08:22 UTC
when i loading a small amount of data  first page, and the scroll bar does not appear.  and then second page data not load.
![1](https://cloud.githubusercontent.com/assets/11400326/7676876/0a918a8a-fd7a-11e4-997a-9ea060c40583.jpg)

**Comment by kevin-brown** [comment] 2015-05-18 18:03
Duplicate of https://github.com/select2/select2/issues/3088.

**Closed by kevin-brown** 2015-05-18 18:03 UTC
