### ISSUE TITLE
"Screenshot" issue when updating multiselect list of items

### ISSUE THREAD

**Issue by ADAGEBF** [select2/select2#4802] opened 2017-02-20 08:48 UTC
## Steps to reproduce the issue

1. Set up a form with at least 1 multiselect select2 field and another field ;
2. Make the multiselect select2 field available items list to be updated when the other field is modified ;
3. While the form is loading datas, click to open the multiselect select2 list.

## Expected behavior and actual behavior

When I follow those steps, a sort of "screenshot" of the opened window of the multiselect select2 is copied in top left page corner.

What is even stranger is some elements of the page layout seem to hide parts of the screenshot. On WordPress for instance, the administrator top bar hides it.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows

Libraries

- Select2 version: 4.0.3

## Isolating the problem

- [x] The bug happens consistently across all tested browsers

![image](https://cloud.githubusercontent.com/assets/13054432/23117788/3ccbb870-f749-11e6-832f-e51845cf33d0.png)

**Comment by alexweissman** [comment] 2017-09-29 05:44
Could be related to #4780.

**Comment by alexweissman** [comment] 2017-12-09 18:19
Duplicate of #4033, #4780, and many others.  The solution is to use `dropdownParent`.

**Closed by alexweissman** 2017-12-09 18:19 UTC
