### ISSUE TITLE
"Loading remote data" drop-up detaches after second select

### ISSUE THREAD

**Issue by Sneakingrocky** [select2/select2#4322] opened 2016-04-21 21:55 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Here are the Steps taken as well as gif to reproduce the behavior. Reproduced in my local project as well as [The Select2 Example Page](https://select2.github.io/examples.html)

GIF/video from Select2 page: 
![select2_bug](https://cloud.githubusercontent.com/assets/3054158/14725224/45d532d8-07e0-11e6-8d62-a8468604284f.gif)

Occurs when a page is shortened or a dropdown is near the end of a page in which the dropdown reverses.

1. Type in a search
2. Select an option
3. Click the dropdown again (Menu appears at its last position)
4.) Reset by: clicking the dropdown again or scrolling

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting... 
1.) The dropdown menu to open with its normal behavior

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: "jquery": "^2.2.3",
- Select2 version: 4.02

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by Zyquivilly** [comment] 2016-04-22 18:19
+1

**Comment by hbremer** [comment] 2016-04-22 18:32
+1

**Comment by crancran** [comment] 2016-04-23 13:33
+1

**Comment by crancran** [comment] 2016-04-23 13:33
+1

**Comment by OpusDevTeam** [comment] 2016-04-24 23:40
Yep same problem here. Its odd that it re-attaches when you click on it again for the 3rd time.

**Comment by arirangz** [comment] 2016-05-12 21:59
+1

**Comment by kevin-brown** [comment] 2016-05-14 18:33
This is actually a duplicate of https://github.com/select2/select2/issues/3905.

**Closed by kevin-brown** 2016-05-14 18:33 UTC
