### ISSUE TITLE
select2:select event not triggered when using tokenSeparators feature in tag mode

### ISSUE THREAD

**Issue by ncolomer** [select2/select2#3597] opened 2015-07-21 09:44 UTC
```javascript
$(".js-keyword-tags").select2({
  tokenSeparators: [','],
  tags: true
});
```

When filling the input with string "k1,k2,k3" and hitting the enter key, only one `select2:select` event is triggered for the last added element (here "k3"). It should triggered an event for each added items (here "k1", "k2" and "k3").

Issue on select2 v4.0.0

**Comment by kevin-brown** [comment] 2015-07-21 13:35
This is a duplicate of https://github.com/select2/select2/issues/3325, which still needs to be merged.

**Closed by kevin-brown** 2015-07-21 13:35 UTC
