### ISSUE TITLE
maximumSelectionLength and up position select

### ISSUE THREAD

**Issue by sergey-kozlov** [select2/select2#4168] opened 2016-02-09 12:01 UTC
1)
$(".js-example-basic-multiple-limit").select2({
  maximumSelectionLength: 2
});
2) scroll page https://i.gyazo.com/c8cb753f36732537d3228e2e2f2f1264.png
3) select 2 item https://i.gyazo.com/2b21d2f726cfc337334b568d435f4778.png
4) try select more == bug position https://i.gyazo.com/2c83877f3ab83e37f25b52dba3af8af9.png

**Comment by kevin-brown** [comment] 2016-08-26 23:19
This is actually a duplicate of https://github.com/select2/select2/issues/3905.

**Closed by kevin-brown** 2016-08-26 23:19 UTC
Labels: 4.x, bug
