### ISSUE TITLE
maximumSelectionLength not working when some fields presented

### ISSUE THREAD

**Issue by mayashavin** [select2/select2#4900] opened 2017-05-09 08:41 UTC
Steps to re-produce:
1. Make a simple multi select drop down
2. Set maximumSelectionLength to 5 & tokenSeparators to [",", ' ']

Example:
`$("select").select2({
  data: ["a","b", "c", "d", "e"],
  multiple: true,
  maximumSelectionLength: 3,
  tokenSeparators: [",", ' '],
 	//closeOnSelect: false,
  width: '100%'
})`

Expected behavior: should limit the selection to 5.
Actual behavior: no limit.

Investigation: The dataAdapter prototypes get decorated with methods when maximumSelectionLength first, and with tokenSeperators later. Unfortunately, they both have same method name "query", and one will override the other in dataAdapter respectively.

Browsers: Google Chrome
Operating System: Windows/Mac OS

Some of the following fields will override maximumSelectionLength:
1. query
2. tokenSeperators
3. closeOnSelect (set it to false with cause maximumSelectionLength) not working.

Libraries
- jQuery version:1.11.1
- Select2 version: 4.0.3

Demo: https://jsfiddle.net/dpnminh/76shLmt2/

**Comment by alexweissman** [comment] 2017-09-25 02:08
I'm going to close this as a duplicate of #3514, but your investigation is very helpful.  So, I will copy your findings over to that issue.

**Closed by alexweissman** 2017-09-25 02:08 UTC
