### ISSUE TITLE
select2 4 focus

### ISSUE THREAD

**Issue by Hlsgs** [select2/select2#3876] opened 2015-10-28 11:08 UTC
Hello!

Do you intend to add the :focus event to select2 4?
For example, i'm working on a project with select2 and have added a tooltip to the selects who's normal behaviour would be to show on mouseover, hide on mouseleave BUT always keep visible when focused on the select. It's not possible to implement this without a :fosuc event. Even worse, using the next best thing, :open and :close results in flickering as select2 4 fires open on unselect.

**Comment by kevin-brown** [comment] 2015-10-28 17:19
This is a duplicate of https://github.com/select2/select2/issues/1908.

Yes, we plan on supporting the `focus` event in the future.

**Closed by kevin-brown** 2015-10-28 17:19 UTC
