### ISSUE TITLE
Odd highlighting of selected option when closeOnSelect is false

### ISSUE THREAD

**Issue by phazei** [select2/select2#4682] opened 2016-11-12 03:25 UTC
Go here:
http://codepen.io/stephenbe/pen/zBrzYP

Click the second option, then click the 5th option.  The selection jumps back up to the second option.  If you click around, in whatever order, it seems to jump to the closest option or top option.  It should just stay under the mouse on the item that was just clicked.

**Comment by aristidesfl** [comment] 2017-01-06 16:17
+1 this also makes the list scroll to the beginning which almost defeats the purpose.

**Comment by aristidesfl** [comment] 2017-01-06 16:18
duplicate of #4584

**Closed** 2017-01-06 19:28 UTC
