### ISSUE TITLE
Tabbing order after selecting single value

### ISSUE THREAD

**Issue by SgtOddball** [select2/select2#4384] opened 2016-05-27 10:28 UTC
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Add select2 inside div with associated label above 

``` HTML
    <div class="form-group">
        <label class="control-label" for="County">County</label>
        <select class="form-control" id="County">
            <optgroup label="England">
                <option value="Avon">Avon</option>
                <option value='Bedfordshire'>Bedfordshire</option>"
                <option value='Berkshire'>Berkshire</option>
                <!-- et al -->
            </optgroup>          
        </select>
    </div>
    <div class="form-group">
        <label class="control-label" for="Tabbing">Tabbing</label>
        <input id="Tabbing" name="Tabbing" type="text"/>
    </div>
```
1. Apply select2 

``` javascript
    $('select.county').select2();
```
1. Run page
## Expected behavior and actual behavior

Tab from input above works fine using keyboard, tab to the select box and select an item and now try to tab to an input below, the tabbing doesn't work and instead goes to the first tabbable element on the page. 

This also occurs if using tabbing index as well. Might be related to loss of focus issues but I've not found one that doesn't claim to have been fixed for 4.0.2 hence the issue.## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Edge

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version:v1.11.3
- Select2 version:v4.0.2
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by jonahgreenthal** [comment] 2016-06-03 13:27
Is there any known workaround for this?

If not, is there an estimate on when a fix will be out?

**Comment by SgtOddball** [comment] 2016-06-06 08:17
I haven't managed to come up with a way around it yet. From what I can see it's because of the select box being rendered a the bottom of the dom and then absolutely positioned. Once an option has been selected, the tab is now at the start of the document so defaults to the first available tabable element (like a menu link or some such).....

Though thats just given me an idea..... I'll write back if I can get it to behave.

**Comment by SgtOddball** [comment] 2016-06-06 08:38
Got it.... admittedly I think this should be happening automatically, but this is doing the trick for me now. 

```javascript
    $('select').on(
        'select2:select',(
            function(){
                $(this).focus();
            }
        )
    );
```

**Comment by hbb1453** [comment] 2016-06-07 21:33
Hi,
I have found when tab problem occures.

When close event fired in AttachBody class _hideDropdown() function is called, Then dropdown removed from DOM, so focus on search input become invalid and body element bocome active element.  

```
container.on('close', function () {
      self._hideDropdown();
      self._detachPositioningHandler(container);
    });
```

I think before this event execution focus should be transfered to $selection on dropdown/search.js
```
    container.on('close', function () {
      self.$search.attr('tabindex', -1);

      self.$search.val('');
      this.$selection.focus();
    });
```
I've created a pull request about it and its link -> https://github.com/select2/select2/pull/4405

**Comment by kevin-brown** [comment] 2016-06-08 23:35
I noticed this was being done on Select2 4.0.2. Can anyone confirm that the issue still exists in Select2 4.0.3?

**Comment by jonahgreenthal** [comment] 2016-06-08 23:36
Anecdotally yes; I do not currently have time to construct a jsfiddle for it.

**Comment by kevin-brown** [comment] 2016-06-08 23:42
I'm going to copy over my comment from https://github.com/select2/select2/pull/4405

> This _should_ be happening in the [base selection](https://github.com/select2/select2/blob/566c7846fbf8c3b7674346f26d0ee872c0a77629/src/js/select2/selection/base.js#L84), which applies for both the single and multiple select. So clearly this is supposed to work, it really works sometimes, but there is something going wrong.

**Comment by hbb1453** [comment] 2016-06-09 07:54
When i select an option, base selection trigger focus event on $selection element as you explained, 
selection/base
```
    container.on('close', function () {
      // When the dropdown is closed, aria-expanded="false"
      self.$selection.attr('aria-expanded', 'false');
      self.$selection.removeAttr('aria-activedescendant');
      self.$selection.removeAttr('aria-owns');

      self.$selection.focus();

      self._detachCloseHandler(container);
    });
```

When focus listener triggered, so all listeners start execution,  focus listener in dropdown/search defined as below, So $search element get focus, but after that listener execution dropdown get detached from dom. Is that piece of code is really necessary ? Because on open event $search element already got focus.
```
    container.on('focus', function () {
      if (container.isOpen()) {
        self.$search.focus();
      }
    });
```

**Comment by juancarlosfarah** [comment] 2016-06-24 21:18
I'm seeing this in 4.0.3. Snippet by @SgtOddball does the trick for selecting, but for tab and esc keys "blurring" the select I have added something like:

```javascript
$('select').on(
    'select2:close',
    function () {
        $(this).focus();
    }
);
```
Not optimal, but works for now.

**Comment by digitalfox** [comment] 2016-07-06 21:02
I confirm that the workaround works. Thank you.

**Comment by afercia** [comment] 2016-07-19 14:34
This happens for me in all the current (v4.0.3) single selection examples on the example page except for [the one with the search hidden](https://select2.github.io/examples.html#hide-search) (maybe this can give a hint).

Instead, on a local checkout of v4.0.2, the focus is always correctly moved back to the selection when the drop down closes so it seems to be a regression.

**Comment by SgtOddball** [comment] 2016-07-19 15:29
@juancarlosfarah Coolbeans - I admit I just tend to use enter, as for tabbing I had a tab order hack for a different issue that masks that tabbing didn't work either. Hadn't even thought about the esc key though (lazy of me I know). 

But yeah, the `select2:close` chained trigger makes sense in this context as a hack and at least preserves tabbing order correctly.

**Comment by evil-shrike** [comment] 2016-07-22 11:16
For me the suggested workaround doesn't work:
```
$('select').on("select2:close", function () { $(this).focus(); });
```
when I got into "select2:close" handler select2 still has focus and nothing happens. But later inside `Search.prototype.bind` we got into `container.on('focus')` handler where `$search.focus()` is invoked. `search.focus` makes blur on `$selection`. So we got into `BaseSelection.prototype._handleBlur` where a setTimeout-ed handler checks for document.activeElement which is body. As so it triggers `blur`. Focus gone.

**Comment by jeffconklin** [comment] 2016-08-31 20:19
This is a frustrating one. Just upgraded from a previous version where I had not ever have this issue. I was about to add the hack above but I am using another plugin that leverages Select2 during in-line editing. Adding this hack to their code is even more of a hack. I hope a solution for this is found and provided within the next release. Thank you for all your great work!

**Comment by ryanjbonnell** [comment] 2016-10-27 14:57
I can confirm this bug exists in select2 v4.0.3.

The suggestion by @SgtOddball temporarily works around the issue.

**Comment by ChaseGiunta** [comment] 2016-11-02 00:26
@SgtOddball Your fix works pretty great. Any chance you know and could provide an example of how to do this for _dynamically created_ select2 elements? The select2 events don't work for these unfortunately.

**Comment by SgtOddball** [comment] 2016-11-02 09:09
@ChaseGiunta - by _dynamically created_ do you mean elements drawn onto the page after the DOM has been rendered? They'll be outside of the tabbing order anyway unless you're specifically applying the tabIndex using javascript to the select element - 
`document.getElementById("select").tabIndex = 1;` 
should do the trick which so long as you've got a consistent tabbing index set up should work (where "select" is the new element and 1 should be replaced by a var with the correct tab index number in it) 

`$('select').attr('tabIndex',1)` for the jQuery version.

**Comment by jonnydowe** [comment] 2017-01-03 13:49
Workaround from @SgtOddball seems to be working well for me on v4.0.3.

**Comment by thinkwelltwd** [comment] 2017-04-25 19:54
Glad to have found this issue; workaround from @SgtOddball seems to be working well for me on v4.0.3.

**Comment by drvid** [comment] 2017-05-01 19:52
Looking forward to this fix in the next version.. Thanks!

**Comment by NeilJS** [comment] 2017-05-24 15:41
For me, I couldn't get these suggestions to work (v4.0.3). I ended up needing to implement a slight delay for some reason, to set the focus back to the original html select element that created the current select2...

```
$('select').on('select2:close', function(e) {
    var setfocus = setTimeout(function() {
        $('select[name ="'+e.currentTarget.name+'"').select2('focus');
    }, 100);
});
```

**Comment by SgtOddball** [comment] 2017-06-08 09:34
@NeilJS Which browser did you check this on? And do you know if there's anything else that could have been blocking the `setfocus()` function? Also have you tried it with a smaller delay (You'd be surprised sometimes that things can be fixed/hacked by using a delay of 0... cue 'Developers hate this one weird trick' jokes).

**Comment by NeilJS** [comment] 2017-06-08 17:04
@SgtOddball I have this issue in lastest Chrome (8 June 2017 Windows Version 59.0.3071.86 (Official Build) (64-bit)) + Firefox + IE Edge) but not IE11.
Can't think of anything else blocking setfocus(). Issue occurs on the [demo page](https://select2.github.io/examples.html) even.

Just tried the zero delay trick - it actually still solved the issue. Now I need to [read](https://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful/4575011?stw=2#4575011) [about](https://www.quora.com/What-does-setTimeout-with-a-0ms-delay-do) this trick! [TL;DR: "So using setTimeout(..., 0) will basically make your code run after the current event loop tick. ... The setTimeout function has its delay value clamped, which means the 0 is ignored and set to a minimum value (usually 4ms or 10ms depending on the browser). "]

**Comment by diegodesouza** [comment] 2017-08-14 20:20
I have tried the above "fixes" but haven't had any _luck_. How would I implement it in an Angular 4 app? I tried placing 
```$('select').on(
    'select2:close',
    function () {
        $(this).focus();
    }
);
```
 in my index.html or even creating a directive so that it would be triggered when the user interacted with the dropdown, and nothing.

**Comment by SgtOddball** [comment] 2017-08-15 07:55
@diegodesouza - So did you try adding a 'timeout 0' delay as advised above?

**Comment by diegodesouza** [comment] 2017-08-15 20:37
I haven't tried the timeout part, @SgtOddball and I suppose I'm being a bad developer for not checking whether the second suggestion works either. All i did was to go in the console and and try to trigger the $('select') and go from there.

**Comment by diegodesouza** [comment] 2017-08-22 16:09
So, I've spend some time now trying to implement this with little progress. I have added the `setTimeout` as suggested above. This allowed me to get the `select` elements. I'm also getting the these `elements` using `getElementsByTagName` and iterating through them. here's the full version. 

    ngAfterViewInit() {
      this.focusing()
    }

    focusing() {
      setTimeout(() => {
        let selects = document.getElementsByTagName('select');

        for (let i = 0; i < selects.length; i++) {
          console.log(selects[i]);
          selects[i].addEventListener('select2:close', (e) => {
            console.log('event', e);
            $(this).focus();
          })
        }
      }, 0)
    }

the issue is that the `addEventListener()` never gets called, I tried a simple `click` or `onmouseover` to test it out and nothing. The console.log for `selects[i]` is the whole element like this `<select tabindex="1" class="select2-hidden-accesscible" aria-hidden="true">_</select>` I'm not sure what I'm missing. suggestions?

**Comment by alexweissman** [comment] 2017-09-24 17:24
This has been fixed in 4.0.4.  See #4427.

**Closed by alexweissman** 2017-09-24 17:24 UTC
Labels: 4.x, confirmed bug

**Comment by teomaragakis** [comment] 2017-09-28 15:57
![Hooray!](https://lh6.googleusercontent.com/M3nkU_a_9Z1BQgpa2vjP6aoxJRq9ciOc_R7SQNKo6Dx6EDHk83tKzHkZScFTm8UdYeaZVF0SffYz63bFYVq2a4Rn3Gu4aY3si8FD7mQsTYDs8JeTa5CjqV7lQ8Yx1Bi1qkASToXb)

**Comment by aconital** [comment] 2018-06-25 17:11
I still have this issue in 4.0.6 and I fixed with adding timeout

**Comment by falko100** [comment] 2018-10-22 11:07
Any news on this issue ?

**Comment by joshkpeterson** [comment] 2018-12-11 17:09
Some of the solutions here didn't work for me, however this one did:

https://github.com/select2/select2/issues/5265#issuecomment-413933390

**Comment by ultrono** [comment] 2020-06-28 19:02
As this page ranks highly in Google, thought I'd save the sanity of some people. 😄 

I was using v4.0.3 and tab did not work as described. Updated the v4.0.13 (at the time the latest stable version before v4.1.* beta) and tab now works.
