### ISSUE TITLE
Tagging doesn't support input Spanish accent mark characters in Firefox 

### ISSUE THREAD

**Issue by gejobj** [select2/select2#4792] opened 2017-02-13 10:29 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and maybe I found a duplicate: https://github.com/select2/select2/issues/4743
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. ONLY in Firefox browsers, no matter which version, which OS
2. Enable tagging
3. Try so write a tag with á, é or ó character
4. Never get the correct result

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

As I write before, I found simmilar issue at: https://github.com/select2/select2/issues/4743

Best regards.

**Comment by ChazyTheBest** [comment] 2017-02-16 14:40
I can't reproduce this, neither on the examples pages nor in my webapp. I can write accents and ñ and it appears as I wrote it.

**Comment by ChazyTheBest** [comment] 2017-02-16 14:42
I can't reproduce this, neither in the examples pages nor in my webapp. I can write accents and ñ and it appears as I wrote it. I'm on linux 4.9 using firefox 50.1.0.

**Comment by gejobj** [comment] 2017-02-17 08:54
It seems it only reproduce on MacOS with firefox.

**Comment by gejobj** [comment] 2017-06-05 08:59
Here you have more details:
When I want to write á inside select2, it shows ´ first and then when I push 'a' it apears as á.
I think it crashes because select2 try to white a single ´ with no character.

Thanks.

**Comment by alexweissman** [comment] 2017-09-13 22:42
Closing this as a duplicate of #4743.

**Closed by alexweissman** 2017-09-13 22:42 UTC
