### ISSUE TITLE
Select2 4 multiple resolves width incorrectly while used with bootstrap 3

### ISSUE THREAD

**Issue by MrAudioGuy** [select2/select2#4032] opened 2015-12-16 20:57 UTC
Hi,
I have noticed this in conjunction with Metronic theme, though I used cdn for all plugins and they are not changed by the vendor. Here is the problem that I think isn't vendor specific:
While I tried to match styling of select2 to the responsiveness of bootstrap 3 used in Metronic, I found the solution is using `width` option. 
The width option works fine in single selection completely and also multiple selection, but to some degree. No matter what I set the value of width in options, in the multiple selection `input.select2-search__field` will have an explicit `style="100px"  attribute. I am sure it is computed while `$(elem).select2(...)` is called. 
I simply fixed this with an `!important` tag in a CSS for 
```css
li.select2-search, li.select2-search--inline {
   width: 100%; !important;
}
```
and JS
```javascript
jQuery('.select2-search__field').removeAttr('style');
```
but thought it'll be good to report.

Thanks for the awesome select2!

**Comment by MrAudioGuy** [comment] 2015-12-16 22:07
Well...
The above trick just make it look ok when there's nothing selected... when selected, the selected li and clear span (little x) is moved a line up and hidden behind other elements!

**Comment by kevin-brown** [comment] 2015-12-21 01:24
This is a duplicate of https://github.com/select2/select2/issues/3278.

**Closed by kevin-brown** 2015-12-21 01:24 UTC
