### ISSUE TITLE
Modal windows and scroll

### ISSUE THREAD

**Issue by curious-jim** [select2/select2#4189] opened 2016-02-14 15:07 UTC
I'm using Select2 with modal window (bootstrap modal) and sidebar (custom js script, simply toggles visibility of fixed block)
sidebar is togglable, it's not visible by default, and accessible only by pressing the button

both of them (modal and sidebar) are higher, than the window height,
so they have scrollbar
but if I will use Select2, scroll is not working anymore

I can't any styles, which blocks the scroll, or any option in documentation, what may help solve this issue
I tried to google the issue, but all possible solutions are not fixing the problem

**Comment by kevin-brown** [comment] 2016-02-16 15:34
Duplicate of https://github.com/select2/select2/issues/3125, it should be fixed in 4.0.2-rc.1.

**Closed by kevin-brown** 2016-02-16 15:34 UTC
