### ISSUE TITLE
Autofocus (with scroll) on opened select on close event

### ISSUE THREAD

**Issue by AnatolyAstapov** [select2/select2#5605] opened 2019-08-13 15:32 UTC
See gif as bug example .
[![Image from Gyazo](https://i.gyazo.com/4b6d02e3b0f2a97040dc51efe978b988.gif)](https://gyazo.com/4b6d02e3b0f2a97040dc51efe978b988)
https://i.gyazo.com/4b6d02e3b0f2a97040dc51efe978b988.gif

Select2 4.0.7
Chome

if selector is opened, and scroll down to other form element, and click mouse on anywhere ,  
Opened selector then closed and focused on closed selector. with scroll to closed selector...

but for my project i finded solution:
in file /node_modules/select2/dist/js/select2.full.js
line : ~1480

remove section 

---
window.setTimeout(function () {
        self.$selection.focus();
      }, 0);
---
![image](https://user-images.githubusercontent.com/12308843/62954819-b522b300-bdf8-11e9-9f8f-7666fb78d1e9.png)

have a nice day.=)

**Comment by kevin-brown** [comment] 2019-08-14 11:36
Duplicate of https://github.com/select2/select2/issues/3663.

**Closed by kevin-brown** 2019-08-14 11:36 UTC
Labels: 4.x
