### ISSUE TITLE
Limiting the number of selections does not work using CTRL

### ISSUE THREAD

**Issue by FredericoSFerreira** [select2/select2#3860] opened 2015-10-22 10:44 UTC
The maximum number of selection does not work when you use the CTRL key to perform the multiple selection

**Comment by Decagon** [comment] 2015-11-12 13:51
:+1:

What browser/OS have you tested this bug with? Since this is an older bug, does the newest version of select (4.0.1-rc.1 at the time of this writing) work?

**Comment by kevin-brown** [comment] 2015-11-12 19:16
You can reproduce this in 4.0.1-rc.1 by looking at the examples page.

https://select2.github.io/examples.html#multiple-max

This is because the maximum selection limit is enforced whenever the dropdown is opened, instead of when the selection is made.

**Comment by urkle** [comment] 2018-03-05 22:52
This issue still happens in the latest 4.x release (new URL to page showing the issue https://select2.org/selections#limiting-the-number-of-selections )

**Comment by urkle** [comment] 2019-03-19 21:31
This is still occurring in the latest code.

**Comment by kevin-brown** [comment] 2019-05-14 22:42
This is a duplicate of https://github.com/select2/select2/issues/3514.

**Closed by kevin-brown** 2019-05-14 22:42 UTC
Labels: 4.x, confirmed bug
