### ISSUE TITLE
Hitting a key from the tokenSeparators array without typing anything errors

### ISSUE THREAD

**Issue by twe4ked** [select2/select2#3849] opened 2015-10-19 12:59 UTC
Error occurs on the [examples page](https://select2.github.io/examples.html) with the following code:

```
$(".js-example-tokenizer").select2({
  tags: true,
  tokenSeparators: [',', ' ']
})
```

Type a ` ` (space) or `,` (comma) to trigger the error.

```
[Error] TypeError: null is not an object (evaluating 'data.selected = true')
```

Version 4.0

**Comment by kevin-brown** [comment] 2015-10-19 14:07
This is a duplicate of https://github.com/select2/select2/issues/3593, which will be fixed in 4.0.1.

**Closed by kevin-brown** 2015-10-19 14:07 UTC
