### ISSUE TITLE
Events not properly detached. Its eating lot of memory. I need the solution.

### ISSUE THREAD

**Issue by elakkuvan** [select2/select2#4726] opened 2016-12-21 08:55 UTC
#Events not properly detached. Its eating lot of memory. I need the solution.Please check this

**Comment by elakkuvan** [comment] 2016-12-22 06:28
Any update

**Comment by kevin-brown** [comment] 2017-01-05 02:15
Duplicate of https://github.com/select2/select2/issues/4725.

**Closed by kevin-brown** 2017-01-05 02:15 UTC

**Comment by Dshoe** [comment] 2018-07-18 20:38
@kevin-brown Did you ever find a solution or root cause the problem?
