### ISSUE TITLE
Select2 4.0.0 on mobile chrome browser closes after opening 

### ISSUE THREAD

**Issue by frankyxcs** [select2/select2#3489] opened 2015-06-18 02:45 UTC
I am using a purchased php script with select2 4.0.0 and it has a city and category dropdown. So far everything is working fine but especially on mobile android phones with chrome browser the drop down box with auto complete closes immediately after opening and i´m not able to select a city or input a name.

I have this java code

 $('.chosen-select').select2({
            theme: "classic"
So far this problem seems to appear only in chrome on android mobile phones. On iphone chrome it works ..

maybe anyone here has a solution for me ??

thanx in advance

**Comment by kevin-brown** [comment] 2015-06-18 03:10
Does this issue happen on the examples page?

https://select2.github.io/examples.html

You can test it out on any of the default themed examples, and there's one with the classic theme at the bottom.

If it does still happen, what Android and Chrome version are you using?

**Comment by frankyxcs** [comment] 2015-06-18 03:18
Hi
yes the problem does still exists ! I´m using android 4.1.2 or 5.1.1 but it does not matter. Chrome is the newest version on android 43.0.2357.93. On selct2 3.5.2 it seems to work fine so far ( i did change the files for testing)

**Comment by kevin-brown** [comment] 2015-06-18 13:58
Unfortunately I can't reproduce the issue here, but that doesn't necessarily mean that the issue does not exist.

> Android 5.1
> Chrome 43.0.2357.93

Historically Select2 has had an issue with this because browsers fire off `resize` and `scroll` events when the dropdown is opened and the keyboard opens up, but Select2 _should be_ catching (and ignoring) those.

**Comment by frankyxcs** [comment] 2015-06-18 14:04
hi kevin 
they have a demo site here http://whiz.dbcinfotech.net 
. You can test it with your mobile. if you test city and category dropdown you should the the behavior that the dropdown closes

**Comment by frankyxcs** [comment] 2015-06-18 14:59
hi i think i have found the bug ..they invoked 2times select2 so i have commented out it. It seems that in the resize function the select2 code does not belong there. so now it seems to work fine. But thanx for your help anyways !! I Think it was false to use the code 2times !? 


<script type="text/javascript">

    jQuery(window).resize(function(){
   
   /*
   
        $('.chosen-select').select2({
            theme: "classic"
        });
		*/
    });

    $(document).ready(function(){
        $('.chosen-select').select2({
            theme: "classic"
        });

**Comment by kevin-brown** [comment] 2015-06-18 15:04
The issue was that browsers will trigger the `resize` event on mobile devices when the keyboard is opened, and re-initializing Select2 will close the dropdown.

Closing this off as it's not an issue with Select2.

**Closed by kevin-brown** 2015-06-18 15:04 UTC
Labels: 4.x, needs information

**Comment by shimu5** [comment] 2016-01-21 07:52
I am using Select2 Version: 3.5.2. it shows problem on android 4.4.2 mobile default browser.
In default browser select2 closes immediately after opening and can't able to select a particular option. 
In mobile Chrome browser can open select2 but when click on select also open key board simultaneously. I have applied in whole website already. So far i can't change the version of select2. 
$("#FixedDeposit_institute_type").select2({
            width: "100%",
            minimumResultsForSearch: -1
    }).on("select2-close", function(e) {
        Rates();                         
    });

**Comment by andresmartindoria** [comment] 2017-06-02 14:33
@frankyxcs Can you share the solution code as the problem? thank you very much

**Comment by frankyxcs** [comment] 2017-06-02 15:15
Hi my post was from 2015 :)  But as you can see the problem did not belong to select2 ! It was double in in my code and i have removed it

**Comment by jaingrv24** [comment] 2019-05-20 11:02
wrote the below code script after spenting lots of hours:

            var ele = $('#control_name');

            // gaurav jain: quick fix for select2 not closing on mobile devices
            ele.on("select2:close", function () {
                setTimeout(function () {
                    $('.select2-container-active').removeClass('select2-container-active');
                    $(':focus').blur();
                }, 1);
            });

            // gaurav jain: quick fix for select2 not opening on mobile devices if with textbox
            ele.on('select2:open', function () {
                $('.select2-search__field').prop('focus', false);
            });

**Comment by vitor5g** [comment] 2024-09-12 14:57
Hello, good afternoon, I have the same problem, how was it fixed?

**Comment by vitor5g** [comment] 2024-09-12 14:57
> Does this issue happen on the examples page?
> 
> https://select2.github.io/examples.html
> 
> You can test it out on any of the default themed examples, and there's one with the classic theme at the bottom.
> 
> If it does still happen, what Android and Chrome version are you using?

Hello, good afternoon, I have the same problem, how was it fixed?
