### ISSUE TITLE
v4.0.3 (standard build) : is there an option to keep search results ?

### ISSUE THREAD

**Issue by vhanahrni** [select2/select2#4727] opened 2016-12-21 14:50 UTC
I see many posts, issues, pull requests about this. What about this in last build ? is there an option to keep search results ? Actually I ended up with below code..

```javascript
  var currentQuery;
   $('#selectid').on('select2:open', function() {

     if (currentQuery) {

        $('.select2-search__field').val(currentQuery);

        //$('.select2-search__field').trigger('event');
        // I try many event ( keyup, keydown, keypress, paste ..)  none of them send ajax request ..

        $('.select2-results__option.loading-results').css({ display: 'none'});
        // hide the loading message

        $('.select2-search__field').trigger('query', {term:ahah});
        // willingly ReferenceError Can't find variable: ahah
     }

    }).on('select2:closing', function() {
      currentQuery = $('.select2-search__field').prop('value');
    });
```

**Comment by kevin-brown** [comment] 2016-12-21 18:42
Duplicate of https://github.com/select2/select2/issues/3949.

**Closed by kevin-brown** 2016-12-21 18:42 UTC
