### ISSUE TITLE
4.0.0 BUG

### ISSUE THREAD

**Issue by c941010623** [select2/select2#2937] opened 2015-01-18 12:10 UTC
in bootstrap 3.X.X please fix

Because use in modal will not show

and in ipad(modal) and android(modal) all not work

**Comment by flip111** [comment] 2015-01-18 14:16
@c941010623 not really the most descriptive error message ever. I would just close this issue if it was my repo.

**Comment by kevin-brown** [comment] 2015-01-18 15:21
I'm assuming this is a duplicate of https://github.com/select2/select2/issues/2936 given that you mentioned "android" and "iphone".

**Closed by kevin-brown** 2015-01-18 15:21 UTC

**Comment by c941010623** [comment] 2015-01-20 13:10
in pc it will not work

use in bootstrap 3.3.x and it in the modal('show')

can't select anything
