### ISSUE TITLE
Add a 'select all' button

### ISSUE THREAD

**Issue by Loadmaster** [select2/select2#4531] opened 2016-08-12 22:39 UTC
## Enhancement request

It would be nice to have a 'Select All' button (or icon) within the select text area, similar to, and as a complement to, the 'Remove All' '&times;' icon. Clicking on this would cause all items in the (currently loaded) selection list to be selected. The 'All' text (or icon) would be located next to the 'Remove' icon within the drop-down selection list area.

(I have coded my own 'Select All' button, but I had to add it *outside* the Select2 drop-down area, since I do not want to have to maintain my own local modified version of Select2.js. This is a less than ideal solution.)

This feature could be controlled by (yet another) configuration option:
```
   var opts = { ..., selectAllText: "All", ... };
```
Or this could even be a app-provided config function that returns an HTML element (similar to the `templateResult()` config function), to which an 'onclick' event handler would be attached.

This could be made to be an optional feature, such that if the `selectAllText` option was null or undefined, the 'All' button/text would not be shown at all.

Upon receiving a `click` event, the handler selects all of the child `options` of the Select2 element, then triggers a `change` event:
```
// Select all the options 
var options = selectElem.options;    // selectElem is the <select> element
for (var i = 0;  i < options.length;  i++)
	options[i].selected = true;

// Inform Select2
select2Elem.trigger("change");       // select2Elem is the Select2 element
```
This code probably needs to trigger a `change` event for each option as it is selected, similar to the way the `Remove' button works today.

## Environment

- Select2 version: 4.0.2

**Comment by kevin-brown** [comment] 2016-08-26 23:25
This is a duplicate of https://github.com/select2/select2/issues/195#issuecomment-140241752.

**Closed by kevin-brown** 2016-08-26 23:25 UTC
