### ISSUE TITLE
prevent scrolling to the first selected element in multiselect

### ISSUE THREAD

**Issue by delphir-com** [select2/select2#4565] opened 2016-09-05 13:00 UTC
Seems that there is a bug in this action as every click on other that the fist selected element in the list (when auto-close is disabled) scrolls list up to the first selected element again and again.

Possible Solution:
self.highlightFirstItem() must be removed or ignored in case when there are more than 1 item selected.

```
    container.on('select', function () {
      if (!container.isOpen()) {
        return;
      }

      self.setClasses();
      self.highlightFirstItem();
    });
```

**Comment by jgbishop** [comment] 2016-09-05 13:05
This may be a duplicate of #4417.

**Closed** 2016-09-05 13:31 UTC
