### ISSUE TITLE
"Selective" download?

### ISSUE THREAD

**Issue by SRGOM** [select2/select2#3784] opened 2015-09-20 06:42 UTC
I realize that this is really hard to do, and am not counting on this to ever happen but throwing it out there anyway- Is it possible to have a downloader that allows one to selectively download what features one needs. For example, if someone wants to only use pre-populated select and multi-select boxes with no plugins. Would that reduce the size of library?

**Comment by kevin-brown** [comment] 2015-09-20 08:42
This is a duplicate of https://github.com/select2/select2/issues/1930#issuecomment-73377586.

**Closed by kevin-brown** 2015-09-20 08:42 UTC
