### ISSUE TITLE
Feature : Disable Multiselect Auto Sorting. Keep order as selected

### ISSUE THREAD

**Issue by BackuPs** [select2/select2#4336] opened 2016-05-02 08:37 UTC
Hi

Is it possible to have the multiselect keep the order of how the elements are selected and not get the order of how they are originally in the elements options list?

There should really be a setting or option for this if you want the multiselected elements to follow the order of the available option list or to keep the order as they are selected.

Why not add a data-select2order="true"  and if set to true keep the elements listed in the multi select search result as selected.

Also how to add back the original selected order once select2order="true" and you get back to the setting and you want to add another element.   We need another data field for that data-select2orderinit='{"optionvalue6","optionvalue2",optionvalue4"}'

Since the input hidden has been deprecated this is a big flaw in this script. What was so easy to accomplish is now so hard to achieve.

I cant update to version 4 because of this issue. A big bummer !

Looking forward to hear from you.
Best regards,
BackuPs

**Comment by kevin-brown** [comment] 2016-05-02 14:16
This is a duplicate of https://github.com/select2/select2/issues/3106.

**Closed by kevin-brown** 2016-05-02 14:16 UTC
