### ISSUE TITLE
Bug Dropdown json data assessibility (braille)

### ISSUE THREAD

**Issue by Priif** [select2/select2#6099] opened 2021-09-21 08:44 UTC
Hello,

When I use Select2 with data retrieved with Json, my dropdown list is not accessible anymore. My braille viewer does not recognize the content of the list.

I tested with this dropdown list:

![image](https://zupimages.net/up/21/38/30r7.png)

Thanks

**Comment by kevin-brown** [comment] 2021-09-21 22:51
Thanks for bringing this to our attention. Unfortunately this one is going to be very hard for us to test (because we lack the tools) but if you are able to go back and forth with us, we can try to get it resolved.

Do you know if this only affects AJAX results or does it affect all Select2-backed dropdowns within our examples?

**Comment by Priif** [comment] 2021-09-22 05:49
I tried on all the examples of the Select2 website, but only the ajax example does not work.

All the other dropdown return a value in the braille viewer.

![image](https://zupimages.net/up/21/38/2hkh.png)

Thanks for your help

**Comment by kevin-brown** [comment] 2021-12-04 00:52
I just realized this is a duplicate of https://github.com/select2/select2/issues/6007, the issue is that the title is not being set properly which is making the option appear blank to screen readers when using AJAX.

**Closed as completed by kevin-brown** 2021-12-04 00:52 UTC
