### ISSUE TITLE
Enter the same text as the option value, tags are created both.

### ISSUE THREAD

**Issue by ppoyang** [select2/select2#5861] opened 2020-05-18 00:25 UTC
Hello,

When I enter at tags input what is not in the text of the option but it is in the value, the two are entered together.

Here is an example.
[https://jsfiddle.net/zg3esxur/](url)
![화면-기록-2020-05-18-오전-9 23 50](https://user-images.githubusercontent.com/40880561/82164033-6e16a080-98e9-11ea-987a-4d89d3155af6.gif)

How do I create tags only with text?

**Comment by kevin-brown** [comment] 2020-05-20 00:17
Marking as a duplicate of https://github.com/select2/select2/issues/5861.

**Closed by kevin-brown** 2020-05-20 00:17 UTC

**Comment by ppoyang** [comment] 2020-05-20 06:46
I solved this problem as a temporary measure.
I am not sure if this will cause other problems.

```
Tags.prototype.createTag = function (decorated, params) {
    var term = $.trim(params.term);
    if (term === '') {
      return null;
    }
    return {
      id: term ,
      text: term
    }; 
    
  };
```
to 

```
Tags.prototype.createTag = function (decorated, params) {
    var term = $.trim(params.term);
    if (term === '') {
      return null;
    }
    return {
      id: term + Math.floor(Math.random()*100000).toString(), // Just add something so that it doesn't overlap with the existing value
      text: term
    }; 
    
  };
```
