### ISSUE TITLE
Title attribute is set even though it wasn't present in the original <select>

### ISSUE THREAD

**Issue by lopis** [select2/select2#3336] opened 2015-05-11 09:45 UTC
In my case, I'm using bootstrap's tooltip in every element with a title attribute. I found out that select2 adds a title to itself, seemingly using the default value of the original `<select>`. In consequence, all my select2s elements now unexpectedly popup a bootstrap tooltip on focus. I've been trying to figure out a way around this, but I might make a pull request with an option "title: false" in the plugin edit.

**Comment by kevin-brown** [comment] 2015-05-11 16:44
There is at least two other duplicate tickets for this, I'll point you towards them when I find it.

**Comment by lopis** [comment] 2015-05-11 18:10
Thanks, I searched but couldn't find any.

**Comment by kevin-brown** [comment] 2015-05-11 18:57
Duplicate of https://github.com/select2/select2/issues/3158.

**Closed by kevin-brown** 2015-05-11 18:57 UTC
