### ISSUE TITLE
Position issues with bootstrap parent

### ISSUE THREAD

**Issue by trasher** [select2/select2#4022] opened 2015-12-15 09:38 UTC
Hello,

I got some issues with select2 position  in a bootstrap form. It looks to me that their float position are not properly handled.

It seems that a fix in 4.0.1 cause this issue; I was able to resolve it changing the following:
```diff
--- select2.js.orig	2015-12-15 10:22:14.369524789 +0100
+++ select2.js	2015-12-15 10:21:58.634722053 +0100
@@ -4201,7 +4201,9 @@
     };
 
     // Fix positioning with static parents
-    if (this.$dropdownParent[0].style.position !== 'static') {
+    if (this.$dropdownParent[0].style.position !== 'static'
+        && this.$dropdownParent[0].style.float == 'none'
+       ) {
       var parentOffset = this.$dropdownParent.offset();
 
       css.top -= parentOffset.top;
```

I wonder if this is an issue in select2, or an issue on our side...

**Comment by kevin-brown** [comment] 2015-12-19 19:49
This is a duplicate of https://github.com/select2/select2/issues/3970, it's a positioning problem with Select2.

**Closed by kevin-brown** 2015-12-19 19:49 UTC
