### ISSUE TITLE
I found a small bug about the limit the max number of selected

### ISSUE THREAD

**Issue by DHclly** [select2/select2#5010] opened 2017-08-14 02:45 UTC
url:[http://select2.github.io/examples.html#multiple-max](http://select2.github.io/examples.html#multiple-max)

in example , the prop `maximumSelectionLength` is 2 , but when I press 'ctrl' key then select item, I can select more than 2 item.

**Comment by alexweissman** [comment] 2017-08-31 19:23
This does seem to be the case:

![screen shot 2017-08-31 at 3 23 42 pm](https://user-images.githubusercontent.com/5004534/29941384-667b7364-8e60-11e7-88c0-8d092c69af64.png)

**Comment by alexweissman** [comment] 2017-09-25 02:03
Closing this, as it is a duplicate of #4827.

**Closed by alexweissman** 2017-09-25 02:03 UTC
Labels: confirmed bug
