### ISSUE TITLE
Website: CSS link examples lack 'rel="stylesheet"' attributes.

### ISSUE THREAD

**Issue by JerseyMilker** [select2/select2#3032] opened 2015-02-10 23:34 UTC
CSS link examples on website lack 'rel="stylesheet"' attributes...
http://puu.sh/fKDRv/e9d9fbbdc4.png
http://puu.sh/fKEbL/177cf0d1a8.png

**Comment by kevin-brown** [comment] 2015-02-10 23:58
Thanks to everyone who caught this! It's a duplicate of https://github.com/select2/select2/issues/3020, which has already been fixed in the next docs build.

**Closed by kevin-brown** 2015-02-10 23:58 UTC

**Comment by JerseyMilker** [comment] 2015-02-11 04:06
Ahh I searched for an open issue, maybe you already closed it.  Thanks though!
