### ISSUE TITLE
Select2 freeze the browser when there are too many select boxes

### ISSUE THREAD

**Issue by rakesha3** [select2/select2#5063] opened 2017-10-04 10:14 UTC
In a form I have thousands of records to update and in each record I have a select box(each select box have 20-30 options) so there are total thousand of select boxes. When I apply Select2 on these all select boxes using same class Its freeze my browser. If I don't use select2 then it works fine.

To reproduce this issue:-
1. create multiple single select boxes (may be 4000) and you can keep 2-3 options in each select box
2. now run this in browser(It will work fine without freezing the browser)
3. Now apply select2 on all select box(It will freeze the browser)
Thanks

**Comment by alexweissman** [comment] 2017-10-04 19:21
This issue has been raised many times before.  Select2 requires some overhead to render, so this will add up when when you have thousands of them on a single page.  This would likely be the case with _any_ jQuery plugin, not just Select2.

If you have thousands of records/rows, you should consider using AJAX+pagination to only render a small number of records (with their dropdowns) at a time.  If you're loading these rows in a table, I'd recommend Mottie's [tablesorter plugin](https://mottie.github.io/tablesorter/docs/) which supports paginated AJAX data sources.

I'm not sure which server-side technology you're using, but if you're using PHP, my UserFrosting framework has some nice components for generating paginated result sets and has a [frontend integration with Tablesorter](https://learn.userfrosting.com/client-side-code/components/tables).

**Comment by rakesha3** [comment] 2017-10-05 08:12
For this I have init select2 on mouse over
<$(document).on('mouseover', 'select', function() { 
    $(this).select2().select2('open');
});>

**Comment by alexweissman** [comment] 2017-11-06 02:21
Closing as a duplicate of #4407.

**Closed by alexweissman** 2017-11-06 02:21 UTC
Labels: performance
