### ISSUE TITLE
Data not being returned in 4.0 |  Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by apank** [select2/select2#3119] opened 2015-03-08 11:13 UTC
I'm trying to retrieve the data by using this code:

jQuery("#element").on('change', function(e) {
	    // Access to full data
	    console.log(jQuery(this).select2('data'));
	});

but it just gives me this-
 Uncaught TypeError: object is not a function

is there another way to retrieve the data?

**Comment by kevin-brown** [comment] 2015-03-08 11:59
Duplicate of https://github.com/select2/select2/issues/3104.

There is not a way to retrieve the data right now.

**Closed by kevin-brown** 2015-03-08 11:59 UTC
