### ISSUE TITLE
Dropdown gets cut off when scrolling with a fixed parent.

### ISSUE THREAD

**Issue by webspecnick** [select2/select2#3672] opened 2015-08-12 17:09 UTC
This seems to be related to a lot of fixed position and scrolling problems, but the end result seems different than the others. As demonstrated in <a href="http://codepen.io/nickhoobin/pen/QbzYdb">this pen</a> the dropdown will  get cut off when scrolling back up after the dropdown's parent is moved with transform.

Steps to Reproduce:
1. Visit this pen: http://codepen.io/nickhoobin/pen/QbzYdb
2. Open the dropdown
3. Move the mouse **outside** the dropdown, into the body
4. Scroll the body
5. The header will get transformed and move off of the page
6. While keeping the dropdown open scroll the body up until it is back at the top
7. The header will move back into place
8. The dropdown does not reposition itself
9. Scrolling the dropdown back up keeps the first option cut off
![select-2-dropdown](https://cloud.githubusercontent.com/assets/6545164/9230809/16af3958-40ea-11e5-82bd-1e216d9709b0.PNG)

It might not seem like much,but if the dropdown is heavily themed and templated, a lot of information can get cut off.

Chrome seems to be the browser that is affected. Edge, Firefox, IE 11 seem to handle the transform a lot more gracefully.

**Comment by Lindsayanng** [comment] 2015-08-12 18:30
I believe this issue stems from a collection of issues regarding the placement and positioning of the select-container element. The select-container is appended to the bottom of the page in the <body> and is given a position:absolute and it calculates where it's supposed to be based on where the input field is. The problem is that the absolute positioning is calculated based off of the <body> position and since your input's container is set to fixed, when you scroll down, the top of <body> disappears and the select-container tries to follow it's position in relation to that. 

From what I have been [told] (https://github.com/select2/select2/issues/3639) there is a way to define the container of the select2-container element or define it's parent. 

If you can tell it to exist inside of your <header> element or make a wrapper div for it, the calculations for positioning would work just fine. 

[The docs say it can take a jquery object or a DOM element] (https://select2.github.io/options.html#dropdown) . There are no examples for this code and I have not tested it yet. **If you wouldn't mind posting your results if you get this working, that would be great**. 

This could probably be achieved with a CSS override as well however it seems that the <span> that contains the drop down results does not have any unique identifier that allows you to target that container over the main one that contains the input field. Maybe that should be a suggestion for a patch. Not sure.

**Comment by webspecnick** [comment] 2015-08-13 12:29
Adding a dropdownParent makes it display the same detached/wrong positioning that other non-static parents are having.

It looks like half of this issue, the body scrolling when the dropdown reaches the end of this options, is due to not having jquery.mousewheel. I updated my pen to use the full version of Select2.

The cutoff problem persists if the user moves their mouse outside of the dropdown and scrolls the body though. I'll update the initial issue to reflect this.

The overall behavior is less of an issue with jquery.mousewheel now that the body doesn't scroll when the dropdown reaches the end of its options.

**Comment by kevin-brown** [comment] 2015-08-13 16:08
This _may_ be a duplicate of https://github.com/select2/select2/issues/3303, which is the positioning issues when using `dropdownParent`.

Though I suppose there is something extra here, as Select2 [should reposition itself](https://github.com/select2/select2/issues/2961) on the `scroll` event and it [should prevent scrolling of inner modal containers](https://github.com/select2/select2/issues/2975).

**Closed** 2015-11-27 22:58 UTC
