### ISSUE TITLE
Delete current list and reinsert new list from event

### ISSUE THREAD

**Issue by leo95works** [select2/select2#5787] opened 2020-03-03 15:54 UTC
I am using [Select2][1], I would appreciate it in advance if you could help me with the following problem. I have a table where I add elements of type ```<select>``` using a button.

[![enter image description here][2]][2]

I am starting the Select2 plugin as follows:
```
<script>
    $(document).ready(function() {
        $('select[name^="table"]').select();
    });
```

After that .. I want to delegate an event so that every time I create a new ```<select>```, I add a new array to that element with the data I want to list.

I have tried it as follows:
```
$(document).on('select2:opening', 'select[name^="table"]', function(e) {
  var data = [
    {
        id: 0,
        text: 'enhancement'
    },
    {
        id: 1,
        text: 'bug'
    },
    {
        id: 2,
        text: 'duplicate'
    },
    {
        id: 3,
        text: 'invalid'
    },
    {
        id: 4,
        text: 'wontfix'
    }
  ];

  $(this).empty().select2({
    data: data
  })
});
```

When I verify, in the browser console I get the following error:
```
TypeError: this.dataAdapter is null
```
I read in the following URLs but I can't find any solution in any of them for my mistake:

https://stackoverflow.com/questions/41872930/jquery-select2-typeerror-b-dataadapter-is-null[3]

https://github.com/select2/select2/issues/4933[4]

Please I would appreciate in advance if someone could help me with this problem.

  [1]: https://select2.org/
  [2]: https://i.stack.imgur.com/k5vDj.png
  [3]: https://stackoverflow.com/questions/41872930/jquery-select2-typeerror-b-dataadapter-is-null
  [4]: https://github.com/select2/select2/issues/4933

**Comment by kevin-brown** [comment] 2020-03-14 17:48
This is a duplicate of https://github.com/select2/select2/issues/5743#issuecomment-575415815. I would recommend re-initializing Select2 outside of a Select2-triggered event cycle.

**Closed by kevin-brown** 2020-03-14 17:49 UTC
