### ISSUE TITLE
Search.prototype.resizeSearch() does not set width of input wide enough for Chinese characters.

### ISSUE THREAD

**Issue by fengdh** [select2/select2#4376] opened 2016-05-24 03:02 UTC
## Steps to reproduce the issue
1. Use Select2 to initialize a SELECT element supporting multiple values.
2. First select one value.
3. Then turn IME "on", enter some Chinese/Japanese character in search INPUT field.
4. Part of Chinese/Japanese character will be cut off.
## Environment

Browsers
- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer

Operating System
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.2.2
- Select2 version: 4.0.2
## Isolating the problem

```
  Search.prototype.resizeSearch = function () {
    this.$search.css('width', '25px');

    var width = '';

    if (this.$search.attr('placeholder') !== '') {
      width = this.$selection.find('.select2-selection__rendered').innerWidth();
    } else {
      var minimumWidth = this.$search.val().length + 1;

      width = (minimumWidth * 0.75) + 'em';
    }

    this.$search.css('width', width);
  };

  return Search;
});
```

Where `width = (minimumWidth * 0.75) + 'em';` is not enough for Chinese/Japanese characters. My suggest is `width = (this.$search.val().length + 0.5) + 'em';`

**Comment by renkaixin** [comment] 2016-07-03 07:45
Hey, @fengdh I have same confusion when I used select2 as a suggest tool and typed Chinese words in it. And your solution `width = (this.$search.val().length + 0.5) + 'em'` works pretty good.

**Comment by alexweissman** [comment] 2017-12-09 01:08
This appears to be a duplicate of #4074.

**Closed by alexweissman** 2017-12-09 01:08 UTC
Labels: 4.x, confirmed bug
