### ISSUE TITLE
[iOS] Select2 Doesn't close when tapping outside

### ISSUE THREAD

**Issue by jaime-franco** [select2/select2#4087] opened 2016-01-16 18:22 UTC
Using select2  in safari iOS phone, doesn't dismiss the select2 when lost focus or tapping outside, also there is no option to use a mobile native component.

**Comment by lukepolo** [comment] 2016-01-29 15:29
Same issue

**Comment by kevin-brown** [comment] 2016-01-29 21:53
This is a duplicate of https://github.com/select2/select2/issues/4013.

**Closed by kevin-brown** 2016-01-29 21:53 UTC
