### ISSUE TITLE
Add tooltip (title) to the 'remove all' 'X' icon

### ISSUE THREAD

**Issue by Loadmaster** [select2/select2#4530] opened 2016-08-12 22:12 UTC
## Enhancement request

Could we please add a `title` attribute to the "remove all tags" '×' span element? In the `AllowClear.prototype.update` function definition, something along the lines of:

```
  AllowClear.prototype.update = function (decorated, data) {
    ...
    var $remove = $(
      '<span class="select2-selection__clear" title="Remove all items">' +    //<<modified line
        '&times;' +
      '</span>'
    );
    ...
  };
```

(I would do it myself (for v4.0.3), but I don't have the GIT infrastructure on my PC here.)

If we really wanted to get fancy, this could be (yet another) configuration options setting:

```
var select2Opts = { ..., removeAllTip: "Remove all items", ... };
```

**Comment by alexweissman** [comment] 2017-12-25 20:09
This appears to be a duplicate of #4456.

**Comment by alexweissman** [comment] 2017-12-25 20:11
Actually, #4456 is about the clear icon for individual selections, whereas this request is for the "clear all" icon when using `allowClear`.

**Comment by nisha-kaushik** [comment] 2018-05-14 08:36
I would like to pick this up as my initial contribution.

**Closed** 2018-09-15 20:04 UTC
Labels: enhancement
