### ISSUE TITLE
X (clear) button not clickable if select input width is smaller than option text

### ISSUE THREAD

**Issue by syndbg** [select2/select2#3809] opened 2015-10-03 18:49 UTC
Reproducible in: http://jsfiddle.net/jEADR/2169/

Scenario:

* Select `Alabama` from input
* Click the X (clear) button
* Verify it works. Good!
* Now select `Long` from input
* Try clicking the X (clear) button
* Verify it does not work.

**Comment by kevin-brown** [comment] 2015-10-12 15:41
This is a duplicate of https://github.com/select2/select2/issues/3306.

**Closed by kevin-brown** 2015-10-12 15:41 UTC
