### ISSUE TITLE
IE8/IE9/IE10/IE11 automatically focusing Select2 on Pageload, clicks don't help

### ISSUE THREAD

**Issue by Moter8** [select2/select2#3657] opened 2015-08-06 17:32 UTC
Screen Recording of this issue [IE11]: https://imgrush.com/VQWfGm9AMp4h

[Isolated webpage, bug still applies](http://bwf.ninja/select2-bug.html) --- [Where I was actually using it](http://bwf.ninja/kaufen-suche.html)

Not sure what else I can provide. Select2 works as expected on FF, Chrome, Edge but no version of IE, on Windows.

**Comment by kevin-brown** [comment] 2015-08-06 17:34
This is a duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-08-06 17:34 UTC
