### ISSUE TITLE
Tagging with multi-value select boxes in IE

### ISSUE THREAD

**Issue by JSGrewal** [select2/select2#5829] opened 2020-04-15 16:47 UTC
I'm using Select2 Dynamic option creation using Tagging with multi-value.

All working fine in Chrome but when using IE and entering new option it always stuck after 2 keys.
Same on api https://select2.org/tagging when test in IE.

Please advise if this is known issue or missing feature?

Thanks

**Comment by vandernorth** [comment] 2020-04-16 07:28
I have an open PR for this issue https://github.com/select2/select2/pull/5821
Same issue as #5378

**Comment by kevin-brown** [comment] 2020-04-18 18:30
Closing this as a duplicate of https://github.com/select2/select2/issues/5378.

**Closed by kevin-brown** 2020-04-18 18:30 UTC
