### ISSUE TITLE
Select 2 With A Gap

### ISSUE THREAD

**Issue by afattahi54** [select2/select2#3504] opened 2015-06-20 10:19 UTC
When I open the select 2 , some time I see a gap between select and its container, please see attached
When I click on select 2 again the position will be fixed !
I have see this only when the select container is shown on the top.

![Gap](https://cloud.githubusercontent.com/assets/5003703/8266880/4bcd222a-175b-11e5-98f3-2062f733df5a.png)

**Comment by kevin-brown** [comment] 2015-06-20 19:01
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by afattahi54** [comment] 2015-06-21 07:21
Select 2: Last version of version 4
OS: windows 7
Firefox: 38
IE: 10
Jquery: 1.11 
Bootstrap : 3.3.4
There are other jquery plugins but none of them are applied to select boxes
As I found this happens when some thing inserted in the DOM dynamically but I could not simulate in in a sample project to add it in fiddle

**Comment by afattahi54** [comment] 2015-06-23 04:27
I also find that the select 2 container is shown at the top although it has plenty space  below it

**Comment by kevin-brown** [comment] 2015-06-24 18:12
> As I found this happens when some thing inserted in the DOM dynamically but I could not simulate it in a sample project to add it in fiddle :(

That's going to end up being a problem. If it can't be reproduced in a controlled environment, then the issue might be with your environment. Are you using a different CSS `position` style on any of the parent elements? Maybe on the `<body>`?

**Comment by pryankster** [comment] 2015-06-25 18:00
I found that this happens when I set position: relative on the body element.

**Comment by kevin-brown** [comment] 2015-06-25 18:43
I suspect this is a duplicate of https://github.com/select2/select2/issues/3303.

**Comment by afattahi54** [comment] 2015-06-30 05:25
May be you are correct, I try to apply the suggested fix there but did not solve the issue.
Here is another scenario which may help, please see attached (the page has vertical scroll)
1- When I click the select box I see the gap (the select box opens up) 
2- I reload the page.
3- Move scroll down, 
4- Click on select box, I didn't see the gag (the select box opens down)
I still try to make a jsfidel sample, to show it.

![sam1](https://cloud.githubusercontent.com/assets/5003703/8424309/dc4292e0-1f0d-11e5-87e5-3acb3f52b1bf.jpg)
![sam2](https://cloud.githubusercontent.com/assets/5003703/8424310/dee401c8-1f0d-11e5-9070-9d79b0bd4fe4.jpg)

**Comment by afattahi54** [comment] 2015-09-07 08:46
When I switched to Select 2: Last version of version 4.0.0-rc.2. It fixed !

**Closed** 2015-09-08 00:45 UTC
Labels: 4.x, needs information
