### ISSUE TITLE
Preventing select2:opening event throws an error

### ISSUE THREAD

**Issue by sarustamyan** [select2/select2#3267] opened 2015-04-17 02:15 UTC
Preventing the **select2:opening** event throws "args is undefined" error. Here is a fiddle for troubleshooting: http://jsfiddle.net/r56zh872/5/

**Comment by pgifford** [comment] 2015-08-28 16:57
I was able to avoid this error by adding a line to `Select2.prototype.trigger` (which is in [core.js](https://github.com/select2/select2/blob/master/src/js/select2/core.js)):

```javascript
actualTrigger.call(this, preTriggerName, preTriggerArgs);
args = args || {};  //   <------ added this line
if (preTriggerArgs.prevented) {
```

I don't know if there are any side effects to this, but this fix seems to work fine.

**Comment by kevin-brown** [comment] 2015-08-28 21:01
This should have been fixed in https://github.com/select2/select2/commit/71669359582ab04571f13bce8ff5c99318739c7b and is a duplicate of https://github.com/select2/select2/issues/3431.

**Closed by kevin-brown** 2015-08-28 21:01 UTC
Labels: 4.x, bug
