### ISSUE TITLE
Select2 loses focus after selecting Item

### ISSUE THREAD

**Issue by PieterjanDeClippel** [select2/select2#5185] opened 2018-01-05 16:04 UTC
Issue apparently already happened earlier: https://github.com/select2/select2/issues/4971.
However I haven't been bothered by it yet. All the time I've been using Select2, it's been working fine [v4.0.4 works fine](https://lyricdb.tk/song/37/edit).

Issue is available at the [very demo page](https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox). Just start typing something, and select a suggested item. Notice that the Select2 loses focus. My version is <b>v4.0.6-rc.1</b>

**Comment by alexweissman** [comment] 2018-01-08 14:45
I have confirmed that this problem is reintroduced in 4.0.6-rc.1.  See this [bin](http://jsbin.com/nuwuyiduru/edit?html,js,console,output).

@PieterjanDeClippel in the future, you need to create a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example using our [JSBin template](http://jsbin.com/hojajiwoye/edit?html,js,output) so that we can easily confirm these regressions.

**Comment by alexweissman** [comment] 2018-01-08 14:55
The only change I can think of that might have introduced this bug, is the addition of `blur` in [this commit](https://github.com/select2/select2/commit/ef2ef8b685c1ade1f5bf5cd691ce94a8b8e55437).  This was merged from #4680 without extensive testing.  Could you please confirm if this is the culprit?

**Comment by tallon1252** [comment] 2018-02-16 09:31
Hej :)
@alexweissman, the referenced commit seems not to be the issue.
I removed the line to test it out, but the behavior didn't change.

**Comment by kzkn** [comment] 2018-02-20 15:27
Probably [this commit](https://github.com/select2/select2/commit/45ee7340e54259156b3b0ed38786f6a730810587). See this [bin](http://jsbin.com/rimeqac/edit?html,js,console,output).

The jsbin has inlined select2 (4.0.6-rc1) code without `window.setTimeout(function() { self.$selection.focus(); }, 0);`, marked with `// REMOVE THIS`.

**Comment by tallon1252** [comment] 2018-02-21 10:53
@kzkn This fix doesn't seem to work for me…
But it works in your JSBin example. This one really starts to confuse me.

**Comment by kzkn** [comment] 2018-02-21 15:29
@tallon1252 The commit edits `dist/js/select2.js` directly, and use this from the jsbin. Perhaps, you built it yourself?

**Comment by tallon1252** [comment] 2018-02-21 20:19
@kzkn I just removed the lines you mentioned in directly in the select2.js…

**Comment by kzkn** [comment] 2018-05-20 10:06
Updated [my hotfix-5185 branch](https://github.com/kzkn/select2/tree/hotfix-5185). How is this?
I have tested on Firefox and Chrome (on Linux), works fine.

By the way, what is 45ee7340e54259156b3b0ed38786f6a730810587 solving? Can we remove this?

**Comment by nino-s** [comment] 2018-06-11 06:52
@alexweissman heyho alex, I am not at home actually to test it correctly, but @kzkn seems to be right.

Why should a 0 seconds delayed command should help while focusing? [#45ee734](https://github.com/select2/select2/commit/45ee7340e54259156b3b0ed38786f6a730810587) What happens is, that some parts of the code afterwards is executed before even `self.$selection.focus();` is executed.

**Comment by fuzzbomb** [comment] 2018-09-21 02:32
It also loses focus after deleting an item, in the multiple select time on the basic usage page.

**Comment by s1lver** [comment] 2019-03-14 07:21
This issue is still relevant

**Comment by jmalatia** [comment] 2019-03-17 20:59
+1

**Comment by HeppyKarlsson** [comment] 2019-03-28 13:30
+1

**Comment by mtaylor091** [comment] 2019-04-09 20:05
I found that  45ee734 fixes and issue with scrolling when they have a select element open. Before this commit if the select element was open and you scrolled down the page and clicked a button or input it would scroll you back to the select. This check in lets the active element change and then it checks if its different before selecting focus again.

On the other hand, without the commit and active element check, it lets you tab through a form with a select element. Without it selecting the select2 element, it loses focus all together and you cant tab to the next input. In my case the active document is the body. 

Somehow it needs to know that I just closed the select but I am still on select form versus I just closed the select because I am trying to type in another field or select a button while the select2 still has focus.

**Comment by mjlabe** [comment] 2019-05-23 12:21
As a temporary fix, I got it to work with this:

```
$('.my_class').click(function () {
    $('.select2-search__field').focus()
});
```

**Closed** 2019-07-21 02:44 UTC
Labels: 4.x, accessibility, confirmed bug, feature: multi-select

**Comment by CemplexIT** [comment] 2020-07-30 17:23
We've been having a similar issue - it turned out that the underlying select element was gaining focus.  I believe that some of our CSS was doing something to make this happen but I couldn't find the culprit.  We added a display none tag to the css for the class below that is applied when the select is turned into a select2 to fully hide the select and that seemed to do the trick for us.

`.select2-hidden-accessible {
      display: none;
    }`
