### ISSUE TITLE
search box keyup event binding

### ISSUE THREAD

**Issue by marslan390** [select2/select2#3989] opened 2015-12-04 12:21 UTC
hi,
I want to bind keyup event on select2 searchbox using my actual select element id. Is there any possible solution?

**Comment by kevin-brown** [comment] 2015-12-19 18:18
Select2 does not currently propagate keyboard events from the search box to the main `<select> `element, but there are plans to possibly add this in the future.

This is a duplicate of https://github.com/select2/select2/issues/1908.

**Closed by kevin-brown** 2015-12-19 18:18 UTC
