### ISSUE TITLE
select2 4.0: When a tag is selected it is still available in the drop down list

### ISSUE THREAD

**Issue by aruizca** [select2/select2#3490] opened 2015-06-18 06:16 UTC
The expected behaviour is that a tag that is already added should not appear in the drop down list

**Comment by kevin-brown** [comment] 2015-06-19 22:40
It should appear in the list with a grey background (depending on your theme), just like any other selected option. If this isn't the case, we're going to need some more information.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by glenpike** [comment] 2015-07-31 11:02
Noticed this behaviour this morning.

If you look at behavioour of 3.5.2, when you select an item from the dropdown list in a Multiple / Tag select box, the selected item is removed from the dropdown results list.  In v4 it is highlighted instead.  Ideally behaviour should remain the same as previous version because the behaviour is confusing:
When you choose an item that is already selected, it removes it from your selection.  This is okay if you have CSS showing highlighted, but as behaviour has changed, users familiar with old behaviour will be caught out.

**Comment by kevin-brown** [comment] 2015-07-31 17:01
Just noticed that this is a duplicate of https://github.com/select2/select2/issues/1538.

The behaviour change from 3.x is intentional, you can still hide the options with CSS or give them a different look.

**Closed by kevin-brown** 2015-07-31 17:01 UTC
Labels: needs information
