### ISSUE TITLE
Using allowClear without placeholder set causes an error

### ISSUE THREAD

**Issue by sabat24** [select2/select2#5808] opened 2020-03-20 16:17 UTC
Add allowClear option to simple select and do not set placeholder. After clicking on "x" you will get an error: this.placeholder is undefined.

https://jsfiddle.net/8x01aqng/ (I included there 4.0.0 version, but I tested in on latest 4.0.13 as well).

**Comment by kevin-brown** [comment] 2020-03-21 14:05
Duplicate of https://github.com/select2/select2/issues/5725.

**Closed by kevin-brown** 2020-03-21 14:06 UTC
