### ISSUE TITLE
Scroll back to the input field when lost focus (after select2:closing)

### ISSUE THREAD

**Issue by roman4e** [select2/select2#4983] opened 2017-07-07 13:33 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

There is jsfiddle with complete example page: https://jsfiddle.net/1hw1250x/

1. Open fiddle link
2. Click on select2 field. It should open with suggestions. Do NOT select anything
3. Scroll down to the gray square
4. Click on the square

## Expected behavior and actual behavior

When I follow those steps, I see the page is scrolled to the top (where select2 element is present)

I was expecting not to scroll and still see gray square

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux

Libraries

- jQuery version: 2.2.4
- Select2 version: 4.0.3

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsfiddle](https://jsfiddle.net/1hw1250x/)

**Comment by alexweissman** [comment] 2017-09-22 20:22
I can reproduce this behavior.  I'm kind of confused though, because #4971 seems to be saying the exact opposite thing.

**Comment by jpic** [comment] 2017-09-22 21:07
I feel pretty confident that it should not auto-focus after programatic deselect: if the developer wants to deselect and focus back then I feel they should call both in a row.
@alexweissman it's not the same issue, in #4971 focus is *lost* after selecting an option which breaks tab navigation. Here, focus is *taken* _after_ selecting an option programaticaly.
So, to answer @zoka123 I think yes, this /might/ be the reason why it's here, in which case this confirms your hypothesis. Are you willing to start a pull request ?

**Comment by alexweissman** [comment] 2017-09-24 17:45
I have confirmed that this issue is still present in 4.0.4.

**Comment by alexweissman** [comment] 2017-09-24 17:50
You'll notice that PR #4860 and #3394 actually wrap `self.$selection.focus();` in a `setTimeout` block...interesting.

**Comment by alexweissman** [comment] 2017-12-29 03:22
This actually appears to be a duplicate of #3663.

**Closed by alexweissman** 2017-12-29 03:22 UTC
Labels: confirmed bug
