### ISSUE TITLE
Placeholder initially not shown

### ISSUE THREAD

**Issue by drbarto** [select2/select2#4467] opened 2016-07-08 13:14 UTC
I want to display a placeholder text on my multi-select field, but the placeholder isn't shown when the page is initially loaded. Only when I select an item and remove it again, the placeholder gets displayed as expected.

I have a very simple multi-select field without any additional options. The only 'special' thing about my setup I can think of is that the `select` is rendered inside a Bootstrap tab which is not visible upon page load. This might be related to #4220, however in that issue the placehodler text is just cut off, while for me it's completely hidden.

The issue appears in Chrome and Safari, but not in Firefox (tested on macOS). 

Can someone give me a hint how I could fix this problem?

**Comment by kevin-brown** [comment] 2016-07-09 00:30
This is a duplicate of https://github.com/select2/select2/issues/4220.

**Closed by kevin-brown** 2016-07-09 00:30 UTC
