### ISSUE TITLE
How to create a new tag on TAB key press? `Select2 4.0.1`

### ISSUE THREAD

**Issue by sampatbadhe** [select2/select2#4039] opened 2015-12-23 05:18 UTC
I would like to create new tag on TAB key press.

Is there any way to create new tag on TAB key press?

**Comment by kevin-brown** [comment] 2015-12-24 23:06
This is a duplicate of https://github.com/select2/select2/issues/3359.

**Closed by kevin-brown** 2015-12-24 23:06 UTC
