### ISSUE TITLE
Tags Don't Wrap Correctly with AllowClear

### ISSUE THREAD

**Issue by vol7ron** [select2/select2#4555] opened 2016-08-29 13:59 UTC
http://jsfiddle.net/vol7ron/y9g9swsr/
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. 535px container with 1.3rem font-size
2. Select options that are just wide enough to cause a problem, but not wide enough to force a newline
## Expected behavior and actual behavior

When I follow those steps, I see...
that the tags don't wrap nicely

I was expecting...
tags to wrap nicely
## Environment

Browsers
- [ ] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.12.x
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by RobertDiebels** [comment] 2016-08-30 05:05
There is a workaround for this mentioned in this issue: https://github.com/select2/select2/issues/4470
So yours is a duplicate of that one.

**Comment by alexweissman** [comment] 2017-09-17 02:51
Closing as duplicate of #4470.

**Closed by alexweissman** 2017-09-17 02:51 UTC
