### ISSUE TITLE
iOS rotation width

### ISSUE THREAD

**Issue by alexcroox** [select2/select2#3621] opened 2015-07-29 15:17 UTC
When I rotate my iOS device the inline css width the plugin applies doesn't update. Meaning if I start in landscape and rotate the device the width is wrong in portrait.

**Comment by kevin-brown** [comment] 2015-07-29 15:23
This is a duplicate of https://github.com/select2/select2/issues/3278.

**Closed by kevin-brown** 2015-07-29 15:23 UTC
