### ISSUE TITLE
readonly attribute not working

### ISSUE THREAD

**Issue by lordjancso** [select2/select2#4198] opened 2016-02-20 12:25 UTC
Read only attribute not working at all.

For example $('#my-select2-element').prop('readonly', true);

I tried on Windows and Linux, Firefox, Chrome and Opera.

**Comment by kevin-brown** [comment] 2016-02-21 00:35
This is a duplicate of https://github.com/select2/select2/issues/3387#issuecomment-104961591, support for `readonly` was removed in 4.0.0.

**Closed by kevin-brown** 2016-02-21 00:35 UTC
