### ISSUE TITLE
4.0.0-rc2 Selecting nothing with a multiselect placeholder prevents dropdown from closing in IE.

### ISSUE THREAD

**Issue by NicoNet** [select2/select2#3257] opened 2015-04-13 19:28 UTC
To reproduce
Using IE11
http://jsfiddle.net/emwgujt5/1/

Click the first dropdown, it opens, do not select anything then click the next drop down.  The first does not close, the second will not close either unless something is selected.

removing 
placeholder: "[ALL]",
from the JS fixes the issue.

I'd expect the previous to collapse and put the placeholder in the box.
This is an IE Only issue.  This issue is not encountered in Opera, FireFox, Safari, or Chrome.
This test page loads jQuery and Select2, nothing else.

**Comment by Masaroth** [comment] 2015-04-15 13:15
Having the same issue with IE as well, It also causes problems with modal windows as the dropdown hangs around even after the modal is closed.

Replication
See https://jsfiddle.net/vmLjdv3L/7/
Click the button, click into the select2 box to open dropdown, close modal

**Comment by kevin-brown** [comment] 2015-04-15 18:09
What versions of IE are affected? And are there any that don't have the issue?

**Comment by Masaroth** [comment] 2015-04-16 08:21
I have just given it a quick test, and it appears the issue is only with IE10 and IE11(Edge) . It does not affect older versions as the placeholder text does not appear in the first place.

**Comment by kevin-brown** [comment] 2015-05-21 15:11
Merged into https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-05-21 15:11 UTC
Labels: 4.x, needs information
