### ISSUE TITLE
dom event "select2:select" does not fire on selection with keyboard enter

### ISSUE THREAD

**Issue by manpenaloza** [select2/select2#3496] opened 2015-06-18 14:32 UTC
I implemented select2 on this startpage: http://www.bier-in-aktion.at - the select field is positioned below the big logos.

the select menu includes beers. i want to fire the select2.select dom event on an option select (like the documentation of 4.0 says it does) to forward the user to the beer detail page, which i solve with defining a "window.location" forward in the code that gets executed when the "select2:select" event is fired. BUT: the event fires on mouse click, not on keyboard enter of the option. 

can you confirm this? 
can someone help me out with a workaround to fix this?
many thx in advance!

**Comment by kevin-brown** [comment] 2015-06-18 21:14
Most likely a duplicate of https://github.com/select2/select2/issues/3325.

**Closed by kevin-brown** 2015-06-18 21:14 UTC
