### ISSUE TITLE
Search Input width autoResize with 0.75em per character may causes display incorrect in some languages.

### ISSUE THREAD

**Issue by renkaixin** [select2/select2#4450] opened 2016-06-30 08:22 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue

## Steps to reproduce the issue

1.Copy the word '布宜诺斯艾利斯' which is Chinese name of Argentine capital city Buenos Aires.
2.Paste it into the Multiple select boxes search input.

## Expected behavior and actual behavior

This word has 6 characters but when I follow those steps, I see only 5 character visible in search input.

## Environment

Browsers

- [x] Google Chrome

Operating System

- [x] Mac OS X

Libraries

- jQuery version:1.11.1
- Select2 version: 4.0.2

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns

**Comment by kevin-brown** [comment] 2016-07-02 16:13
Duplicate of https://github.com/select2/select2/issues/4376.

**Closed by kevin-brown** 2016-07-02 16:13 UTC

**Comment by renkaixin** [comment] 2016-07-03 07:24
LGTM
