### ISSUE TITLE
When ellipsis appears, the clear 'X' doesn't work on Chrome

### ISSUE THREAD

**Issue by oterrada** [select2/select2#3500] opened 2015-06-19 09:53 UTC
I'm using a select2 with this options:
```javascript
$("#cbo").select2({
        multiple: false,      minimumInputLength: 4,        allowClear: true,
        ajax: {
            url: "FiltersWs.asmx/getData",
            dataType: 'json',            delay: 250,            type: 'POST',
            data: function (params) {                return { searchTerm: params.term};            },
            processResults: function (data, page) {  return { results: data };
            }
        },
        templateResult: cboFormatResult,
        templateSelection: cboFormatSelection,
    });
```
When the result is so long the **ellipsis** appears on the right (it's great) but the cross to clear the selection doesn't work. I think it's a Chrome problem ('...' is over de X) I don't know the easy way to fix it. Meanwhile I put on the left side removing the float:right and adding some margin.

```javascript
.select2-container--default .select2-selection--single .select2-selection__clear {
    cursor: pointer;
    /*float: right;*/
    margin-right:2px;
    font-weight: bold; }
```
I'm using W8.1, Chrome 43.0.2357.124 m, jquery 2.1.4 and no other pluggins.
In FF 38.0.5 works fine.

**Comment by kevin-brown** [comment] 2015-06-19 12:40
This appears to be a duplicate of https://github.com/select2/select2/issues/3306.

**Closed by kevin-brown** 2015-06-19 12:40 UTC
