### ISSUE TITLE
Bug: Ajax Multiselect Checkbox Does't Delete(Deselect) When You Double Click(Toggle) On Select.

### ISSUE THREAD

**Issue by tolgakurtulus** [select2/select2#6029] opened 2021-05-03 07:24 UTC
Hello,

Checkbox normally works after double clicks. It carries out the Add and Delete operation.

But when I use the ajax multiselect checkbox, it can add but I cannot delete it through select.

When I want to delete, I can only delete it by pressing x on the top.

This is my code : https://codepen.io/tolga-kurtulu/pen/KKaOVXp?editors=1011

![image](https://user-images.githubusercontent.com/43134032/116850608-9d591700-abf9-11eb-9f40-9c0660c10a47.png)

**Comment by kevin-brown** [comment] 2021-06-10 01:55
Duplicate of https://github.com/select2/select2/issues/4406

**Closed as completed by kevin-brown** 2021-06-10 01:55 UTC
