### ISSUE TITLE
Optgroup cannot be disabled.

### ISSUE THREAD

**Issue by dsarosi** [select2/select2#4876] opened 2017-04-21 02:04 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Apply select2 to a simple select with a disabled optgoup
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.0
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

https://jsbin.com/birezar/edit?html,js,console,output

**Comment by alexweissman** [comment] 2017-09-27 22:33
Looks like a duplicate of #2306.  It may be related to #3347, possibly fixed by #5035.

**Closed** 2017-12-14 20:38 UTC
Labels: confirmed bug, status: duplicate

**Comment by jackdeguest** [comment] 2018-04-01 23:55
@alexweissman you can re-open this bug. As of the latest version ie 4.0.6 rc1 a disabled optgroup is not honoured in selected. This means that even though one has the following html in the select object
<optgroup label="Alaskan/Hawaiian Time Zone" disabled>
    <option value="AK">Alaska</option>
    <option value="HI">Hawaii</option>
</optgroup>
with select2, one can still select Alaska or Hawaii whereas in the pure html version of the select the disabled optgroup makes it impossible to select any option inside it.
The code pen is here: [](https://codepen.io/jdeguest/pen/eMrbJy)
The code pen use rc0, but I checked with rc1 and the issue remains.
