### ISSUE TITLE
Bootstrap modal scroll freezes after selecting an option of multiple select

### ISSUE THREAD

**Issue by andysoa** [select2/select2#4125] opened 2016-01-27 00:42 UTC
I've a bootstrap modal that is bigger then the window height that scrolls normally but if I choose an  option of a multiple select the scroll it freezes and doesn't allow to scroll anymore. This doesn't happen on a normal select and I've tested it in Chrome, IE and Firefox.

I'm using bootstrap 3.3.6 with select2 4.0.1.

**Comment by kevin-brown** [comment] 2016-01-27 22:16
This is more than likely a duplicate of https://github.com/select2/select2/issues/3125.

**Closed by kevin-brown** 2016-01-27 22:16 UTC
