### ISSUE TITLE
Can't remove data

### ISSUE THREAD

**Issue by jgarturo** [select2/select2#3529] opened 2015-06-27 11:57 UTC
I have a state/location selector. When someone choses a state, the locations dropdown needs to get populated with the locations for that state.

```
	var $state = $('.select2.state').select2({
		placeholder: "Select a state"
	});

	$('.select2.location').select2({
		placeholder: "Select a location"
	});

	$state.on("change", function (e) {

		$(".select2.location").prop("disabled", false);

		$('.select2.location').select2({
		 	data: locations[$state.val()]
		});

	});
```

No matter what I do, I can't replace the old data when the state is changed after the initial selection— the new data just gets appended to the bottom of the list. I've tried .select2("destroy") which destroys it properly, but when I reinstate it the old data is still there. I've tried setting data to null as well but no luck.

**Comment by kevin-brown** [comment] 2015-06-27 12:14
Duplicate of https://github.com/select2/select2/issues/3348 / https://github.com/select2/select2/issues/3185#issuecomment-88955394.

**Closed by kevin-brown** 2015-06-27 12:14 UTC
