### ISSUE TITLE
Position of Message when drop down is above. 

### ISSUE THREAD

**Issue by rhamej** [select2/select2#4764] opened 2017-01-25 14:48 UTC
1. Have a select2 at the bottom of the browser where the dropdown will open above.
2. Limit the number of selections to 1.
3. Try to select again after you select the 1. The message will be way above the select because it is still using the old position and height of the dropdown. Scrolling the window fixes the position and is the only solution I have found. 

I attached a screenshot of the bug from your own site. This is on all browsers on Windows. 

![screen](https://cloud.githubusercontent.com/assets/1900225/22294910/171c47e0-e2e3-11e6-8a11-d98c6732f0e2.jpg)

**Comment by alexweissman** [comment] 2017-09-17 02:04
Duplicate of #4614.

**Closed by alexweissman** 2017-09-17 02:04 UTC
