### ISSUE TITLE
Wrong position when open select2  first time

### ISSUE THREAD

**Issue by allan1488** [select2/select2#4460] opened 2016-07-06 18:03 UTC
whenever the select2 is first opened, the combo is loaded with the wrong position. After typing something or open again, it corrects the position.

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: jquery-2.2.3
- Select2 version: select2-4.0.0
## Isolating the problem

https://s32.postimg.org/ybxk9iykl/select.jpg

see in top bar

**Comment by alexweissman** [comment] 2017-09-17 02:38
This is a duplicate of #3228.

**Closed by alexweissman** 2017-09-17 02:38 UTC
