### ISSUE TITLE
Clear button does not work if placeholder is not defined

### ISSUE THREAD

**Issue by xumix** [select2/select2#3944] opened 2015-11-19 09:09 UTC
Select2 4.0.0

The error is in the method ```_handleClear``` on the line:
```
this.$element.val(this.placeholder.id).trigger('change');
```
Obviously, if options.placeholder is undefined this will fail

**Comment by marbin** [comment] 2015-12-01 11:28
I see the same behavior in 3.5.4, i.e. that if allowClear: true and placeholder is undefined, the clear button (X) does not appear, which is because the class select2-allowclear is not added.
Looking at the code at line 2662 reveals why:

    if (this.opts.allowClear && this.getPlaceholder() !== undefined) {
        this.container.addClass("select2-allowclear");
    }

If I remove the placeholder check it works as expected. 
I am not sure I understand why the check for placeholder is there, though.

**Comment by kevin-brown** [comment] 2015-12-02 09:15
This is a duplicate of https://github.com/select2/select2/issues/3016, the clear button is designed to reset the `<select>` to the placeholder, which is why it is required.

**Closed by kevin-brown** 2015-12-02 09:15 UTC
