### ISSUE TITLE
AJAX results caching?

### ISSUE THREAD

**Issue by igorsantos07** [select2/select2#3984] opened 2015-12-03 13:11 UTC
I tried including the `ajax.cache` option as true, but every time I open the select box or type the same letter in the search box, it makes a query to my server again.

Do the cache settings changed from one version to the other and the docs we find in the web are outdated?

**Comment by kevin-brown** [comment] 2015-12-19 18:17
This is a duplicate of https://github.com/select2/select2/issues/3862.

**Closed by kevin-brown** 2015-12-19 18:17 UTC
