### ISSUE TITLE
IE11 doesnt allow to clear last entry in multiple select boxes with placeholder

### ISSUE THREAD

**Issue by n1smo** [select2/select2#3142] opened 2015-03-12 21:13 UTC
See title.

Im not able to clear the last item in a multi select box in IE11 when a placeholder is set.
The dropdown cant be closed. If i remove the placeholder it works fine.

No issues in latest chrome.

You can see this even in the placeholder example on the select2 website.

**Comment by kevin-brown** [comment] 2015-03-12 23:17
I think this _might_ be a duplicate of an existing issue, but I can't find it right now.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by n1smo** [comment] 2015-03-13 19:43
If you look at the the second Placeholder example (multi select) on the select2 website (https://select2.github.io/examples.html).

Try to add an element to the list and then try to remove it. The list is cleared but the dropdown wont close until you select another element. You can make it invisible by hit the ESC button, but it will still be there blocking all other interaction.

It has something to do with the placeholder. If disable placeholder it works.

This happens on IE11 on Win8.1. 
No Problems in Chrome.

And like described it even happens on the select2 website. So not jquery or version problem.

**Comment by oleg-nn** [comment] 2015-03-24 13:30
There is no error in the first version of the select2 4.0. The bug has come with last updates. Has anybody fixed it?

**Comment by oleg-nn** [comment] 2015-03-26 11:28
I fixed it for myself.
this.$selection.on('keyup.search input', '.select2-search--inline',
        function (evt) {
      self.handleSearch(evt);
    });
is substituted for
this.$selection.on('keyup.search, paste', '.select2-search--inline', function (evt) {
        setTimeout( function(){ self.handleSearch( evt ) } , 10 );
    });
setTimeout is used for copypasting in search field by using mouse.

**Comment by digitaldonkey** [comment] 2015-07-14 14:35
I can confirm this Issue using Version 4.0.

* After removing last tag the combobox with placeholder in ie11 won't close
* Any click outside (in other form elements reopens the combobox
* If there is any tag selected it works as expected (like in Firefox, chrome, android iphone ....)
* Sadly oleg-nn's fix don't work for me (and I think it is targeting a different problem "copypasting in search")

Any suggestions? I urgently need to fix this.

**Comment by kevin-brown** [comment] 2015-07-14 14:41
This sounds like a duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-07-14 14:41 UTC
Labels: needs information

**Comment by digitaldonkey** [comment] 2015-07-14 14:56
:+1:  I can confirm.

https://github.com/select2/select2/issues/3300#issuecomment-114304535

fixed this issue for me. Thank you!
