### ISSUE TITLE
allowClear: true with no placeholder causes error on clear

### ISSUE THREAD

**Issue by jimitndiaye** [select2/select2#5771] opened 2020-02-11 11:30 UTC
Sample code: https://codepen.io/jimitndiaye/pen/OJVVBKG

To summarize, any select2 dropdown list with allowClear  set to true but no placeholder results in a null reference error when you attempt to clear a selection due to the placeholder being undefined.

Given the following html:
```
<form class="col-6">
   <div class="form-group>
      <label for="Order_RecdViaId">RecdViaId</label>
      <select class="form-control select2" autofocus="" id="Order_RecdViaId" name="Order.RecdViaId" >
         <option></option>
         <option value="4">Ground - UPS</option>
         <option value="5">3-Day - UPS Orange</option>
         <option value="6">2-Day - UPS Blue</option>
         <option value="7">1-Day PM - UPS Red Saver ~4:30pm</option>
         <option value="8">1-Day AM - UPS Red ~10:30am</option>
      </select>
   </div>
   <br />
   <div class="form-group">
      <label for="ctl2">Control2</label>
      <input type="text" id="ctl2" name="ctl2" class="form-control" />
   </div>
</form>
```
... and javascript:
```
$('select.select2').select2({
  // Uncomment placeholder setting to workaround issue
  //placeholder: 'Select an option...',
  theme: 'bootstrap',
  allowClear: true
});
```
Clearing out a selection results in the following error:
```
select2.min.js:2 Uncaught TypeError: Cannot read property 'id' of undefined
    at o.e._handleClear (select2.min.js:2)
    at o._handleClear (select2.min.js:2)
    at HTMLSpanElement.<anonymous> (select2.min.js:2)
    at HTMLSpanElement.dispatch (jquery.min.js:2)
    at HTMLSpanElement.v.handle (jquery.min.js:2)
```
select2 version 4.0.10, 4.0.12 and 4.0.13
Tested on Windows 10, Chrome 80

Steps to reproduce
1. Select an option from in select2
2. Click X to clear the option
3. The selection is not cleared and an error is thrown as described above.

**Comment by kevin-brown** [comment] 2020-03-21 14:06
Duplicate of https://github.com/select2/select2/issues/5725.

**Closed by kevin-brown** 2020-03-21 14:06 UTC
