### ISSUE TITLE
inputData does not work in 4.0.0-rc.2 full mode - require is not defined

### ISSUE THREAD

**Issue by kantyka** [select2/select2#3211] opened 2015-03-31 12:23 UTC
I have select2 4.0.0-rc.2 (full mode version) with no module system in my app. Script throws an exception when initiated on hidden input - "require is not defined".
Jsbin illustrating the problem:
http://jsbin.com/mogexoqona/1/edit?html,js,output

**Comment by kevin-brown** [comment] 2015-03-31 13:09
Duplicate of https://github.com/select2/select2/pull/3192 - This will be fixed before the final release.

**Closed by kevin-brown** 2015-03-31 13:09 UTC
