### ISSUE TITLE
Search Box misplace on first click

### ISSUE THREAD

**Issue by sureshvtt** [select2/select2#4532] opened 2016-08-13 07:59 UTC
![select2bug](https://cloud.githubusercontent.com/assets/2316933/17642174/dfb823b0-6159-11e6-9835-9618a2d9342e.png)

**Comment by LuuchoRocha** [comment] 2016-08-17 18:08
https://github.com/select2/select2/issues/4526

**Comment by alexweissman** [comment] 2017-12-08 20:08
Duplicate of #4614.

**Closed by alexweissman** 2017-12-08 20:08 UTC
