### ISSUE TITLE
Adding CSS Class to Dropdown or Container

### ISSUE THREAD

**Issue by nuriye** [select2/select2#5642] opened 2019-09-17 06:35 UTC
Hi!
I tried to add a CSS Class to the Dropdown, but it is resulting in a Console Error.

`Uncaught Error: No select2/compat/dropdownCss`

`        $('.myfilter').select2({
            placeholder: name,
            allowClear: true,
            dropdownCssClass: "mytestdropdown",
        });`

What I try to achieve is to add a Class to the Dropdown, so I can style the Dropdown-Elements of one Dropdown with CSS (Instead of just styling all Select2 Dropdowns all over the Website!)

**Comment by kevin-brown** [comment] 2019-09-18 00:51
Duplicate of https://github.com/select2/select2/issues/3302#issuecomment-98030694.

**Closed by kevin-brown** 2019-09-18 00:51 UTC
