### ISSUE TITLE
FEATURE REQUEST | Search Custom Data Object

### ISSUE THREAD

**Issue by harshadsatra** [select2/select2#5948] opened 2020-11-11 08:04 UTC
Looking for option to Use Custom data object search where `text` object is not present in the object.

`
object{
id: 1,
name: "abc",
surname: "xyz"
}
`

**Comment by kevin-brown** [comment] 2020-11-12 17:00
Duplicate of https://github.com/select2/select2/issues/5095, there are ways to solve this in various places including our docs.

**Closed by kevin-brown** 2020-11-12 17:00 UTC
