### ISSUE TITLE
data-* custom attributes throws a TypeError

### ISSUE THREAD

**Issue by CHuLoYo** [select2/select2#3460] opened 2015-06-10 13:30 UTC
This issue I think that is a bug.
If you fill a **select** tag name with a customized _data-*_ attribute, console throws this error:

> TypeError: b.dataAdapter is null

or 

> TypeError: this.dataAdapter is null

Depending on the scope.

The code example is like this:

``` html
<select multiple data-placeholder="Search here" data-activate-after="some-value"></select>
```

Please, note that "data-placeholder" doesn't works.
"data-activate-after" makes the crash that I describe in top of this issue.

**Comment by FractalizeR** [comment] 2015-06-18 14:08
I have two different code branches, where I have the same issue on the first one and unable to reproduce it on the second ;)

**Comment by kevin-brown** [comment] 2015-06-18 14:49
Select2 should be ignoring extra data attributes, and without an actual traceback (from the unminified version) there isn't much to work from here.

**Comment by FractalizeR** [comment] 2015-06-19 07:52
Trace:

```
Uncaught TypeError: Cannot read property 'query' of null(anonymous function) 
@ select2.full.js:5070i.invoke
@ select2.full.js:614i.trigger 
@ select2.full.js:604r.trigger 
@ select2.full.js:5167r.open 
@ select2.full.js:5187r.toggleDropdown 
@ select2.full.js:5178(anonymous function) 
@ select2.full.js:5010i.invoke 
@ select2.full.js:614i.trigger 
@ select2.full.js:604n._handleClear 
@ select2.full.js:1723c 
@ select2.full.js:571(anonymous function) 
@ select2.full.js:1681jQuery.event.dispatch 
@ jquery.js:4670elemData.handle 
@ jquery.js:4338```

**Comment by kevin-brown** [comment] 2015-06-19 12:30
Reopening this back up for now, at least the trace will give us a starting point.

A jsbin/jsfiddle which reproduces this issue would also make things easier (so we don't have to hunt for the bug). Alternatively, answers to these questions could help

- What steps can be used to reproduce the issue?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

**Comment by FractalizeR** [comment] 2015-06-19 13:09
Currently in my code this happens at the following code fragment:

```
        $select.off ( "select2:open" ).on ( "select2:open", function( e ) {
            if ( $ ( this ).data ( "state" ) === "unselected" ) {
                $ ( this ).removeData ( "state" );
                setTimeout ( () => $ ( this ).select2 ( "close" ), 1 );
            }
        } );
```

The error appears when `$ ( this ).select2 ( "close" )` is executed. The solution was taken from here: http://stackoverflow.com/questions/29618382/disable-dropdown-opening-on-select2-clear

This happens only when I use select2 from inside React component. That event handler is attached inside React's `componentDidUpdate` handler.

Investigating further.

**Comment by rryen** [comment] 2016-01-04 12:41
1.	What steps can be used to reproduce the issue? See below
2.	What browser(s) and Operating System have you tested with? Chrome. Windows 7 Professional
3.	Does the bug happen consistently across all tested browsers? Yes (firefox, IE, Chrome)
4.	What version of jQuery are you using? And what version of Select2? jQuery: jquery-1.10.2.js. Select2:4.0.1
5.	Are you using Select2 with other plugins? No
I’ve had the same problem as this issue dictates but under different circumstances. I’m using a Select2 select box with this clientside code:
                
    <div class="form-group" style="width: 203px">
    <label class="col-sm-4 control-label">Category</label>
    <div class="col-sm-6" style="left: 0px; top: 0px; width: 244px">
    <select id="DDListCat2" style="width: 150px" name="DDListCat2" multiple="multiple"></select>
    <script type="text/javascript">
        //On client side - this calls the C# function that will retrieve the data
        //test way to see if this will work
        $(document).ready(function () 
        {
            $("#DDListCat2").select2(   
            {
                tags: true, 
                tokenSeparators: [',', ' '], 
                allowClear: true,  // only clears choices not items in the list itself.
//                minimumInputLength: 1,  // minimumInputLength for sending ajax request to server
                width: 'resolve',   // to adjust proper width of select2 wrapped elements 
                cache: true,
                id: function(DDListCat2) {return DDListCat2._id},
                ajax: 
                {
                   url: '<%= ResolveUrl("SearchComp.aspx/LoadData") %>', 
                    type: "POST",    
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8", 
                    data: {},
                    success: function (response)
                    {
                        console.log(typeof response);
                        alert("We returned successful: " + response.d);
                        alert("Data length: " + response.d.length );
                            return {
                                results: response
                            };
                    },
                    failure: function (response) {
                        alert(response.d);
                    }
                }
            });
        });
    </script>
    </div>

When I invoke the select box it gives me the error: 
“Uncaught TypeError: Cannot read property 'length' of undefined” wrapper @ Select2.full.js:3502(anonymous function) @ Select2.full.js:3441(anonymous function) @ jquery-1.10.2.js:3218fire @ jquery-1.10.2.js:3062self.fireWith @ jquery-1.10.2.js:3174done @ jquery-1.10.2.js:8249callback @ jquery-1.10.2.js:8792

It is receiving the url information back from the C# Method but not passing it to the wrapper function. 
Here is the Server side code:
    [WebMethod()]
    public static string LoadData()
    {
        System.Diagnostics.Debug.WriteLine("Went into the subroutine ");

        string strcon = ConfigurationManager.ConnectionStrings["sqlclienttest"].ConnectionString;
        SqlConnection con = new SqlConnection(strcon);
        SqlCommand cmd = new SqlCommand("select * from CatType", con);
        cmd.CommandType = CommandType.Text;
        SqlDataAdapter da = new SqlDataAdapter(cmd);
        DataSet ds = new DataSet();
        da.Fill(ds);
        string jsondata = JsonConvert.SerializeObject(ds.Tables[0]);
        System.Diagnostics.Debug.WriteLine(jsondata);
        return jsondata;
    }

Here’s what is being returned:
[{"CatID":1,"Category":"Documentation  "},{"CatID":2,"Category":"DTSC           "},{"CatID":3,"Category":"General        "},{"CatID":4,"Category":"Hardware       "},{"CatID":5,"Category":"HMI            "},{"CatID":6,"Category":"Network        "},{"CatID":7,"Category":"Programming    "}]

**Comment by rryen** [comment] 2016-01-04 12:46
I'm commenting this code again, it didn't go through in the last comment.
                
    <div class="form-group" style="width: 203px">
    <label class="col-sm-4 control-label">Category</label>
    <div class="col-sm-6" style="left: 0px; top: 0px; width: 244px">
    <select id="DDListCat2" style="width: 150px" name="DDListCat2" multiple="multiple"></select>
    <script type="text/javascript">
        //On client side - this calls the C# function that will retrieve the data
        //test way to see if this will work
        $(document).ready(function () 
        {
            $("#DDListCat2").select2(   
            {
                tags: true, 
                tokenSeparators: [',', ' '], 
                allowClear: true,  // only clears choices not items in the list itself.
//                minimumInputLength: 1,  // minimumInputLength for sending ajax request to server
                width: 'resolve',   // to adjust proper width of select2 wrapped elements 
                cache: true,
                id: function(DDListCat2) {return DDListCat2._id},
                ajax: 
                {
                   url: '<%= ResolveUrl("SearchComp.aspx/LoadData") %>', 
                    type: "POST",    
                    dataType: 'json',
                    contentType: "application/json; charset=utf-8", 
                    data: {},
                    success: function (response)
                    {
                        console.log(typeof response);
                        alert("We returned successful: " + response.d);
                        alert("Data length: " + response.d.length );
                            return {
                                results: response
                            };
                    },
                    failure: function (response) {
                        alert(response.d);
                    }
                }
            });
        });
    </script>
    </div>

**Comment by int-ua** [comment] 2016-02-23 16:03
I've encountered this bug while rewriting select contents on `select2:unselecting` event. In my case just adding `event.preventDefault();` to the event handler function helped.

**Comment by msxavi** [comment] 2017-01-16 22:42
Hi guys,

How is this issue going? Have you got some updates?

Thanks!

**Comment by heohni** [comment] 2017-01-26 12:06
Hi,

I get the same message on a multiselect. It works fine but still throws this message when selecting an option. And I found that select2:unselect and select2:select does not fire event with multiselects.

**Comment by alexweissman** [comment] 2017-12-14 20:52
I'm closing this issue, because discussion seems to have gone completely off topic from the original issue (i.e., looks like people are dumping anything with `TypeError` here, even if it is a completely unrelated problem).

**Closed by alexweissman** 2017-12-14 20:52 UTC
Labels: 4.x, status: needs information
