### ISSUE TITLE
Can I prevent the loss of search results in the dropdown list after selecting an item? (remote data)

### ISSUE THREAD

**Issue by kit-tolma** [select2/select2#3949] opened 2015-11-19 18:46 UTC
Suppose I have a remote data configuration:

```
    minimumInputLength: 2,
    dataType: 'json',
    ajax: { ... }
```

Suppose a User has clicked on Select2 element and has entered a long search term.
After loading a data from server, the drop-down list with some items has apрeared.
Then the User clicks on the first item.  The first item gone selected, and the drop-down list is disappeared. Good job!
But then, the User has decided that the second item is better than first...
Не clicks on the Select2 element to open drop-down list again. But the drop-down is empty!
There are no his hardly typed long search term, and no previously founded items! 
But they were here just a moment ago! Where have they gone?

How I can prevent such loss of search results?

I think the convenient behavior of Select2 would be:
When User reopens the drop-down list, the search field should contain the previously typed term and the corresponding set of elements, and the scroll position in the set, and previously selected item is highlighted. But the term in the search field should be selected, so that when User starts typing a new characters they would replace the previous.
In this approach, if User has opens a drop-down list just for a completely new search, his actions will not differ from the current ones.

**Comment by deanperry** [comment] 2015-11-22 14:08
:+1:

**Comment by cigaar** [comment] 2015-11-24 09:40
:+1:

**Comment by alexweissman** [comment] 2017-12-09 18:44
Duplicate of #3902 - please continue the conversation there.

**Closed by alexweissman** 2017-12-09 18:44 UTC
