### ISSUE TITLE
Prevent opening dropdown when removing tags

### ISSUE THREAD

**Issue by dmdm22** [select2/select2#3953] opened 2015-11-20 09:14 UTC
I have a multiple select with some selectable tags.
Every time a tag is removed (by clicking its remove button) the dropdown is being opened.

While this might make sense in some cases, i would like to have the dropdown stay closed, as some users (with nervous fingers) accidently click on dropdown entries which causes confusion here.

I've seen #3320 and assume this might be the same issue.
Have tried all workarounds from that issue, without success.

Any chance to get this working? Maybe some option would be nice in future releases, but any workaround would do.

Thanks

**Comment by kevin-brown** [comment] 2015-11-20 19:49
This is actually a duplicate of https://github.com/select2/select2/issues/3209#issuecomment-149663474, and you can find a solution to the problem at the comment I linked.

The other ticket (https://github.com/select2/select2/issues/3320) is about the `allowClear` option.

**Closed by kevin-brown** 2015-11-20 19:49 UTC

**Comment by dmdm22** [comment] 2015-11-30 17:20
Thank you, that works perfectly. 
Totally missed the other post, sorry for asking this again.
