### ISSUE TITLE
How to append data-* in option tag (Loading remote data)

### ISSUE THREAD

**Issue by yoyhosoft** [select2/select2#3510] opened 2015-06-22 17:38 UTC
Hi,
I code following https://kevin-brown.com/select2/examples.html in section "Loading remote data",
and I  don't know how to add data-* inside option tag.

Current is:
< select class="js-example-data-ajax" >
    ....
    < option value="220">xxx</ option >
</ select >

What I want is:
< select class="js-example-data-ajax" >
    ....
    < option value="220" data-desc="test desc" >xxx</ option >
</ select >

My json response is:
{
    "total_count":1,
    "items":[{
        "id":"220",
        "text":"xxx",
        "desc":"test desc"
    ]]
}

**Comment by kevin-brown** [comment] 2015-06-22 17:54
Closing this as a duplicate of https://github.com/select2/select2/issues/3116#issuecomment-112976757, feel free to weigh in over there.

**Closed by kevin-brown** 2015-06-22 17:54 UTC

**Comment by yoyhosoft** [comment] 2015-06-22 17:59
$ ('select'). select2 ('data')

Thanks you so much.
