### ISSUE TITLE
How to : Single selection using tab and search without a click or key pressed

### ISSUE THREAD

**Issue by lenamtl** [select2/select2#6223] opened 2023-02-08 13:44 UTC
Hi,

What I need is when user use Tab key and arrive on the dropbox (single select) can then type a letter for searching without any extra click or key pressed.

*This is possible to do that on multi select / pills but not on single select.

To reproduce the case 
https://select2.org/appearance#labels
tab to the first select (single) then type a letter
tab to the second select (multiple) the type a letter

Any help would be appreciate.

**Comment by lenamtl** [comment] 2023-02-09 16:25
Hi, 

I found this solution
I have tested with jQuery v3.5.1 and Select2 v4.0.13
**It not working with jQuery v3.6.0+**

```
$(document).on('focus', '.select2-selection.select2-selection--single', function (e) {
  $(this).closest(".select2-container").siblings('select:enabled').select2('open');
});

$('select.select2').on('select2:closing', function (e) {
  $(e.target).data("select2").$selection.one('focus focusin', function (e) {
    e.stopPropagation();
  });
});
```

Ref
https://stackoverflow.com/questions/20989458/select2-open-dropdown-on-focus

I saw many issues with focus ans jQuery v3.6.0+ so I'm not sure if there is a solution and how to apply it to this example.

**Comment by kevin-brown** [comment] 2023-02-14 17:24
Duplicate of https://github.com/select2/select2/issues/3279

**Closed as not planned by kevin-brown** 2023-02-14 17:24 UTC
