### ISSUE TITLE
Can't close dropdown on IE11 when there is a placeholder and no selection

### ISSUE THREAD

**Issue by Julie95** [select2/select2#3848] opened 2015-10-19 10:03 UTC
Hi,

I have an issue on IE11 when I am using a placeholder : the dropdown menu can't close if we don't select anything. 
We can see this here : http://jsfiddle.net/ng66Lo2x/2/
Once we once the menu, it can't be close unless we select an option.
We can see this behavior on the examples page too for the placeholders example : https://select2.github.io/examples.html#placeholders
(Only for the multiple select)

Is there a way to fix this ? (I am using many multiple select2 with a placeholder options, that are optional, so it can become very annoying if we can't close any)

Thanks!

EDIT : Sorry, I didn't see there was already a request for this : https://github.com/select2/select2/issues/3300

**Comment by kevin-brown** [comment] 2015-10-19 15:31
As noted, this is a duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-10-19 15:31 UTC
