### ISSUE TITLE
Dropdown positioned too high when appended to absolute parent with scrollTop.

### ISSUE THREAD

**Issue by epjoey** [select2/select2#4381] opened 2016-05-26 18:12 UTC
See this plunker:
https://plnkr.co/edit/JN8THx7eEaOX76h7bELN?p=preview
<img width="1053" alt="screen shot 2016-05-26 at 11 14 40 am" src="https://cloud.githubusercontent.com/assets/1261376/15585201/17adf886-2333-11e6-86b6-08541fff4288.png">

Bug seen in FF, safari, chrome.

The issue is because an absolute (absolute or fixed) container's edge shifts upward when you scroll within it.

Select2 uses the offset from document edge to the bottom edge of the fake select to position the dropdown. For appending the dropdown to a positioned parent, the parent's own offset is subtracted. This is complete for most cases.

But if the fake select is in a container that overflows a fixed container (the `dropdownParent`), when you scroll the select up, its offset is reduced, but its top positioning relative to the edge of the dropdownParent is not, because the dropdownParent's edge is pushed up with it. The scrollTop of the dropdownParent needs to be added to the css positioning.

As you can see in the screenshot, Ive scrolled the static blue box up about 80px within the fixed red box. The dropdown `top` needs another 80px.

I added this near the end of `_positionDropdown` and it fixed the issue for me.

```
    var parentCssPosition = $offsetParent.css('position');
    if (parentCssPosition === 'fixed' || parentCssPosition === 'absolute') {
      css.top += $offsetParent.scrollTop();
      css.left += $offsetParent.scrollLeft();
    }
```

I can make a pull request if we think its the best approach.

**Comment by kevin-brown** [comment] 2016-05-26 20:31
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by ne0guille** [comment] 2016-08-17 16:16
i can reproduce this in the examples page.
![image](https://cloud.githubusercontent.com/assets/15113782/17744065/85657b58-647c-11e6-8db9-8d98c85bd969.png)

on the Loading remote data select2. select an option, then click again and the dropdown is positionated on top, if there is no place to display it below.
This is also happening in my application, can you check this out?
thanks

**Comment by ne0guille** [comment] 2016-08-17 18:35
@kevin-brown this is also happening in the 4.0.3 version

**Comment by decodekult** [comment] 2016-09-14 07:37
This is happening for me to on an application where i am using select 2. I also can reproduce it on the repo examples page as stated above.

Using Win 10, checked with Firefox 48, Chrome 53, Edge 38 and Opera 39. In all cases, a first open of the select2 search box places it a little offset to the top, and then after searching, selecting a result, and opening it again the search box is placd just where it would site if the old search results were shown. Closing and opening again clears the issue.

I will do some extra tests. Maybe selecting a value bypasses clearing some data somehow that a "natural" closing addresses.

**Comment by zakjan** [comment] 2016-10-04 14:37
@kevin-brown Updated original test case to 4.0.3 shows the same error for me. Chrome 54. https://plnkr.co/edit/aSmiYLalXof5FpdkYrUW?p=preview

**Comment by luchorengo** [comment] 2017-01-09 00:13
Same issue when select2 is on Bootstrap Modal. Any updates about this? I can't figure out how to fix it.
![imageedit_3_9268193859](https://cloud.githubusercontent.com/assets/12195864/21754833/177ea25e-d5e7-11e6-9846-b6070e97299e.jpg)

**Comment by poulnike** [comment] 2017-02-28 09:03
+
I have the same problem

**Comment by alexweissman** [comment] 2017-09-17 02:08
Closing this as a duplicate of #4614.

**Closed by alexweissman** 2017-09-17 02:08 UTC
Labels: 4.x, needs information

**Comment by AnthonyVidal** [comment] 2020-04-16 04:37
This is not solution when existing scroll in parent dropdown (if content of modal).

For example: Its a OK:
![image](https://user-images.githubusercontent.com/6953533/79414920-90777000-7f71-11ea-85cb-4baa036d4bfd.png)

but lowering the scroll of the parent body is the problem:
![image](https://user-images.githubusercontent.com/6953533/79415023-d5030b80-7f71-11ea-999a-4c84e93403ac.png)

and if the scroll body grows, worse:
![image](https://user-images.githubusercontent.com/6953533/79415083-07146d80-7f72-11ea-8fb7-efb6e809f612.png)

Someone who has solved this problem? Thanks

**Comment by ChangDev123** [comment] 2021-06-26 05:08
I found the same issues on my project..
I have solved it right away..
The issue was the dropdownparent not placing on the right place..
just point your dropdownparent to another id which contained your select..

**Comment by AnthonyVidal** [comment] 2021-06-26 05:45
> I found the same issues on my project..
> I have solved it right away..
> The issue was the dropdownparent not placing on the right place..
> just point your dropdownparent to another id which contained your select..

@ChangDev123  please write the code example
