### ISSUE TITLE
"You have x items selected" & show checkmarks in select2

### ISSUE THREAD

**Issue by seiyria** [select2/select2#2318] opened 2014-04-25 17:29 UTC
I have a demo [here](http://jsfiddle.net/LUsMb/2779/) but it would be really nice if this were just built in to select2. Search for "run". You can pick items and they show up, but if you get more than 1 it shows how many items you have selected. Also, it shows checkmarks in select2 and moves these items to the top so you know what items you've selected.

Also, for some reason, closeOnSelect isn't working and I'm not sure why. I'm using 3.4.6 in this demo.

**Comment by kevin-brown** [comment] 2016-06-25 18:05
This is a duplicate of https://github.com/select2/select2/issues/411.

**Closed by kevin-brown** 2016-06-25 18:05 UTC

**Comment by homer2** [comment] 2016-09-02 19:59
@seiyria the link to your example is broken.
