### ISSUE TITLE
Set Focus to next element on Enter Key Press

### ISSUE THREAD

**Issue by sanjaicybro** [select2/select2#2930] opened 2015-01-16 06:20 UTC
I am using enter key navigation in all the pages and recently I started using select2 js for my drop down. The focus will reach from previous control to selct2 drop down on enter key press. But after selecting a item in the drop down via search and pressing enter only close the select2 drop down. Version I am using is 3.5.2

Can any one please suggest the way to navigate to next control on enter key press form select2. Will be thank full if could provide me with the code.

**Comment by kevin-brown** [comment] 2015-01-18 03:07
I'm going to close this as a duplicate of https://github.com/select2/select2/issues/1456, as the answer for both is "it's not possible in 3.5.2, but it can be done in 4.0.0".

**Closed by kevin-brown** 2015-01-18 03:07 UTC
