### ISSUE TITLE
Dropdown above 1px misposition

### ISSUE THREAD

**Issue by x000000** [select2/select2#2049] opened 2014-01-18 15:28 UTC
On white background it's not so noticeable
![select2_above](https://f.cloud.github.com/assets/1010098/1947427/05af8a24-8055-11e3-881a-0a2087ee3186.PNG)

**Comment by mfurtado-mdsol** [comment] 2015-03-13 11:31
I face same issue with one of the select fields I have in a form. Its strange it calculates width for the other field on same form correctly.

**Comment by mfurtado-mdsol** [comment] 2015-03-13 11:32
@kevin-brown any idea if there a fix for this in 4.0?

**Comment by kevin-brown** [comment] 2015-03-13 14:44
> @kevin-brown any idea if there a fix for this in 4.0?

I can no longer reproduce it, but it also didn't happen consistently before.

**Comment by mfurtado-mdsol** [comment] 2015-03-16 10:05
@kevin-brown cheers!

**Closed** 2015-03-16 16:09 UTC

**Comment by sferoze** [comment] 2015-06-26 20:08
I just had this same issue but after resizing the browser and trying again the issue disappeared. Now I cannot reproduce even when trying to match the original browser size when I had the issue.

**Comment by vadimkuragkovskiy** [comment] 2016-06-10 12:26
Hello Guys, 
Hello @kevin-brown 

First of all I'd like to say you Big Thank you for awesome library and cool support!
Here is video how that 1px offset issue can be reproduced:
https://youtu.be/SOo9AIx5J1A

**Comment by JLHwung** [comment] 2016-07-04 13:38
Quoted from @rjlevesque on #1892.

> I believe the problem here is jQuery's outerWidth returns an integer. I was able to correct this issue by replacing "this.container.outerWidth(false)" with "this.container[0].getBoundingClientRect().width" in the select2 source.

<img width="618" alt="screen shot 2016-07-04 at 10 34 12" src="https://cloud.githubusercontent.com/assets/3607926/16562311/f91ce4c2-41d2-11e6-9e20-2a243dc68a8c.png">

version: 4.0.3
option: `{ width: '100%' }`

The container's width is 498.98 px, yet jQuery's outerWidth returns an integer that round up to 495px. @rjlevesque 's solution LGTM.
