### ISSUE TITLE
Can not search.

### ISSUE THREAD

**Issue by code-artisan** [select2/select2#3921] opened 2015-11-11 06:32 UTC
Hi, I get a problem, When I call the select2 component in bootstrap modal. The input element can not foucs or type. I think it's a bug. [example](http://jsfiddle.net/0bnsj5e4/1/)

**Comment by kevin-brown** [comment] 2015-11-11 15:08
This is a duplicate of https://github.com/select2/select2/issues/600#issuecomment-102857595.

**Closed by kevin-brown** 2015-11-11 15:08 UTC
