### ISSUE TITLE
input field (tagging, select multiple) doesn't allow more than 2 or 3 characters in IE

### ISSUE THREAD

**Issue by frechl** [select2/select2#4410] opened 2016-06-10 07:30 UTC
Input field seems to be broken in IE when tagging/select multiple is enabled.

After typing 2 or 3 characters, the input field doesn't allow anymore characters in IE. It also happens in the demo page.

https://select2.github.io/examples.html#tags

I tested in IE11, Windows 8.1

Libraries I use
- jQuery version: 1.7.2
- Select2 version: 4.0.3

**Comment by kevin-brown** [comment] 2016-06-10 13:33
Duplicate of https://github.com/select2/select2/issues/4398.

**Closed by kevin-brown** 2016-06-10 13:33 UTC
