### ISSUE TITLE
Selecting the same value a second time does not fire a select event.

### ISSUE THREAD

**Issue by Enie** [select2/select2#5040] opened 2017-09-15 10:03 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a select2 element with something to select
2. Select something.
3. Select that same thing again

## Expected behavior and actual behavior

The second time I select a value the select event is not being fired.

I was expecting to get an event. I guess that this should be the difference between the change and the select event. the change event should not be fired since nothing changed, but I still selected something so I need an event.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [?] Internet Explorer
- [?] Safari

Operating System

- [?] Windows
- [x] Mac OS X
- [?] Linux
- [x] Mobile (iOS)

Libraries

- jQuery version: 1.12
- Select2 version: 4.0.3

## Isolating the problem

- [x] The bug happens consistently across all tested browsers

**Comment by alexweissman** [comment] 2017-09-15 15:51
This appears to be a duplicate of #4934.  Please search the open issues carefully before opening a new issue!

**Closed by alexweissman** 2017-09-15 15:51 UTC
