### ISSUE TITLE
multiple custom

### ISSUE THREAD

**Issue by Triden** [select2/select2#5061] opened 2017-10-03 11:10 UTC
![screenshot_3](https://user-images.githubusercontent.com/16622856/31122248-b71917c0-a843-11e7-8d17-98a5759bcbd1.png)
Hello. Tell me how easy it is to implement. When clicking not on "plus", insert one value and close the window. If you click on the plus, then increase the number of selected fields and do not close the window. The event passes through plus. I know that this will not help:
$('body').on('click', '.group-add', function(e){
            e.stopPropagation()
  });

**Comment by alexweissman** [comment] 2017-10-03 15:46
Seems like a duplicate of #5028.  It's possible that one of these widgets might be more appropriate for your needs:

- [Bootstrap Multiselect](https://davidstutz.github.io/bootstrap-multiselect/)
- [select2-multi-checkboxes](https://github.com/wasikuss/select2-multi-checkboxes)

**Comment by alexweissman** [comment] 2017-11-06 02:18
For future help with general usage and troubleshooting, please ask on the [forums](https://forums.select2.org) instead.

**Closed by alexweissman** 2017-11-06 02:18 UTC
Labels: support: usage question
