### ISSUE TITLE
Select2 Cascading Dropdown options issue 

### ISSUE THREAD

**Issue by boulepick** [select2/select2#4031] opened 2015-12-16 15:16 UTC
Good day,
i'm having some issues with a select2 cascading dropdown that i have implemented. First i have to say that my code worked perfectly prior to version 4.0.0.
So i have the classic Country, Province and City dropdowns, prior to V4 it worked ok but now that i have upgraded to 4 when ever i change a country the province dropdown does not clear the options to add the new values instead it add them to the previous result. see the screenshot
![capture](https://cloud.githubusercontent.com/assets/9008447/11843764/4eff3c8e-a3d9-11e5-9c33-8073fe82517c.PNG)
![capture1](https://cloud.githubusercontent.com/assets/9008447/11843770/5a508ce6-a3d9-11e5-8766-25ab712f9b67.PNG)
![capture2](https://cloud.githubusercontent.com/assets/9008447/11843772/5caa56c0-a3d9-11e5-990d-8f841ce69110.PNG)
you can see now that when changing from Jamaica to Japan, in the province dropdown i have provinces from both countries now Jamaica circle in red and Japan circle in black.

this is my code to populate the province dropdown:
HTML:

     <div class="col-xs-4">
          div class="form-group form-group-sm"
                label class="control-label">Province</label>
                select id="Province" name="province" class="form-control" required="required"
		   option>/option>
		/select>
             /div>
        /div>

JS:

```js
function (locationInfo) {
        this.getProvinces = function(ctr_id) {
			var provincelist =[];
			var userSelCountry ="";
			if (ctr_id {userSelCountry = ctr_id;
			} else {userSelCountry = loadList(rootGetSelURL + '?action=country' );}
			var userSelProvince = loadList(rootGetSelURL + '?action=province' );
			var prlist = loadList(rootLocURL + '?action=province&country_id=' + userSelCountry);
			if(prlist === -1){
				provincelist = [{"id":"0","text":provinceNoresult}];
			} else{
				provincelist = prlist;
			}
			//populate country select
			$("#Province").select2({
				data		:provincelist,
				cache		:false,
				formatNoMatches: function (term) {
					return provinceNoMatch;
				}
			}).select2('val', [userSelProvince]);
        };
}
```

and i trigger the change like this for the province and city dropdown

```js
 $("#Country").on("change", function(ev) {
//get current selection
var country_id = $(this).val();
var province_id = "";
		// reinit province and city
			loc.getProvinces(country_id);
			loc.getCities(country_id,province_id);
});
```

so is this a bug or am i doing something wrong with the new version V4?

**Comment by kevin-brown** [comment] 2015-12-22 00:23
Duplicate of https://github.com/select2/select2/issues/3348 / https://github.com/select2/select2/issues/3185#issuecomment-88955394.

**Closed by kevin-brown** 2015-12-22 00:23 UTC
