### ISSUE TITLE
Selected Tags get reordered in INPUT field

### ISSUE THREAD

**Issue by krishnat2** [select2/select2#3586] opened 2015-07-17 19:39 UTC
I have a Select2 control with 5 TAGS, lets say "By", "Near", "In", "Where". I want the use to be able to Select "By" type there input, then select "Near" and input, for example: John.

However, when I select the "Near", the values in the INPUT Field get reordered to "By", "Near", "John". Where as  I would like it to be "By" "John" "Near"

Is there a option or can we add a feature so that, the order in the INPUT field is same as that of selected order?

**Comment by kevin-brown** [comment] 2015-07-17 19:47
This is a duplicate of https://github.com/select2/select2/issues/3106.

Unlike a `<select>`, where you can easily change the order, it's not possible with a `<input />`.

**Closed by kevin-brown** 2015-07-17 19:47 UTC
