### ISSUE TITLE
Ajax + jQuery v10+ can't select first option

### ISSUE THREAD

**Issue by AlexEmashev** [select2/select2#3807] opened 2015-10-01 08:50 UTC
Hello, first of all, thank you for this brilliant control. 

I'm experiencing an issue with Select2 v4.0 and ajax request. When results are shown I can't select first one. If I select something other than first it selects, but then I can't change this selection.

I found that issue appears when jQuery v10+ is used, in v9 and lower everything is fine. By the way Select2 v3.5 works OK.

Here is a jsfiddle link http://jsfiddle.net/AlexEmashev/31ph7yk3/

**Comment by haykerhsdremks** [comment] 2015-10-02 16:21
Hi, Alex the problem is the id = 0, prove with id=1

Here is a jsfiddli link: https://jsfiddle.net/59czf4x8/

**Comment by GpadillaQ** [comment] 2015-10-02 16:29
Hi, Alex the problem is the id = 0, prove with id=1

Here is a jsfiddli link: https://jsfiddle.net/59czf4x8/

**Comment by kevin-brown** [comment] 2015-10-02 21:23
The problem is actually that your `id` is not a string. Because of this, we are doing checks and `'' == 0`, so it's not changing from the placeholder. When you use a string though, `'' != '0'`, and the first option can be set.

Also, a `<select>` tag is not self-closing. You should be using `<select></select>`.

https://jsfiddle.net/31ph7yk3/5/

**Closed by kevin-brown** 2015-10-02 21:23 UTC

**Comment by AlexEmashev** [comment] 2015-10-03 07:52
Wow, thank you. I didn't realize that. So, my Id's should be in strings in order not to cause any problems.
