### ISSUE TITLE
Select2 doesn`t work with a specific select name

### ISSUE THREAD

**Issue by marinovdf** [select2/select2#4079] opened 2016-01-12 09:51 UTC
Hi!
Select2 is the great plugin. But it doesn't work with a specific select name, such as `some[name-1]` (https://jsfiddle.net/d1obxunL/)

Versions:
Select2 - 4.0.1
jQuery - 2.2.0

**Comment by kevin-brown** [comment] 2016-01-12 14:57
This is a duplicate of https://github.com/select2/select2/issues/3618.

**Closed by kevin-brown** 2016-01-12 14:57 UTC
