### ISSUE TITLE
maximumSelectionLength not enforced with closeOnSelect: false

### ISSUE THREAD

**Issue by realalex** [select2/select2#4457] opened 2016-07-05 21:02 UTC
While I'd normally be more thorough with your reporting format, this one is pretty self-explanatory.

```js
$('.select2').select2({
    	closeOnSelect: false, 
    	maximumSelectionLength: 4
});
```

When closeOnSelect is false, the users have free reign to select as many options as they want. closeOnSelect: true solves the issue, but it's totally unintuitive.

**Comment by kevin-brown** [comment] 2016-07-05 23:35
This is a duplicate of https://github.com/select2/select2/issues/3514.

**Closed by kevin-brown** 2016-07-05 23:35 UTC
