### ISSUE TITLE
internal select2 code update

### ISSUE THREAD

**Issue by joomlaA1** [select2/select2#4522] opened 2016-08-08 00:37 UTC
if for in case you put both ajax and data options
                        
currently, ajax will be the one to take effect instead of data. but i think it must be reverse data must be priority than ajax(meaning if data contains something, that's it and disregard ajax option)
with the rationale that the data is already there thus you won't have to get anything else

could we implement this...
thanks

**Comment by kevin-brown** [comment] 2016-08-09 15:39
This is a duplicate of https://github.com/select2/select2/issues/2427.

**Closed by kevin-brown** 2016-08-09 15:39 UTC
