### ISSUE TITLE
[BUG REPORT] the repositioning of the select options

### ISSUE THREAD

**Issue by joseph1125** [select2/select2#3432] opened 2015-06-03 03:14 UTC
If I set "closeOnSelect: false", the select dropdown wont reposition once I finished selecting an item
![image](https://cloud.githubusercontent.com/assets/8279406/7952031/c1306a72-09e1-11e5-9d8c-63c19cddb022.png)

**Comment by kevin-brown** [comment] 2015-06-03 03:32
Duplicate of https://github.com/select2/select2/issues/3373, there's a temporary solution there that you can also use.

**Closed by kevin-brown** 2015-06-03 03:32 UTC
