### ISSUE TITLE
Default Functionality of select fields when search and single select.

### ISSUE THREAD

**Issue by MarcGodard** [select2/select2#2334] opened 2014-04-30 20:47 UTC
This is needed in this library. 

When there isn't a search field, and its single select, it should act like most users are used to (default usability). This means that if you hit the key F the option that starts with F should automatically be selected. If you hit F again, it should go to the next one that has an F.

Don't get me wrong, the search has its place, however, for lists like provinces (only 10 of them here in Canada), people are used to tabing and then just typing 'A' for Alberta. With the stupid search thing this causes problems because if Ontario is before it in the list, it comes up first because it contains an 'A'.

Search is great for very long lists... but default functionality is good for short lists. This is why every browser on the face of the planet does it, and missing this is a bad thing for your awesome but lacking library.

**Comment by kevin-brown** [comment] 2016-06-25 18:18
In Select2 4.0, this is effectively a duplicate of https://github.com/select2/select2/issues/3279. Both of them have the same root issue, so they both will be fixed at the same time.

**Closed by kevin-brown** 2016-06-25 18:18 UTC
Labels: enhancement
