### ISSUE TITLE
Touch event not triggering Select2

### ISSUE THREAD

**Issue by jasonniebauer** [select2/select2#3064] opened 2015-02-23 20:21 UTC
I am able to get the select2 to work on desktop, but when I test on mobile devices the select2 does not open on touch. I am using version 4.0.0 using the standard build. When tapping on the select2 menu on iOS8 using Chrome browser the select2 menu does not open on iPhone. I am unable to open the select2 menu on iOS7 simulator through Safari browser too.

**Comment by jasonniebauer** [comment] 2015-02-26 16:19
I am using version 4.0.0 using the standard build. When tapping on the select2 menu on iOS8 using Chrome browser the select2 menu does not open. I am unable to open the select2 menu on iOS7 simulator through Safari browser too.

**Comment by pixelpie** [comment] 2015-06-30 05:15
I am experiencing the same issue. Using Select2 4.0.0. It works fine on desktop but on iOS 8.3 doesn't do anything (tested on Chrome and Mobile Safari). I am able to replicate the issue by using Chrome's device simulator.

**Comment by kevin-brown** [comment] 2015-07-02 20:37
See anything strange in the [Select2 events](http://select2.github.io/examples.html#programmatic) being triggered?

> I am able to replicate the issue by using Chrome's device simulator.

Unfortunately I can't even replicate this.

**Comment by pixelpie** [comment] 2015-07-03 00:17
Turns out the issue was being caused by FastClick.js. So nothing to do with Select2, thanks heaps for looking into it.

**Comment by kevin-brown** [comment] 2015-07-04 18:18
Sounds like this is a duplicate of https://github.com/select2/select2/issues/3381 then.

**Closed by kevin-brown** 2015-07-04 18:18 UTC
Labels: needs information
