### ISSUE TITLE
Weird display issue in IE9, duplicated on Win7 and WinVista

### ISSUE THREAD

**Issue by SlowburnAZ** [select2/select2#4821] opened 2017-03-08 00:51 UTC
So, I'm using Select2 with the well-known Inspinia theme ([https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S](url)), and I'm running into a weird issue in IE9:

![ie9-select2-weirdness](https://cloud.githubusercontent.com/assets/5659169/23684877/778ff888-035e-11e7-911c-74f185f3e918.png)

As you can see, the dropdown is basically all but missing, and it doesn't seem as if much of the usual styling has been applied.

The weird thing is that Select2 is working fine on the Select2 demo site, as well as in the Inspinia demos, so it's obviously in my particular setup.  There are no errors loading and CSS or JS files, no console errors.  I'm having a bear of a time figuring out what could possibly be causing this.  Has anyone here run into anything similar?

**Comment by alexweissman** [comment] 2017-09-29 05:35
Possibly a duplicate of #4780.  Have you tried setting `dropdownParent`?  See https://select2.org/dropdown#dropdown-placement

**Comment by alexweissman** [comment] 2017-11-06 02:41
Please feel free to comment if you have any more insight, and we can reopen the issue.

**Closed by alexweissman** 2017-11-06 02:41 UTC
Labels: browser: IE, needs information
