### ISSUE TITLE
Opens and immediately closes on Android and Windows Phone 

### ISSUE THREAD

**Issue by PSimonMotech** [select2/select2#2606] opened 2014-08-12 16:22 UTC
I have the 3.5.1 version. 
When viewing a page on an android or windows phone device (including the examples on the select2 github page).

Selecting a select2 dropdown causes this to happen:
dropdown opens,
virtual keyboard opens,
dropdown closes,
virtual keyboard closes

you cannot select anything from the dropdown in the short time it is opened.

I have combed through all the other positngs about this problem, none of the workarounds have worked.

Any ideas?

**Comment by beermad** [comment] 2015-01-23 19:02
The new example page seems to work right for me (chrome, Firefox Android and Naked Browser) but curiously, even when using the next release version mentioned the site I'm working on still has the problem (my suspicion is that it may be something to do with the fact that I'm having to play around with z-index all over the place to fit the various layers of my pages.

One thing I've observed is that the problem seems to occur on occasions when the page resizes itself as the select is clicked on. With this in mind, I tried replacing

<meta name="viewport" content="width=device-width, initial-scale=1.0">
with
<meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1.0">
First indications are that this is a good workaround (though I haven't done intensive testing yet).

**Comment by kevin-brown** [comment] 2015-01-23 20:09
In the latest unstable version (on the `select2-ng` branch), we should have fixed the resizing and scrolling issues that were previously seen on mobile devices.

**Comment by vnyvs** [comment] 2015-02-04 08:49
I am experiencing same issue here.. Any one has any fix or workarounds for this issue?

**Comment by kevin-brown** [comment] 2015-02-04 15:05
@vnyvs What version of Select2 and what OS are you having issues with?

**Comment by vnyvs** [comment] 2015-03-02 08:07
I am using 3.5.2  version of select2. The issue is seen in android JB. I have same device of version Kitkat on which it works fine.

**Comment by kevin-brown** [comment] 2015-03-18 16:04
Should be fixed in 4.0.0.

**Closed by kevin-brown** 2015-03-18 16:04 UTC
Labels: bug
