### ISSUE TITLE
placeholder not working on IE

### ISSUE THREAD

**Issue by brunoDegaspare** [select2/select2#3737] opened 2015-09-04 09:44 UTC
Placeholder is not working properly on IE 11. Note that on IE you need to select at least 2 options in order to close the dropdown.

Also on IE, once the select input is focused you are not able to close it by clicking outside.

Please test it on IE 11: http://jsfiddle.net/brunodd/jEADR/2018/

The solution that worked for me was commenting out the `self.handleSearch(evt);` on select2.full.js

Ref. https://github.com/select2/select2/issues/3300

```'this.$selection.on('keyup.search input', '.select2-search--inline',
        function (evt) {
      self.handleSearch(evt);
    });```

I know this fix is not ideal as if I update the plugin the bug will come back.

Is there any fix for this?

**Comment by kevin-brown** [comment] 2015-09-04 10:43
This is a duplicate of https://github.com/select2/select2/issues/3300.

**Closed by kevin-brown** 2015-09-04 10:43 UTC
