### ISSUE TITLE
Gap appearing between options and selected options list

### ISSUE THREAD

**Issue by CPD** [select2/select2#4106] opened 2016-01-21 16:59 UTC
A gap appears between the options and selected options list. Unsure as to why but the only code run on the select statement is $(selector).select2(); so I can only assume it should work.

See https://gyazo.com/e9f6c75f89b3eacb249e1a27b5038109

**Comment by kevin-brown** [comment] 2016-01-26 16:17
Without any more information, this is most likely a duplicate of https://github.com/select2/select2/issues/3970.

**Closed by kevin-brown** 2016-01-26 16:17 UTC
